/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
// allow unused variables and dead code due to gen code weirdness
#[allow(unused_variables)]
#[allow(dead_code)]
impl Core {
    /// Lookback period for [`Core::mult`].
    ///
    /// # Arguments
    ///
    pub fn mult_lookback(&self) -> i32 {
        return 0;
    }
    /// Vector Arithmetic Mult
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal0` - Input price series
    /// * `inReal1` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    ///
    /// # Returns
    ///
    /// [`RetCode::Success`] on success, or an error code on failure.
    ///
    /// # Example
    ///
    /// ```
    /// use ta_lib::ta_func::{Core, RetCode};
    ///
    /// let input = [1.0_f64; 50];
    /// let input = [1.0_f64; 50];
    /// let mut out = [0.0_f64; 50];
    /// let mut out_beg_idx: usize = 0;
    /// let mut out_nb_element: usize = 0;
    ///
    /// let core = Core::new();
    /// let result = core.mult(
    ///  0,
    ///  49,
    ///  &input,
    ///  &input,
    ///  &mut out_beg_idx,
    ///  &mut out_nb_element,
    ///  &mut out,
    /// );
    ///
    /// assert_eq!(result, RetCode::Success);
    /// ```
    pub fn mult(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal0: &[f64],
        inReal1: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut outIdx: usize;
        if endIdx < startIdx {
            return RetCode::OutOfRangeEndIndex;
        }
        outIdx = 0;
        for i in (startIdx as usize)..=(endIdx as usize) {
            outReal[outIdx] = (inReal0[i] * inReal1[i]) as f64;
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    /// Single-precision variant of [`Core::mult`].
    pub fn mult_s(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal0: &[f32],
        inReal1: &[f32],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut outIdx: usize;
        if endIdx < startIdx {
            return RetCode::OutOfRangeEndIndex;
        }
        outIdx = 0;
        for i in (startIdx as usize)..=(endIdx as usize) {
            outReal[outIdx] = (inReal0[i] * inReal1[i]) as f64;
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
