/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
// allow unused variables and dead code due to gen code weirdness
#[allow(unused_variables)]
#[allow(dead_code)]
impl Core {
    /// Lookback period for [`Core::rsi`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    pub fn rsi_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        let mut retValue: i32;
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        retValue = optInTimePeriod + (self.unstable_period[FuncUnstId::Rsi as usize]);
        if (self.compatibility) == Compatibility::Metastock {
            retValue = retValue - 1;
        }
        return retValue;
    }
    /// Relative Strength Index
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    ///
    /// # Returns
    ///
    /// [`RetCode::Success`] on success, or an error code on failure.
    ///
    /// # Example
    ///
    /// ```
    /// use ta_lib::ta_func::{Core, RetCode};
    ///
    ///
    /// let prices = [
    ///  44.0, 44.34, 44.09, 43.61, 44.33, 44.83, 44.32, 44.55,
    ///  43.93, 44.05, 43.80, 43.64, 43.82, 44.29, 44.09, 44.15,
    ///  43.61, 44.33, 44.83, 44.32, 44.55, 43.93, 44.05, 43.80,
    ///  43.64, 43.82, 44.29, 44.09, 44.15, 43.61_f64,
    /// ];
    /// let mut out = [0.0_f64; 30];
    /// let mut out_beg_idx: usize = 0;
    /// let mut out_nb_element: usize = 0;
    ///
    /// let core = Core::new();
    /// let result = core.rsi(
    ///  0,
    ///  prices.len() - 1,
    ///  &prices,
    ///  14,
    ///  &mut out_beg_idx,
    ///  &mut out_nb_element,
    ///  &mut out,
    /// );
    ///
    /// assert_eq!(result, RetCode::Success);
    /// assert_eq!(out_beg_idx, 14);
    /// assert!(out_nb_element > 0);
    ///
    ///
    /// for i in 0..out_nb_element {
    ///  assert!(out[i] >= 0.0 && out[i] <= 100.0);
    /// }
    /// ```
    pub fn rsi(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut outIdx: usize;
        let mut today: usize;
        let lookbackTotal: usize;
        let unstablePeriod: i32;
        let i: i32;
        let mut prevGain: f64;
        let mut prevLoss: f64;
        let mut prevValue: f64;
        let savePrevValue: f64;
        let mut tempValue1: f64;
        let mut tempValue2: f64;
        if endIdx < startIdx {
            return RetCode::OutOfRangeEndIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = (self.rsi_lookback(optInTimePeriod)) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod == 1 {
            (*outBegIdx) = startIdx;
            i = ((endIdx - startIdx) + 1) as i32;
            (*outNBElement) = (i) as usize;
            {
                let _n = (i) as usize;
                let _di = (0) as usize;
                let _si = (startIdx) as usize;
                outReal[_di.._di + _n].copy_from_slice(&inReal[_si.._si + _n]);
            };
            return RetCode::Success;
        }
        today = startIdx - lookbackTotal;
        prevValue = (inReal[today]) as f64;
        unstablePeriod = self.unstable_period[FuncUnstId::Rsi as usize];
        if (unstablePeriod == 0) && ((self.compatibility) == Compatibility::Metastock) {
            savePrevValue = prevValue;
            prevGain = 0.0;
            prevLoss = 0.0;
            for i in (1..=optInTimePeriod).rev() {
                tempValue1 = (inReal[today]) as f64;
                today = today + 1;
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                if tempValue2 < 0.0 {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
            }
            tempValue1 = prevLoss / ((optInTimePeriod) as f64);
            tempValue2 = prevGain / ((optInTimePeriod) as f64);
            tempValue1 = tempValue2 + tempValue1;
            if !(((-(0.00000000000001)) < tempValue1) && (tempValue1 < (0.00000000000001))) {
                outReal[outIdx] = 100.0 * (tempValue2 / tempValue1);
                outIdx = outIdx + 1;
            } else {
                outReal[outIdx] = 0.0;
                outIdx = outIdx + 1;
            }
            if today > endIdx {
                (*outBegIdx) = startIdx;
                (*outNBElement) = outIdx;
                return RetCode::Success;
            }
            today = today - ((optInTimePeriod) as usize);
            prevValue = savePrevValue;
        }
        prevGain = 0.0;
        prevLoss = 0.0;
        today = today + 1;
        for i in (1..=optInTimePeriod).rev() {
            tempValue1 = (inReal[today]) as f64;
            today = today + 1;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            if tempValue2 < 0.0 {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
        }
        prevLoss /= (optInTimePeriod) as f64;
        prevGain /= (optInTimePeriod) as f64;
        if today > startIdx {
            tempValue1 = prevGain + prevLoss;
            if !(((-(0.00000000000001)) < tempValue1) && (tempValue1 < (0.00000000000001))) {
                outReal[outIdx] = 100.0 * (prevGain / tempValue1);
                outIdx = outIdx + 1;
            } else {
                outReal[outIdx] = 0.0;
                outIdx = outIdx + 1;
            }
        } else {
            while today < startIdx {
                tempValue1 = (inReal[today]) as f64;
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                prevLoss *= (optInTimePeriod - 1) as f64;
                prevGain *= (optInTimePeriod - 1) as f64;
                if tempValue2 < 0.0 {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
                prevLoss /= (optInTimePeriod) as f64;
                prevGain /= (optInTimePeriod) as f64;
                today = today + 1;
            }
        }
        while today <= endIdx {
            tempValue1 = (inReal[today]) as f64;
            today = today + 1;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            prevLoss *= (optInTimePeriod - 1) as f64;
            prevGain *= (optInTimePeriod - 1) as f64;
            if tempValue2 < 0.0 {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
            prevLoss /= (optInTimePeriod) as f64;
            prevGain /= (optInTimePeriod) as f64;
            tempValue1 = prevGain + prevLoss;
            if !(((-(0.00000000000001)) < tempValue1) && (tempValue1 < (0.00000000000001))) {
                outReal[outIdx] = 100.0 * (prevGain / tempValue1);
                outIdx = outIdx + 1;
            } else {
                outReal[outIdx] = 0.0;
                outIdx = outIdx + 1;
            }
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    /// Single-precision variant of [`Core::rsi`].
    pub fn rsi_s(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f32],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut outIdx: usize;
        let mut today: usize;
        let lookbackTotal: usize;
        let unstablePeriod: i32;
        let i: i32;
        let mut prevGain: f64;
        let mut prevLoss: f64;
        let mut prevValue: f64;
        let savePrevValue: f64;
        let mut tempValue1: f64;
        let mut tempValue2: f64;
        if endIdx < startIdx {
            return RetCode::OutOfRangeEndIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = (self.rsi_lookback(optInTimePeriod)) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod == 1 {
            (*outBegIdx) = startIdx;
            i = ((endIdx - startIdx) + 1) as i32;
            (*outNBElement) = (i) as usize;
            {
                let _n = (i) as usize;
                let _di = (0) as usize;
                let _si = (startIdx) as usize;
                for _k in 0.._n {
                    outReal[_di + _k] = inReal[_si + _k] as f64;
                }
            };
            return RetCode::Success;
        }
        today = startIdx - lookbackTotal;
        prevValue = (inReal[today]) as f64;
        unstablePeriod = self.unstable_period[FuncUnstId::Rsi as usize];
        if (unstablePeriod == 0) && ((self.compatibility) == Compatibility::Metastock) {
            savePrevValue = prevValue;
            prevGain = 0.0;
            prevLoss = 0.0;
            for i in (1..=optInTimePeriod).rev() {
                tempValue1 = (inReal[today]) as f64;
                today = today + 1;
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                if tempValue2 < 0.0 {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
            }
            tempValue1 = prevLoss / ((optInTimePeriod) as f64);
            tempValue2 = prevGain / ((optInTimePeriod) as f64);
            tempValue1 = tempValue2 + tempValue1;
            if !(((-(0.00000000000001)) < tempValue1) && (tempValue1 < (0.00000000000001))) {
                outReal[outIdx] = 100.0 * (tempValue2 / tempValue1);
                outIdx = outIdx + 1;
            } else {
                outReal[outIdx] = 0.0;
                outIdx = outIdx + 1;
            }
            if today > endIdx {
                (*outBegIdx) = startIdx;
                (*outNBElement) = outIdx;
                return RetCode::Success;
            }
            today = today - ((optInTimePeriod) as usize);
            prevValue = savePrevValue;
        }
        prevGain = 0.0;
        prevLoss = 0.0;
        today = today + 1;
        for i in (1..=optInTimePeriod).rev() {
            tempValue1 = (inReal[today]) as f64;
            today = today + 1;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            if tempValue2 < 0.0 {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
        }
        prevLoss /= (optInTimePeriod) as f64;
        prevGain /= (optInTimePeriod) as f64;
        if today > startIdx {
            tempValue1 = prevGain + prevLoss;
            if !(((-(0.00000000000001)) < tempValue1) && (tempValue1 < (0.00000000000001))) {
                outReal[outIdx] = 100.0 * (prevGain / tempValue1);
                outIdx = outIdx + 1;
            } else {
                outReal[outIdx] = 0.0;
                outIdx = outIdx + 1;
            }
        } else {
            while today < startIdx {
                tempValue1 = (inReal[today]) as f64;
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                prevLoss *= (optInTimePeriod - 1) as f64;
                prevGain *= (optInTimePeriod - 1) as f64;
                if tempValue2 < 0.0 {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
                prevLoss /= (optInTimePeriod) as f64;
                prevGain /= (optInTimePeriod) as f64;
                today = today + 1;
            }
        }
        while today <= endIdx {
            tempValue1 = (inReal[today]) as f64;
            today = today + 1;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            prevLoss *= (optInTimePeriod - 1) as f64;
            prevGain *= (optInTimePeriod - 1) as f64;
            if tempValue2 < 0.0 {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
            prevLoss /= (optInTimePeriod) as f64;
            prevGain /= (optInTimePeriod) as f64;
            tempValue1 = prevGain + prevLoss;
            if !(((-(0.00000000000001)) < tempValue1) && (tempValue1 < (0.00000000000001))) {
                outReal[outIdx] = 100.0 * (prevGain / tempValue1);
                outIdx = outIdx + 1;
            } else {
                outReal[outIdx] = 0.0;
                outIdx = outIdx + 1;
            }
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
