/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::bbands`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 5, range: 2..=100000)
    /// * `optInNbDevUp` - Number of period (default: 2, range: -2147483648..=2147483647)
    /// * `optInNbDevDn` - Number of period (default: 2, range: -2147483648..=2147483647)
    pub fn bbands_lookback(&self, mut optInTimePeriod: i32, mut optInNbDevUp: f64, mut optInNbDevDn: f64, mut optInMAType: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        return self.ma_lookback(optInTimePeriod, optInMAType);
    }
    /// Bollinger Bands
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 5, range: 2..=100000)
    /// * `optInNbDevUp` - Number of period (default: 2, range: -2147483648..=2147483647)
    /// * `optInNbDevDn` - Number of period (default: 2, range: -2147483648..=2147483647)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outRealUpperBand` - Output values
    /// * `outRealMiddleBand` - Output values
    /// * `outRealLowerBand` - Output values
    pub fn bbands<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        mut optInNbDevUp: f64,
        mut optInNbDevDn: f64,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [T],
        outRealMiddleBand: &mut [T],
        outRealLowerBand: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.bbands_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            optInNbDevUp,
            optInNbDevDn,
            optInMAType,
            outBegIdx,
            outNBElement,
            outRealUpperBand,
            outRealMiddleBand,
            outRealLowerBand,
        );
    }
    pub fn bbands_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        mut optInNbDevUp: f64,
        mut optInNbDevDn: f64,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [T],
        outRealMiddleBand: &mut [T],
        outRealLowerBand: &mut [T],
    ) -> RetCode {
        let mut retCode: RetCode;
        let i: i32;
        let mut tempReal: T;
        let mut tempReal2: T;
        let mut tempBuffer1: Vec<T>;
        let mut tempBuffer2: Vec<T>;
        if inReal == outRealUpperBand {
            tempBuffer1 = outRealMiddleBand;
            tempBuffer2 = outRealLowerBand;
        } else if inReal == outRealLowerBand {
            tempBuffer1 = outRealMiddleBand;
            tempBuffer2 = outRealUpperBand;
        } else if inReal == outRealMiddleBand {
            tempBuffer1 = outRealLowerBand;
            tempBuffer2 = outRealUpperBand;
        } else {
            tempBuffer1 = outRealMiddleBand;
            tempBuffer2 = outRealUpperBand;
        }
        if tempBuffer1 == inReal || tempBuffer2 == inReal {
            return RetCode::BadParam;
        }
        retCode = self.ma_unguarded(startIdx, endIdx, inReal, optInTimePeriod, optInMAType, outBegIdx, outNBElement, tempBuffer1);
        if retCode != RetCode::Success || (((*outNBElement)) as i32) == 0 {
            (*outNBElement) = 0;
            return retCode;
        }
        if optInMAType == TA_MAType_SMA {
            _startSum = 1 + (((*outBegIdx)) as i32) - optInTimePeriod;
            _endSum = ((*outBegIdx)) as i32;
            _periodTotal2 = 0;
            // for( _outIdx = _startSum; _outIdx < _endSum; _outIdx += 1 )
            _outIdx = _startSum;
            while _outIdx < _endSum {
                _tempReal = inReal[_outIdx];
                _tempReal *= _tempReal;
                _periodTotal2 += _tempReal;
                _outIdx += 1;
            }
            // for( _outIdx = 0; _outIdx < (((*outNBElement)) as i32); _outIdx += 1;
_startSum += 1;
_endSum += 1 )
            _outIdx = 0;
            while _outIdx < (((*outNBElement)) as i32) {
                _tempReal = inReal[_endSum];
                _tempReal *= _tempReal;
                _periodTotal2 += _tempReal;
                _meanValue2 = _periodTotal2 / optInTimePeriod;
                _tempReal = inReal[_startSum];
                _tempReal *= _tempReal;
                _periodTotal2 -= _tempReal;
                _tempReal = tempBuffer1[_outIdx];
                _tempReal *= _tempReal;
                _meanValue2 -= _tempReal;
                if !(_meanValue2 < T::ta_from_f64(0.00000001)) {
                    tempBuffer2[_outIdx] = _meanValue2.ta_sqrt();
                } else {
                    tempBuffer2[_outIdx] = T::ta_from_f64(0.0);
                }
                _outIdx += 1;
_startSum += 1;
_endSum += 1;
            }
        } else {
            retCode = self.stddev_unguarded(((*outBegIdx)) as i32, endIdx, inReal, optInTimePeriod, T::ta_from_f64(1.0), outBegIdx, outNBElement, tempBuffer2);
            if retCode != RetCode::Success {
                (*outNBElement) = 0;
                return retCode;
            }
        }
        if tempBuffer1 != outRealMiddleBand {
            {
            let _n = ((*outNBElement) * 1) as usize;
            let _di = (0) as usize;
            let _si = (0) as usize;
            outRealMiddleBand[_di.._di + _n].copy_from_slice(&tempBuffer1[_si.._si + _n]);
        };
        }
        if T::ta_from_f64(optInNbDevUp) == T::ta_from_f64(optInNbDevDn) {
            if T::ta_from_f64(optInNbDevUp) == T::ta_from_f64(1.0) {
                // for( i = 0; i < (((*outNBElement)) as i32); i += 1 )
                i = 0;
                while i < (((*outNBElement)) as i32) {
                    tempReal = tempBuffer2[i];
                    tempReal2 = outRealMiddleBand[i];
                    outRealUpperBand[i] = tempReal2 + tempReal;
                    outRealLowerBand[i] = tempReal2 - tempReal;
                    i += 1;
                }
            } else {
                // for( i = 0; i < (((*outNBElement)) as i32); i += 1 )
                i = 0;
                while i < (((*outNBElement)) as i32) {
                    tempReal = tempBuffer2[i] * T::ta_from_f64(optInNbDevUp);
                    tempReal2 = outRealMiddleBand[i];
                    outRealUpperBand[i] = tempReal2 + tempReal;
                    outRealLowerBand[i] = tempReal2 - tempReal;
                    i += 1;
                }
            }
        } else if T::ta_from_f64(optInNbDevUp) == T::ta_from_f64(1.0) {
            // for( i = 0; i < (((*outNBElement)) as i32); i += 1 )
            i = 0;
            while i < (((*outNBElement)) as i32) {
                tempReal = tempBuffer2[i];
                tempReal2 = outRealMiddleBand[i];
                outRealUpperBand[i] = tempReal2 + tempReal;
                outRealLowerBand[i] = tempReal2 - tempReal * T::ta_from_f64(optInNbDevDn);
                i += 1;
            }
        } else if T::ta_from_f64(optInNbDevDn) == T::ta_from_f64(1.0) {
            // for( i = 0; i < (((*outNBElement)) as i32); i += 1 )
            i = 0;
            while i < (((*outNBElement)) as i32) {
                tempReal = tempBuffer2[i];
                tempReal2 = outRealMiddleBand[i];
                outRealLowerBand[i] = tempReal2 - tempReal;
                outRealUpperBand[i] = tempReal2 + tempReal * T::ta_from_f64(optInNbDevUp);
                i += 1;
            }
        } else {
            // for( i = 0; i < (((*outNBElement)) as i32); i += 1 )
            i = 0;
            while i < (((*outNBElement)) as i32) {
                tempReal = tempBuffer2[i];
                tempReal2 = outRealMiddleBand[i];
                outRealUpperBand[i] = tempReal2 + tempReal * T::ta_from_f64(optInNbDevUp);
                outRealLowerBand[i] = tempReal2 - tempReal * T::ta_from_f64(optInNbDevDn);
                i += 1;
            }
        }
        return RetCode::Success;
    }
    pub unsafe fn bbands_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        mut optInNbDevUp: f64,
        mut optInNbDevDn: f64,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [T],
        outRealMiddleBand: &mut [T],
        outRealLowerBand: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.bbands_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            optInNbDevUp,
            optInNbDevDn,
            optInMAType,
            outBegIdx,
            outNBElement,
            outRealUpperBand,
            outRealMiddleBand,
            outRealLowerBand,
        );
    }
    pub unsafe fn bbands_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        mut optInNbDevUp: f64,
        mut optInNbDevDn: f64,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [T],
        outRealMiddleBand: &mut [T],
        outRealLowerBand: &mut [T],
    ) -> RetCode {
        let mut retCode: RetCode;
        let i: i32;
        let mut tempReal: T;
        let mut tempReal2: T;
        let mut tempBuffer1: Vec<T>;
        let mut tempBuffer2: Vec<T>;
        if inReal == outRealUpperBand {
            tempBuffer1 = outRealMiddleBand;
            tempBuffer2 = outRealLowerBand;
        } else if inReal == outRealLowerBand {
            tempBuffer1 = outRealMiddleBand;
            tempBuffer2 = outRealUpperBand;
        } else if inReal == outRealMiddleBand {
            tempBuffer1 = outRealLowerBand;
            tempBuffer2 = outRealUpperBand;
        } else {
            tempBuffer1 = outRealMiddleBand;
            tempBuffer2 = outRealUpperBand;
        }
        if tempBuffer1 == inReal || tempBuffer2 == inReal {
            return RetCode::BadParam;
        }
        retCode = self.ma_unguarded(startIdx, endIdx, inReal, optInTimePeriod, optInMAType, outBegIdx, outNBElement, tempBuffer1);
        if retCode != RetCode::Success || (((*outNBElement)) as i32) == 0 {
            (*outNBElement) = 0;
            return retCode;
        }
        if optInMAType == TA_MAType_SMA {
            _startSum = 1 + (((*outBegIdx)) as i32) - optInTimePeriod;
            _endSum = ((*outBegIdx)) as i32;
            _periodTotal2 = 0;
            // for( _outIdx = _startSum; _outIdx < _endSum; _outIdx += 1 )
            _outIdx = _startSum;
            while _outIdx < _endSum {
                _tempReal = *inReal.get_unchecked(_outIdx);
                _tempReal *= _tempReal;
                _periodTotal2 += _tempReal;
                _outIdx += 1;
            }
            // for( _outIdx = 0; _outIdx < (((*outNBElement)) as i32); _outIdx += 1;
_startSum += 1;
_endSum += 1 )
            _outIdx = 0;
            while _outIdx < (((*outNBElement)) as i32) {
                _tempReal = *inReal.get_unchecked(_endSum);
                _tempReal *= _tempReal;
                _periodTotal2 += _tempReal;
                _meanValue2 = _periodTotal2 / optInTimePeriod;
                _tempReal = *inReal.get_unchecked(_startSum);
                _tempReal *= _tempReal;
                _periodTotal2 -= _tempReal;
                _tempReal = *tempBuffer1.get_unchecked(_outIdx);
                _tempReal *= _tempReal;
                _meanValue2 -= _tempReal;
                if !(_meanValue2 < T::ta_from_f64(0.00000001)) {
                    *tempBuffer2.get_unchecked_mut(_outIdx) = _meanValue2.ta_sqrt();
                } else {
                    *tempBuffer2.get_unchecked_mut(_outIdx) = T::ta_from_f64(0.0);
                }
                _outIdx += 1;
_startSum += 1;
_endSum += 1;
            }
        } else {
            retCode = self.stddev_unguarded(((*outBegIdx)) as i32, endIdx, inReal, optInTimePeriod, T::ta_from_f64(1.0), outBegIdx, outNBElement, tempBuffer2);
            if retCode != RetCode::Success {
                (*outNBElement) = 0;
                return retCode;
            }
        }
        if tempBuffer1 != outRealMiddleBand {
            {
            let _n = ((*outNBElement) * 1) as usize;
            let _di = (0) as usize;
            let _si = (0) as usize;
            outRealMiddleBand[_di.._di + _n].copy_from_slice(&tempBuffer1[_si.._si + _n]);
        };
        }
        if T::ta_from_f64(optInNbDevUp) == T::ta_from_f64(optInNbDevDn) {
            if T::ta_from_f64(optInNbDevUp) == T::ta_from_f64(1.0) {
                // for( i = 0; i < (((*outNBElement)) as i32); i += 1 )
                i = 0;
                while i < (((*outNBElement)) as i32) {
                    tempReal = *tempBuffer2.get_unchecked(i);
                    tempReal2 = *outRealMiddleBand.get_unchecked(i);
                    *outRealUpperBand.get_unchecked_mut(i) = tempReal2 + tempReal;
                    *outRealLowerBand.get_unchecked_mut(i) = tempReal2 - tempReal;
                    i += 1;
                }
            } else {
                // for( i = 0; i < (((*outNBElement)) as i32); i += 1 )
                i = 0;
                while i < (((*outNBElement)) as i32) {
                    tempReal = *tempBuffer2.get_unchecked(i) * T::ta_from_f64(optInNbDevUp);
                    tempReal2 = *outRealMiddleBand.get_unchecked(i);
                    *outRealUpperBand.get_unchecked_mut(i) = tempReal2 + tempReal;
                    *outRealLowerBand.get_unchecked_mut(i) = tempReal2 - tempReal;
                    i += 1;
                }
            }
        } else if T::ta_from_f64(optInNbDevUp) == T::ta_from_f64(1.0) {
            // for( i = 0; i < (((*outNBElement)) as i32); i += 1 )
            i = 0;
            while i < (((*outNBElement)) as i32) {
                tempReal = *tempBuffer2.get_unchecked(i);
                tempReal2 = *outRealMiddleBand.get_unchecked(i);
                *outRealUpperBand.get_unchecked_mut(i) = tempReal2 + tempReal;
                *outRealLowerBand.get_unchecked_mut(i) = tempReal2 - tempReal * T::ta_from_f64(optInNbDevDn);
                i += 1;
            }
        } else if T::ta_from_f64(optInNbDevDn) == T::ta_from_f64(1.0) {
            // for( i = 0; i < (((*outNBElement)) as i32); i += 1 )
            i = 0;
            while i < (((*outNBElement)) as i32) {
                tempReal = *tempBuffer2.get_unchecked(i);
                tempReal2 = *outRealMiddleBand.get_unchecked(i);
                *outRealLowerBand.get_unchecked_mut(i) = tempReal2 - tempReal;
                *outRealUpperBand.get_unchecked_mut(i) = tempReal2 + tempReal * T::ta_from_f64(optInNbDevUp);
                i += 1;
            }
        } else {
            // for( i = 0; i < (((*outNBElement)) as i32); i += 1 )
            i = 0;
            while i < (((*outNBElement)) as i32) {
                tempReal = *tempBuffer2.get_unchecked(i);
                tempReal2 = *outRealMiddleBand.get_unchecked(i);
                *outRealUpperBand.get_unchecked_mut(i) = tempReal2 + tempReal * T::ta_from_f64(optInNbDevUp);
                *outRealLowerBand.get_unchecked_mut(i) = tempReal2 - tempReal * T::ta_from_f64(optInNbDevDn);
                i += 1;
            }
        }
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
