/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::beta`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 5, range: 1..=100000)
    pub fn beta_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        return optInTimePeriod;
    }
    /// Beta
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal0` - Input price series
    /// * `inReal1` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 5, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn beta<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal0: &[T],
        inReal1: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.beta_unguarded(
            startIdx,
            endIdx,
            inReal0,
            inReal1,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn beta_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal0: &[T],
        inReal1: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut S_xx: T;
        let mut S_xy: T;
        let mut S_x: T;
        let mut S_y: T;
        let mut last_price_x: T;
        let mut last_price_y: T;
        let mut trailing_last_price_x: T;
        let mut trailing_last_price_y: T;
        let mut tmp_real: T;
        let mut x: T;
        let mut y: T;
        let mut n: T;
        S_xx = T::ta_from_f64(0.0);
        S_xy = T::ta_from_f64(0.0);
        S_x = T::ta_from_f64(0.0);
        S_y = T::ta_from_f64(0.0);
        last_price_x = T::ta_from_f64(0.0);
        last_price_y = T::ta_from_f64(0.0);
        trailing_last_price_x = T::ta_from_f64(0.0);
        trailing_last_price_y = T::ta_from_f64(0.0);
        tmp_real = T::ta_from_f64(0.0);
        nbInitialElementNeeded = optInTimePeriod;
        if startIdx < nbInitialElementNeeded {
            startIdx = nbInitialElementNeeded;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        trailingIdx = startIdx - nbInitialElementNeeded;
        trailing_last_price_x = inReal0[trailingIdx];
        last_price_x = trailing_last_price_x;
        trailing_last_price_y = inReal1[trailingIdx];
        last_price_y = trailing_last_price_y;
        i = { trailingIdx += 1; trailingIdx };
        while i < startIdx {
            tmp_real = inReal0[i];
            if !(0 - T::ta_from_f64(0.00000001) < last_price_x && last_price_x < T::ta_from_f64(0.00000001)) {
                x = (tmp_real - last_price_x) / last_price_x;
            } else {
                x = T::ta_from_f64(0.0);
            }
            last_price_x = tmp_real;
            tmp_real = inReal1[{ let _v = i; i += 1; _v }];
            if !(0 - T::ta_from_f64(0.00000001) < last_price_y && last_price_y < T::ta_from_f64(0.00000001)) {
                y = (tmp_real - last_price_y) / last_price_y;
            } else {
                y = T::ta_from_f64(0.0);
            }
            last_price_y = tmp_real;
            S_xx += x * x;
            S_xy += x * y;
            S_x += x;
            S_y += y;
        }
        outIdx = 0;
        n = T::ta_from_f64((optInTimePeriod).ta_to_f64());
        loop {
            tmp_real = inReal0[i];
            if !(0 - T::ta_from_f64(0.00000001) < last_price_x && last_price_x < T::ta_from_f64(0.00000001)) {
                x = (tmp_real - last_price_x) / last_price_x;
            } else {
                x = T::ta_from_f64(0.0);
            }
            last_price_x = tmp_real;
            tmp_real = inReal1[{ let _v = i; i += 1; _v }];
            if !(0 - T::ta_from_f64(0.00000001) < last_price_y && last_price_y < T::ta_from_f64(0.00000001)) {
                y = (tmp_real - last_price_y) / last_price_y;
            } else {
                y = T::ta_from_f64(0.0);
            }
            last_price_y = tmp_real;
            S_xx += x * x;
            S_xy += x * y;
            S_x += x;
            S_y += y;
            tmp_real = inReal0[trailingIdx];
            if !(0 - T::ta_from_f64(0.00000001) < trailing_last_price_x && trailing_last_price_x < T::ta_from_f64(0.00000001)) {
                x = (tmp_real - trailing_last_price_x) / trailing_last_price_x;
            } else {
                x = T::ta_from_f64(0.0);
            }
            trailing_last_price_x = tmp_real;
            tmp_real = inReal1[{ let _v = trailingIdx; trailingIdx += 1; _v }];
            if !(0 - T::ta_from_f64(0.00000001) < trailing_last_price_y && trailing_last_price_y < T::ta_from_f64(0.00000001)) {
                y = (tmp_real - trailing_last_price_y) / trailing_last_price_y;
            } else {
                y = T::ta_from_f64(0.0);
            }
            trailing_last_price_y = tmp_real;
            tmp_real = n * S_xx - S_x * S_x;
            if !(0 - T::ta_from_f64(0.00000001) < tmp_real && tmp_real < T::ta_from_f64(0.00000001)) {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = (n * S_xy - S_x * S_y) / tmp_real;
            } else {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = T::ta_from_f64(0.0);
            }
            S_xx -= x * x;
            S_xy -= x * y;
            S_x -= x;
            S_y -= y;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn beta_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal0: &[T],
        inReal1: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.beta_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal0,
            inReal1,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn beta_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal0: &[T],
        inReal1: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut S_xx: T;
        let mut S_xy: T;
        let mut S_x: T;
        let mut S_y: T;
        let mut last_price_x: T;
        let mut last_price_y: T;
        let mut trailing_last_price_x: T;
        let mut trailing_last_price_y: T;
        let mut tmp_real: T;
        let mut x: T;
        let mut y: T;
        let mut n: T;
        S_xx = T::ta_from_f64(0.0);
        S_xy = T::ta_from_f64(0.0);
        S_x = T::ta_from_f64(0.0);
        S_y = T::ta_from_f64(0.0);
        last_price_x = T::ta_from_f64(0.0);
        last_price_y = T::ta_from_f64(0.0);
        trailing_last_price_x = T::ta_from_f64(0.0);
        trailing_last_price_y = T::ta_from_f64(0.0);
        tmp_real = T::ta_from_f64(0.0);
        nbInitialElementNeeded = optInTimePeriod;
        if startIdx < nbInitialElementNeeded {
            startIdx = nbInitialElementNeeded;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        trailingIdx = startIdx - nbInitialElementNeeded;
        trailing_last_price_x = *inReal0.get_unchecked(trailingIdx);
        last_price_x = trailing_last_price_x;
        trailing_last_price_y = *inReal1.get_unchecked(trailingIdx);
        last_price_y = trailing_last_price_y;
        i = { trailingIdx += 1; trailingIdx };
        while i < startIdx {
            tmp_real = *inReal0.get_unchecked(i);
            if !(0 - T::ta_from_f64(0.00000001) < last_price_x && last_price_x < T::ta_from_f64(0.00000001)) {
                x = (tmp_real - last_price_x) / last_price_x;
            } else {
                x = T::ta_from_f64(0.0);
            }
            last_price_x = tmp_real;
            tmp_real = *inReal1.get_unchecked({ let _v = i; i += 1; _v });
            if !(0 - T::ta_from_f64(0.00000001) < last_price_y && last_price_y < T::ta_from_f64(0.00000001)) {
                y = (tmp_real - last_price_y) / last_price_y;
            } else {
                y = T::ta_from_f64(0.0);
            }
            last_price_y = tmp_real;
            S_xx += x * x;
            S_xy += x * y;
            S_x += x;
            S_y += y;
        }
        outIdx = 0;
        n = T::ta_from_f64((optInTimePeriod).ta_to_f64());
        loop {
            tmp_real = *inReal0.get_unchecked(i);
            if !(0 - T::ta_from_f64(0.00000001) < last_price_x && last_price_x < T::ta_from_f64(0.00000001)) {
                x = (tmp_real - last_price_x) / last_price_x;
            } else {
                x = T::ta_from_f64(0.0);
            }
            last_price_x = tmp_real;
            tmp_real = *inReal1.get_unchecked({ let _v = i; i += 1; _v });
            if !(0 - T::ta_from_f64(0.00000001) < last_price_y && last_price_y < T::ta_from_f64(0.00000001)) {
                y = (tmp_real - last_price_y) / last_price_y;
            } else {
                y = T::ta_from_f64(0.0);
            }
            last_price_y = tmp_real;
            S_xx += x * x;
            S_xy += x * y;
            S_x += x;
            S_y += y;
            tmp_real = *inReal0.get_unchecked(trailingIdx);
            if !(0 - T::ta_from_f64(0.00000001) < trailing_last_price_x && trailing_last_price_x < T::ta_from_f64(0.00000001)) {
                x = (tmp_real - trailing_last_price_x) / trailing_last_price_x;
            } else {
                x = T::ta_from_f64(0.0);
            }
            trailing_last_price_x = tmp_real;
            tmp_real = *inReal1.get_unchecked({ let _v = trailingIdx; trailingIdx += 1; _v });
            if !(0 - T::ta_from_f64(0.00000001) < trailing_last_price_y && trailing_last_price_y < T::ta_from_f64(0.00000001)) {
                y = (tmp_real - trailing_last_price_y) / trailing_last_price_y;
            } else {
                y = T::ta_from_f64(0.0);
            }
            trailing_last_price_y = tmp_real;
            tmp_real = n * S_xx - S_x * S_x;
            if !(0 - T::ta_from_f64(0.00000001) < tmp_real && tmp_real < T::ta_from_f64(0.00000001)) {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = (n * S_xy - S_x * S_y) / tmp_real;
            } else {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = T::ta_from_f64(0.0);
            }
            S_xx -= x * x;
            S_xy -= x * y;
            S_x -= x;
            S_y -= y;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
