/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cci`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    pub fn cci_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        return optInTimePeriod - 1;
    }
    /// Commodity Channel Index
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn cci<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.cci_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn cci_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut tempReal: T;
        let mut tempReal2: T;
        let mut theAverage: T;
        let mut lastValue: T;
        let mut i: i32;
        let j: i32;
        let outIdx: i32;
        let lookbackTotal: i32;
        let mut circBuffer: [T; 30 as usize] = [T::zero(); 30 as usize];
        let mut circBuffer_Idx: i32;
        lookbackTotal = optInTimePeriod - 1;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        {
            let _n = (optInTimePeriod * 1) as usize;
            let _si = (0) as usize;
            circBuffer[_si.._si + _n].fill(T::default());
        };
        circBuffer_Idx = 0;
        i = startIdx - lookbackTotal;
        if optInTimePeriod > 1 {
            while i < startIdx {
                circBuffer[circBuffer_Idx] = (inHigh[i] + inLow[i] + inClose[i]) / 3;
                i += 1;
                circBuffer_Idx = (circBuffer_Idx + 1) % optInTimePeriod;
            }
        }
        outIdx = 0;
        loop {
            lastValue = (inHigh[i] + inLow[i] + inClose[i]) / 3;
            circBuffer[circBuffer_Idx] = lastValue;
            theAverage = 0;
            // for( j = 0; j < optInTimePeriod; j += 1 )
            j = 0;
            while j < optInTimePeriod {
                theAverage += circBuffer[j];
                j += 1;
            }
            theAverage /= optInTimePeriod;
            tempReal2 = 0;
            // for( j = 0; j < optInTimePeriod; j += 1 )
            j = 0;
            while j < optInTimePeriod {
                tempReal2 += circBuffer[j] - theAverage.ta_abs();
                j += 1;
            }
            tempReal = lastValue - theAverage;
            if tempReal != T::ta_from_f64(0.0) && tempReal2 != T::ta_from_f64(0.0) {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = tempReal / (T::ta_from_f64(0.015) * (tempReal2 / optInTimePeriod));
            } else {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = T::ta_from_f64(0.0);
            }
            circBuffer_Idx = (circBuffer_Idx + 1) % optInTimePeriod;
            i += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    pub unsafe fn cci_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.cci_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn cci_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut tempReal: T;
        let mut tempReal2: T;
        let mut theAverage: T;
        let mut lastValue: T;
        let mut i: i32;
        let j: i32;
        let outIdx: i32;
        let lookbackTotal: i32;
        let mut circBuffer: [T; 30 as usize] = [T::zero(); 30 as usize];
        let mut circBuffer_Idx: i32;
        lookbackTotal = optInTimePeriod - 1;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        {
            let _n = (optInTimePeriod * 1) as usize;
            let _si = (0) as usize;
            circBuffer[_si.._si + _n].fill(T::default());
        };
        circBuffer_Idx = 0;
        i = startIdx - lookbackTotal;
        if optInTimePeriod > 1 {
            while i < startIdx {
                *circBuffer.get_unchecked_mut(circBuffer_Idx) = (*inHigh.get_unchecked(i) + *inLow.get_unchecked(i) + *inClose.get_unchecked(i)) / 3;
                i += 1;
                circBuffer_Idx = (circBuffer_Idx + 1) % optInTimePeriod;
            }
        }
        outIdx = 0;
        loop {
            lastValue = (*inHigh.get_unchecked(i) + *inLow.get_unchecked(i) + *inClose.get_unchecked(i)) / 3;
            *circBuffer.get_unchecked_mut(circBuffer_Idx) = lastValue;
            theAverage = 0;
            // for( j = 0; j < optInTimePeriod; j += 1 )
            j = 0;
            while j < optInTimePeriod {
                theAverage += *circBuffer.get_unchecked(j);
                j += 1;
            }
            theAverage /= optInTimePeriod;
            tempReal2 = 0;
            // for( j = 0; j < optInTimePeriod; j += 1 )
            j = 0;
            while j < optInTimePeriod {
                tempReal2 += *circBuffer.get_unchecked(j) - theAverage.ta_abs();
                j += 1;
            }
            tempReal = lastValue - theAverage;
            if tempReal != T::ta_from_f64(0.0) && tempReal2 != T::ta_from_f64(0.0) {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = tempReal / (T::ta_from_f64(0.015) * (tempReal2 / optInTimePeriod));
            } else {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = T::ta_from_f64(0.0);
            }
            circBuffer_Idx = (circBuffer_Idx + 1) % optInTimePeriod;
            i += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
