/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdl3whitesoldiers`].
    ///
    /// # Arguments
    ///
    pub fn cdl3whitesoldiers_lookback(&self) -> i32 {
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let Far_rangeType: i32 = self.candle_settings.far.range_type;
        #[allow(non_snake_case)]
        let Far_avgPeriod: i32 = self.candle_settings.far.avg_period;
        #[allow(non_snake_case)]
        let Far_factor: f64 = self.candle_settings.far.factor;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        return ((ShadowVeryShort_avgPeriod).max(BodyShort_avgPeriod)).max((Far_avgPeriod).max(Near_avgPeriod)) + 2;
    }
    /// Three Advancing White Soldiers
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdl3whitesoldiers<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdl3whitesoldiers_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdl3whitesoldiers_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut ShadowVeryShortPeriodTotal: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut NearPeriodTotal: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut FarPeriodTotal: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut BodyShortPeriodTotal: T;
        let mut i: i32;
        let outIdx: i32;
        let totIdx: i32;
        let mut ShadowVeryShortTrailingIdx: i32;
        let mut NearTrailingIdx: i32;
        let mut FarTrailingIdx: i32;
        let mut BodyShortTrailingIdx: i32;
        let lookbackTotal: i32;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let Far_rangeType: i32 = self.candle_settings.far.range_type;
        #[allow(non_snake_case)]
        let Far_avgPeriod: i32 = self.candle_settings.far.avg_period;
        #[allow(non_snake_case)]
        let Far_factor: f64 = self.candle_settings.far.factor;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        lookbackTotal = self.cdl3whitesoldiers_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        ShadowVeryShortPeriodTotal[2] = 0;
        ShadowVeryShortPeriodTotal[1] = 0;
        ShadowVeryShortPeriodTotal[0] = 0;
        ShadowVeryShortTrailingIdx = startIdx - ShadowVeryShort_avgPeriod;
        NearPeriodTotal[2] = 0;
        NearPeriodTotal[1] = 0;
        NearPeriodTotal[0] = 0;
        NearTrailingIdx = startIdx - Near_avgPeriod;
        FarPeriodTotal[2] = 0;
        FarPeriodTotal[1] = 0;
        FarPeriodTotal[0] = 0;
        FarTrailingIdx = startIdx - Far_avgPeriod;
        BodyShortPeriodTotal = 0;
        BodyShortTrailingIdx = startIdx - BodyShort_avgPeriod;
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_0 = inClose[i - 2] - inOpen[i - 2].ta_abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_0 = inHigh[i - 2] - inLow[i - 2] - inClose[i - 2] - inOpen[i - 2].ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryShortPeriodTotal[2] = ShadowVeryShortPeriodTotal[2] + _candlerange_0;
            let mut _candlerange_1: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_1 = inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_1 = inHigh[i - 1] - inLow[i - 1] - inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryShortPeriodTotal[1] = ShadowVeryShortPeriodTotal[1] + _candlerange_1;
            let mut _candlerange_2: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_2 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_2 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryShortPeriodTotal[0] = ShadowVeryShortPeriodTotal[0] + _candlerange_2;
            i += 1;
        }
        i = NearTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: T;
            match Near_rangeType {
                0 => {
                    _candlerange_3 = inClose[i - 2] - inOpen[i - 2].ta_abs();
                }
                1 => {
                    _candlerange_3 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_3 = inHigh[i - 2] - inLow[i - 2] - inClose[i - 2] - inOpen[i - 2].ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            NearPeriodTotal[2] = NearPeriodTotal[2] + _candlerange_3;
            let mut _candlerange_4: T;
            match Near_rangeType {
                0 => {
                    _candlerange_4 = inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                1 => {
                    _candlerange_4 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_4 = inHigh[i - 1] - inLow[i - 1] - inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            NearPeriodTotal[1] = NearPeriodTotal[1] + _candlerange_4;
            i += 1;
        }
        i = FarTrailingIdx;
        while i < startIdx {
            let mut _candlerange_5: T;
            match Far_rangeType {
                0 => {
                    _candlerange_5 = inClose[i - 2] - inOpen[i - 2].ta_abs();
                }
                1 => {
                    _candlerange_5 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_5 = inHigh[i - 2] - inLow[i - 2] - inClose[i - 2] - inOpen[i - 2].ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            FarPeriodTotal[2] = FarPeriodTotal[2] + _candlerange_5;
            let mut _candlerange_6: T;
            match Far_rangeType {
                0 => {
                    _candlerange_6 = inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                1 => {
                    _candlerange_6 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_6 = inHigh[i - 1] - inLow[i - 1] - inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                _ => {
                    _candlerange_6 = T::ta_from_f64(0.0);
                }
            }
            FarPeriodTotal[1] = FarPeriodTotal[1] + _candlerange_6;
            i += 1;
        }
        i = BodyShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_7: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_7 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_7 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_7 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_7 = T::ta_from_f64(0.0);
                }
            }
            BodyShortPeriodTotal += _candlerange_7;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if if inClose[i - 2] >= inOpen[i - 2] { 1 } else { 0 - 1 } == 1 && inHigh[i - 2] - if inClose[i - 2] >= inOpen[i - 2] { inClose[i - 2] } else { inOpen[i - 2] } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, ShadowVeryShortPeriodTotal[2], inOpen[i - 2], inHigh[i - 2], inLow[i - 2], inClose[i - 2]) && if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 } == 1 && inHigh[i - 1] - if inClose[i - 1] >= inOpen[i - 1] { inClose[i - 1] } else { inOpen[i - 1] } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, ShadowVeryShortPeriodTotal[1], inOpen[i - 1], inHigh[i - 1], inLow[i - 1], inClose[i - 1]) && if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 } == 1 && inHigh[i] - if inClose[i] >= inOpen[i] { inClose[i] } else { inOpen[i] } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, ShadowVeryShortPeriodTotal[0], inOpen[i], inHigh[i], inLow[i], inClose[i]) && inClose[i] > inClose[i - 1] && inClose[i - 1] > inClose[i - 2] && inOpen[i - 1] > inOpen[i - 2] && inOpen[i - 1] <= inClose[i - 2] + ta_candleaverage(Near_rangeType, Near_avgPeriod, Near_factor, NearPeriodTotal[2], inOpen[i - 2], inHigh[i - 2], inLow[i - 2], inClose[i - 2]) && inOpen[i] > inOpen[i - 1] && inOpen[i] <= inClose[i - 1] + ta_candleaverage(Near_rangeType, Near_avgPeriod, Near_factor, NearPeriodTotal[1], inOpen[i - 1], inHigh[i - 1], inLow[i - 1], inClose[i - 1]) && inClose[i - 1] - inOpen[i - 1].ta_abs() > inClose[i - 2] - inOpen[i - 2].ta_abs() - ta_candleaverage(Far_rangeType, Far_avgPeriod, Far_factor, FarPeriodTotal[2], inOpen[i - 2], inHigh[i - 2], inLow[i - 2], inClose[i - 2]) && inClose[i] - inOpen[i].ta_abs() > inClose[i - 1] - inOpen[i - 1].ta_abs() - ta_candleaverage(Far_rangeType, Far_avgPeriod, Far_factor, FarPeriodTotal[1], inOpen[i - 1], inHigh[i - 1], inLow[i - 1], inClose[i - 1]) && inClose[i] - inOpen[i].ta_abs() > ta_candleaverage(BodyShort_rangeType, BodyShort_avgPeriod, BodyShort_factor, BodyShortPeriodTotal, inOpen[i], inHigh[i], inLow[i], inClose[i]) {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 100;
            } else {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 0;
            }
            // for( totIdx = 2; totIdx >= 0; totIdx -= 1 )
            totIdx = 2;
            while totIdx >= 0 {
                let mut _candlerange_8: T;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_8 = inClose[i - totIdx] - inOpen[i - totIdx].ta_abs();
                    }
                    1 => {
                        _candlerange_8 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_8 = inHigh[i - totIdx] - inLow[i - totIdx] - inClose[i - totIdx] - inOpen[i - totIdx].ta_abs();
                    }
                    _ => {
                        _candlerange_8 = T::ta_from_f64(0.0);
                    }
                }
                let mut _candlerange_9: T;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_9 = inClose[ShadowVeryShortTrailingIdx - totIdx] - inOpen[ShadowVeryShortTrailingIdx - totIdx].ta_abs();
                    }
                    1 => {
                        _candlerange_9 = inHigh[ShadowVeryShortTrailingIdx - totIdx] - inLow[ShadowVeryShortTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_9 = inHigh[ShadowVeryShortTrailingIdx - totIdx] - inLow[ShadowVeryShortTrailingIdx - totIdx] - inClose[ShadowVeryShortTrailingIdx - totIdx] - inOpen[ShadowVeryShortTrailingIdx - totIdx].ta_abs();
                    }
                    _ => {
                        _candlerange_9 = T::ta_from_f64(0.0);
                    }
                }
                ShadowVeryShortPeriodTotal[totIdx] = ShadowVeryShortPeriodTotal[totIdx] + (_candlerange_8 - _candlerange_9);
                totIdx -= 1;
            }
            // for( totIdx = 2; totIdx >= 1; totIdx -= 1 )
            totIdx = 2;
            while totIdx >= 1 {
                let mut _candlerange_10: T;
                match Far_rangeType {
                    0 => {
                        _candlerange_10 = inClose[i - totIdx] - inOpen[i - totIdx].ta_abs();
                    }
                    1 => {
                        _candlerange_10 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_10 = inHigh[i - totIdx] - inLow[i - totIdx] - inClose[i - totIdx] - inOpen[i - totIdx].ta_abs();
                    }
                    _ => {
                        _candlerange_10 = T::ta_from_f64(0.0);
                    }
                }
                let mut _candlerange_11: T;
                match Far_rangeType {
                    0 => {
                        _candlerange_11 = inClose[FarTrailingIdx - totIdx] - inOpen[FarTrailingIdx - totIdx].ta_abs();
                    }
                    1 => {
                        _candlerange_11 = inHigh[FarTrailingIdx - totIdx] - inLow[FarTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_11 = inHigh[FarTrailingIdx - totIdx] - inLow[FarTrailingIdx - totIdx] - inClose[FarTrailingIdx - totIdx] - inOpen[FarTrailingIdx - totIdx].ta_abs();
                    }
                    _ => {
                        _candlerange_11 = T::ta_from_f64(0.0);
                    }
                }
                FarPeriodTotal[totIdx] = FarPeriodTotal[totIdx] + (_candlerange_10 - _candlerange_11);
                let mut _candlerange_12: T;
                match Near_rangeType {
                    0 => {
                        _candlerange_12 = inClose[i - totIdx] - inOpen[i - totIdx].ta_abs();
                    }
                    1 => {
                        _candlerange_12 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_12 = inHigh[i - totIdx] - inLow[i - totIdx] - inClose[i - totIdx] - inOpen[i - totIdx].ta_abs();
                    }
                    _ => {
                        _candlerange_12 = T::ta_from_f64(0.0);
                    }
                }
                let mut _candlerange_13: T;
                match Near_rangeType {
                    0 => {
                        _candlerange_13 = inClose[NearTrailingIdx - totIdx] - inOpen[NearTrailingIdx - totIdx].ta_abs();
                    }
                    1 => {
                        _candlerange_13 = inHigh[NearTrailingIdx - totIdx] - inLow[NearTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_13 = inHigh[NearTrailingIdx - totIdx] - inLow[NearTrailingIdx - totIdx] - inClose[NearTrailingIdx - totIdx] - inOpen[NearTrailingIdx - totIdx].ta_abs();
                    }
                    _ => {
                        _candlerange_13 = T::ta_from_f64(0.0);
                    }
                }
                NearPeriodTotal[totIdx] = NearPeriodTotal[totIdx] + (_candlerange_12 - _candlerange_13);
                totIdx -= 1;
            }
            let mut _candlerange_14: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_14 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_14 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_14 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_14 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_15: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_15 = inClose[BodyShortTrailingIdx] - inOpen[BodyShortTrailingIdx].ta_abs();
                }
                1 => {
                    _candlerange_15 = inHigh[BodyShortTrailingIdx] - inLow[BodyShortTrailingIdx];
                }
                2 => {
                    _candlerange_15 = inHigh[BodyShortTrailingIdx] - inLow[BodyShortTrailingIdx] - inClose[BodyShortTrailingIdx] - inOpen[BodyShortTrailingIdx].ta_abs();
                }
                _ => {
                    _candlerange_15 = T::ta_from_f64(0.0);
                }
            }
            BodyShortPeriodTotal += _candlerange_14 - _candlerange_15;
            i += 1;
            ShadowVeryShortTrailingIdx += 1;
            NearTrailingIdx += 1;
            FarTrailingIdx += 1;
            BodyShortTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    pub unsafe fn cdl3whitesoldiers_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdl3whitesoldiers_unguarded_unchecked(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn cdl3whitesoldiers_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut ShadowVeryShortPeriodTotal: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut NearPeriodTotal: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut FarPeriodTotal: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut BodyShortPeriodTotal: T;
        let mut i: i32;
        let outIdx: i32;
        let totIdx: i32;
        let mut ShadowVeryShortTrailingIdx: i32;
        let mut NearTrailingIdx: i32;
        let mut FarTrailingIdx: i32;
        let mut BodyShortTrailingIdx: i32;
        let lookbackTotal: i32;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let Far_rangeType: i32 = self.candle_settings.far.range_type;
        #[allow(non_snake_case)]
        let Far_avgPeriod: i32 = self.candle_settings.far.avg_period;
        #[allow(non_snake_case)]
        let Far_factor: f64 = self.candle_settings.far.factor;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        lookbackTotal = self.cdl3whitesoldiers_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        *ShadowVeryShortPeriodTotal.get_unchecked_mut(2) = 0;
        *ShadowVeryShortPeriodTotal.get_unchecked_mut(1) = 0;
        *ShadowVeryShortPeriodTotal.get_unchecked_mut(0) = 0;
        ShadowVeryShortTrailingIdx = startIdx - ShadowVeryShort_avgPeriod;
        *NearPeriodTotal.get_unchecked_mut(2) = 0;
        *NearPeriodTotal.get_unchecked_mut(1) = 0;
        *NearPeriodTotal.get_unchecked_mut(0) = 0;
        NearTrailingIdx = startIdx - Near_avgPeriod;
        *FarPeriodTotal.get_unchecked_mut(2) = 0;
        *FarPeriodTotal.get_unchecked_mut(1) = 0;
        *FarPeriodTotal.get_unchecked_mut(0) = 0;
        FarTrailingIdx = startIdx - Far_avgPeriod;
        BodyShortPeriodTotal = 0;
        BodyShortTrailingIdx = startIdx - BodyShort_avgPeriod;
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_0 = *inClose.get_unchecked(i - 2) - *inOpen.get_unchecked(i - 2).ta_abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.get_unchecked(i - 2) - *inLow.get_unchecked(i - 2);
                }
                2 => {
                    _candlerange_0 = *inHigh.get_unchecked(i - 2) - *inLow.get_unchecked(i - 2) - *inClose.get_unchecked(i - 2) - *inOpen.get_unchecked(i - 2).ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            *ShadowVeryShortPeriodTotal.get_unchecked_mut(2) = *ShadowVeryShortPeriodTotal.get_unchecked(2) + _candlerange_0;
            let mut _candlerange_1: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_1 = *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1);
                }
                2 => {
                    _candlerange_1 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1) - *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            *ShadowVeryShortPeriodTotal.get_unchecked_mut(1) = *ShadowVeryShortPeriodTotal.get_unchecked(1) + _candlerange_1;
            let mut _candlerange_2: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_2 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_2 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            *ShadowVeryShortPeriodTotal.get_unchecked_mut(0) = *ShadowVeryShortPeriodTotal.get_unchecked(0) + _candlerange_2;
            i += 1;
        }
        i = NearTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: T;
            match Near_rangeType {
                0 => {
                    _candlerange_3 = *inClose.get_unchecked(i - 2) - *inOpen.get_unchecked(i - 2).ta_abs();
                }
                1 => {
                    _candlerange_3 = *inHigh.get_unchecked(i - 2) - *inLow.get_unchecked(i - 2);
                }
                2 => {
                    _candlerange_3 = *inHigh.get_unchecked(i - 2) - *inLow.get_unchecked(i - 2) - *inClose.get_unchecked(i - 2) - *inOpen.get_unchecked(i - 2).ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            *NearPeriodTotal.get_unchecked_mut(2) = *NearPeriodTotal.get_unchecked(2) + _candlerange_3;
            let mut _candlerange_4: T;
            match Near_rangeType {
                0 => {
                    _candlerange_4 = *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                1 => {
                    _candlerange_4 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1);
                }
                2 => {
                    _candlerange_4 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1) - *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            *NearPeriodTotal.get_unchecked_mut(1) = *NearPeriodTotal.get_unchecked(1) + _candlerange_4;
            i += 1;
        }
        i = FarTrailingIdx;
        while i < startIdx {
            let mut _candlerange_5: T;
            match Far_rangeType {
                0 => {
                    _candlerange_5 = *inClose.get_unchecked(i - 2) - *inOpen.get_unchecked(i - 2).ta_abs();
                }
                1 => {
                    _candlerange_5 = *inHigh.get_unchecked(i - 2) - *inLow.get_unchecked(i - 2);
                }
                2 => {
                    _candlerange_5 = *inHigh.get_unchecked(i - 2) - *inLow.get_unchecked(i - 2) - *inClose.get_unchecked(i - 2) - *inOpen.get_unchecked(i - 2).ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            *FarPeriodTotal.get_unchecked_mut(2) = *FarPeriodTotal.get_unchecked(2) + _candlerange_5;
            let mut _candlerange_6: T;
            match Far_rangeType {
                0 => {
                    _candlerange_6 = *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                1 => {
                    _candlerange_6 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1);
                }
                2 => {
                    _candlerange_6 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1) - *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                _ => {
                    _candlerange_6 = T::ta_from_f64(0.0);
                }
            }
            *FarPeriodTotal.get_unchecked_mut(1) = *FarPeriodTotal.get_unchecked(1) + _candlerange_6;
            i += 1;
        }
        i = BodyShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_7: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_7 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_7 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_7 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_7 = T::ta_from_f64(0.0);
                }
            }
            BodyShortPeriodTotal += _candlerange_7;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if if *inClose.get_unchecked(i - 2) >= *inOpen.get_unchecked(i - 2) { 1 } else { 0 - 1 } == 1 && *inHigh.get_unchecked(i - 2) - if *inClose.get_unchecked(i - 2) >= *inOpen.get_unchecked(i - 2) { *inClose.get_unchecked(i - 2) } else { *inOpen.get_unchecked(i - 2) } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, *ShadowVeryShortPeriodTotal.get_unchecked(2), *inOpen.get_unchecked(i - 2), *inHigh.get_unchecked(i - 2), *inLow.get_unchecked(i - 2), *inClose.get_unchecked(i - 2)) && if *inClose.get_unchecked(i - 1) >= *inOpen.get_unchecked(i - 1) { 1 } else { 0 - 1 } == 1 && *inHigh.get_unchecked(i - 1) - if *inClose.get_unchecked(i - 1) >= *inOpen.get_unchecked(i - 1) { *inClose.get_unchecked(i - 1) } else { *inOpen.get_unchecked(i - 1) } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, *ShadowVeryShortPeriodTotal.get_unchecked(1), *inOpen.get_unchecked(i - 1), *inHigh.get_unchecked(i - 1), *inLow.get_unchecked(i - 1), *inClose.get_unchecked(i - 1)) && if *inClose.get_unchecked(i) >= *inOpen.get_unchecked(i) { 1 } else { 0 - 1 } == 1 && *inHigh.get_unchecked(i) - if *inClose.get_unchecked(i) >= *inOpen.get_unchecked(i) { *inClose.get_unchecked(i) } else { *inOpen.get_unchecked(i) } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, *ShadowVeryShortPeriodTotal.get_unchecked(0), *inOpen.get_unchecked(i), *inHigh.get_unchecked(i), *inLow.get_unchecked(i), *inClose.get_unchecked(i)) && *inClose.get_unchecked(i) > *inClose.get_unchecked(i - 1) && *inClose.get_unchecked(i - 1) > *inClose.get_unchecked(i - 2) && *inOpen.get_unchecked(i - 1) > *inOpen.get_unchecked(i - 2) && *inOpen.get_unchecked(i - 1) <= *inClose.get_unchecked(i - 2) + ta_candleaverage(Near_rangeType, Near_avgPeriod, Near_factor, *NearPeriodTotal.get_unchecked(2), *inOpen.get_unchecked(i - 2), *inHigh.get_unchecked(i - 2), *inLow.get_unchecked(i - 2), *inClose.get_unchecked(i - 2)) && *inOpen.get_unchecked(i) > *inOpen.get_unchecked(i - 1) && *inOpen.get_unchecked(i) <= *inClose.get_unchecked(i - 1) + ta_candleaverage(Near_rangeType, Near_avgPeriod, Near_factor, *NearPeriodTotal.get_unchecked(1), *inOpen.get_unchecked(i - 1), *inHigh.get_unchecked(i - 1), *inLow.get_unchecked(i - 1), *inClose.get_unchecked(i - 1)) && *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs() > *inClose.get_unchecked(i - 2) - *inOpen.get_unchecked(i - 2).ta_abs() - ta_candleaverage(Far_rangeType, Far_avgPeriod, Far_factor, *FarPeriodTotal.get_unchecked(2), *inOpen.get_unchecked(i - 2), *inHigh.get_unchecked(i - 2), *inLow.get_unchecked(i - 2), *inClose.get_unchecked(i - 2)) && *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs() > *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs() - ta_candleaverage(Far_rangeType, Far_avgPeriod, Far_factor, *FarPeriodTotal.get_unchecked(1), *inOpen.get_unchecked(i - 1), *inHigh.get_unchecked(i - 1), *inLow.get_unchecked(i - 1), *inClose.get_unchecked(i - 1)) && *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs() > ta_candleaverage(BodyShort_rangeType, BodyShort_avgPeriod, BodyShort_factor, BodyShortPeriodTotal, *inOpen.get_unchecked(i), *inHigh.get_unchecked(i), *inLow.get_unchecked(i), *inClose.get_unchecked(i)) {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 100;
            } else {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 0;
            }
            // for( totIdx = 2; totIdx >= 0; totIdx -= 1 )
            totIdx = 2;
            while totIdx >= 0 {
                let mut _candlerange_8: T;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_8 = *inClose.get_unchecked(i - totIdx) - *inOpen.get_unchecked(i - totIdx).ta_abs();
                    }
                    1 => {
                        _candlerange_8 = *inHigh.get_unchecked(i - totIdx) - *inLow.get_unchecked(i - totIdx);
                    }
                    2 => {
                        _candlerange_8 = *inHigh.get_unchecked(i - totIdx) - *inLow.get_unchecked(i - totIdx) - *inClose.get_unchecked(i - totIdx) - *inOpen.get_unchecked(i - totIdx).ta_abs();
                    }
                    _ => {
                        _candlerange_8 = T::ta_from_f64(0.0);
                    }
                }
                let mut _candlerange_9: T;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_9 = *inClose.get_unchecked(ShadowVeryShortTrailingIdx - totIdx) - *inOpen.get_unchecked(ShadowVeryShortTrailingIdx - totIdx).ta_abs();
                    }
                    1 => {
                        _candlerange_9 = *inHigh.get_unchecked(ShadowVeryShortTrailingIdx - totIdx) - *inLow.get_unchecked(ShadowVeryShortTrailingIdx - totIdx);
                    }
                    2 => {
                        _candlerange_9 = *inHigh.get_unchecked(ShadowVeryShortTrailingIdx - totIdx) - *inLow.get_unchecked(ShadowVeryShortTrailingIdx - totIdx) - *inClose.get_unchecked(ShadowVeryShortTrailingIdx - totIdx) - *inOpen.get_unchecked(ShadowVeryShortTrailingIdx - totIdx).ta_abs();
                    }
                    _ => {
                        _candlerange_9 = T::ta_from_f64(0.0);
                    }
                }
                *ShadowVeryShortPeriodTotal.get_unchecked_mut(totIdx) = *ShadowVeryShortPeriodTotal.get_unchecked(totIdx) + (_candlerange_8 - _candlerange_9);
                totIdx -= 1;
            }
            // for( totIdx = 2; totIdx >= 1; totIdx -= 1 )
            totIdx = 2;
            while totIdx >= 1 {
                let mut _candlerange_10: T;
                match Far_rangeType {
                    0 => {
                        _candlerange_10 = *inClose.get_unchecked(i - totIdx) - *inOpen.get_unchecked(i - totIdx).ta_abs();
                    }
                    1 => {
                        _candlerange_10 = *inHigh.get_unchecked(i - totIdx) - *inLow.get_unchecked(i - totIdx);
                    }
                    2 => {
                        _candlerange_10 = *inHigh.get_unchecked(i - totIdx) - *inLow.get_unchecked(i - totIdx) - *inClose.get_unchecked(i - totIdx) - *inOpen.get_unchecked(i - totIdx).ta_abs();
                    }
                    _ => {
                        _candlerange_10 = T::ta_from_f64(0.0);
                    }
                }
                let mut _candlerange_11: T;
                match Far_rangeType {
                    0 => {
                        _candlerange_11 = *inClose.get_unchecked(FarTrailingIdx - totIdx) - *inOpen.get_unchecked(FarTrailingIdx - totIdx).ta_abs();
                    }
                    1 => {
                        _candlerange_11 = *inHigh.get_unchecked(FarTrailingIdx - totIdx) - *inLow.get_unchecked(FarTrailingIdx - totIdx);
                    }
                    2 => {
                        _candlerange_11 = *inHigh.get_unchecked(FarTrailingIdx - totIdx) - *inLow.get_unchecked(FarTrailingIdx - totIdx) - *inClose.get_unchecked(FarTrailingIdx - totIdx) - *inOpen.get_unchecked(FarTrailingIdx - totIdx).ta_abs();
                    }
                    _ => {
                        _candlerange_11 = T::ta_from_f64(0.0);
                    }
                }
                *FarPeriodTotal.get_unchecked_mut(totIdx) = *FarPeriodTotal.get_unchecked(totIdx) + (_candlerange_10 - _candlerange_11);
                let mut _candlerange_12: T;
                match Near_rangeType {
                    0 => {
                        _candlerange_12 = *inClose.get_unchecked(i - totIdx) - *inOpen.get_unchecked(i - totIdx).ta_abs();
                    }
                    1 => {
                        _candlerange_12 = *inHigh.get_unchecked(i - totIdx) - *inLow.get_unchecked(i - totIdx);
                    }
                    2 => {
                        _candlerange_12 = *inHigh.get_unchecked(i - totIdx) - *inLow.get_unchecked(i - totIdx) - *inClose.get_unchecked(i - totIdx) - *inOpen.get_unchecked(i - totIdx).ta_abs();
                    }
                    _ => {
                        _candlerange_12 = T::ta_from_f64(0.0);
                    }
                }
                let mut _candlerange_13: T;
                match Near_rangeType {
                    0 => {
                        _candlerange_13 = *inClose.get_unchecked(NearTrailingIdx - totIdx) - *inOpen.get_unchecked(NearTrailingIdx - totIdx).ta_abs();
                    }
                    1 => {
                        _candlerange_13 = *inHigh.get_unchecked(NearTrailingIdx - totIdx) - *inLow.get_unchecked(NearTrailingIdx - totIdx);
                    }
                    2 => {
                        _candlerange_13 = *inHigh.get_unchecked(NearTrailingIdx - totIdx) - *inLow.get_unchecked(NearTrailingIdx - totIdx) - *inClose.get_unchecked(NearTrailingIdx - totIdx) - *inOpen.get_unchecked(NearTrailingIdx - totIdx).ta_abs();
                    }
                    _ => {
                        _candlerange_13 = T::ta_from_f64(0.0);
                    }
                }
                *NearPeriodTotal.get_unchecked_mut(totIdx) = *NearPeriodTotal.get_unchecked(totIdx) + (_candlerange_12 - _candlerange_13);
                totIdx -= 1;
            }
            let mut _candlerange_14: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_14 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_14 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_14 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_14 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_15: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_15 = *inClose.get_unchecked(BodyShortTrailingIdx) - *inOpen.get_unchecked(BodyShortTrailingIdx).ta_abs();
                }
                1 => {
                    _candlerange_15 = *inHigh.get_unchecked(BodyShortTrailingIdx) - *inLow.get_unchecked(BodyShortTrailingIdx);
                }
                2 => {
                    _candlerange_15 = *inHigh.get_unchecked(BodyShortTrailingIdx) - *inLow.get_unchecked(BodyShortTrailingIdx) - *inClose.get_unchecked(BodyShortTrailingIdx) - *inOpen.get_unchecked(BodyShortTrailingIdx).ta_abs();
                }
                _ => {
                    _candlerange_15 = T::ta_from_f64(0.0);
                }
            }
            BodyShortPeriodTotal += _candlerange_14 - _candlerange_15;
            i += 1;
            ShadowVeryShortTrailingIdx += 1;
            NearTrailingIdx += 1;
            FarTrailingIdx += 1;
            BodyShortTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
