/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlconcealbabyswall`].
    ///
    /// # Arguments
    ///
    pub fn cdlconcealbabyswall_lookback(&self) -> i32 {
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        return ShadowVeryShort_avgPeriod + 3;
    }
    /// Concealing Baby Swallow
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlconcealbabyswall<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlconcealbabyswall_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdlconcealbabyswall_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut ShadowVeryShortPeriodTotal: [T; 4 as usize] = [T::zero(); 4 as usize];
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        lookbackTotal = self.cdlconcealbabyswall_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        ShadowVeryShortPeriodTotal[3] = 0;
        ShadowVeryShortPeriodTotal[2] = 0;
        ShadowVeryShortPeriodTotal[1] = 0;
        ShadowVeryShortTrailingIdx = startIdx - ShadowVeryShort_avgPeriod;
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_0 = inClose[i - 3] - inOpen[i - 3].ta_abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i - 3] - inLow[i - 3];
                }
                2 => {
                    _candlerange_0 = inHigh[i - 3] - inLow[i - 3] - inClose[i - 3] - inOpen[i - 3].ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryShortPeriodTotal[3] = ShadowVeryShortPeriodTotal[3] + _candlerange_0;
            let mut _candlerange_1: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_1 = inClose[i - 2] - inOpen[i - 2].ta_abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_1 = inHigh[i - 2] - inLow[i - 2] - inClose[i - 2] - inOpen[i - 2].ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryShortPeriodTotal[2] = ShadowVeryShortPeriodTotal[2] + _candlerange_1;
            let mut _candlerange_2: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_2 = inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_2 = inHigh[i - 1] - inLow[i - 1] - inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryShortPeriodTotal[1] = ShadowVeryShortPeriodTotal[1] + _candlerange_2;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if if inClose[i - 3] >= inOpen[i - 3] { 1 } else { 0 - 1 } == 0 - 1 && if inClose[i - 2] >= inOpen[i - 2] { 1 } else { 0 - 1 } == 0 - 1 && if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 } == 0 - 1 && if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 } == 0 - 1 && if inClose[i - 3] >= inOpen[i - 3] { inOpen[i - 3] } else { inClose[i - 3] } - inLow[i - 3] < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, ShadowVeryShortPeriodTotal[3], inOpen[i - 3], inHigh[i - 3], inLow[i - 3], inClose[i - 3]) && inHigh[i - 3] - if inClose[i - 3] >= inOpen[i - 3] { inClose[i - 3] } else { inOpen[i - 3] } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, ShadowVeryShortPeriodTotal[3], inOpen[i - 3], inHigh[i - 3], inLow[i - 3], inClose[i - 3]) && if inClose[i - 2] >= inOpen[i - 2] { inOpen[i - 2] } else { inClose[i - 2] } - inLow[i - 2] < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, ShadowVeryShortPeriodTotal[2], inOpen[i - 2], inHigh[i - 2], inLow[i - 2], inClose[i - 2]) && inHigh[i - 2] - if inClose[i - 2] >= inOpen[i - 2] { inClose[i - 2] } else { inOpen[i - 2] } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, ShadowVeryShortPeriodTotal[2], inOpen[i - 2], inHigh[i - 2], inLow[i - 2], inClose[i - 2]) && if (inOpen[i - 1]).max(inClose[i - 1]) < (inOpen[i - 2]).min(inClose[i - 2]) { 1 } else { 0 } && inHigh[i - 1] - if inClose[i - 1] >= inOpen[i - 1] { inClose[i - 1] } else { inOpen[i - 1] } > ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, ShadowVeryShortPeriodTotal[1], inOpen[i - 1], inHigh[i - 1], inLow[i - 1], inClose[i - 1]) && inHigh[i - 1] > inClose[i - 2] && inHigh[i] > inHigh[i - 1] && inLow[i] < inLow[i - 1] {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 100;
            } else {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 0;
            }
            // for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
            totIdx = 3;
            while totIdx >= 1 {
                let mut _candlerange_3: T;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_3 = inClose[i - totIdx] - inOpen[i - totIdx].ta_abs();
                    }
                    1 => {
                        _candlerange_3 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_3 = inHigh[i - totIdx] - inLow[i - totIdx] - inClose[i - totIdx] - inOpen[i - totIdx].ta_abs();
                    }
                    _ => {
                        _candlerange_3 = T::ta_from_f64(0.0);
                    }
                }
                let mut _candlerange_4: T;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_4 = inClose[ShadowVeryShortTrailingIdx - totIdx] - inOpen[ShadowVeryShortTrailingIdx - totIdx].ta_abs();
                    }
                    1 => {
                        _candlerange_4 = inHigh[ShadowVeryShortTrailingIdx - totIdx] - inLow[ShadowVeryShortTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_4 = inHigh[ShadowVeryShortTrailingIdx - totIdx] - inLow[ShadowVeryShortTrailingIdx - totIdx] - inClose[ShadowVeryShortTrailingIdx - totIdx] - inOpen[ShadowVeryShortTrailingIdx - totIdx].ta_abs();
                    }
                    _ => {
                        _candlerange_4 = T::ta_from_f64(0.0);
                    }
                }
                ShadowVeryShortPeriodTotal[totIdx] = ShadowVeryShortPeriodTotal[totIdx] + (_candlerange_3 - _candlerange_4);
                totIdx -= 1;
            }
            i += 1;
            ShadowVeryShortTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn cdlconcealbabyswall_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlconcealbabyswall_unguarded_unchecked(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn cdlconcealbabyswall_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut ShadowVeryShortPeriodTotal: [T; 4 as usize] = [T::zero(); 4 as usize];
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        lookbackTotal = self.cdlconcealbabyswall_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        *ShadowVeryShortPeriodTotal.get_unchecked_mut(3) = 0;
        *ShadowVeryShortPeriodTotal.get_unchecked_mut(2) = 0;
        *ShadowVeryShortPeriodTotal.get_unchecked_mut(1) = 0;
        ShadowVeryShortTrailingIdx = startIdx - ShadowVeryShort_avgPeriod;
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_0 = *inClose.get_unchecked(i - 3) - *inOpen.get_unchecked(i - 3).ta_abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.get_unchecked(i - 3) - *inLow.get_unchecked(i - 3);
                }
                2 => {
                    _candlerange_0 = *inHigh.get_unchecked(i - 3) - *inLow.get_unchecked(i - 3) - *inClose.get_unchecked(i - 3) - *inOpen.get_unchecked(i - 3).ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            *ShadowVeryShortPeriodTotal.get_unchecked_mut(3) = *ShadowVeryShortPeriodTotal.get_unchecked(3) + _candlerange_0;
            let mut _candlerange_1: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_1 = *inClose.get_unchecked(i - 2) - *inOpen.get_unchecked(i - 2).ta_abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.get_unchecked(i - 2) - *inLow.get_unchecked(i - 2);
                }
                2 => {
                    _candlerange_1 = *inHigh.get_unchecked(i - 2) - *inLow.get_unchecked(i - 2) - *inClose.get_unchecked(i - 2) - *inOpen.get_unchecked(i - 2).ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            *ShadowVeryShortPeriodTotal.get_unchecked_mut(2) = *ShadowVeryShortPeriodTotal.get_unchecked(2) + _candlerange_1;
            let mut _candlerange_2: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_2 = *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1);
                }
                2 => {
                    _candlerange_2 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1) - *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            *ShadowVeryShortPeriodTotal.get_unchecked_mut(1) = *ShadowVeryShortPeriodTotal.get_unchecked(1) + _candlerange_2;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if if *inClose.get_unchecked(i - 3) >= *inOpen.get_unchecked(i - 3) { 1 } else { 0 - 1 } == 0 - 1 && if *inClose.get_unchecked(i - 2) >= *inOpen.get_unchecked(i - 2) { 1 } else { 0 - 1 } == 0 - 1 && if *inClose.get_unchecked(i - 1) >= *inOpen.get_unchecked(i - 1) { 1 } else { 0 - 1 } == 0 - 1 && if *inClose.get_unchecked(i) >= *inOpen.get_unchecked(i) { 1 } else { 0 - 1 } == 0 - 1 && if *inClose.get_unchecked(i - 3) >= *inOpen.get_unchecked(i - 3) { *inOpen.get_unchecked(i - 3) } else { *inClose.get_unchecked(i - 3) } - *inLow.get_unchecked(i - 3) < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, *ShadowVeryShortPeriodTotal.get_unchecked(3), *inOpen.get_unchecked(i - 3), *inHigh.get_unchecked(i - 3), *inLow.get_unchecked(i - 3), *inClose.get_unchecked(i - 3)) && *inHigh.get_unchecked(i - 3) - if *inClose.get_unchecked(i - 3) >= *inOpen.get_unchecked(i - 3) { *inClose.get_unchecked(i - 3) } else { *inOpen.get_unchecked(i - 3) } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, *ShadowVeryShortPeriodTotal.get_unchecked(3), *inOpen.get_unchecked(i - 3), *inHigh.get_unchecked(i - 3), *inLow.get_unchecked(i - 3), *inClose.get_unchecked(i - 3)) && if *inClose.get_unchecked(i - 2) >= *inOpen.get_unchecked(i - 2) { *inOpen.get_unchecked(i - 2) } else { *inClose.get_unchecked(i - 2) } - *inLow.get_unchecked(i - 2) < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, *ShadowVeryShortPeriodTotal.get_unchecked(2), *inOpen.get_unchecked(i - 2), *inHigh.get_unchecked(i - 2), *inLow.get_unchecked(i - 2), *inClose.get_unchecked(i - 2)) && *inHigh.get_unchecked(i - 2) - if *inClose.get_unchecked(i - 2) >= *inOpen.get_unchecked(i - 2) { *inClose.get_unchecked(i - 2) } else { *inOpen.get_unchecked(i - 2) } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, *ShadowVeryShortPeriodTotal.get_unchecked(2), *inOpen.get_unchecked(i - 2), *inHigh.get_unchecked(i - 2), *inLow.get_unchecked(i - 2), *inClose.get_unchecked(i - 2)) && if (*inOpen.get_unchecked(i - 1)).max(*inClose.get_unchecked(i - 1)) < (*inOpen.get_unchecked(i - 2)).min(*inClose.get_unchecked(i - 2)) { 1 } else { 0 } && *inHigh.get_unchecked(i - 1) - if *inClose.get_unchecked(i - 1) >= *inOpen.get_unchecked(i - 1) { *inClose.get_unchecked(i - 1) } else { *inOpen.get_unchecked(i - 1) } > ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, *ShadowVeryShortPeriodTotal.get_unchecked(1), *inOpen.get_unchecked(i - 1), *inHigh.get_unchecked(i - 1), *inLow.get_unchecked(i - 1), *inClose.get_unchecked(i - 1)) && *inHigh.get_unchecked(i - 1) > *inClose.get_unchecked(i - 2) && *inHigh.get_unchecked(i) > *inHigh.get_unchecked(i - 1) && *inLow.get_unchecked(i) < *inLow.get_unchecked(i - 1) {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 100;
            } else {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 0;
            }
            // for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
            totIdx = 3;
            while totIdx >= 1 {
                let mut _candlerange_3: T;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_3 = *inClose.get_unchecked(i - totIdx) - *inOpen.get_unchecked(i - totIdx).ta_abs();
                    }
                    1 => {
                        _candlerange_3 = *inHigh.get_unchecked(i - totIdx) - *inLow.get_unchecked(i - totIdx);
                    }
                    2 => {
                        _candlerange_3 = *inHigh.get_unchecked(i - totIdx) - *inLow.get_unchecked(i - totIdx) - *inClose.get_unchecked(i - totIdx) - *inOpen.get_unchecked(i - totIdx).ta_abs();
                    }
                    _ => {
                        _candlerange_3 = T::ta_from_f64(0.0);
                    }
                }
                let mut _candlerange_4: T;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_4 = *inClose.get_unchecked(ShadowVeryShortTrailingIdx - totIdx) - *inOpen.get_unchecked(ShadowVeryShortTrailingIdx - totIdx).ta_abs();
                    }
                    1 => {
                        _candlerange_4 = *inHigh.get_unchecked(ShadowVeryShortTrailingIdx - totIdx) - *inLow.get_unchecked(ShadowVeryShortTrailingIdx - totIdx);
                    }
                    2 => {
                        _candlerange_4 = *inHigh.get_unchecked(ShadowVeryShortTrailingIdx - totIdx) - *inLow.get_unchecked(ShadowVeryShortTrailingIdx - totIdx) - *inClose.get_unchecked(ShadowVeryShortTrailingIdx - totIdx) - *inOpen.get_unchecked(ShadowVeryShortTrailingIdx - totIdx).ta_abs();
                    }
                    _ => {
                        _candlerange_4 = T::ta_from_f64(0.0);
                    }
                }
                *ShadowVeryShortPeriodTotal.get_unchecked_mut(totIdx) = *ShadowVeryShortPeriodTotal.get_unchecked(totIdx) + (_candlerange_3 - _candlerange_4);
                totIdx -= 1;
            }
            i += 1;
            ShadowVeryShortTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
