/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlharamicross`].
    ///
    /// # Arguments
    ///
    pub fn cdlharamicross_lookback(&self) -> i32 {
        #[allow(non_snake_case)]
        let BodyDoji_rangeType: i32 = self.candle_settings.body_doji.range_type;
        #[allow(non_snake_case)]
        let BodyDoji_avgPeriod: i32 = self.candle_settings.body_doji.avg_period;
        #[allow(non_snake_case)]
        let BodyDoji_factor: f64 = self.candle_settings.body_doji.factor;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        return (BodyDoji_avgPeriod).max(BodyLong_avgPeriod) + 1;
    }
    /// Harami Cross Pattern
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlharamicross<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlharamicross_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdlharamicross_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyDojiPeriodTotal: T;
        let mut BodyLongPeriodTotal: T;
        let mut i: i32;
        let outIdx: i32;
        let mut BodyDojiTrailingIdx: i32;
        let mut BodyLongTrailingIdx: i32;
        let lookbackTotal: i32;
        #[allow(non_snake_case)]
        let BodyDoji_rangeType: i32 = self.candle_settings.body_doji.range_type;
        #[allow(non_snake_case)]
        let BodyDoji_avgPeriod: i32 = self.candle_settings.body_doji.avg_period;
        #[allow(non_snake_case)]
        let BodyDoji_factor: f64 = self.candle_settings.body_doji.factor;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        lookbackTotal = self.cdlharamicross_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyLongPeriodTotal = 0;
        BodyDojiPeriodTotal = 0;
        BodyLongTrailingIdx = startIdx - 1 - BodyLong_avgPeriod;
        BodyDojiTrailingIdx = startIdx - BodyDoji_avgPeriod;
        i = BodyLongTrailingIdx;
        while i < startIdx - 1 {
            let mut _candlerange_0: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_0 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_0 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            BodyLongPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = BodyDojiTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_1 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_1 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            BodyDojiPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if inClose[i - 1] - inOpen[i - 1].ta_abs() > ta_candleaverage(BodyLong_rangeType, BodyLong_avgPeriod, BodyLong_factor, BodyLongPeriodTotal, inOpen[i - 1], inHigh[i - 1], inLow[i - 1], inClose[i - 1]) && inClose[i] - inOpen[i].ta_abs() <= ta_candleaverage(BodyDoji_rangeType, BodyDoji_avgPeriod, BodyDoji_factor, BodyDojiPeriodTotal, inOpen[i], inHigh[i], inLow[i], inClose[i]) {
                if (inClose[i]).max(inOpen[i]) < (inClose[i - 1]).max(inOpen[i - 1]) && (inClose[i]).min(inOpen[i]) > (inClose[i - 1]).min(inOpen[i - 1]) {
                    outInteger[{ let _v = outIdx; outIdx += 1; _v }] = (0 - if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 }) * 100;
                } else if (inClose[i]).max(inOpen[i]) <= (inClose[i - 1]).max(inOpen[i - 1]) && (inClose[i]).min(inOpen[i]) >= (inClose[i - 1]).min(inOpen[i - 1]) {
                    outInteger[{ let _v = outIdx; outIdx += 1; _v }] = (0 - if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 }) * 80;
                } else {
                    outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 0;
                }
            } else {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 0;
            }
            let mut _candlerange_2: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_2 = inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_2 = inHigh[i - 1] - inLow[i - 1] - inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_3: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_3 = inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx].ta_abs();
                }
                1 => {
                    _candlerange_3 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx];
                }
                2 => {
                    _candlerange_3 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx] - inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx].ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            BodyLongPeriodTotal += _candlerange_2 - _candlerange_3;
            let mut _candlerange_4: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_4 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_4 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_4 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_5: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_5 = inClose[BodyDojiTrailingIdx] - inOpen[BodyDojiTrailingIdx].ta_abs();
                }
                1 => {
                    _candlerange_5 = inHigh[BodyDojiTrailingIdx] - inLow[BodyDojiTrailingIdx];
                }
                2 => {
                    _candlerange_5 = inHigh[BodyDojiTrailingIdx] - inLow[BodyDojiTrailingIdx] - inClose[BodyDojiTrailingIdx] - inOpen[BodyDojiTrailingIdx].ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            BodyDojiPeriodTotal += _candlerange_4 - _candlerange_5;
            i += 1;
            BodyLongTrailingIdx += 1;
            BodyDojiTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    pub unsafe fn cdlharamicross_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlharamicross_unguarded_unchecked(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn cdlharamicross_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyDojiPeriodTotal: T;
        let mut BodyLongPeriodTotal: T;
        let mut i: i32;
        let outIdx: i32;
        let mut BodyDojiTrailingIdx: i32;
        let mut BodyLongTrailingIdx: i32;
        let lookbackTotal: i32;
        #[allow(non_snake_case)]
        let BodyDoji_rangeType: i32 = self.candle_settings.body_doji.range_type;
        #[allow(non_snake_case)]
        let BodyDoji_avgPeriod: i32 = self.candle_settings.body_doji.avg_period;
        #[allow(non_snake_case)]
        let BodyDoji_factor: f64 = self.candle_settings.body_doji.factor;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        lookbackTotal = self.cdlharamicross_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyLongPeriodTotal = 0;
        BodyDojiPeriodTotal = 0;
        BodyLongTrailingIdx = startIdx - 1 - BodyLong_avgPeriod;
        BodyDojiTrailingIdx = startIdx - BodyDoji_avgPeriod;
        i = BodyLongTrailingIdx;
        while i < startIdx - 1 {
            let mut _candlerange_0: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_0 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_0 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            BodyLongPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = BodyDojiTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_1 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_1 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            BodyDojiPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs() > ta_candleaverage(BodyLong_rangeType, BodyLong_avgPeriod, BodyLong_factor, BodyLongPeriodTotal, *inOpen.get_unchecked(i - 1), *inHigh.get_unchecked(i - 1), *inLow.get_unchecked(i - 1), *inClose.get_unchecked(i - 1)) && *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs() <= ta_candleaverage(BodyDoji_rangeType, BodyDoji_avgPeriod, BodyDoji_factor, BodyDojiPeriodTotal, *inOpen.get_unchecked(i), *inHigh.get_unchecked(i), *inLow.get_unchecked(i), *inClose.get_unchecked(i)) {
                if (*inClose.get_unchecked(i)).max(*inOpen.get_unchecked(i)) < (*inClose.get_unchecked(i - 1)).max(*inOpen.get_unchecked(i - 1)) && (*inClose.get_unchecked(i)).min(*inOpen.get_unchecked(i)) > (*inClose.get_unchecked(i - 1)).min(*inOpen.get_unchecked(i - 1)) {
                    *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = (0 - if *inClose.get_unchecked(i - 1) >= *inOpen.get_unchecked(i - 1) { 1 } else { 0 - 1 }) * 100;
                } else if (*inClose.get_unchecked(i)).max(*inOpen.get_unchecked(i)) <= (*inClose.get_unchecked(i - 1)).max(*inOpen.get_unchecked(i - 1)) && (*inClose.get_unchecked(i)).min(*inOpen.get_unchecked(i)) >= (*inClose.get_unchecked(i - 1)).min(*inOpen.get_unchecked(i - 1)) {
                    *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = (0 - if *inClose.get_unchecked(i - 1) >= *inOpen.get_unchecked(i - 1) { 1 } else { 0 - 1 }) * 80;
                } else {
                    *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 0;
                }
            } else {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 0;
            }
            let mut _candlerange_2: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_2 = *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1);
                }
                2 => {
                    _candlerange_2 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1) - *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_3: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_3 = *inClose.get_unchecked(BodyLongTrailingIdx) - *inOpen.get_unchecked(BodyLongTrailingIdx).ta_abs();
                }
                1 => {
                    _candlerange_3 = *inHigh.get_unchecked(BodyLongTrailingIdx) - *inLow.get_unchecked(BodyLongTrailingIdx);
                }
                2 => {
                    _candlerange_3 = *inHigh.get_unchecked(BodyLongTrailingIdx) - *inLow.get_unchecked(BodyLongTrailingIdx) - *inClose.get_unchecked(BodyLongTrailingIdx) - *inOpen.get_unchecked(BodyLongTrailingIdx).ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            BodyLongPeriodTotal += _candlerange_2 - _candlerange_3;
            let mut _candlerange_4: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_4 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_4 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_4 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_5: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_5 = *inClose.get_unchecked(BodyDojiTrailingIdx) - *inOpen.get_unchecked(BodyDojiTrailingIdx).ta_abs();
                }
                1 => {
                    _candlerange_5 = *inHigh.get_unchecked(BodyDojiTrailingIdx) - *inLow.get_unchecked(BodyDojiTrailingIdx);
                }
                2 => {
                    _candlerange_5 = *inHigh.get_unchecked(BodyDojiTrailingIdx) - *inLow.get_unchecked(BodyDojiTrailingIdx) - *inClose.get_unchecked(BodyDojiTrailingIdx) - *inOpen.get_unchecked(BodyDojiTrailingIdx).ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            BodyDojiPeriodTotal += _candlerange_4 - _candlerange_5;
            i += 1;
            BodyLongTrailingIdx += 1;
            BodyDojiTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
