/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlshortline`].
    ///
    /// # Arguments
    ///
    pub fn cdlshortline_lookback(&self) -> i32 {
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let ShadowShort_rangeType: i32 = self.candle_settings.shadow_short.range_type;
        #[allow(non_snake_case)]
        let ShadowShort_avgPeriod: i32 = self.candle_settings.shadow_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowShort_factor: f64 = self.candle_settings.shadow_short.factor;
        return (BodyShort_avgPeriod).max(ShadowShort_avgPeriod);
    }
    /// Short Line Candle
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlshortline<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlshortline_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdlshortline_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyPeriodTotal: T;
        let mut ShadowPeriodTotal: T;
        let mut i: i32;
        let outIdx: i32;
        let mut BodyTrailingIdx: i32;
        let mut ShadowTrailingIdx: i32;
        let lookbackTotal: i32;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let ShadowShort_rangeType: i32 = self.candle_settings.shadow_short.range_type;
        #[allow(non_snake_case)]
        let ShadowShort_avgPeriod: i32 = self.candle_settings.shadow_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowShort_factor: f64 = self.candle_settings.shadow_short.factor;
        lookbackTotal = self.cdlshortline_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyPeriodTotal = 0;
        BodyTrailingIdx = startIdx - BodyShort_avgPeriod;
        ShadowPeriodTotal = 0;
        ShadowTrailingIdx = startIdx - ShadowShort_avgPeriod;
        i = BodyTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_0 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_0 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = ShadowTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: T;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_1 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_1 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            ShadowPeriodTotal += _candlerange_1;
            i += 1;
        }
        outIdx = 0;
        loop {
            if inClose[i] - inOpen[i].ta_abs() < ta_candleaverage(BodyShort_rangeType, BodyShort_avgPeriod, BodyShort_factor, BodyPeriodTotal, inOpen[i], inHigh[i], inLow[i], inClose[i]) && inHigh[i] - if inClose[i] >= inOpen[i] { inClose[i] } else { inOpen[i] } < ta_candleaverage(ShadowShort_rangeType, ShadowShort_avgPeriod, ShadowShort_factor, ShadowPeriodTotal, inOpen[i], inHigh[i], inLow[i], inClose[i]) && if inClose[i] >= inOpen[i] { inOpen[i] } else { inClose[i] } - inLow[i] < ta_candleaverage(ShadowShort_rangeType, ShadowShort_avgPeriod, ShadowShort_factor, ShadowPeriodTotal, inOpen[i], inHigh[i], inLow[i], inClose[i]) {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 } * 100;
            } else {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 0;
            }
            let mut _candlerange_2: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_2 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_2 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_3: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_3 = inClose[BodyTrailingIdx] - inOpen[BodyTrailingIdx].ta_abs();
                }
                1 => {
                    _candlerange_3 = inHigh[BodyTrailingIdx] - inLow[BodyTrailingIdx];
                }
                2 => {
                    _candlerange_3 = inHigh[BodyTrailingIdx] - inLow[BodyTrailingIdx] - inClose[BodyTrailingIdx] - inOpen[BodyTrailingIdx].ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal += _candlerange_2 - _candlerange_3;
            let mut _candlerange_4: T;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_4 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_4 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_4 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_5: T;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_5 = inClose[ShadowTrailingIdx] - inOpen[ShadowTrailingIdx].ta_abs();
                }
                1 => {
                    _candlerange_5 = inHigh[ShadowTrailingIdx] - inLow[ShadowTrailingIdx];
                }
                2 => {
                    _candlerange_5 = inHigh[ShadowTrailingIdx] - inLow[ShadowTrailingIdx] - inClose[ShadowTrailingIdx] - inOpen[ShadowTrailingIdx].ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            ShadowPeriodTotal += _candlerange_4 - _candlerange_5;
            i += 1;
            BodyTrailingIdx += 1;
            ShadowTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    pub unsafe fn cdlshortline_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlshortline_unguarded_unchecked(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn cdlshortline_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyPeriodTotal: T;
        let mut ShadowPeriodTotal: T;
        let mut i: i32;
        let outIdx: i32;
        let mut BodyTrailingIdx: i32;
        let mut ShadowTrailingIdx: i32;
        let lookbackTotal: i32;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let ShadowShort_rangeType: i32 = self.candle_settings.shadow_short.range_type;
        #[allow(non_snake_case)]
        let ShadowShort_avgPeriod: i32 = self.candle_settings.shadow_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowShort_factor: f64 = self.candle_settings.shadow_short.factor;
        lookbackTotal = self.cdlshortline_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyPeriodTotal = 0;
        BodyTrailingIdx = startIdx - BodyShort_avgPeriod;
        ShadowPeriodTotal = 0;
        ShadowTrailingIdx = startIdx - ShadowShort_avgPeriod;
        i = BodyTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_0 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_0 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = ShadowTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: T;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_1 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_1 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            ShadowPeriodTotal += _candlerange_1;
            i += 1;
        }
        outIdx = 0;
        loop {
            if *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs() < ta_candleaverage(BodyShort_rangeType, BodyShort_avgPeriod, BodyShort_factor, BodyPeriodTotal, *inOpen.get_unchecked(i), *inHigh.get_unchecked(i), *inLow.get_unchecked(i), *inClose.get_unchecked(i)) && *inHigh.get_unchecked(i) - if *inClose.get_unchecked(i) >= *inOpen.get_unchecked(i) { *inClose.get_unchecked(i) } else { *inOpen.get_unchecked(i) } < ta_candleaverage(ShadowShort_rangeType, ShadowShort_avgPeriod, ShadowShort_factor, ShadowPeriodTotal, *inOpen.get_unchecked(i), *inHigh.get_unchecked(i), *inLow.get_unchecked(i), *inClose.get_unchecked(i)) && if *inClose.get_unchecked(i) >= *inOpen.get_unchecked(i) { *inOpen.get_unchecked(i) } else { *inClose.get_unchecked(i) } - *inLow.get_unchecked(i) < ta_candleaverage(ShadowShort_rangeType, ShadowShort_avgPeriod, ShadowShort_factor, ShadowPeriodTotal, *inOpen.get_unchecked(i), *inHigh.get_unchecked(i), *inLow.get_unchecked(i), *inClose.get_unchecked(i)) {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = if *inClose.get_unchecked(i) >= *inOpen.get_unchecked(i) { 1 } else { 0 - 1 } * 100;
            } else {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 0;
            }
            let mut _candlerange_2: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_2 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_2 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_3: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_3 = *inClose.get_unchecked(BodyTrailingIdx) - *inOpen.get_unchecked(BodyTrailingIdx).ta_abs();
                }
                1 => {
                    _candlerange_3 = *inHigh.get_unchecked(BodyTrailingIdx) - *inLow.get_unchecked(BodyTrailingIdx);
                }
                2 => {
                    _candlerange_3 = *inHigh.get_unchecked(BodyTrailingIdx) - *inLow.get_unchecked(BodyTrailingIdx) - *inClose.get_unchecked(BodyTrailingIdx) - *inOpen.get_unchecked(BodyTrailingIdx).ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal += _candlerange_2 - _candlerange_3;
            let mut _candlerange_4: T;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_4 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_4 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_4 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_5: T;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_5 = *inClose.get_unchecked(ShadowTrailingIdx) - *inOpen.get_unchecked(ShadowTrailingIdx).ta_abs();
                }
                1 => {
                    _candlerange_5 = *inHigh.get_unchecked(ShadowTrailingIdx) - *inLow.get_unchecked(ShadowTrailingIdx);
                }
                2 => {
                    _candlerange_5 = *inHigh.get_unchecked(ShadowTrailingIdx) - *inLow.get_unchecked(ShadowTrailingIdx) - *inClose.get_unchecked(ShadowTrailingIdx) - *inOpen.get_unchecked(ShadowTrailingIdx).ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            ShadowPeriodTotal += _candlerange_4 - _candlerange_5;
            i += 1;
            BodyTrailingIdx += 1;
            ShadowTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
