/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdltasukigap`].
    ///
    /// # Arguments
    ///
    pub fn cdltasukigap_lookback(&self) -> i32 {
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        return Near_avgPeriod + 2;
    }
    /// Tasuki Gap
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdltasukigap<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdltasukigap_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdltasukigap_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut NearPeriodTotal: T;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        lookbackTotal = self.cdltasukigap_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        NearPeriodTotal = 0;
        NearTrailingIdx = startIdx - Near_avgPeriod;
        i = NearTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match Near_rangeType {
                0 => {
                    _candlerange_0 = inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_0 = inHigh[i - 1] - inLow[i - 1] - inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            NearPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if if (inOpen[i - 1]).min(inClose[i - 1]) > (inOpen[i - 2]).max(inClose[i - 2]) { 1 } else { 0 } && if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 } == 1 && if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 } == 0 - 1 && inOpen[i] < inClose[i - 1] && inOpen[i] > inOpen[i - 1] && inClose[i] < inOpen[i - 1] && inClose[i] > (inClose[i - 2]).max(inOpen[i - 2]) && inClose[i - 1] - inOpen[i - 1].ta_abs() - inClose[i] - inOpen[i].ta_abs().ta_abs() < ta_candleaverage(Near_rangeType, Near_avgPeriod, Near_factor, NearPeriodTotal, inOpen[i - 1], inHigh[i - 1], inLow[i - 1], inClose[i - 1]) || if (inOpen[i - 1]).max(inClose[i - 1]) < (inOpen[i - 2]).min(inClose[i - 2]) { 1 } else { 0 } && if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 } == 0 - 1 && if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 } == 1 && inOpen[i] < inOpen[i - 1] && inOpen[i] > inClose[i - 1] && inClose[i] > inOpen[i - 1] && inClose[i] < (inClose[i - 2]).min(inOpen[i - 2]) && inClose[i - 1] - inOpen[i - 1].ta_abs() - inClose[i] - inOpen[i].ta_abs().ta_abs() < ta_candleaverage(Near_rangeType, Near_avgPeriod, Near_factor, NearPeriodTotal, inOpen[i - 1], inHigh[i - 1], inLow[i - 1], inClose[i - 1]) {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 } * 100;
            } else {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 0;
            }
            let mut _candlerange_1: T;
            match Near_rangeType {
                0 => {
                    _candlerange_1 = inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_1 = inHigh[i - 1] - inLow[i - 1] - inClose[i - 1] - inOpen[i - 1].ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_2: T;
            match Near_rangeType {
                0 => {
                    _candlerange_2 = inClose[NearTrailingIdx - 1] - inOpen[NearTrailingIdx - 1].ta_abs();
                }
                1 => {
                    _candlerange_2 = inHigh[NearTrailingIdx - 1] - inLow[NearTrailingIdx - 1];
                }
                2 => {
                    _candlerange_2 = inHigh[NearTrailingIdx - 1] - inLow[NearTrailingIdx - 1] - inClose[NearTrailingIdx - 1] - inOpen[NearTrailingIdx - 1].ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            NearPeriodTotal += _candlerange_1 - _candlerange_2;
            i += 1;
            NearTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn cdltasukigap_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdltasukigap_unguarded_unchecked(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn cdltasukigap_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut NearPeriodTotal: T;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        lookbackTotal = self.cdltasukigap_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        NearPeriodTotal = 0;
        NearTrailingIdx = startIdx - Near_avgPeriod;
        i = NearTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match Near_rangeType {
                0 => {
                    _candlerange_0 = *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1);
                }
                2 => {
                    _candlerange_0 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1) - *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            NearPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if if (*inOpen.get_unchecked(i - 1)).min(*inClose.get_unchecked(i - 1)) > (*inOpen.get_unchecked(i - 2)).max(*inClose.get_unchecked(i - 2)) { 1 } else { 0 } && if *inClose.get_unchecked(i - 1) >= *inOpen.get_unchecked(i - 1) { 1 } else { 0 - 1 } == 1 && if *inClose.get_unchecked(i) >= *inOpen.get_unchecked(i) { 1 } else { 0 - 1 } == 0 - 1 && *inOpen.get_unchecked(i) < *inClose.get_unchecked(i - 1) && *inOpen.get_unchecked(i) > *inOpen.get_unchecked(i - 1) && *inClose.get_unchecked(i) < *inOpen.get_unchecked(i - 1) && *inClose.get_unchecked(i) > (*inClose.get_unchecked(i - 2)).max(*inOpen.get_unchecked(i - 2)) && *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs() - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs().ta_abs() < ta_candleaverage(Near_rangeType, Near_avgPeriod, Near_factor, NearPeriodTotal, *inOpen.get_unchecked(i - 1), *inHigh.get_unchecked(i - 1), *inLow.get_unchecked(i - 1), *inClose.get_unchecked(i - 1)) || if (*inOpen.get_unchecked(i - 1)).max(*inClose.get_unchecked(i - 1)) < (*inOpen.get_unchecked(i - 2)).min(*inClose.get_unchecked(i - 2)) { 1 } else { 0 } && if *inClose.get_unchecked(i - 1) >= *inOpen.get_unchecked(i - 1) { 1 } else { 0 - 1 } == 0 - 1 && if *inClose.get_unchecked(i) >= *inOpen.get_unchecked(i) { 1 } else { 0 - 1 } == 1 && *inOpen.get_unchecked(i) < *inOpen.get_unchecked(i - 1) && *inOpen.get_unchecked(i) > *inClose.get_unchecked(i - 1) && *inClose.get_unchecked(i) > *inOpen.get_unchecked(i - 1) && *inClose.get_unchecked(i) < (*inClose.get_unchecked(i - 2)).min(*inOpen.get_unchecked(i - 2)) && *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs() - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs().ta_abs() < ta_candleaverage(Near_rangeType, Near_avgPeriod, Near_factor, NearPeriodTotal, *inOpen.get_unchecked(i - 1), *inHigh.get_unchecked(i - 1), *inLow.get_unchecked(i - 1), *inClose.get_unchecked(i - 1)) {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = if *inClose.get_unchecked(i - 1) >= *inOpen.get_unchecked(i - 1) { 1 } else { 0 - 1 } * 100;
            } else {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 0;
            }
            let mut _candlerange_1: T;
            match Near_rangeType {
                0 => {
                    _candlerange_1 = *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1);
                }
                2 => {
                    _candlerange_1 = *inHigh.get_unchecked(i - 1) - *inLow.get_unchecked(i - 1) - *inClose.get_unchecked(i - 1) - *inOpen.get_unchecked(i - 1).ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_2: T;
            match Near_rangeType {
                0 => {
                    _candlerange_2 = *inClose.get_unchecked(NearTrailingIdx - 1) - *inOpen.get_unchecked(NearTrailingIdx - 1).ta_abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.get_unchecked(NearTrailingIdx - 1) - *inLow.get_unchecked(NearTrailingIdx - 1);
                }
                2 => {
                    _candlerange_2 = *inHigh.get_unchecked(NearTrailingIdx - 1) - *inLow.get_unchecked(NearTrailingIdx - 1) - *inClose.get_unchecked(NearTrailingIdx - 1) - *inOpen.get_unchecked(NearTrailingIdx - 1).ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            NearPeriodTotal += _candlerange_1 - _candlerange_2;
            i += 1;
            NearTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
