/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdltakuri`].
    ///
    /// # Arguments
    ///
    pub fn cdltakuri_lookback(&self) -> i32 {
        #[allow(non_snake_case)]
        let BodyDoji_rangeType: i32 = self.candle_settings.body_doji.range_type;
        #[allow(non_snake_case)]
        let BodyDoji_avgPeriod: i32 = self.candle_settings.body_doji.avg_period;
        #[allow(non_snake_case)]
        let BodyDoji_factor: f64 = self.candle_settings.body_doji.factor;
        #[allow(non_snake_case)]
        let ShadowVeryLong_rangeType: i32 = self.candle_settings.shadow_very_long.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryLong_avgPeriod: i32 = self.candle_settings.shadow_very_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryLong_factor: f64 = self.candle_settings.shadow_very_long.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        return ((BodyDoji_avgPeriod).max(ShadowVeryShort_avgPeriod)).max(ShadowVeryLong_avgPeriod);
    }
    /// Takuri (Dragonfly Doji with very long lower shadow)
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdltakuri<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdltakuri_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdltakuri_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        #[allow(non_snake_case)]
        let BodyDoji_rangeType: i32 = self.candle_settings.body_doji.range_type;
        #[allow(non_snake_case)]
        let BodyDoji_avgPeriod: i32 = self.candle_settings.body_doji.avg_period;
        #[allow(non_snake_case)]
        let BodyDoji_factor: f64 = self.candle_settings.body_doji.factor;
        #[allow(non_snake_case)]
        let ShadowVeryLong_rangeType: i32 = self.candle_settings.shadow_very_long.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryLong_avgPeriod: i32 = self.candle_settings.shadow_very_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryLong_factor: f64 = self.candle_settings.shadow_very_long.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        lookbackTotal = self.cdltakuri_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyDojiPeriodTotal = 0;
        BodyDojiTrailingIdx = startIdx - BodyDoji_avgPeriod;
        ShadowVeryShortPeriodTotal = 0;
        ShadowVeryShortTrailingIdx = startIdx - ShadowVeryShort_avgPeriod;
        ShadowVeryLongPeriodTotal = 0;
        ShadowVeryLongTrailingIdx = startIdx - ShadowVeryLong_avgPeriod;
        i = BodyDojiTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_0 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_0 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            BodyDojiPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_1 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_1 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryShortPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = ShadowVeryLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_2: T;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_2 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_2 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryLongPeriodTotal += _candlerange_2;
            i += 1;
        }
        outIdx = 0;
        loop {
            if inClose[i] - inOpen[i].ta_abs() <= ta_candleaverage(BodyDoji_rangeType, BodyDoji_avgPeriod, BodyDoji_factor, BodyDojiPeriodTotal, inOpen[i], inHigh[i], inLow[i], inClose[i]) && inHigh[i] - if inClose[i] >= inOpen[i] { inClose[i] } else { inOpen[i] } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, ShadowVeryShortPeriodTotal, inOpen[i], inHigh[i], inLow[i], inClose[i]) && if inClose[i] >= inOpen[i] { inOpen[i] } else { inClose[i] } - inLow[i] > ta_candleaverage(ShadowVeryLong_rangeType, ShadowVeryLong_avgPeriod, ShadowVeryLong_factor, ShadowVeryLongPeriodTotal, inOpen[i], inHigh[i], inLow[i], inClose[i]) {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 100;
            } else {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 0;
            }
            let mut _candlerange_3: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_3 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_3 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_3 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_4: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_4 = inClose[BodyDojiTrailingIdx] - inOpen[BodyDojiTrailingIdx].ta_abs();
                }
                1 => {
                    _candlerange_4 = inHigh[BodyDojiTrailingIdx] - inLow[BodyDojiTrailingIdx];
                }
                2 => {
                    _candlerange_4 = inHigh[BodyDojiTrailingIdx] - inLow[BodyDojiTrailingIdx] - inClose[BodyDojiTrailingIdx] - inOpen[BodyDojiTrailingIdx].ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            BodyDojiPeriodTotal += _candlerange_3 - _candlerange_4;
            let mut _candlerange_5: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_5 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_5 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_5 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_6: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_6 = inClose[ShadowVeryShortTrailingIdx] - inOpen[ShadowVeryShortTrailingIdx].ta_abs();
                }
                1 => {
                    _candlerange_6 = inHigh[ShadowVeryShortTrailingIdx] - inLow[ShadowVeryShortTrailingIdx];
                }
                2 => {
                    _candlerange_6 = inHigh[ShadowVeryShortTrailingIdx] - inLow[ShadowVeryShortTrailingIdx] - inClose[ShadowVeryShortTrailingIdx] - inOpen[ShadowVeryShortTrailingIdx].ta_abs();
                }
                _ => {
                    _candlerange_6 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryShortPeriodTotal += _candlerange_5 - _candlerange_6;
            let mut _candlerange_7: T;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_7 = inClose[i] - inOpen[i].ta_abs();
                }
                1 => {
                    _candlerange_7 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_7 = inHigh[i] - inLow[i] - inClose[i] - inOpen[i].ta_abs();
                }
                _ => {
                    _candlerange_7 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_8: T;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_8 = inClose[ShadowVeryLongTrailingIdx] - inOpen[ShadowVeryLongTrailingIdx].ta_abs();
                }
                1 => {
                    _candlerange_8 = inHigh[ShadowVeryLongTrailingIdx] - inLow[ShadowVeryLongTrailingIdx];
                }
                2 => {
                    _candlerange_8 = inHigh[ShadowVeryLongTrailingIdx] - inLow[ShadowVeryLongTrailingIdx] - inClose[ShadowVeryLongTrailingIdx] - inOpen[ShadowVeryLongTrailingIdx].ta_abs();
                }
                _ => {
                    _candlerange_8 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryLongPeriodTotal += _candlerange_7 - _candlerange_8;
            i += 1;
            BodyDojiTrailingIdx += 1;
            ShadowVeryShortTrailingIdx += 1;
            ShadowVeryLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn cdltakuri_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdltakuri_unguarded_unchecked(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn cdltakuri_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        #[allow(non_snake_case)]
        let BodyDoji_rangeType: i32 = self.candle_settings.body_doji.range_type;
        #[allow(non_snake_case)]
        let BodyDoji_avgPeriod: i32 = self.candle_settings.body_doji.avg_period;
        #[allow(non_snake_case)]
        let BodyDoji_factor: f64 = self.candle_settings.body_doji.factor;
        #[allow(non_snake_case)]
        let ShadowVeryLong_rangeType: i32 = self.candle_settings.shadow_very_long.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryLong_avgPeriod: i32 = self.candle_settings.shadow_very_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryLong_factor: f64 = self.candle_settings.shadow_very_long.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        lookbackTotal = self.cdltakuri_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyDojiPeriodTotal = 0;
        BodyDojiTrailingIdx = startIdx - BodyDoji_avgPeriod;
        ShadowVeryShortPeriodTotal = 0;
        ShadowVeryShortTrailingIdx = startIdx - ShadowVeryShort_avgPeriod;
        ShadowVeryLongPeriodTotal = 0;
        ShadowVeryLongTrailingIdx = startIdx - ShadowVeryLong_avgPeriod;
        i = BodyDojiTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_0 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_0 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            BodyDojiPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_1 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_1 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryShortPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = ShadowVeryLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_2: T;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_2 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_2 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryLongPeriodTotal += _candlerange_2;
            i += 1;
        }
        outIdx = 0;
        loop {
            if *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs() <= ta_candleaverage(BodyDoji_rangeType, BodyDoji_avgPeriod, BodyDoji_factor, BodyDojiPeriodTotal, *inOpen.get_unchecked(i), *inHigh.get_unchecked(i), *inLow.get_unchecked(i), *inClose.get_unchecked(i)) && *inHigh.get_unchecked(i) - if *inClose.get_unchecked(i) >= *inOpen.get_unchecked(i) { *inClose.get_unchecked(i) } else { *inOpen.get_unchecked(i) } < ta_candleaverage(ShadowVeryShort_rangeType, ShadowVeryShort_avgPeriod, ShadowVeryShort_factor, ShadowVeryShortPeriodTotal, *inOpen.get_unchecked(i), *inHigh.get_unchecked(i), *inLow.get_unchecked(i), *inClose.get_unchecked(i)) && if *inClose.get_unchecked(i) >= *inOpen.get_unchecked(i) { *inOpen.get_unchecked(i) } else { *inClose.get_unchecked(i) } - *inLow.get_unchecked(i) > ta_candleaverage(ShadowVeryLong_rangeType, ShadowVeryLong_avgPeriod, ShadowVeryLong_factor, ShadowVeryLongPeriodTotal, *inOpen.get_unchecked(i), *inHigh.get_unchecked(i), *inLow.get_unchecked(i), *inClose.get_unchecked(i)) {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 100;
            } else {
                *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 0;
            }
            let mut _candlerange_3: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_3 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_3 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_3 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_4: T;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_4 = *inClose.get_unchecked(BodyDojiTrailingIdx) - *inOpen.get_unchecked(BodyDojiTrailingIdx).ta_abs();
                }
                1 => {
                    _candlerange_4 = *inHigh.get_unchecked(BodyDojiTrailingIdx) - *inLow.get_unchecked(BodyDojiTrailingIdx);
                }
                2 => {
                    _candlerange_4 = *inHigh.get_unchecked(BodyDojiTrailingIdx) - *inLow.get_unchecked(BodyDojiTrailingIdx) - *inClose.get_unchecked(BodyDojiTrailingIdx) - *inOpen.get_unchecked(BodyDojiTrailingIdx).ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            BodyDojiPeriodTotal += _candlerange_3 - _candlerange_4;
            let mut _candlerange_5: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_5 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_5 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_5 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_6: T;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_6 = *inClose.get_unchecked(ShadowVeryShortTrailingIdx) - *inOpen.get_unchecked(ShadowVeryShortTrailingIdx).ta_abs();
                }
                1 => {
                    _candlerange_6 = *inHigh.get_unchecked(ShadowVeryShortTrailingIdx) - *inLow.get_unchecked(ShadowVeryShortTrailingIdx);
                }
                2 => {
                    _candlerange_6 = *inHigh.get_unchecked(ShadowVeryShortTrailingIdx) - *inLow.get_unchecked(ShadowVeryShortTrailingIdx) - *inClose.get_unchecked(ShadowVeryShortTrailingIdx) - *inOpen.get_unchecked(ShadowVeryShortTrailingIdx).ta_abs();
                }
                _ => {
                    _candlerange_6 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryShortPeriodTotal += _candlerange_5 - _candlerange_6;
            let mut _candlerange_7: T;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_7 = *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                1 => {
                    _candlerange_7 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i);
                }
                2 => {
                    _candlerange_7 = *inHigh.get_unchecked(i) - *inLow.get_unchecked(i) - *inClose.get_unchecked(i) - *inOpen.get_unchecked(i).ta_abs();
                }
                _ => {
                    _candlerange_7 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_8: T;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_8 = *inClose.get_unchecked(ShadowVeryLongTrailingIdx) - *inOpen.get_unchecked(ShadowVeryLongTrailingIdx).ta_abs();
                }
                1 => {
                    _candlerange_8 = *inHigh.get_unchecked(ShadowVeryLongTrailingIdx) - *inLow.get_unchecked(ShadowVeryLongTrailingIdx);
                }
                2 => {
                    _candlerange_8 = *inHigh.get_unchecked(ShadowVeryLongTrailingIdx) - *inLow.get_unchecked(ShadowVeryLongTrailingIdx) - *inClose.get_unchecked(ShadowVeryLongTrailingIdx) - *inOpen.get_unchecked(ShadowVeryLongTrailingIdx).ta_abs();
                }
                _ => {
                    _candlerange_8 = T::ta_from_f64(0.0);
                }
            }
            ShadowVeryLongPeriodTotal += _candlerange_7 - _candlerange_8;
            i += 1;
            BodyDojiTrailingIdx += 1;
            ShadowVeryShortTrailingIdx += 1;
            ShadowVeryLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
