/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cmo`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    pub fn cmo_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        let mut retValue: i32;
        retValue = optInTimePeriod + self.unstable_period[FuncUnstId::Cmo as usize];
        if self.compatibility == Compatibility::Metastock {
            retValue -= 1;
        }
        return retValue;
    }
    /// Chande Momentum Oscillator
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn cmo<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.cmo_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn cmo_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let outIdx: i32;
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = self.cmo_lookback(optInTimePeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod == 1 {
            (*outBegIdx) = startIdx;
            i = endIdx - startIdx + 1;
            (*outNBElement) = i;
            {
            let _n = (i * 1) as usize;
            let _di = (0) as usize;
            let _si = (startIdx) as usize;
            outReal[_di.._di + _n].copy_from_slice(&inReal[_si.._si + _n]);
        };
            return RetCode::Success;
        }
        today = startIdx - lookbackTotal;
        prevValue = inReal[today];
        unstablePeriod = self.unstable_period[FuncUnstId::Cmo as usize];
        if unstablePeriod == 0 && self.compatibility == Compatibility::Metastock {
            savePrevValue = prevValue;
            prevGain = T::ta_from_f64(0.0);
            prevLoss = T::ta_from_f64(0.0);
            // for( i = optInTimePeriod; i > 0; i -= 1 )
            i = optInTimePeriod;
            while i > 0 {
                tempValue1 = inReal[{ let _v = today; today += 1; _v }];
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                if tempValue2 < 0 {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
                i -= 1;
            }
            tempValue1 = prevLoss / optInTimePeriod;
            tempValue2 = prevGain / optInTimePeriod;
            tempValue3 = tempValue2 - tempValue1;
            tempValue4 = tempValue1 + tempValue2;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue4 && tempValue4 < T::ta_from_f64(0.00000001)) {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = 100 * (tempValue3 / tempValue4);
            } else {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = T::ta_from_f64(0.0);
            }
            if today > endIdx {
                (*outBegIdx) = startIdx;
                (*outNBElement) = outIdx;
                return RetCode::Success;
            }
            today -= optInTimePeriod;
            prevValue = savePrevValue;
        }
        prevGain = T::ta_from_f64(0.0);
        prevLoss = T::ta_from_f64(0.0);
        today += 1;
        // for( i = optInTimePeriod; i > 0; i -= 1 )
        i = optInTimePeriod;
        while i > 0 {
            tempValue1 = inReal[{ let _v = today; today += 1; _v }];
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            if tempValue2 < 0 {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
            i -= 1;
        }
        prevLoss /= optInTimePeriod;
        prevGain /= optInTimePeriod;
        if today > startIdx {
            tempValue1 = prevGain + prevLoss;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue1 && tempValue1 < T::ta_from_f64(0.00000001)) {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = T::ta_from_f64(100.0) * ((prevGain - prevLoss) / tempValue1);
            } else {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = T::ta_from_f64(0.0);
            }
        } else {
            while today < startIdx {
                tempValue1 = inReal[today];
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                prevLoss *= optInTimePeriod - 1;
                prevGain *= optInTimePeriod - 1;
                if tempValue2 < 0 {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
                prevLoss /= optInTimePeriod;
                prevGain /= optInTimePeriod;
                today += 1;
            }
        }
        while today <= endIdx {
            tempValue1 = inReal[{ let _v = today; today += 1; _v }];
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            prevLoss *= optInTimePeriod - 1;
            prevGain *= optInTimePeriod - 1;
            if tempValue2 < 0 {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
            prevLoss /= optInTimePeriod;
            prevGain /= optInTimePeriod;
            tempValue1 = prevGain + prevLoss;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue1 && tempValue1 < T::ta_from_f64(0.00000001)) {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = T::ta_from_f64(100.0) * ((prevGain - prevLoss) / tempValue1);
            } else {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = T::ta_from_f64(0.0);
            }
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn cmo_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.cmo_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn cmo_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let outIdx: i32;
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = self.cmo_lookback(optInTimePeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod == 1 {
            (*outBegIdx) = startIdx;
            i = endIdx - startIdx + 1;
            (*outNBElement) = i;
            {
            let _n = (i * 1) as usize;
            let _di = (0) as usize;
            let _si = (startIdx) as usize;
            outReal[_di.._di + _n].copy_from_slice(&inReal[_si.._si + _n]);
        };
            return RetCode::Success;
        }
        today = startIdx - lookbackTotal;
        prevValue = *inReal.get_unchecked(today);
        unstablePeriod = self.unstable_period[FuncUnstId::Cmo as usize];
        if unstablePeriod == 0 && self.compatibility == Compatibility::Metastock {
            savePrevValue = prevValue;
            prevGain = T::ta_from_f64(0.0);
            prevLoss = T::ta_from_f64(0.0);
            // for( i = optInTimePeriod; i > 0; i -= 1 )
            i = optInTimePeriod;
            while i > 0 {
                tempValue1 = *inReal.get_unchecked({ let _v = today; today += 1; _v });
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                if tempValue2 < 0 {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
                i -= 1;
            }
            tempValue1 = prevLoss / optInTimePeriod;
            tempValue2 = prevGain / optInTimePeriod;
            tempValue3 = tempValue2 - tempValue1;
            tempValue4 = tempValue1 + tempValue2;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue4 && tempValue4 < T::ta_from_f64(0.00000001)) {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 100 * (tempValue3 / tempValue4);
            } else {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = T::ta_from_f64(0.0);
            }
            if today > endIdx {
                (*outBegIdx) = startIdx;
                (*outNBElement) = outIdx;
                return RetCode::Success;
            }
            today -= optInTimePeriod;
            prevValue = savePrevValue;
        }
        prevGain = T::ta_from_f64(0.0);
        prevLoss = T::ta_from_f64(0.0);
        today += 1;
        // for( i = optInTimePeriod; i > 0; i -= 1 )
        i = optInTimePeriod;
        while i > 0 {
            tempValue1 = *inReal.get_unchecked({ let _v = today; today += 1; _v });
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            if tempValue2 < 0 {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
            i -= 1;
        }
        prevLoss /= optInTimePeriod;
        prevGain /= optInTimePeriod;
        if today > startIdx {
            tempValue1 = prevGain + prevLoss;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue1 && tempValue1 < T::ta_from_f64(0.00000001)) {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = T::ta_from_f64(100.0) * ((prevGain - prevLoss) / tempValue1);
            } else {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = T::ta_from_f64(0.0);
            }
        } else {
            while today < startIdx {
                tempValue1 = *inReal.get_unchecked(today);
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                prevLoss *= optInTimePeriod - 1;
                prevGain *= optInTimePeriod - 1;
                if tempValue2 < 0 {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
                prevLoss /= optInTimePeriod;
                prevGain /= optInTimePeriod;
                today += 1;
            }
        }
        while today <= endIdx {
            tempValue1 = *inReal.get_unchecked({ let _v = today; today += 1; _v });
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            prevLoss *= optInTimePeriod - 1;
            prevGain *= optInTimePeriod - 1;
            if tempValue2 < 0 {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
            prevLoss /= optInTimePeriod;
            prevGain /= optInTimePeriod;
            tempValue1 = prevGain + prevLoss;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue1 && tempValue1 < T::ta_from_f64(0.00000001)) {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = T::ta_from_f64(100.0) * ((prevGain - prevLoss) / tempValue1);
            } else {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = T::ta_from_f64(0.0);
            }
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
