/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
// allow unused variables and dead code due to gen code weirdness
#[allow(unused_variables)]
#[allow(dead_code)]
impl Core {
    /// Lookback period for [`Core::ema`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    pub fn ema_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        return optInTimePeriod - 1 + self.unstable_period[FuncUnstId::Ema as usize];
    }
    /// Exponential Moving Average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    ///
    /// # Returns
    ///
    /// [`RetCode::Success`] on success, or an error code on failure.
    ///
    /// # Example
    ///
    /// ```
    /// use ta_lib::ta_func::{Core, RetCode};
    ///
    ///
    /// let close_prices = [1.0, 2.0, 3.0, 4.0, 5.0_f64];
    /// let mut out = [0.0_f64; 5];
    /// let mut out_beg_idx: usize = 0;
    /// let mut out_nb_element: usize = 0;
    ///
    /// let core = Core::new();
    /// let result = core.ema(
    ///  0,
    ///  4,
    ///  &close_prices,
    ///  3,
    ///  &mut out_beg_idx,
    ///  &mut out_nb_element,
    ///  &mut out,
    /// );
    ///
    /// assert_eq!(result, RetCode::Success);
    /// assert_eq!(out_beg_idx, 2);
    /// assert_eq!(out_nb_element, 3);
    /// assert!((out[0] - 2.0).abs() < 1e-10);
    /// assert!((out[1] - 3.0).abs() < 1e-10);
    /// assert!((out[2] - 4.0).abs() < 1e-10);
    /// ```
    pub fn ema(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeEndIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.int_ema(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    fn int_ema(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut tempReal: f64;
        let mut prevMA: f64;
        let i: i32;
        let mut today: usize;
        let mut outIdx: usize;
        let lookbackTotal: usize;
        let optInK_1: f64;
        lookbackTotal = (self.ema_lookback(optInTimePeriod)) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        optInK_1 = 2.0_f64 / ((optInTimePeriod) as f64 + 1.0_f64);
        (*outBegIdx) = startIdx;
        if self.compatibility == Compatibility::Default {
            today = startIdx - lookbackTotal;
            i = optInTimePeriod;
            tempReal = 0.0;
            // for( i = optInTimePeriod; i > 0; i -= 1 )
            i = optInTimePeriod;
            while i > 0 {
                tempReal += (inReal[today]) as f64;
                today = today + 1;
                i -= 1;
            }
            prevMA = tempReal / ((optInTimePeriod) as f64);
        } else {
            prevMA = (inReal[0]) as f64;
            today = 1;
        }
        while today <= startIdx {
            prevMA = (((inReal[today]) as f64) - prevMA) * optInK_1 + prevMA;
            today = today + 1;
        }
        outReal[0] = prevMA;
        outIdx = 1;
        while today <= endIdx {
            prevMA = (((inReal[today]) as f64) - prevMA) * optInK_1 + prevMA;
            today = today + 1;
            outReal[outIdx] = prevMA;
            outIdx = outIdx + 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    /// Single-precision variant of [`Core::ema`].
    pub fn ema_s(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f32],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeEndIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.int_ema_s(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    fn int_ema_s(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f32],
        optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut tempReal: f64;
        let mut prevMA: f64;
        let i: i32;
        let mut today: usize;
        let mut outIdx: usize;
        let lookbackTotal: usize;
        let optInK_1: f64;
        lookbackTotal = (self.ema_lookback(optInTimePeriod)) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        optInK_1 = 2.0_f64 / ((optInTimePeriod) as f64 + 1.0_f64);
        (*outBegIdx) = startIdx;
        if self.compatibility == Compatibility::Default {
            today = startIdx - lookbackTotal;
            i = optInTimePeriod;
            tempReal = 0.0;
            // for( i = optInTimePeriod; i > 0; i -= 1 )
            i = optInTimePeriod;
            while i > 0 {
                tempReal += (inReal[today]) as f64;
                today = today + 1;
                i -= 1;
            }
            prevMA = tempReal / ((optInTimePeriod) as f64);
        } else {
            prevMA = (inReal[0]) as f64;
            today = 1;
        }
        while today <= startIdx {
            prevMA = (((inReal[today]) as f64) - prevMA) * optInK_1 + prevMA;
            today = today + 1;
        }
        outReal[0] = prevMA;
        outIdx = 1;
        while today <= endIdx {
            prevMA = (((inReal[today]) as f64) - prevMA) * optInK_1 + prevMA;
            today = today + 1;
            outReal[outIdx] = prevMA;
            outIdx = outIdx + 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
