/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::ht_trendline`].
    ///
    /// # Arguments
    ///
    pub fn ht_trendline_lookback(&self) -> i32 {
        return 63 + self.unstable_period[FuncUnstId::Ht_trendline as usize];
    }
    /// Hilbert Transform - Instantaneous Trendline
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn ht_trendline<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.ht_trendline_unguarded(
            startIdx,
            endIdx,
            inReal,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn ht_trendline_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let outIdx: i32;
        let i: i32;
        let lookbackTotal: i32;
        let mut today: i32;
        let mut tempReal: T;
        let mut tempReal2: T;
        let mut adjustedPrevPeriod: T;
        let mut period: T;
        let trailingWMAIdx: i32;
        let mut periodWMASum: T;
        let mut periodWMASub: T;
        let mut trailingWMAValue: T;
        let mut smoothedValue: T;
        let mut iTrend1: T;
        let mut iTrend2: T;
        let mut iTrend3: T;
        let a: T;
        let b: T;
        let mut hilbertTempReal: T;
        let mut hilbertIdx: i32;
        let mut detrender_Odd: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut detrender_Even: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut detrender: T;
        let mut prev_detrender_Odd: T;
        let mut prev_detrender_Even: T;
        let mut prev_detrender_input_Odd: T;
        let mut prev_detrender_input_Even: T;
        let mut Q1_Odd: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut Q1_Even: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut Q1: T;
        let mut prev_Q1_Odd: T;
        let mut prev_Q1_Even: T;
        let mut prev_Q1_input_Odd: T;
        let mut prev_Q1_input_Even: T;
        let mut jI_Odd: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut jI_Even: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut jI: T;
        let mut prev_jI_Odd: T;
        let mut prev_jI_Even: T;
        let mut prev_jI_input_Odd: T;
        let mut prev_jI_input_Even: T;
        let mut jQ_Odd: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut jQ_Even: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut jQ: T;
        let mut prev_jQ_Odd: T;
        let mut prev_jQ_Even: T;
        let mut prev_jQ_input_Odd: T;
        let mut prev_jQ_input_Even: T;
        let mut Q2: T;
        let mut I2: T;
        let mut prevQ2: T;
        let mut prevI2: T;
        let mut Re: T;
        let mut Im: T;
        let mut I1ForOddPrev2: T;
        let mut I1ForOddPrev3: T;
        let mut I1ForEvenPrev2: T;
        let mut I1ForEvenPrev3: T;
        let rad2Deg: T;
        let mut todayValue: T;
        let mut smoothPeriod: T;
        let mut smoothPrice: [T; 50 as usize] = [T::zero(); 50 as usize];
        let mut smoothPrice_Idx: i32;
        let mut idx: i32;
        let mut DCPeriodInt: i32;
        let mut DCPeriod: T;
        a = T::ta_from_f64(0.0962);
        b = T::ta_from_f64(0.5769);
        smoothPrice_Idx = 0;
        iTrend3 = T::ta_from_f64(0.0);
        iTrend2 = iTrend3;
        iTrend1 = iTrend2;
        tempReal = 1.ta_atan();
        rad2Deg = T::ta_from_f64(45.0) / tempReal;
        lookbackTotal = 63 + self.unstable_period[FuncUnstId::Ht_trendline as usize];
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        trailingWMAIdx = startIdx - lookbackTotal;
        today = trailingWMAIdx;
        tempReal = inReal[{ let _v = today; today += 1; _v }];
        periodWMASub = tempReal;
        periodWMASum = tempReal;
        tempReal = inReal[{ let _v = today; today += 1; _v }];
        periodWMASub += tempReal;
        periodWMASum += tempReal * T::ta_from_f64(2.0);
        tempReal = inReal[{ let _v = today; today += 1; _v }];
        periodWMASub += tempReal;
        periodWMASum += tempReal * T::ta_from_f64(3.0);
        trailingWMAValue = T::ta_from_f64(0.0);
        i = 34;
        loop {
            tempReal = inReal[{ let _v = today; today += 1; _v }];
            periodWMASub += tempReal;
            periodWMASub -= trailingWMAValue;
            periodWMASum += tempReal * T::ta_from_f64(4.0);
            trailingWMAValue = inReal[{ let _v = trailingWMAIdx; trailingWMAIdx += 1; _v }];
            smoothedValue = periodWMASum * T::ta_from_f64(0.1);
            periodWMASum -= periodWMASub;
            if !({ i -= 1; i } != 0) { break; }
        }
        hilbertIdx = 0;
        detrender_Odd[0] = T::ta_from_f64(0.0);
        detrender_Odd[1] = T::ta_from_f64(0.0);
        detrender_Odd[2] = T::ta_from_f64(0.0);
        detrender_Even[0] = T::ta_from_f64(0.0);
        detrender_Even[1] = T::ta_from_f64(0.0);
        detrender_Even[2] = T::ta_from_f64(0.0);
        detrender = T::ta_from_f64(0.0);
        prev_detrender_Odd = T::ta_from_f64(0.0);
        prev_detrender_Even = T::ta_from_f64(0.0);
        prev_detrender_input_Odd = T::ta_from_f64(0.0);
        prev_detrender_input_Even = T::ta_from_f64(0.0);
        Q1_Odd[0] = T::ta_from_f64(0.0);
        Q1_Odd[1] = T::ta_from_f64(0.0);
        Q1_Odd[2] = T::ta_from_f64(0.0);
        Q1_Even[0] = T::ta_from_f64(0.0);
        Q1_Even[1] = T::ta_from_f64(0.0);
        Q1_Even[2] = T::ta_from_f64(0.0);
        Q1 = T::ta_from_f64(0.0);
        prev_Q1_Odd = T::ta_from_f64(0.0);
        prev_Q1_Even = T::ta_from_f64(0.0);
        prev_Q1_input_Odd = T::ta_from_f64(0.0);
        prev_Q1_input_Even = T::ta_from_f64(0.0);
        jI_Odd[0] = T::ta_from_f64(0.0);
        jI_Odd[1] = T::ta_from_f64(0.0);
        jI_Odd[2] = T::ta_from_f64(0.0);
        jI_Even[0] = T::ta_from_f64(0.0);
        jI_Even[1] = T::ta_from_f64(0.0);
        jI_Even[2] = T::ta_from_f64(0.0);
        jI = T::ta_from_f64(0.0);
        prev_jI_Odd = T::ta_from_f64(0.0);
        prev_jI_Even = T::ta_from_f64(0.0);
        prev_jI_input_Odd = T::ta_from_f64(0.0);
        prev_jI_input_Even = T::ta_from_f64(0.0);
        jQ_Odd[0] = T::ta_from_f64(0.0);
        jQ_Odd[1] = T::ta_from_f64(0.0);
        jQ_Odd[2] = T::ta_from_f64(0.0);
        jQ_Even[0] = T::ta_from_f64(0.0);
        jQ_Even[1] = T::ta_from_f64(0.0);
        jQ_Even[2] = T::ta_from_f64(0.0);
        jQ = T::ta_from_f64(0.0);
        prev_jQ_Odd = T::ta_from_f64(0.0);
        prev_jQ_Even = T::ta_from_f64(0.0);
        prev_jQ_input_Odd = T::ta_from_f64(0.0);
        prev_jQ_input_Even = T::ta_from_f64(0.0);
        period = T::ta_from_f64(0.0);
        outIdx = 0;
        prevQ2 = T::ta_from_f64(0.0);
        prevI2 = prevQ2;
        Im = T::ta_from_f64(0.0);
        Re = Im;
        I1ForEvenPrev3 = T::ta_from_f64(0.0);
        I1ForOddPrev3 = I1ForEvenPrev3;
        I1ForEvenPrev2 = T::ta_from_f64(0.0);
        I1ForOddPrev2 = I1ForEvenPrev2;
        smoothPeriod = T::ta_from_f64(0.0);
        // for( i = 0; i < 50; i += 1 )
        i = 0;
        while i < 50 {
            smoothPrice[i] = T::ta_from_f64(0.0);
            i += 1;
        }
        while today <= endIdx {
            adjustedPrevPeriod = T::ta_from_f64(0.075) * period + T::ta_from_f64(0.54);
            todayValue = inReal[today];
            periodWMASub += todayValue;
            periodWMASub -= trailingWMAValue;
            periodWMASum += todayValue * T::ta_from_f64(4.0);
            trailingWMAValue = inReal[{ let _v = trailingWMAIdx; trailingWMAIdx += 1; _v }];
            smoothedValue = periodWMASum * T::ta_from_f64(0.1);
            periodWMASum -= periodWMASub;
            smoothPrice[smoothPrice_Idx] = smoothedValue;
            if today % 2 == 0 {
                hilbertTempReal = a * smoothedValue;
                detrender = 0 - detrender_Even[hilbertIdx];
                detrender_Even[hilbertIdx] = hilbertTempReal;
                detrender += hilbertTempReal;
                detrender -= prev_detrender_Even;
                prev_detrender_Even = b * prev_detrender_input_Even;
                detrender += prev_detrender_Even;
                prev_detrender_input_Even = smoothedValue;
                detrender *= adjustedPrevPeriod;
                hilbertTempReal = a * detrender;
                Q1 = 0 - Q1_Even[hilbertIdx];
                Q1_Even[hilbertIdx] = hilbertTempReal;
                Q1 += hilbertTempReal;
                Q1 -= prev_Q1_Even;
                prev_Q1_Even = b * prev_Q1_input_Even;
                Q1 += prev_Q1_Even;
                prev_Q1_input_Even = detrender;
                Q1 *= adjustedPrevPeriod;
                hilbertTempReal = a * I1ForEvenPrev3;
                jI = 0 - jI_Even[hilbertIdx];
                jI_Even[hilbertIdx] = hilbertTempReal;
                jI += hilbertTempReal;
                jI -= prev_jI_Even;
                prev_jI_Even = b * prev_jI_input_Even;
                jI += prev_jI_Even;
                prev_jI_input_Even = I1ForEvenPrev3;
                jI *= adjustedPrevPeriod;
                hilbertTempReal = a * Q1;
                jQ = 0 - jQ_Even[hilbertIdx];
                jQ_Even[hilbertIdx] = hilbertTempReal;
                jQ += hilbertTempReal;
                jQ -= prev_jQ_Even;
                prev_jQ_Even = b * prev_jQ_input_Even;
                jQ += prev_jQ_Even;
                prev_jQ_input_Even = Q1;
                jQ *= adjustedPrevPeriod;
                if { hilbertIdx += 1; hilbertIdx } == 3 {
                    hilbertIdx = 0;
                }
                Q2 = T::ta_from_f64(0.2) * (Q1 + jI) + T::ta_from_f64(0.8) * prevQ2;
                I2 = T::ta_from_f64(0.2) * (I1ForEvenPrev3 - jQ) + T::ta_from_f64(0.8) * prevI2;
                I1ForOddPrev3 = I1ForOddPrev2;
                I1ForOddPrev2 = detrender;
            } else {
                hilbertTempReal = a * smoothedValue;
                detrender = 0 - detrender_Odd[hilbertIdx];
                detrender_Odd[hilbertIdx] = hilbertTempReal;
                detrender += hilbertTempReal;
                detrender -= prev_detrender_Odd;
                prev_detrender_Odd = b * prev_detrender_input_Odd;
                detrender += prev_detrender_Odd;
                prev_detrender_input_Odd = smoothedValue;
                detrender *= adjustedPrevPeriod;
                hilbertTempReal = a * detrender;
                Q1 = 0 - Q1_Odd[hilbertIdx];
                Q1_Odd[hilbertIdx] = hilbertTempReal;
                Q1 += hilbertTempReal;
                Q1 -= prev_Q1_Odd;
                prev_Q1_Odd = b * prev_Q1_input_Odd;
                Q1 += prev_Q1_Odd;
                prev_Q1_input_Odd = detrender;
                Q1 *= adjustedPrevPeriod;
                hilbertTempReal = a * I1ForOddPrev3;
                jI = 0 - jI_Odd[hilbertIdx];
                jI_Odd[hilbertIdx] = hilbertTempReal;
                jI += hilbertTempReal;
                jI -= prev_jI_Odd;
                prev_jI_Odd = b * prev_jI_input_Odd;
                jI += prev_jI_Odd;
                prev_jI_input_Odd = I1ForOddPrev3;
                jI *= adjustedPrevPeriod;
                hilbertTempReal = a * Q1;
                jQ = 0 - jQ_Odd[hilbertIdx];
                jQ_Odd[hilbertIdx] = hilbertTempReal;
                jQ += hilbertTempReal;
                jQ -= prev_jQ_Odd;
                prev_jQ_Odd = b * prev_jQ_input_Odd;
                jQ += prev_jQ_Odd;
                prev_jQ_input_Odd = Q1;
                jQ *= adjustedPrevPeriod;
                Q2 = T::ta_from_f64(0.2) * (Q1 + jI) + T::ta_from_f64(0.8) * prevQ2;
                I2 = T::ta_from_f64(0.2) * (I1ForOddPrev3 - jQ) + T::ta_from_f64(0.8) * prevI2;
                I1ForEvenPrev3 = I1ForEvenPrev2;
                I1ForEvenPrev2 = detrender;
            }
            Re = T::ta_from_f64(0.2) * (I2 * prevI2 + Q2 * prevQ2) + T::ta_from_f64(0.8) * Re;
            Im = T::ta_from_f64(0.2) * (I2 * prevQ2 - Q2 * prevI2) + T::ta_from_f64(0.8) * Im;
            prevQ2 = Q2;
            prevI2 = I2;
            tempReal = period;
            if Im != T::ta_from_f64(0.0) && Re != T::ta_from_f64(0.0) {
                period = T::ta_from_f64(360.0) / (Im / Re.ta_atan() * rad2Deg);
            }
            tempReal2 = T::ta_from_f64(1.5) * tempReal;
            if period > tempReal2 {
                period = tempReal2;
            }
            tempReal2 = T::ta_from_f64(0.67) * tempReal;
            if period < tempReal2 {
                period = tempReal2;
            }
            if period < 6 {
                period = 6;
            } else if period > 50 {
                period = 50;
            }
            period = T::ta_from_f64(0.2) * period + T::ta_from_f64(0.8) * tempReal;
            smoothPeriod = T::ta_from_f64(0.33) * period + T::ta_from_f64(0.67) * smoothPeriod;
            DCPeriod = smoothPeriod + T::ta_from_f64(0.5);
            DCPeriodInt = (DCPeriod) as i32;
            idx = today;
            tempReal = T::ta_from_f64(0.0);
            // for( i = 0; i < DCPeriodInt; i += 1 )
            i = 0;
            while i < DCPeriodInt {
                tempReal += inReal[{ let _v = idx; idx -= 1; _v }];
                i += 1;
            }
            if DCPeriodInt > 0 {
                tempReal = tempReal / (T::ta_from_f64((DCPeriodInt).ta_to_f64()));
            }
            tempReal2 = (T::ta_from_f64(4.0) * tempReal + T::ta_from_f64(3.0) * iTrend1 + T::ta_from_f64(2.0) * iTrend2 + iTrend3) / T::ta_from_f64(10.0);
            iTrend3 = iTrend2;
            iTrend2 = iTrend1;
            iTrend1 = tempReal;
            if today >= startIdx {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = tempReal2;
            }
            smoothPrice_Idx = (smoothPrice_Idx + 1) % 50;
            today += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    pub unsafe fn ht_trendline_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.ht_trendline_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn ht_trendline_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let outIdx: i32;
        let i: i32;
        let lookbackTotal: i32;
        let mut today: i32;
        let mut tempReal: T;
        let mut tempReal2: T;
        let mut adjustedPrevPeriod: T;
        let mut period: T;
        let trailingWMAIdx: i32;
        let mut periodWMASum: T;
        let mut periodWMASub: T;
        let mut trailingWMAValue: T;
        let mut smoothedValue: T;
        let mut iTrend1: T;
        let mut iTrend2: T;
        let mut iTrend3: T;
        let a: T;
        let b: T;
        let mut hilbertTempReal: T;
        let mut hilbertIdx: i32;
        let mut detrender_Odd: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut detrender_Even: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut detrender: T;
        let mut prev_detrender_Odd: T;
        let mut prev_detrender_Even: T;
        let mut prev_detrender_input_Odd: T;
        let mut prev_detrender_input_Even: T;
        let mut Q1_Odd: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut Q1_Even: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut Q1: T;
        let mut prev_Q1_Odd: T;
        let mut prev_Q1_Even: T;
        let mut prev_Q1_input_Odd: T;
        let mut prev_Q1_input_Even: T;
        let mut jI_Odd: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut jI_Even: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut jI: T;
        let mut prev_jI_Odd: T;
        let mut prev_jI_Even: T;
        let mut prev_jI_input_Odd: T;
        let mut prev_jI_input_Even: T;
        let mut jQ_Odd: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut jQ_Even: [T; 3 as usize] = [T::zero(); 3 as usize];
        let mut jQ: T;
        let mut prev_jQ_Odd: T;
        let mut prev_jQ_Even: T;
        let mut prev_jQ_input_Odd: T;
        let mut prev_jQ_input_Even: T;
        let mut Q2: T;
        let mut I2: T;
        let mut prevQ2: T;
        let mut prevI2: T;
        let mut Re: T;
        let mut Im: T;
        let mut I1ForOddPrev2: T;
        let mut I1ForOddPrev3: T;
        let mut I1ForEvenPrev2: T;
        let mut I1ForEvenPrev3: T;
        let rad2Deg: T;
        let mut todayValue: T;
        let mut smoothPeriod: T;
        let mut smoothPrice: [T; 50 as usize] = [T::zero(); 50 as usize];
        let mut smoothPrice_Idx: i32;
        let mut idx: i32;
        let mut DCPeriodInt: i32;
        let mut DCPeriod: T;
        a = T::ta_from_f64(0.0962);
        b = T::ta_from_f64(0.5769);
        smoothPrice_Idx = 0;
        iTrend3 = T::ta_from_f64(0.0);
        iTrend2 = iTrend3;
        iTrend1 = iTrend2;
        tempReal = 1.ta_atan();
        rad2Deg = T::ta_from_f64(45.0) / tempReal;
        lookbackTotal = 63 + self.unstable_period[FuncUnstId::Ht_trendline as usize];
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        trailingWMAIdx = startIdx - lookbackTotal;
        today = trailingWMAIdx;
        tempReal = *inReal.get_unchecked({ let _v = today; today += 1; _v });
        periodWMASub = tempReal;
        periodWMASum = tempReal;
        tempReal = *inReal.get_unchecked({ let _v = today; today += 1; _v });
        periodWMASub += tempReal;
        periodWMASum += tempReal * T::ta_from_f64(2.0);
        tempReal = *inReal.get_unchecked({ let _v = today; today += 1; _v });
        periodWMASub += tempReal;
        periodWMASum += tempReal * T::ta_from_f64(3.0);
        trailingWMAValue = T::ta_from_f64(0.0);
        i = 34;
        loop {
            tempReal = *inReal.get_unchecked({ let _v = today; today += 1; _v });
            periodWMASub += tempReal;
            periodWMASub -= trailingWMAValue;
            periodWMASum += tempReal * T::ta_from_f64(4.0);
            trailingWMAValue = *inReal.get_unchecked({ let _v = trailingWMAIdx; trailingWMAIdx += 1; _v });
            smoothedValue = periodWMASum * T::ta_from_f64(0.1);
            periodWMASum -= periodWMASub;
            if !({ i -= 1; i } != 0) { break; }
        }
        hilbertIdx = 0;
        *detrender_Odd.get_unchecked_mut(0) = T::ta_from_f64(0.0);
        *detrender_Odd.get_unchecked_mut(1) = T::ta_from_f64(0.0);
        *detrender_Odd.get_unchecked_mut(2) = T::ta_from_f64(0.0);
        *detrender_Even.get_unchecked_mut(0) = T::ta_from_f64(0.0);
        *detrender_Even.get_unchecked_mut(1) = T::ta_from_f64(0.0);
        *detrender_Even.get_unchecked_mut(2) = T::ta_from_f64(0.0);
        detrender = T::ta_from_f64(0.0);
        prev_detrender_Odd = T::ta_from_f64(0.0);
        prev_detrender_Even = T::ta_from_f64(0.0);
        prev_detrender_input_Odd = T::ta_from_f64(0.0);
        prev_detrender_input_Even = T::ta_from_f64(0.0);
        *Q1_Odd.get_unchecked_mut(0) = T::ta_from_f64(0.0);
        *Q1_Odd.get_unchecked_mut(1) = T::ta_from_f64(0.0);
        *Q1_Odd.get_unchecked_mut(2) = T::ta_from_f64(0.0);
        *Q1_Even.get_unchecked_mut(0) = T::ta_from_f64(0.0);
        *Q1_Even.get_unchecked_mut(1) = T::ta_from_f64(0.0);
        *Q1_Even.get_unchecked_mut(2) = T::ta_from_f64(0.0);
        Q1 = T::ta_from_f64(0.0);
        prev_Q1_Odd = T::ta_from_f64(0.0);
        prev_Q1_Even = T::ta_from_f64(0.0);
        prev_Q1_input_Odd = T::ta_from_f64(0.0);
        prev_Q1_input_Even = T::ta_from_f64(0.0);
        *jI_Odd.get_unchecked_mut(0) = T::ta_from_f64(0.0);
        *jI_Odd.get_unchecked_mut(1) = T::ta_from_f64(0.0);
        *jI_Odd.get_unchecked_mut(2) = T::ta_from_f64(0.0);
        *jI_Even.get_unchecked_mut(0) = T::ta_from_f64(0.0);
        *jI_Even.get_unchecked_mut(1) = T::ta_from_f64(0.0);
        *jI_Even.get_unchecked_mut(2) = T::ta_from_f64(0.0);
        jI = T::ta_from_f64(0.0);
        prev_jI_Odd = T::ta_from_f64(0.0);
        prev_jI_Even = T::ta_from_f64(0.0);
        prev_jI_input_Odd = T::ta_from_f64(0.0);
        prev_jI_input_Even = T::ta_from_f64(0.0);
        *jQ_Odd.get_unchecked_mut(0) = T::ta_from_f64(0.0);
        *jQ_Odd.get_unchecked_mut(1) = T::ta_from_f64(0.0);
        *jQ_Odd.get_unchecked_mut(2) = T::ta_from_f64(0.0);
        *jQ_Even.get_unchecked_mut(0) = T::ta_from_f64(0.0);
        *jQ_Even.get_unchecked_mut(1) = T::ta_from_f64(0.0);
        *jQ_Even.get_unchecked_mut(2) = T::ta_from_f64(0.0);
        jQ = T::ta_from_f64(0.0);
        prev_jQ_Odd = T::ta_from_f64(0.0);
        prev_jQ_Even = T::ta_from_f64(0.0);
        prev_jQ_input_Odd = T::ta_from_f64(0.0);
        prev_jQ_input_Even = T::ta_from_f64(0.0);
        period = T::ta_from_f64(0.0);
        outIdx = 0;
        prevQ2 = T::ta_from_f64(0.0);
        prevI2 = prevQ2;
        Im = T::ta_from_f64(0.0);
        Re = Im;
        I1ForEvenPrev3 = T::ta_from_f64(0.0);
        I1ForOddPrev3 = I1ForEvenPrev3;
        I1ForEvenPrev2 = T::ta_from_f64(0.0);
        I1ForOddPrev2 = I1ForEvenPrev2;
        smoothPeriod = T::ta_from_f64(0.0);
        // for( i = 0; i < 50; i += 1 )
        i = 0;
        while i < 50 {
            *smoothPrice.get_unchecked_mut(i) = T::ta_from_f64(0.0);
            i += 1;
        }
        while today <= endIdx {
            adjustedPrevPeriod = T::ta_from_f64(0.075) * period + T::ta_from_f64(0.54);
            todayValue = *inReal.get_unchecked(today);
            periodWMASub += todayValue;
            periodWMASub -= trailingWMAValue;
            periodWMASum += todayValue * T::ta_from_f64(4.0);
            trailingWMAValue = *inReal.get_unchecked({ let _v = trailingWMAIdx; trailingWMAIdx += 1; _v });
            smoothedValue = periodWMASum * T::ta_from_f64(0.1);
            periodWMASum -= periodWMASub;
            *smoothPrice.get_unchecked_mut(smoothPrice_Idx) = smoothedValue;
            if today % 2 == 0 {
                hilbertTempReal = a * smoothedValue;
                detrender = 0 - *detrender_Even.get_unchecked(hilbertIdx);
                *detrender_Even.get_unchecked_mut(hilbertIdx) = hilbertTempReal;
                detrender += hilbertTempReal;
                detrender -= prev_detrender_Even;
                prev_detrender_Even = b * prev_detrender_input_Even;
                detrender += prev_detrender_Even;
                prev_detrender_input_Even = smoothedValue;
                detrender *= adjustedPrevPeriod;
                hilbertTempReal = a * detrender;
                Q1 = 0 - *Q1_Even.get_unchecked(hilbertIdx);
                *Q1_Even.get_unchecked_mut(hilbertIdx) = hilbertTempReal;
                Q1 += hilbertTempReal;
                Q1 -= prev_Q1_Even;
                prev_Q1_Even = b * prev_Q1_input_Even;
                Q1 += prev_Q1_Even;
                prev_Q1_input_Even = detrender;
                Q1 *= adjustedPrevPeriod;
                hilbertTempReal = a * I1ForEvenPrev3;
                jI = 0 - *jI_Even.get_unchecked(hilbertIdx);
                *jI_Even.get_unchecked_mut(hilbertIdx) = hilbertTempReal;
                jI += hilbertTempReal;
                jI -= prev_jI_Even;
                prev_jI_Even = b * prev_jI_input_Even;
                jI += prev_jI_Even;
                prev_jI_input_Even = I1ForEvenPrev3;
                jI *= adjustedPrevPeriod;
                hilbertTempReal = a * Q1;
                jQ = 0 - *jQ_Even.get_unchecked(hilbertIdx);
                *jQ_Even.get_unchecked_mut(hilbertIdx) = hilbertTempReal;
                jQ += hilbertTempReal;
                jQ -= prev_jQ_Even;
                prev_jQ_Even = b * prev_jQ_input_Even;
                jQ += prev_jQ_Even;
                prev_jQ_input_Even = Q1;
                jQ *= adjustedPrevPeriod;
                if { hilbertIdx += 1; hilbertIdx } == 3 {
                    hilbertIdx = 0;
                }
                Q2 = T::ta_from_f64(0.2) * (Q1 + jI) + T::ta_from_f64(0.8) * prevQ2;
                I2 = T::ta_from_f64(0.2) * (I1ForEvenPrev3 - jQ) + T::ta_from_f64(0.8) * prevI2;
                I1ForOddPrev3 = I1ForOddPrev2;
                I1ForOddPrev2 = detrender;
            } else {
                hilbertTempReal = a * smoothedValue;
                detrender = 0 - *detrender_Odd.get_unchecked(hilbertIdx);
                *detrender_Odd.get_unchecked_mut(hilbertIdx) = hilbertTempReal;
                detrender += hilbertTempReal;
                detrender -= prev_detrender_Odd;
                prev_detrender_Odd = b * prev_detrender_input_Odd;
                detrender += prev_detrender_Odd;
                prev_detrender_input_Odd = smoothedValue;
                detrender *= adjustedPrevPeriod;
                hilbertTempReal = a * detrender;
                Q1 = 0 - *Q1_Odd.get_unchecked(hilbertIdx);
                *Q1_Odd.get_unchecked_mut(hilbertIdx) = hilbertTempReal;
                Q1 += hilbertTempReal;
                Q1 -= prev_Q1_Odd;
                prev_Q1_Odd = b * prev_Q1_input_Odd;
                Q1 += prev_Q1_Odd;
                prev_Q1_input_Odd = detrender;
                Q1 *= adjustedPrevPeriod;
                hilbertTempReal = a * I1ForOddPrev3;
                jI = 0 - *jI_Odd.get_unchecked(hilbertIdx);
                *jI_Odd.get_unchecked_mut(hilbertIdx) = hilbertTempReal;
                jI += hilbertTempReal;
                jI -= prev_jI_Odd;
                prev_jI_Odd = b * prev_jI_input_Odd;
                jI += prev_jI_Odd;
                prev_jI_input_Odd = I1ForOddPrev3;
                jI *= adjustedPrevPeriod;
                hilbertTempReal = a * Q1;
                jQ = 0 - *jQ_Odd.get_unchecked(hilbertIdx);
                *jQ_Odd.get_unchecked_mut(hilbertIdx) = hilbertTempReal;
                jQ += hilbertTempReal;
                jQ -= prev_jQ_Odd;
                prev_jQ_Odd = b * prev_jQ_input_Odd;
                jQ += prev_jQ_Odd;
                prev_jQ_input_Odd = Q1;
                jQ *= adjustedPrevPeriod;
                Q2 = T::ta_from_f64(0.2) * (Q1 + jI) + T::ta_from_f64(0.8) * prevQ2;
                I2 = T::ta_from_f64(0.2) * (I1ForOddPrev3 - jQ) + T::ta_from_f64(0.8) * prevI2;
                I1ForEvenPrev3 = I1ForEvenPrev2;
                I1ForEvenPrev2 = detrender;
            }
            Re = T::ta_from_f64(0.2) * (I2 * prevI2 + Q2 * prevQ2) + T::ta_from_f64(0.8) * Re;
            Im = T::ta_from_f64(0.2) * (I2 * prevQ2 - Q2 * prevI2) + T::ta_from_f64(0.8) * Im;
            prevQ2 = Q2;
            prevI2 = I2;
            tempReal = period;
            if Im != T::ta_from_f64(0.0) && Re != T::ta_from_f64(0.0) {
                period = T::ta_from_f64(360.0) / (Im / Re.ta_atan() * rad2Deg);
            }
            tempReal2 = T::ta_from_f64(1.5) * tempReal;
            if period > tempReal2 {
                period = tempReal2;
            }
            tempReal2 = T::ta_from_f64(0.67) * tempReal;
            if period < tempReal2 {
                period = tempReal2;
            }
            if period < 6 {
                period = 6;
            } else if period > 50 {
                period = 50;
            }
            period = T::ta_from_f64(0.2) * period + T::ta_from_f64(0.8) * tempReal;
            smoothPeriod = T::ta_from_f64(0.33) * period + T::ta_from_f64(0.67) * smoothPeriod;
            DCPeriod = smoothPeriod + T::ta_from_f64(0.5);
            DCPeriodInt = (DCPeriod) as i32;
            idx = today;
            tempReal = T::ta_from_f64(0.0);
            // for( i = 0; i < DCPeriodInt; i += 1 )
            i = 0;
            while i < DCPeriodInt {
                tempReal += *inReal.get_unchecked({ let _v = idx; idx -= 1; _v });
                i += 1;
            }
            if DCPeriodInt > 0 {
                tempReal = tempReal / (T::ta_from_f64((DCPeriodInt).ta_to_f64()));
            }
            tempReal2 = (T::ta_from_f64(4.0) * tempReal + T::ta_from_f64(3.0) * iTrend1 + T::ta_from_f64(2.0) * iTrend2 + iTrend3) / T::ta_from_f64(10.0);
            iTrend3 = iTrend2;
            iTrend2 = iTrend1;
            iTrend1 = tempReal;
            if today >= startIdx {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = tempReal2;
            }
            smoothPrice_Idx = (smoothPrice_Idx + 1) % 50;
            today += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
