/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
// allow unused variables and dead code due to gen code weirdness
#[allow(unused_variables)]
#[allow(dead_code)]
impl Core {
    /// Lookback period for [`Core::ma`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 1..=100000)
    /// * `optInMAType` - Number of period (default: 0, range: 0..=8)
    pub fn ma_lookback(&self, mut optInTimePeriod: i32, mut optInMAType: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        if ((optInMAType) as i32) == (i32::MIN) {
            optInMAType = 0;
        } else if (((optInMAType) as i32) < 0) || (((optInMAType) as i32) > 8) {
            return -1;
        }
        let mut retValue: i32;
        if optInTimePeriod <= 1 {
            return 0;
        }
        match optInMAType {
            0 => {
                retValue = self.sma_lookback(optInTimePeriod);
            }
            1 => {
                retValue = self.ema_lookback(optInTimePeriod);
            }
            _ => {
                retValue = 0;
            }
        }
        return retValue;
    }
    /// Moving average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 1..=100000)
    /// * `optInMAType` - Number of period (default: 0, range: 0..=8)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    ///
    /// # Returns
    ///
    /// [`RetCode::Success`] on success, or an error code on failure.
    ///
    /// # Example
    ///
    /// ```
    /// use ta_lib::ta_func::{Core, RetCode};
    ///
    ///
    /// let close_prices = [1.0, 2.0, 3.0, 4.0, 5.0_f64];
    /// let mut out = [0.0_f64; 5];
    /// let mut out_beg_idx: usize = 0;
    /// let mut out_nb_element: usize = 0;
    ///
    /// let core = Core::new();
    /// let result = core.ma(
    ///  0,
    ///  4,
    ///  &close_prices,
    ///  2,
    ///  1,
    ///  &mut out_beg_idx,
    ///  &mut out_nb_element,
    ///  &mut out,
    /// );
    ///
    /// assert_eq!(result, RetCode::Success);
    /// assert_eq!(out_beg_idx, 2);
    /// assert_eq!(out_nb_element, 3);
    /// assert!((out[0] - 2.0).abs() < 1e-10);
    /// assert!((out[1] - 3.0).abs() < 1e-10);
    /// assert!((out[2] - 4.0).abs() < 1e-10);
    /// ```
    pub fn ma(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeEndIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInMAType) as i32) == (i32::MIN) {
            optInMAType = 0;
        } else if (((optInMAType) as i32) < 0) || (((optInMAType) as i32) > 8) {
            return RetCode::BadParam;
        }
        return self.int_ma(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            optInMAType,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    fn int_ma(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        optInTimePeriod: i32,
        optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let nbElement: usize;
        let mut outIdx: usize;
        let mut todayIdx: usize;
        let mut retCode: RetCode;
        if optInTimePeriod == 1 {
            nbElement = endIdx - startIdx + 1;
            (*outNBElement) = nbElement;
            todayIdx = startIdx;
            outIdx = 0;
            while outIdx < nbElement {
                outReal[outIdx] = (inReal[todayIdx]) as f64;
                outIdx = outIdx + 1;
                todayIdx = todayIdx + 1;
            }
            (*outBegIdx) = startIdx;
            return RetCode::Success;
        }
        match optInMAType {
            0 => {
                retCode = self.sma(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            1 => {
                retCode = self.ema(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            _ => {
                retCode = RetCode::BadParam;
            }
        }
        return retCode;
        return RetCode::Success;
    }
    /// Single-precision variant of [`Core::ma`].
    pub fn ma_s(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f32],
        mut optInTimePeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeEndIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInMAType) as i32) == (i32::MIN) {
            optInMAType = 0;
        } else if (((optInMAType) as i32) < 0) || (((optInMAType) as i32) > 8) {
            return RetCode::BadParam;
        }
        return self.int_ma_s(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            optInMAType,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    fn int_ma_s(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f32],
        optInTimePeriod: i32,
        optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let nbElement: usize;
        let mut outIdx: usize;
        let mut todayIdx: usize;
        let mut retCode: RetCode;
        if optInTimePeriod == 1 {
            nbElement = endIdx - startIdx + 1;
            (*outNBElement) = nbElement;
            todayIdx = startIdx;
            outIdx = 0;
            while outIdx < nbElement {
                outReal[outIdx] = (inReal[todayIdx]) as f64;
                outIdx = outIdx + 1;
                todayIdx = todayIdx + 1;
            }
            (*outBegIdx) = startIdx;
            return RetCode::Success;
        }
        match optInMAType {
            0 => {
                retCode = self.sma_s(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            1 => {
                retCode = self.ema_s(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            _ => {
                retCode = RetCode::BadParam;
            }
        }
        return retCode;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
