/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::macd`].
    ///
    /// # Arguments
    ///
    /// * `optInFastPeriod` - Number of period (default: 12, range: 2..=100000)
    /// * `optInSlowPeriod` - Number of period (default: 26, range: 2..=100000)
    /// * `optInSignalPeriod` - Number of period (default: 9, range: 1..=100000)
    pub fn macd_lookback(&self, mut optInFastPeriod: i32, mut optInSlowPeriod: i32, mut optInSignalPeriod: i32) -> i32 {
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 12;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return -1;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 26;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return -1;
        }
        if ((optInSignalPeriod) as i32) == (i32::MIN) {
            optInSignalPeriod = 9;
        } else if (((optInSignalPeriod) as i32) < 1) || (((optInSignalPeriod) as i32) > 100000) {
            return -1;
        }
        let tempInteger: i32;
        if optInSlowPeriod < optInFastPeriod {
            tempInteger = optInSlowPeriod;
            optInSlowPeriod = optInFastPeriod;
            optInFastPeriod = tempInteger;
        }
        return self.ema_lookback(optInSlowPeriod) + self.ema_lookback(optInSignalPeriod);
    }
    /// Moving Average Convergence/Divergence
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInFastPeriod` - Number of period (default: 12, range: 2..=100000)
    /// * `optInSlowPeriod` - Number of period (default: 26, range: 2..=100000)
    /// * `optInSignalPeriod` - Number of period (default: 9, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outMACD` - Output values
    /// * `outMACDSignal` - Output values
    /// * `outMACDHist` - Output values
    pub fn macd<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInFastPeriod: i32,
        mut optInSlowPeriod: i32,
        mut optInSignalPeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outMACD: &mut [T],
        outMACDSignal: &mut [T],
        outMACDHist: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 12;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 26;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSignalPeriod) as i32) == (i32::MIN) {
            optInSignalPeriod = 9;
        } else if (((optInSignalPeriod) as i32) < 1) || (((optInSignalPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.macd_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInFastPeriod,
            optInSlowPeriod,
            optInSignalPeriod,
            outBegIdx,
            outNBElement,
            outMACD,
            outMACDSignal,
            outMACDHist,
        );
    }
    pub fn macd_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInFastPeriod: i32,
        mut optInSlowPeriod: i32,
        mut optInSignalPeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outMACD: &mut [T],
        outMACDSignal: &mut [T],
        outMACDHist: &mut [T],
    ) -> RetCode {
        let slowEMABuffer: Vec<T>;
        let fastEMABuffer: Vec<T>;
        let mut retCode: RetCode;
        let mut tempInteger: i32;
        let outBegIdx1: i32;
        let outNbElement1: i32;
        let outBegIdx2: i32;
        let outNbElement2: i32;
        let mut lookbackTotal: i32;
        let lookbackSignal: i32;
        let i: i32;
        if optInSlowPeriod < optInFastPeriod {
            tempInteger = optInSlowPeriod;
            optInSlowPeriod = optInFastPeriod;
            optInFastPeriod = tempInteger;
        }
        if optInSlowPeriod == 0 {
            optInSlowPeriod = 26;
        }
        if optInFastPeriod == 0 {
            optInFastPeriod = 12;
        }
        lookbackSignal = self.ema_lookback(optInSignalPeriod);
        lookbackTotal = lookbackSignal;
        lookbackTotal += self.ema_lookback(optInSlowPeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        tempInteger = endIdx - startIdx + 1 + lookbackSignal;
        fastEMABuffer = vec![T::default(); (tempInteger * 1) as usize];
        slowEMABuffer = vec![T::default(); (tempInteger * 1) as usize];
        tempInteger = startIdx - lookbackSignal;
        retCode = self.ema_unguarded(tempInteger, endIdx, inReal, optInSlowPeriod, outBegIdx1, outNbElement1, slowEMABuffer);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.ema_unguarded(tempInteger, endIdx, inReal, optInFastPeriod, outBegIdx2, outNbElement2, fastEMABuffer);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        if outBegIdx1 != tempInteger || outBegIdx2 != tempInteger || outNbElement1 != outNbElement2 || outNbElement1 != endIdx - startIdx + 1 + lookbackSignal {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::BadParam;
        }
        // for( i = 0; i < outNbElement1; i += 1 )
        i = 0;
        while i < outNbElement1 {
            fastEMABuffer[i] = fastEMABuffer[i] - slowEMABuffer[i];
            i += 1;
        }
        {
            let _n = ((endIdx - startIdx + 1) * 1) as usize;
            let _di = (0) as usize;
            let _si = (lookbackSignal) as usize;
            outMACD[_di.._di + _n].copy_from_slice(&fastEMABuffer[_si.._si + _n]);
        };
        retCode = self.ema_unguarded(0, outNbElement1 - 1, fastEMABuffer, optInSignalPeriod, outBegIdx2, outNbElement2, outMACDSignal);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        // for( i = 0; i < outNbElement2; i += 1 )
        i = 0;
        while i < outNbElement2 {
            outMACDHist[i] = outMACD[i] - outMACDSignal[i];
            i += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outNbElement2;
        return RetCode::Success;
    }
    pub unsafe fn macd_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInFastPeriod: i32,
        mut optInSlowPeriod: i32,
        mut optInSignalPeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outMACD: &mut [T],
        outMACDSignal: &mut [T],
        outMACDHist: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 12;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 26;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSignalPeriod) as i32) == (i32::MIN) {
            optInSignalPeriod = 9;
        } else if (((optInSignalPeriod) as i32) < 1) || (((optInSignalPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.macd_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            optInFastPeriod,
            optInSlowPeriod,
            optInSignalPeriod,
            outBegIdx,
            outNBElement,
            outMACD,
            outMACDSignal,
            outMACDHist,
        );
    }
    pub unsafe fn macd_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInFastPeriod: i32,
        mut optInSlowPeriod: i32,
        mut optInSignalPeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outMACD: &mut [T],
        outMACDSignal: &mut [T],
        outMACDHist: &mut [T],
    ) -> RetCode {
        let slowEMABuffer: Vec<T>;
        let fastEMABuffer: Vec<T>;
        let mut retCode: RetCode;
        let mut tempInteger: i32;
        let outBegIdx1: i32;
        let outNbElement1: i32;
        let outBegIdx2: i32;
        let outNbElement2: i32;
        let mut lookbackTotal: i32;
        let lookbackSignal: i32;
        let i: i32;
        if optInSlowPeriod < optInFastPeriod {
            tempInteger = optInSlowPeriod;
            optInSlowPeriod = optInFastPeriod;
            optInFastPeriod = tempInteger;
        }
        if optInSlowPeriod == 0 {
            optInSlowPeriod = 26;
        }
        if optInFastPeriod == 0 {
            optInFastPeriod = 12;
        }
        lookbackSignal = self.ema_lookback(optInSignalPeriod);
        lookbackTotal = lookbackSignal;
        lookbackTotal += self.ema_lookback(optInSlowPeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        tempInteger = endIdx - startIdx + 1 + lookbackSignal;
        fastEMABuffer = vec![T::default(); (tempInteger * 1) as usize];
        slowEMABuffer = vec![T::default(); (tempInteger * 1) as usize];
        tempInteger = startIdx - lookbackSignal;
        retCode = self.ema_unguarded(tempInteger, endIdx, inReal, optInSlowPeriod, outBegIdx1, outNbElement1, slowEMABuffer);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.ema_unguarded(tempInteger, endIdx, inReal, optInFastPeriod, outBegIdx2, outNbElement2, fastEMABuffer);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        if outBegIdx1 != tempInteger || outBegIdx2 != tempInteger || outNbElement1 != outNbElement2 || outNbElement1 != endIdx - startIdx + 1 + lookbackSignal {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::BadParam;
        }
        // for( i = 0; i < outNbElement1; i += 1 )
        i = 0;
        while i < outNbElement1 {
            *fastEMABuffer.get_unchecked_mut(i) = *fastEMABuffer.get_unchecked(i) - *slowEMABuffer.get_unchecked(i);
            i += 1;
        }
        {
            let _n = ((endIdx - startIdx + 1) * 1) as usize;
            let _di = (0) as usize;
            let _si = (lookbackSignal) as usize;
            outMACD[_di.._di + _n].copy_from_slice(&fastEMABuffer[_si.._si + _n]);
        };
        retCode = self.ema_unguarded(0, outNbElement1 - 1, fastEMABuffer, optInSignalPeriod, outBegIdx2, outNbElement2, outMACDSignal);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        // for( i = 0; i < outNbElement2; i += 1 )
        i = 0;
        while i < outNbElement2 {
            *outMACDHist.get_unchecked_mut(i) = *outMACD.get_unchecked(i) - *outMACDSignal.get_unchecked(i);
            i += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outNbElement2;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
