/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::mavp`].
    ///
    /// # Arguments
    ///
    /// * `optInMinPeriod` - Number of period (default: 2, range: 2..=100000)
    /// * `optInMaxPeriod` - Number of period (default: 30, range: 2..=100000)
    pub fn mavp_lookback(&self, mut optInMinPeriod: i32, mut optInMaxPeriod: i32, mut optInMAType: i32) -> i32 {
        if ((optInMinPeriod) as i32) == (i32::MIN) {
            optInMinPeriod = 2;
        } else if (((optInMinPeriod) as i32) < 2) || (((optInMinPeriod) as i32) > 100000) {
            return -1;
        }
        if ((optInMaxPeriod) as i32) == (i32::MIN) {
            optInMaxPeriod = 30;
        } else if (((optInMaxPeriod) as i32) < 2) || (((optInMaxPeriod) as i32) > 100000) {
            return -1;
        }
        return self.ma_lookback(optInMaxPeriod, optInMAType);
    }
    /// Moving average with variable period
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `inPeriods` - Input price series
    /// * `optInMinPeriod` - Number of period (default: 2, range: 2..=100000)
    /// * `optInMaxPeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn mavp<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        inPeriods: &[T],
        mut optInMinPeriod: i32,
        mut optInMaxPeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInMinPeriod) as i32) == (i32::MIN) {
            optInMinPeriod = 2;
        } else if (((optInMinPeriod) as i32) < 2) || (((optInMinPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInMaxPeriod) as i32) == (i32::MIN) {
            optInMaxPeriod = 30;
        } else if (((optInMaxPeriod) as i32) < 2) || (((optInMaxPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.mavp_unguarded(
            startIdx,
            endIdx,
            inReal,
            inPeriods,
            optInMinPeriod,
            optInMaxPeriod,
            optInMAType,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn mavp_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        inPeriods: &[T],
        mut optInMinPeriod: i32,
        mut optInMaxPeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let localPeriodArray: Vec<i32>;
        let localOutputArray: Vec<T>;
        let localBegIdx: i32;
        let localNbElement: i32;
        let mut retCode: RetCode;
        let localOutputArray: Vec<T>;
        let localPeriodArray: Vec<i32>;
        localOutputArray = vec![T::default(); (outputSize * 1) as usize];
        localPeriodArray = vec![0_i32; (outputSize * 1) as usize];
        lookbackTotal = self.ma_lookback(optInMaxPeriod, optInMAType);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        if lookbackTotal > startIdx {
            tempInt = lookbackTotal;
        } else {
            tempInt = startIdx;
        }
        if tempInt > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outputSize = endIdx - tempInt + 1;
        // for( i = 0; i < outputSize; i += 1 )
        i = 0;
        while i < outputSize {
            tempInt = (inPeriods[startIdx + i]) as i32;
            if tempInt < optInMinPeriod {
                tempInt = optInMinPeriod;
            } else if tempInt > optInMaxPeriod {
                tempInt = optInMaxPeriod;
            }
            localPeriodArray[i] = tempInt;
            i += 1;
        }
        // for( i = 0; i < outputSize; i += 1 )
        i = 0;
        while i < outputSize {
            curPeriod = localPeriodArray[i];
            if curPeriod != 0 {
                retCode = self.ma_unguarded(startIdx, endIdx, inReal, curPeriod, optInMAType, localBegIdx, localNbElement, localOutputArray);
                if retCode != RetCode::Success {
                    (*outBegIdx) = 0;
                    (*outNBElement) = 0;
                    return retCode;
                }
                outReal[i] = localOutputArray[i];
                // for( j = i + 1; j < outputSize; j += 1 )
                j = i + 1;
                while j < outputSize {
                    if localPeriodArray[j] == curPeriod {
                        localPeriodArray[j] = 0;
                        outReal[j] = localOutputArray[j];
                    }
                    j += 1;
                }
            }
            i += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outputSize;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn mavp_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        inPeriods: &[T],
        mut optInMinPeriod: i32,
        mut optInMaxPeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInMinPeriod) as i32) == (i32::MIN) {
            optInMinPeriod = 2;
        } else if (((optInMinPeriod) as i32) < 2) || (((optInMinPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInMaxPeriod) as i32) == (i32::MIN) {
            optInMaxPeriod = 30;
        } else if (((optInMaxPeriod) as i32) < 2) || (((optInMaxPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.mavp_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            inPeriods,
            optInMinPeriod,
            optInMaxPeriod,
            optInMAType,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn mavp_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        inPeriods: &[T],
        mut optInMinPeriod: i32,
        mut optInMaxPeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let localPeriodArray: Vec<i32>;
        let localOutputArray: Vec<T>;
        let localBegIdx: i32;
        let localNbElement: i32;
        let mut retCode: RetCode;
        let localOutputArray: Vec<T>;
        let localPeriodArray: Vec<i32>;
        localOutputArray = vec![T::default(); (outputSize * 1) as usize];
        localPeriodArray = vec![0_i32; (outputSize * 1) as usize];
        lookbackTotal = self.ma_lookback(optInMaxPeriod, optInMAType);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        if lookbackTotal > startIdx {
            tempInt = lookbackTotal;
        } else {
            tempInt = startIdx;
        }
        if tempInt > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outputSize = endIdx - tempInt + 1;
        // for( i = 0; i < outputSize; i += 1 )
        i = 0;
        while i < outputSize {
            tempInt = (*inPeriods.get_unchecked(startIdx + i)) as i32;
            if tempInt < optInMinPeriod {
                tempInt = optInMinPeriod;
            } else if tempInt > optInMaxPeriod {
                tempInt = optInMaxPeriod;
            }
            *localPeriodArray.get_unchecked_mut(i) = tempInt;
            i += 1;
        }
        // for( i = 0; i < outputSize; i += 1 )
        i = 0;
        while i < outputSize {
            curPeriod = *localPeriodArray.get_unchecked(i);
            if curPeriod != 0 {
                retCode = self.ma_unguarded(startIdx, endIdx, inReal, curPeriod, optInMAType, localBegIdx, localNbElement, localOutputArray);
                if retCode != RetCode::Success {
                    (*outBegIdx) = 0;
                    (*outNBElement) = 0;
                    return retCode;
                }
                *outReal.get_unchecked_mut(i) = *localOutputArray.get_unchecked(i);
                // for( j = i + 1; j < outputSize; j += 1 )
                j = i + 1;
                while j < outputSize {
                    if *localPeriodArray.get_unchecked(j) == curPeriod {
                        *localPeriodArray.get_unchecked_mut(j) = 0;
                        *outReal.get_unchecked_mut(j) = *localOutputArray.get_unchecked(j);
                    }
                    j += 1;
                }
            }
            i += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outputSize;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
