/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::minus_dm`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 1..=100000)
    pub fn minus_dm_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        if optInTimePeriod > 1 {
            return optInTimePeriod + self.unstable_period[FuncUnstId::Minus_dm as usize] - 1;
        } else {
            return 1;
        }
    }
    /// Minus Directional Movement
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn minus_dm<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.minus_dm_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn minus_dm_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut prevMinusDM: T;
        let mut i: i32;
        if optInTimePeriod > 1 {
            lookbackTotal = optInTimePeriod + self.unstable_period[FuncUnstId::Minus_dm as usize] - 1;
        } else {
            lookbackTotal = 1;
        }
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod <= 1 {
            (*outBegIdx) = startIdx;
            today = startIdx - 1;
            prevHigh = inHigh[today];
            prevLow = inLow[today];
            while today < endIdx {
                today += 1;
                tempReal = inHigh[today];
                diffP = tempReal - prevHigh;
                prevHigh = tempReal;
                tempReal = inLow[today];
                diffM = prevLow - tempReal;
                prevLow = tempReal;
                if diffM > 0 && diffP < diffM {
                    outReal[{ let _v = outIdx; outIdx += 1; _v }] = diffM;
                } else {
                    outReal[{ let _v = outIdx; outIdx += 1; _v }] = 0;
                }
            }
            (*outNBElement) = outIdx;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        prevMinusDM = T::ta_from_f64(0.0);
        today = startIdx - lookbackTotal;
        prevHigh = inHigh[today];
        prevLow = inLow[today];
        i = optInTimePeriod - 1;
        while { let _v = i; i -= 1; _v } > 0 {
            today += 1;
            tempReal = inHigh[today];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[today];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0 && diffP < diffM {
                prevMinusDM += diffM;
            }
        }
        i = self.unstable_period[FuncUnstId::Minus_dm as usize];
        while { let _v = i; i -= 1; _v } != 0 {
            today += 1;
            tempReal = inHigh[today];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[today];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0 && diffP < diffM {
                prevMinusDM = prevMinusDM - prevMinusDM / optInTimePeriod + diffM;
            } else {
                prevMinusDM = prevMinusDM - prevMinusDM / optInTimePeriod;
            }
        }
        outReal[0] = prevMinusDM;
        outIdx = 1;
        while today < endIdx {
            today += 1;
            tempReal = inHigh[today];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[today];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0 && diffP < diffM {
                prevMinusDM = prevMinusDM - prevMinusDM / optInTimePeriod + diffM;
            } else {
                prevMinusDM = prevMinusDM - prevMinusDM / optInTimePeriod;
            }
            outReal[{ let _v = outIdx; outIdx += 1; _v }] = prevMinusDM;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn minus_dm_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.minus_dm_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn minus_dm_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut prevMinusDM: T;
        let mut i: i32;
        if optInTimePeriod > 1 {
            lookbackTotal = optInTimePeriod + self.unstable_period[FuncUnstId::Minus_dm as usize] - 1;
        } else {
            lookbackTotal = 1;
        }
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod <= 1 {
            (*outBegIdx) = startIdx;
            today = startIdx - 1;
            prevHigh = *inHigh.get_unchecked(today);
            prevLow = *inLow.get_unchecked(today);
            while today < endIdx {
                today += 1;
                tempReal = *inHigh.get_unchecked(today);
                diffP = tempReal - prevHigh;
                prevHigh = tempReal;
                tempReal = *inLow.get_unchecked(today);
                diffM = prevLow - tempReal;
                prevLow = tempReal;
                if diffM > 0 && diffP < diffM {
                    *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = diffM;
                } else {
                    *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 0;
                }
            }
            (*outNBElement) = outIdx;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        prevMinusDM = T::ta_from_f64(0.0);
        today = startIdx - lookbackTotal;
        prevHigh = *inHigh.get_unchecked(today);
        prevLow = *inLow.get_unchecked(today);
        i = optInTimePeriod - 1;
        while { let _v = i; i -= 1; _v } > 0 {
            today += 1;
            tempReal = *inHigh.get_unchecked(today);
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = *inLow.get_unchecked(today);
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0 && diffP < diffM {
                prevMinusDM += diffM;
            }
        }
        i = self.unstable_period[FuncUnstId::Minus_dm as usize];
        while { let _v = i; i -= 1; _v } != 0 {
            today += 1;
            tempReal = *inHigh.get_unchecked(today);
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = *inLow.get_unchecked(today);
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0 && diffP < diffM {
                prevMinusDM = prevMinusDM - prevMinusDM / optInTimePeriod + diffM;
            } else {
                prevMinusDM = prevMinusDM - prevMinusDM / optInTimePeriod;
            }
        }
        *outReal.get_unchecked_mut(0) = prevMinusDM;
        outIdx = 1;
        while today < endIdx {
            today += 1;
            tempReal = *inHigh.get_unchecked(today);
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = *inLow.get_unchecked(today);
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0 && diffP < diffM {
                prevMinusDM = prevMinusDM - prevMinusDM / optInTimePeriod + diffM;
            } else {
                prevMinusDM = prevMinusDM - prevMinusDM / optInTimePeriod;
            }
            *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = prevMinusDM;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
