/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::rsi`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    pub fn rsi_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        let mut retValue: i32;
        retValue = optInTimePeriod + self.unstable_period[FuncUnstId::Rsi as usize];
        if self.compatibility == Compatibility::Metastock {
            retValue = retValue - 1;
        }
        return retValue;
    }
    /// Relative Strength Index
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn rsi<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.rsi_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn rsi_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut outIdx: usize;
        let mut today: usize;
        let lookbackTotal: usize;
        let unstablePeriod: i32;
        let i: i32;
        let mut prevGain: T;
        let mut prevLoss: T;
        let mut prevValue: T;
        let savePrevValue: T;
        let mut tempValue1: T;
        let mut tempValue2: T;
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = (self.rsi_lookback(optInTimePeriod)) as i32;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod == 1 {
            (*outBegIdx) = startIdx;
            i = (endIdx - startIdx + 1) as i32;
            (*outNBElement) = (i) as usize;
            {
            let _n = (i * 1) as usize;
            let _di = (0) as usize;
            let _si = (startIdx) as usize;
            outReal[_di.._di + _n].copy_from_slice(&inReal[_si.._si + _n]);
        };
            return RetCode::Success;
        }
        today = startIdx - lookbackTotal;
        prevValue = T::ta_from_f64((inReal[today]).ta_to_f64());
        unstablePeriod = self.unstable_period[FuncUnstId::Rsi as usize];
        if unstablePeriod == 0 && self.compatibility == Compatibility::Metastock {
            savePrevValue = prevValue;
            prevGain = T::ta_from_f64(0.0);
            prevLoss = T::ta_from_f64(0.0);
            // for( i = optInTimePeriod; i > 0; i -= 1 )
            i = optInTimePeriod;
            while i > 0 {
                tempValue1 = T::ta_from_f64((inReal[today]).ta_to_f64());
                today = today + 1;
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                if tempValue2 < T::ta_from_f64(0.0) {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
                i -= 1;
            }
            tempValue1 = prevLoss / (T::ta_from_f64((optInTimePeriod).ta_to_f64()));
            tempValue2 = prevGain / (T::ta_from_f64((optInTimePeriod).ta_to_f64()));
            tempValue1 = tempValue2 + tempValue1;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue1 && tempValue1 < T::ta_from_f64(0.00000001)) {
                outReal[outIdx] = T::ta_from_f64(100.0) * (tempValue2 / tempValue1);
                outIdx = outIdx + 1;
            } else {
                outReal[outIdx] = T::ta_from_f64(0.0);
                outIdx = outIdx + 1;
            }
            if today > endIdx {
                (*outBegIdx) = startIdx;
                (*outNBElement) = outIdx;
                return RetCode::Success;
            }
            today = today - ((optInTimePeriod) as usize);
            prevValue = savePrevValue;
        }
        prevGain = T::ta_from_f64(0.0);
        prevLoss = T::ta_from_f64(0.0);
        today = today + 1;
        // for( i = optInTimePeriod; i > 0; i -= 1 )
        i = optInTimePeriod;
        while i > 0 {
            tempValue1 = T::ta_from_f64((inReal[today]).ta_to_f64());
            today = today + 1;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            if tempValue2 < T::ta_from_f64(0.0) {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
            i -= 1;
        }
        prevLoss /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
        prevGain /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
        if today > startIdx {
            tempValue1 = prevGain + prevLoss;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue1 && tempValue1 < T::ta_from_f64(0.00000001)) {
                outReal[outIdx] = T::ta_from_f64(100.0) * (prevGain / tempValue1);
                outIdx = outIdx + 1;
            } else {
                outReal[outIdx] = T::ta_from_f64(0.0);
                outIdx = outIdx + 1;
            }
        } else {
            while today < startIdx {
                tempValue1 = T::ta_from_f64((inReal[today]).ta_to_f64());
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                prevLoss *= T::ta_from_f64((optInTimePeriod - 1).ta_to_f64());
                prevGain *= T::ta_from_f64((optInTimePeriod - 1).ta_to_f64());
                if tempValue2 < T::ta_from_f64(0.0) {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
                prevLoss /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
                prevGain /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
                today = today + 1;
            }
        }
        while today <= endIdx {
            tempValue1 = T::ta_from_f64((inReal[today]).ta_to_f64());
            today = today + 1;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            prevLoss *= T::ta_from_f64((optInTimePeriod - 1).ta_to_f64());
            prevGain *= T::ta_from_f64((optInTimePeriod - 1).ta_to_f64());
            if tempValue2 < T::ta_from_f64(0.0) {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
            prevLoss /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
            prevGain /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
            tempValue1 = prevGain + prevLoss;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue1 && tempValue1 < T::ta_from_f64(0.00000001)) {
                outReal[outIdx] = T::ta_from_f64(100.0) * (prevGain / tempValue1);
                outIdx = outIdx + 1;
            } else {
                outReal[outIdx] = T::ta_from_f64(0.0);
                outIdx = outIdx + 1;
            }
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn rsi_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.rsi_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn rsi_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut outIdx: usize;
        let mut today: usize;
        let lookbackTotal: usize;
        let unstablePeriod: i32;
        let i: i32;
        let mut prevGain: T;
        let mut prevLoss: T;
        let mut prevValue: T;
        let savePrevValue: T;
        let mut tempValue1: T;
        let mut tempValue2: T;
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = (self.rsi_lookback(optInTimePeriod)) as i32;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod == 1 {
            (*outBegIdx) = startIdx;
            i = (endIdx - startIdx + 1) as i32;
            (*outNBElement) = (i) as usize;
            {
            let _n = (i * 1) as usize;
            let _di = (0) as usize;
            let _si = (startIdx) as usize;
            outReal[_di.._di + _n].copy_from_slice(&inReal[_si.._si + _n]);
        };
            return RetCode::Success;
        }
        today = startIdx - lookbackTotal;
        prevValue = T::ta_from_f64((*inReal.get_unchecked(today)).ta_to_f64());
        unstablePeriod = self.unstable_period[FuncUnstId::Rsi as usize];
        if unstablePeriod == 0 && self.compatibility == Compatibility::Metastock {
            savePrevValue = prevValue;
            prevGain = T::ta_from_f64(0.0);
            prevLoss = T::ta_from_f64(0.0);
            // for( i = optInTimePeriod; i > 0; i -= 1 )
            i = optInTimePeriod;
            while i > 0 {
                tempValue1 = T::ta_from_f64((*inReal.get_unchecked(today)).ta_to_f64());
                today = today + 1;
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                if tempValue2 < T::ta_from_f64(0.0) {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
                i -= 1;
            }
            tempValue1 = prevLoss / (T::ta_from_f64((optInTimePeriod).ta_to_f64()));
            tempValue2 = prevGain / (T::ta_from_f64((optInTimePeriod).ta_to_f64()));
            tempValue1 = tempValue2 + tempValue1;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue1 && tempValue1 < T::ta_from_f64(0.00000001)) {
                *outReal.get_unchecked_mut(outIdx) = T::ta_from_f64(100.0) * (tempValue2 / tempValue1);
                outIdx = outIdx + 1;
            } else {
                *outReal.get_unchecked_mut(outIdx) = T::ta_from_f64(0.0);
                outIdx = outIdx + 1;
            }
            if today > endIdx {
                (*outBegIdx) = startIdx;
                (*outNBElement) = outIdx;
                return RetCode::Success;
            }
            today = today - ((optInTimePeriod) as usize);
            prevValue = savePrevValue;
        }
        prevGain = T::ta_from_f64(0.0);
        prevLoss = T::ta_from_f64(0.0);
        today = today + 1;
        // for( i = optInTimePeriod; i > 0; i -= 1 )
        i = optInTimePeriod;
        while i > 0 {
            tempValue1 = T::ta_from_f64((*inReal.get_unchecked(today)).ta_to_f64());
            today = today + 1;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            if tempValue2 < T::ta_from_f64(0.0) {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
            i -= 1;
        }
        prevLoss /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
        prevGain /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
        if today > startIdx {
            tempValue1 = prevGain + prevLoss;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue1 && tempValue1 < T::ta_from_f64(0.00000001)) {
                *outReal.get_unchecked_mut(outIdx) = T::ta_from_f64(100.0) * (prevGain / tempValue1);
                outIdx = outIdx + 1;
            } else {
                *outReal.get_unchecked_mut(outIdx) = T::ta_from_f64(0.0);
                outIdx = outIdx + 1;
            }
        } else {
            while today < startIdx {
                tempValue1 = T::ta_from_f64((*inReal.get_unchecked(today)).ta_to_f64());
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                prevLoss *= T::ta_from_f64((optInTimePeriod - 1).ta_to_f64());
                prevGain *= T::ta_from_f64((optInTimePeriod - 1).ta_to_f64());
                if tempValue2 < T::ta_from_f64(0.0) {
                    prevLoss -= tempValue2;
                } else {
                    prevGain += tempValue2;
                }
                prevLoss /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
                prevGain /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
                today = today + 1;
            }
        }
        while today <= endIdx {
            tempValue1 = T::ta_from_f64((*inReal.get_unchecked(today)).ta_to_f64());
            today = today + 1;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            prevLoss *= T::ta_from_f64((optInTimePeriod - 1).ta_to_f64());
            prevGain *= T::ta_from_f64((optInTimePeriod - 1).ta_to_f64());
            if tempValue2 < T::ta_from_f64(0.0) {
                prevLoss -= tempValue2;
            } else {
                prevGain += tempValue2;
            }
            prevLoss /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
            prevGain /= T::ta_from_f64((optInTimePeriod).ta_to_f64());
            tempValue1 = prevGain + prevLoss;
            if !(0 - T::ta_from_f64(0.00000001) < tempValue1 && tempValue1 < T::ta_from_f64(0.00000001)) {
                *outReal.get_unchecked_mut(outIdx) = T::ta_from_f64(100.0) * (prevGain / tempValue1);
                outIdx = outIdx + 1;
            } else {
                *outReal.get_unchecked_mut(outIdx) = T::ta_from_f64(0.0);
                outIdx = outIdx + 1;
            }
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
