/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::sarext`].
    ///
    /// # Arguments
    ///
    /// * `optInStartValue` - Number of period (default: 0, range: -2147483648..=2147483647)
    /// * `optInOffsetOnReverse` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationInitLong` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationLong` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationMaxLong` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationInitShort` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationShort` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationMaxShort` - Number of period (default: 0, range: 0..=2147483647)
    pub fn sarext_lookback(&self, mut optInStartValue: f64, mut optInOffsetOnReverse: f64, mut optInAccelerationInitLong: f64, mut optInAccelerationLong: f64, mut optInAccelerationMaxLong: f64, mut optInAccelerationInitShort: f64, mut optInAccelerationShort: f64, mut optInAccelerationMaxShort: f64) -> i32 {
        return 1;
    }
    /// Parabolic SAR - Extended
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `optInStartValue` - Number of period (default: 0, range: -2147483648..=2147483647)
    /// * `optInOffsetOnReverse` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationInitLong` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationLong` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationMaxLong` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationInitShort` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationShort` - Number of period (default: 0, range: 0..=2147483647)
    /// * `optInAccelerationMaxShort` - Number of period (default: 0, range: 0..=2147483647)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn sarext<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInStartValue: f64,
        mut optInOffsetOnReverse: f64,
        mut optInAccelerationInitLong: f64,
        mut optInAccelerationLong: f64,
        mut optInAccelerationMaxLong: f64,
        mut optInAccelerationInitShort: f64,
        mut optInAccelerationShort: f64,
        mut optInAccelerationMaxShort: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.sarext_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            optInStartValue,
            optInOffsetOnReverse,
            optInAccelerationInitLong,
            optInAccelerationLong,
            optInAccelerationMaxLong,
            optInAccelerationInitShort,
            optInAccelerationShort,
            optInAccelerationMaxShort,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn sarext_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInStartValue: f64,
        mut optInOffsetOnReverse: f64,
        mut optInAccelerationInitLong: f64,
        mut optInAccelerationLong: f64,
        mut optInAccelerationMaxLong: f64,
        mut optInAccelerationInitShort: f64,
        mut optInAccelerationShort: f64,
        mut optInAccelerationMaxShort: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let retCode: RetCode;
        let mut isLong: i32;
        let tempInt: i32;
        let mut ep_temp: [T; 1 as usize] = [T::zero(); 1 as usize];
        if startIdx < 1 {
            startIdx = 1;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        afLong = T::ta_from_f64(optInAccelerationInitLong);
        afShort = T::ta_from_f64(optInAccelerationInitShort);
        if afLong > T::ta_from_f64(optInAccelerationMaxLong) {
            optInAccelerationInitLong = T::ta_from_f64(optInAccelerationMaxLong);
            afLong = T::ta_from_f64(optInAccelerationInitLong);
        }
        if T::ta_from_f64(optInAccelerationLong) > T::ta_from_f64(optInAccelerationMaxLong) {
            optInAccelerationLong = T::ta_from_f64(optInAccelerationMaxLong);
        }
        if afShort > T::ta_from_f64(optInAccelerationMaxShort) {
            optInAccelerationInitShort = T::ta_from_f64(optInAccelerationMaxShort);
            afShort = T::ta_from_f64(optInAccelerationInitShort);
        }
        if T::ta_from_f64(optInAccelerationShort) > T::ta_from_f64(optInAccelerationMaxShort) {
            optInAccelerationShort = T::ta_from_f64(optInAccelerationMaxShort);
        }
        if T::ta_from_f64(optInStartValue) == 0 {
            retCode = self.minus_dm_unguarded(startIdx, startIdx, inHigh, inLow, 1, tempInt, tempInt, ep_temp);
            if ep_temp[0] > 0 {
                isLong = 0;
            } else {
                isLong = 1;
            }
            if retCode != RetCode::Success {
                (*outBegIdx) = 0;
                (*outNBElement) = 0;
                return retCode;
            }
        } else if T::ta_from_f64(optInStartValue) > 0 {
            isLong = 1;
        } else {
            isLong = 0;
        }
        (*outBegIdx) = startIdx;
        outIdx = 0;
        todayIdx = startIdx;
        newHigh = inHigh[todayIdx - 1];
        newLow = inLow[todayIdx - 1];
        if T::ta_from_f64(optInStartValue) == 0 {
            if isLong == 1 {
                ep = inHigh[todayIdx];
                sar = newLow;
            } else {
                ep = inLow[todayIdx];
                sar = newHigh;
            }
        } else if T::ta_from_f64(optInStartValue) > 0 {
            ep = inHigh[todayIdx];
            sar = T::ta_from_f64(optInStartValue);
        } else {
            ep = inLow[todayIdx];
            sar = T::ta_from_f64(optInStartValue).ta_abs();
        }
        newLow = inLow[todayIdx];
        newHigh = inHigh[todayIdx];
        while todayIdx <= endIdx {
            prevLow = newLow;
            prevHigh = newHigh;
            newLow = inLow[todayIdx];
            newHigh = inHigh[todayIdx];
            todayIdx += 1;
            if isLong == 1 {
                if newLow <= sar {
                    isLong = 0;
                    sar = ep;
                    if sar < prevHigh {
                        sar = prevHigh;
                    }
                    if sar < newHigh {
                        sar = newHigh;
                    }
                    if T::ta_from_f64(optInOffsetOnReverse) != T::ta_from_f64(0.0) {
                        sar += sar * T::ta_from_f64(optInOffsetOnReverse);
                    }
                    outReal[{ let _v = outIdx; outIdx += 1; _v }] = 0 - sar;
                    afShort = T::ta_from_f64(optInAccelerationInitShort);
                    ep = newLow;
                    sar = sar + afShort * (ep - sar);
                    if sar < prevHigh {
                        sar = prevHigh;
                    }
                    if sar < newHigh {
                        sar = newHigh;
                    }
                } else {
                    outReal[{ let _v = outIdx; outIdx += 1; _v }] = sar;
                    if newHigh > ep {
                        ep = newHigh;
                        afLong += T::ta_from_f64(optInAccelerationLong);
                        if afLong > T::ta_from_f64(optInAccelerationMaxLong) {
                            afLong = T::ta_from_f64(optInAccelerationMaxLong);
                        }
                    }
                    sar = sar + afLong * (ep - sar);
                    if sar > prevLow {
                        sar = prevLow;
                    }
                    if sar > newLow {
                        sar = newLow;
                    }
                }
            } else if newHigh >= sar {
                isLong = 1;
                sar = ep;
                if sar > prevLow {
                    sar = prevLow;
                }
                if sar > newLow {
                    sar = newLow;
                }
                if T::ta_from_f64(optInOffsetOnReverse) != T::ta_from_f64(0.0) {
                    sar -= sar * T::ta_from_f64(optInOffsetOnReverse);
                }
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = sar;
                afLong = T::ta_from_f64(optInAccelerationInitLong);
                ep = newHigh;
                sar = sar + afLong * (ep - sar);
                if sar > prevLow {
                    sar = prevLow;
                }
                if sar > newLow {
                    sar = newLow;
                }
            } else {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = 0 - sar;
                if newLow < ep {
                    ep = newLow;
                    afShort += T::ta_from_f64(optInAccelerationShort);
                    if afShort > T::ta_from_f64(optInAccelerationMaxShort) {
                        afShort = T::ta_from_f64(optInAccelerationMaxShort);
                    }
                }
                sar = sar + afShort * (ep - sar);
                if sar < prevHigh {
                    sar = prevHigh;
                }
                if sar < newHigh {
                    sar = newHigh;
                }
            }
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn sarext_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInStartValue: f64,
        mut optInOffsetOnReverse: f64,
        mut optInAccelerationInitLong: f64,
        mut optInAccelerationLong: f64,
        mut optInAccelerationMaxLong: f64,
        mut optInAccelerationInitShort: f64,
        mut optInAccelerationShort: f64,
        mut optInAccelerationMaxShort: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.sarext_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            optInStartValue,
            optInOffsetOnReverse,
            optInAccelerationInitLong,
            optInAccelerationLong,
            optInAccelerationMaxLong,
            optInAccelerationInitShort,
            optInAccelerationShort,
            optInAccelerationMaxShort,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn sarext_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInStartValue: f64,
        mut optInOffsetOnReverse: f64,
        mut optInAccelerationInitLong: f64,
        mut optInAccelerationLong: f64,
        mut optInAccelerationMaxLong: f64,
        mut optInAccelerationInitShort: f64,
        mut optInAccelerationShort: f64,
        mut optInAccelerationMaxShort: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let retCode: RetCode;
        let mut isLong: i32;
        let tempInt: i32;
        let mut ep_temp: [T; 1 as usize] = [T::zero(); 1 as usize];
        if startIdx < 1 {
            startIdx = 1;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        afLong = T::ta_from_f64(optInAccelerationInitLong);
        afShort = T::ta_from_f64(optInAccelerationInitShort);
        if afLong > T::ta_from_f64(optInAccelerationMaxLong) {
            optInAccelerationInitLong = T::ta_from_f64(optInAccelerationMaxLong);
            afLong = T::ta_from_f64(optInAccelerationInitLong);
        }
        if T::ta_from_f64(optInAccelerationLong) > T::ta_from_f64(optInAccelerationMaxLong) {
            optInAccelerationLong = T::ta_from_f64(optInAccelerationMaxLong);
        }
        if afShort > T::ta_from_f64(optInAccelerationMaxShort) {
            optInAccelerationInitShort = T::ta_from_f64(optInAccelerationMaxShort);
            afShort = T::ta_from_f64(optInAccelerationInitShort);
        }
        if T::ta_from_f64(optInAccelerationShort) > T::ta_from_f64(optInAccelerationMaxShort) {
            optInAccelerationShort = T::ta_from_f64(optInAccelerationMaxShort);
        }
        if T::ta_from_f64(optInStartValue) == 0 {
            retCode = self.minus_dm_unguarded(startIdx, startIdx, inHigh, inLow, 1, tempInt, tempInt, ep_temp);
            if *ep_temp.get_unchecked(0) > 0 {
                isLong = 0;
            } else {
                isLong = 1;
            }
            if retCode != RetCode::Success {
                (*outBegIdx) = 0;
                (*outNBElement) = 0;
                return retCode;
            }
        } else if T::ta_from_f64(optInStartValue) > 0 {
            isLong = 1;
        } else {
            isLong = 0;
        }
        (*outBegIdx) = startIdx;
        outIdx = 0;
        todayIdx = startIdx;
        newHigh = *inHigh.get_unchecked(todayIdx - 1);
        newLow = *inLow.get_unchecked(todayIdx - 1);
        if T::ta_from_f64(optInStartValue) == 0 {
            if isLong == 1 {
                ep = *inHigh.get_unchecked(todayIdx);
                sar = newLow;
            } else {
                ep = *inLow.get_unchecked(todayIdx);
                sar = newHigh;
            }
        } else if T::ta_from_f64(optInStartValue) > 0 {
            ep = *inHigh.get_unchecked(todayIdx);
            sar = T::ta_from_f64(optInStartValue);
        } else {
            ep = *inLow.get_unchecked(todayIdx);
            sar = T::ta_from_f64(optInStartValue).ta_abs();
        }
        newLow = *inLow.get_unchecked(todayIdx);
        newHigh = *inHigh.get_unchecked(todayIdx);
        while todayIdx <= endIdx {
            prevLow = newLow;
            prevHigh = newHigh;
            newLow = *inLow.get_unchecked(todayIdx);
            newHigh = *inHigh.get_unchecked(todayIdx);
            todayIdx += 1;
            if isLong == 1 {
                if newLow <= sar {
                    isLong = 0;
                    sar = ep;
                    if sar < prevHigh {
                        sar = prevHigh;
                    }
                    if sar < newHigh {
                        sar = newHigh;
                    }
                    if T::ta_from_f64(optInOffsetOnReverse) != T::ta_from_f64(0.0) {
                        sar += sar * T::ta_from_f64(optInOffsetOnReverse);
                    }
                    *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 0 - sar;
                    afShort = T::ta_from_f64(optInAccelerationInitShort);
                    ep = newLow;
                    sar = sar + afShort * (ep - sar);
                    if sar < prevHigh {
                        sar = prevHigh;
                    }
                    if sar < newHigh {
                        sar = newHigh;
                    }
                } else {
                    *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = sar;
                    if newHigh > ep {
                        ep = newHigh;
                        afLong += T::ta_from_f64(optInAccelerationLong);
                        if afLong > T::ta_from_f64(optInAccelerationMaxLong) {
                            afLong = T::ta_from_f64(optInAccelerationMaxLong);
                        }
                    }
                    sar = sar + afLong * (ep - sar);
                    if sar > prevLow {
                        sar = prevLow;
                    }
                    if sar > newLow {
                        sar = newLow;
                    }
                }
            } else if newHigh >= sar {
                isLong = 1;
                sar = ep;
                if sar > prevLow {
                    sar = prevLow;
                }
                if sar > newLow {
                    sar = newLow;
                }
                if T::ta_from_f64(optInOffsetOnReverse) != T::ta_from_f64(0.0) {
                    sar -= sar * T::ta_from_f64(optInOffsetOnReverse);
                }
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = sar;
                afLong = T::ta_from_f64(optInAccelerationInitLong);
                ep = newHigh;
                sar = sar + afLong * (ep - sar);
                if sar > prevLow {
                    sar = prevLow;
                }
                if sar > newLow {
                    sar = newLow;
                }
            } else {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = 0 - sar;
                if newLow < ep {
                    ep = newLow;
                    afShort += T::ta_from_f64(optInAccelerationShort);
                    if afShort > T::ta_from_f64(optInAccelerationMaxShort) {
                        afShort = T::ta_from_f64(optInAccelerationMaxShort);
                    }
                }
                sar = sar + afShort * (ep - sar);
                if sar < prevHigh {
                    sar = prevHigh;
                }
                if sar < newHigh {
                    sar = newHigh;
                }
            }
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
