/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::sma`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    pub fn sma_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        return optInTimePeriod - 1;
    }
    /// Simple Moving Average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn sma<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.sma_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn sma_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut periodTotal: T;
        let mut tempReal: T;
        let mut i: usize;
        let mut outIdx: usize;
        let mut trailingIdx: usize;
        let lookbackTotal: usize;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        periodTotal = T::ta_from_f64(0.0);
        trailingIdx = startIdx - lookbackTotal;
        i = trailingIdx;
        if optInTimePeriod > 1 {
            while i < startIdx {
                periodTotal += T::ta_from_f64((inReal[i]).ta_to_f64());
                i = i + 1;
            }
        }
        outIdx = 0;
        while i <= endIdx {
            periodTotal += T::ta_from_f64((inReal[i]).ta_to_f64());
            i = i + 1;
            tempReal = periodTotal;
            periodTotal -= T::ta_from_f64((inReal[trailingIdx]).ta_to_f64());
            trailingIdx = trailingIdx + 1;
            outReal[outIdx] = tempReal / (T::ta_from_f64((optInTimePeriod).ta_to_f64()));
            outIdx = outIdx + 1;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn sma_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.sma_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn sma_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut periodTotal: T;
        let mut tempReal: T;
        let mut i: usize;
        let mut outIdx: usize;
        let mut trailingIdx: usize;
        let lookbackTotal: usize;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        periodTotal = T::ta_from_f64(0.0);
        trailingIdx = startIdx - lookbackTotal;
        i = trailingIdx;
        if optInTimePeriod > 1 {
            while i < startIdx {
                periodTotal += T::ta_from_f64((*inReal.get_unchecked(i)).ta_to_f64());
                i = i + 1;
            }
        }
        outIdx = 0;
        while i <= endIdx {
            periodTotal += T::ta_from_f64((*inReal.get_unchecked(i)).ta_to_f64());
            i = i + 1;
            tempReal = periodTotal;
            periodTotal -= T::ta_from_f64((*inReal.get_unchecked(trailingIdx)).ta_to_f64());
            trailingIdx = trailingIdx + 1;
            *outReal.get_unchecked_mut(outIdx) = tempReal / (T::ta_from_f64((optInTimePeriod).ta_to_f64()));
            outIdx = outIdx + 1;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
