/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::stoch`].
    ///
    /// # Arguments
    ///
    /// * `optInFastK_Period` - Number of period (default: 5, range: 1..=100000)
    /// * `optInSlowK_Period` - Number of period (default: 3, range: 1..=100000)
    /// * `optInSlowD_Period` - Number of period (default: 3, range: 1..=100000)
    pub fn stoch_lookback(&self, mut optInFastK_Period: i32, mut optInSlowK_Period: i32, mut optInSlowK_MAType: i32, mut optInSlowD_Period: i32, mut optInSlowD_MAType: i32) -> i32 {
        if ((optInFastK_Period) as i32) == (i32::MIN) {
            optInFastK_Period = 5;
        } else if (((optInFastK_Period) as i32) < 1) || (((optInFastK_Period) as i32) > 100000) {
            return -1;
        }
        if ((optInSlowK_Period) as i32) == (i32::MIN) {
            optInSlowK_Period = 3;
        } else if (((optInSlowK_Period) as i32) < 1) || (((optInSlowK_Period) as i32) > 100000) {
            return -1;
        }
        if ((optInSlowD_Period) as i32) == (i32::MIN) {
            optInSlowD_Period = 3;
        } else if (((optInSlowD_Period) as i32) < 1) || (((optInSlowD_Period) as i32) > 100000) {
            return -1;
        }
        let mut retValue: i32;
        retValue = optInFastK_Period - 1;
        retValue += self.ma_lookback(optInSlowK_Period, optInSlowK_MAType);
        retValue += self.ma_lookback(optInSlowD_Period, optInSlowD_MAType);
        return retValue;
    }
    /// Stochastic
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInFastK_Period` - Number of period (default: 5, range: 1..=100000)
    /// * `optInSlowK_Period` - Number of period (default: 3, range: 1..=100000)
    /// * `optInSlowD_Period` - Number of period (default: 3, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outSlowK` - Output values
    /// * `outSlowD` - Output values
    pub fn stoch<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInFastK_Period: i32,
        mut optInSlowK_Period: i32,
        mut optInSlowK_MAType: i32,
        mut optInSlowD_Period: i32,
        mut optInSlowD_MAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outSlowK: &mut [T],
        outSlowD: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInFastK_Period) as i32) == (i32::MIN) {
            optInFastK_Period = 5;
        } else if (((optInFastK_Period) as i32) < 1) || (((optInFastK_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowK_Period) as i32) == (i32::MIN) {
            optInSlowK_Period = 3;
        } else if (((optInSlowK_Period) as i32) < 1) || (((optInSlowK_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowD_Period) as i32) == (i32::MIN) {
            optInSlowD_Period = 3;
        } else if (((optInSlowD_Period) as i32) < 1) || (((optInSlowD_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.stoch_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInFastK_Period,
            optInSlowK_Period,
            optInSlowK_MAType,
            optInSlowD_Period,
            optInSlowD_MAType,
            outBegIdx,
            outNBElement,
            outSlowK,
            outSlowD,
        );
    }
    pub fn stoch_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInFastK_Period: i32,
        mut optInSlowK_Period: i32,
        mut optInSlowK_MAType: i32,
        mut optInSlowD_Period: i32,
        mut optInSlowD_MAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outSlowK: &mut [T],
        outSlowD: &mut [T],
    ) -> RetCode {
        let mut retCode: RetCode;
        let mut tempBuffer: Vec<T>;
        let mut bufferIsAllocated: i32;
        lookbackK = optInFastK_Period - 1;
        lookbackKSlow = self.ma_lookback(optInSlowK_Period, optInSlowK_MAType);
        lookbackDSlow = self.ma_lookback(optInSlowD_Period, optInSlowD_MAType);
        lookbackTotal = lookbackK + lookbackDSlow + lookbackKSlow;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        trailingIdx = startIdx - lookbackTotal;
        today = trailingIdx + lookbackK;
        highestIdx = 0 - 1;
        lowestIdx = highestIdx;
        lowest = T::ta_from_f64(0.0);
        highest = lowest;
        diff = highest;
        bufferIsAllocated = 0;
        if outSlowK == inHigh || outSlowK == inLow || outSlowK == inClose {
            tempBuffer = outSlowK;
        } else if outSlowD == inHigh || outSlowD == inLow || outSlowD == inClose {
            tempBuffer = outSlowD;
        } else {
            bufferIsAllocated = 1;
            tempBuffer = vec![T::default(); ((endIdx - today + 1) * 1) as usize];
        }
        while today <= endIdx {
            tmp = inLow[today];
            if lowestIdx < trailingIdx {
                lowestIdx = trailingIdx;
                lowest = inLow[lowestIdx];
                i = lowestIdx;
                while { i += 1; i } <= today {
                    tmp = inLow[i];
                    if tmp < lowest {
                        lowestIdx = i;
                        lowest = tmp;
                    }
                }
                diff = (highest - lowest) / T::ta_from_f64(100.0);
            } else if tmp <= lowest {
                lowestIdx = today;
                lowest = tmp;
                diff = (highest - lowest) / T::ta_from_f64(100.0);
            }
            tmp = inHigh[today];
            if highestIdx < trailingIdx {
                highestIdx = trailingIdx;
                highest = inHigh[highestIdx];
                i = highestIdx;
                while { i += 1; i } <= today {
                    tmp = inHigh[i];
                    if tmp > highest {
                        highestIdx = i;
                        highest = tmp;
                    }
                }
                diff = (highest - lowest) / T::ta_from_f64(100.0);
            } else if tmp >= highest {
                highestIdx = today;
                highest = tmp;
                diff = (highest - lowest) / T::ta_from_f64(100.0);
            }
            if diff != T::ta_from_f64(0.0) {
                tempBuffer[{ let _v = outIdx; outIdx += 1; _v }] = (inClose[today] - lowest) / diff;
            } else {
                tempBuffer[{ let _v = outIdx; outIdx += 1; _v }] = T::ta_from_f64(0.0);
            }
            trailingIdx += 1;
            today += 1;
        }
        retCode = self.ma_unguarded(0, outIdx - 1, tempBuffer, optInSlowK_Period, optInSlowK_MAType, outBegIdx, outNBElement, tempBuffer);
        if retCode != RetCode::Success || (((*outNBElement)) as i32) == 0 {
            if bufferIsAllocated {
            }
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.ma_unguarded(0, (((*outNBElement)) as i32) - 1, tempBuffer, optInSlowD_Period, optInSlowD_MAType, outBegIdx, outNBElement, outSlowD);
        {
            let _n = ((((*outNBElement)) as i32) * 1) as usize;
            let _di = (0) as usize;
            let _si = (lookbackDSlow) as usize;
            outSlowK[_di.._di + _n].copy_from_slice(&tempBuffer[_si.._si + _n]);
        };
        if bufferIsAllocated {
        }
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn stoch_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInFastK_Period: i32,
        mut optInSlowK_Period: i32,
        mut optInSlowK_MAType: i32,
        mut optInSlowD_Period: i32,
        mut optInSlowD_MAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outSlowK: &mut [T],
        outSlowD: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInFastK_Period) as i32) == (i32::MIN) {
            optInFastK_Period = 5;
        } else if (((optInFastK_Period) as i32) < 1) || (((optInFastK_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowK_Period) as i32) == (i32::MIN) {
            optInSlowK_Period = 3;
        } else if (((optInSlowK_Period) as i32) < 1) || (((optInSlowK_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowD_Period) as i32) == (i32::MIN) {
            optInSlowD_Period = 3;
        } else if (((optInSlowD_Period) as i32) < 1) || (((optInSlowD_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.stoch_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInFastK_Period,
            optInSlowK_Period,
            optInSlowK_MAType,
            optInSlowD_Period,
            optInSlowD_MAType,
            outBegIdx,
            outNBElement,
            outSlowK,
            outSlowD,
        );
    }
    pub unsafe fn stoch_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInFastK_Period: i32,
        mut optInSlowK_Period: i32,
        mut optInSlowK_MAType: i32,
        mut optInSlowD_Period: i32,
        mut optInSlowD_MAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outSlowK: &mut [T],
        outSlowD: &mut [T],
    ) -> RetCode {
        let mut retCode: RetCode;
        let mut tempBuffer: Vec<T>;
        let mut bufferIsAllocated: i32;
        lookbackK = optInFastK_Period - 1;
        lookbackKSlow = self.ma_lookback(optInSlowK_Period, optInSlowK_MAType);
        lookbackDSlow = self.ma_lookback(optInSlowD_Period, optInSlowD_MAType);
        lookbackTotal = lookbackK + lookbackDSlow + lookbackKSlow;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        trailingIdx = startIdx - lookbackTotal;
        today = trailingIdx + lookbackK;
        highestIdx = 0 - 1;
        lowestIdx = highestIdx;
        lowest = T::ta_from_f64(0.0);
        highest = lowest;
        diff = highest;
        bufferIsAllocated = 0;
        if outSlowK == inHigh || outSlowK == inLow || outSlowK == inClose {
            tempBuffer = outSlowK;
        } else if outSlowD == inHigh || outSlowD == inLow || outSlowD == inClose {
            tempBuffer = outSlowD;
        } else {
            bufferIsAllocated = 1;
            tempBuffer = vec![T::default(); ((endIdx - today + 1) * 1) as usize];
        }
        while today <= endIdx {
            tmp = *inLow.get_unchecked(today);
            if lowestIdx < trailingIdx {
                lowestIdx = trailingIdx;
                lowest = *inLow.get_unchecked(lowestIdx);
                i = lowestIdx;
                while { i += 1; i } <= today {
                    tmp = *inLow.get_unchecked(i);
                    if tmp < lowest {
                        lowestIdx = i;
                        lowest = tmp;
                    }
                }
                diff = (highest - lowest) / T::ta_from_f64(100.0);
            } else if tmp <= lowest {
                lowestIdx = today;
                lowest = tmp;
                diff = (highest - lowest) / T::ta_from_f64(100.0);
            }
            tmp = *inHigh.get_unchecked(today);
            if highestIdx < trailingIdx {
                highestIdx = trailingIdx;
                highest = *inHigh.get_unchecked(highestIdx);
                i = highestIdx;
                while { i += 1; i } <= today {
                    tmp = *inHigh.get_unchecked(i);
                    if tmp > highest {
                        highestIdx = i;
                        highest = tmp;
                    }
                }
                diff = (highest - lowest) / T::ta_from_f64(100.0);
            } else if tmp >= highest {
                highestIdx = today;
                highest = tmp;
                diff = (highest - lowest) / T::ta_from_f64(100.0);
            }
            if diff != T::ta_from_f64(0.0) {
                *tempBuffer.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = (*inClose.get_unchecked(today) - lowest) / diff;
            } else {
                *tempBuffer.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = T::ta_from_f64(0.0);
            }
            trailingIdx += 1;
            today += 1;
        }
        retCode = self.ma_unguarded(0, outIdx - 1, tempBuffer, optInSlowK_Period, optInSlowK_MAType, outBegIdx, outNBElement, tempBuffer);
        if retCode != RetCode::Success || (((*outNBElement)) as i32) == 0 {
            if bufferIsAllocated {
            }
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.ma_unguarded(0, (((*outNBElement)) as i32) - 1, tempBuffer, optInSlowD_Period, optInSlowD_MAType, outBegIdx, outNBElement, outSlowD);
        {
            let _n = ((((*outNBElement)) as i32) * 1) as usize;
            let _di = (0) as usize;
            let _si = (lookbackDSlow) as usize;
            outSlowK[_di.._di + _n].copy_from_slice(&tempBuffer[_si.._si + _n]);
        };
        if bufferIsAllocated {
        }
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
