/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::ultosc`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod1` - Number of period (default: 7, range: 1..=100000)
    /// * `optInTimePeriod2` - Number of period (default: 14, range: 1..=100000)
    /// * `optInTimePeriod3` - Number of period (default: 28, range: 1..=100000)
    pub fn ultosc_lookback(&self, mut optInTimePeriod1: i32, mut optInTimePeriod2: i32, mut optInTimePeriod3: i32) -> i32 {
        if ((optInTimePeriod1) as i32) == (i32::MIN) {
            optInTimePeriod1 = 7;
        } else if (((optInTimePeriod1) as i32) < 1) || (((optInTimePeriod1) as i32) > 100000) {
            return -1;
        }
        if ((optInTimePeriod2) as i32) == (i32::MIN) {
            optInTimePeriod2 = 14;
        } else if (((optInTimePeriod2) as i32) < 1) || (((optInTimePeriod2) as i32) > 100000) {
            return -1;
        }
        if ((optInTimePeriod3) as i32) == (i32::MIN) {
            optInTimePeriod3 = 28;
        } else if (((optInTimePeriod3) as i32) < 1) || (((optInTimePeriod3) as i32) > 100000) {
            return -1;
        }
        let maxPeriod: i32;
        maxPeriod = ((optInTimePeriod1).max(optInTimePeriod2)).max(optInTimePeriod3);
        return self.sma_lookback(maxPeriod) + 1;
    }
    /// Ultimate Oscillator
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInTimePeriod1` - Number of period (default: 7, range: 1..=100000)
    /// * `optInTimePeriod2` - Number of period (default: 14, range: 1..=100000)
    /// * `optInTimePeriod3` - Number of period (default: 28, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn ultosc<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod1: i32,
        mut optInTimePeriod2: i32,
        mut optInTimePeriod3: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod1) as i32) == (i32::MIN) {
            optInTimePeriod1 = 7;
        } else if (((optInTimePeriod1) as i32) < 1) || (((optInTimePeriod1) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInTimePeriod2) as i32) == (i32::MIN) {
            optInTimePeriod2 = 14;
        } else if (((optInTimePeriod2) as i32) < 1) || (((optInTimePeriod2) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInTimePeriod3) as i32) == (i32::MIN) {
            optInTimePeriod3 = 28;
        } else if (((optInTimePeriod3) as i32) < 1) || (((optInTimePeriod3) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.ultosc_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod1,
            optInTimePeriod2,
            optInTimePeriod3,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn ultosc_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod1: i32,
        mut optInTimePeriod2: i32,
        mut optInTimePeriod3: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let lookbackTotal: i32;
        let mut usedFlag: [i32; 3 as usize] = [0i32; 3 as usize];
        let mut periods: [i32; 3 as usize] = [0i32; 3 as usize];
        let mut sortedPeriods: [i32; 3 as usize] = [0i32; 3 as usize];
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        periods[0] = optInTimePeriod1;
        periods[1] = optInTimePeriod2;
        periods[2] = optInTimePeriod3;
        usedFlag[0] = 0;
        usedFlag[1] = 0;
        usedFlag[2] = 0;
        // for( i = 0; i < 3; i += 1 )
        i = 0;
        while i < 3 {
            longestPeriod = 0;
            longestIndex = 0;
            // for( j = 0; j < 3; j += 1 )
            j = 0;
            while j < 3 {
                if usedFlag[j] == 0 && periods[j] > longestPeriod {
                    longestPeriod = periods[j];
                    longestIndex = j;
                }
                j += 1;
            }
            usedFlag[longestIndex] = 1;
            sortedPeriods[i] = longestPeriod;
            i += 1;
        }
        optInTimePeriod1 = sortedPeriods[2];
        optInTimePeriod2 = sortedPeriods[1];
        optInTimePeriod3 = sortedPeriods[0];
        lookbackTotal = self.ultosc_lookback(optInTimePeriod1, optInTimePeriod2, optInTimePeriod3);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        a1Total = 0;
        b1Total = 0;
        // for( i = startIdx - optInTimePeriod1 + 1; i < startIdx; i += 1 )
        i = startIdx - optInTimePeriod1 + 1;
        while i < startIdx {
            tempLT = inLow[i];
            tempHT = inHigh[i];
            tempCY = inClose[i - 1];
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = inClose[i] - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a1Total += closeMinusTrueLow;
            b1Total += trueRange;
            i += 1;
        }
        a2Total = 0;
        b2Total = 0;
        // for( i = startIdx - optInTimePeriod2 + 1; i < startIdx; i += 1 )
        i = startIdx - optInTimePeriod2 + 1;
        while i < startIdx {
            tempLT = inLow[i];
            tempHT = inHigh[i];
            tempCY = inClose[i - 1];
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = inClose[i] - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a2Total += closeMinusTrueLow;
            b2Total += trueRange;
            i += 1;
        }
        a3Total = 0;
        b3Total = 0;
        // for( i = startIdx - optInTimePeriod3 + 1; i < startIdx; i += 1 )
        i = startIdx - optInTimePeriod3 + 1;
        while i < startIdx {
            tempLT = inLow[i];
            tempHT = inHigh[i];
            tempCY = inClose[i - 1];
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = inClose[i] - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a3Total += closeMinusTrueLow;
            b3Total += trueRange;
            i += 1;
        }
        today = startIdx;
        outIdx = 0;
        trailingIdx1 = today - optInTimePeriod1 + 1;
        trailingIdx2 = today - optInTimePeriod2 + 1;
        trailingIdx3 = today - optInTimePeriod3 + 1;
        while today <= endIdx {
            tempLT = inLow[today];
            tempHT = inHigh[today];
            tempCY = inClose[today - 1];
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = inClose[today] - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a1Total += closeMinusTrueLow;
            a2Total += closeMinusTrueLow;
            a3Total += closeMinusTrueLow;
            b1Total += trueRange;
            b2Total += trueRange;
            b3Total += trueRange;
            output = T::ta_from_f64(0.0);
            if !(0 - T::ta_from_f64(0.00000001) < b1Total && b1Total < T::ta_from_f64(0.00000001)) {
                output += T::ta_from_f64(4.0) * (a1Total / b1Total);
            }
            if !(0 - T::ta_from_f64(0.00000001) < b2Total && b2Total < T::ta_from_f64(0.00000001)) {
                output += T::ta_from_f64(2.0) * (a2Total / b2Total);
            }
            if !(0 - T::ta_from_f64(0.00000001) < b3Total && b3Total < T::ta_from_f64(0.00000001)) {
                output += a3Total / b3Total;
            }
            tempLT = inLow[trailingIdx1];
            tempHT = inHigh[trailingIdx1];
            tempCY = inClose[trailingIdx1 - 1];
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = inClose[trailingIdx1] - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a1Total -= closeMinusTrueLow;
            b1Total -= trueRange;
            tempLT = inLow[trailingIdx2];
            tempHT = inHigh[trailingIdx2];
            tempCY = inClose[trailingIdx2 - 1];
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = inClose[trailingIdx2] - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a2Total -= closeMinusTrueLow;
            b2Total -= trueRange;
            tempLT = inLow[trailingIdx3];
            tempHT = inHigh[trailingIdx3];
            tempCY = inClose[trailingIdx3 - 1];
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = inClose[trailingIdx3] - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a3Total -= closeMinusTrueLow;
            b3Total -= trueRange;
            outReal[outIdx] = T::ta_from_f64(100.0) * (output / T::ta_from_f64(7.0));
            outIdx += 1;
            today += 1;
            trailingIdx1 += 1;
            trailingIdx2 += 1;
            trailingIdx3 += 1;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    pub unsafe fn ultosc_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod1: i32,
        mut optInTimePeriod2: i32,
        mut optInTimePeriod3: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod1) as i32) == (i32::MIN) {
            optInTimePeriod1 = 7;
        } else if (((optInTimePeriod1) as i32) < 1) || (((optInTimePeriod1) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInTimePeriod2) as i32) == (i32::MIN) {
            optInTimePeriod2 = 14;
        } else if (((optInTimePeriod2) as i32) < 1) || (((optInTimePeriod2) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInTimePeriod3) as i32) == (i32::MIN) {
            optInTimePeriod3 = 28;
        } else if (((optInTimePeriod3) as i32) < 1) || (((optInTimePeriod3) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.ultosc_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod1,
            optInTimePeriod2,
            optInTimePeriod3,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn ultosc_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod1: i32,
        mut optInTimePeriod2: i32,
        mut optInTimePeriod3: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let lookbackTotal: i32;
        let mut usedFlag: [i32; 3 as usize] = [0i32; 3 as usize];
        let mut periods: [i32; 3 as usize] = [0i32; 3 as usize];
        let mut sortedPeriods: [i32; 3 as usize] = [0i32; 3 as usize];
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        *periods.get_unchecked_mut(0) = optInTimePeriod1;
        *periods.get_unchecked_mut(1) = optInTimePeriod2;
        *periods.get_unchecked_mut(2) = optInTimePeriod3;
        *usedFlag.get_unchecked_mut(0) = 0;
        *usedFlag.get_unchecked_mut(1) = 0;
        *usedFlag.get_unchecked_mut(2) = 0;
        // for( i = 0; i < 3; i += 1 )
        i = 0;
        while i < 3 {
            longestPeriod = 0;
            longestIndex = 0;
            // for( j = 0; j < 3; j += 1 )
            j = 0;
            while j < 3 {
                if *usedFlag.get_unchecked(j) == 0 && *periods.get_unchecked(j) > longestPeriod {
                    longestPeriod = *periods.get_unchecked(j);
                    longestIndex = j;
                }
                j += 1;
            }
            *usedFlag.get_unchecked_mut(longestIndex) = 1;
            *sortedPeriods.get_unchecked_mut(i) = longestPeriod;
            i += 1;
        }
        optInTimePeriod1 = *sortedPeriods.get_unchecked(2);
        optInTimePeriod2 = *sortedPeriods.get_unchecked(1);
        optInTimePeriod3 = *sortedPeriods.get_unchecked(0);
        lookbackTotal = self.ultosc_lookback(optInTimePeriod1, optInTimePeriod2, optInTimePeriod3);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        a1Total = 0;
        b1Total = 0;
        // for( i = startIdx - optInTimePeriod1 + 1; i < startIdx; i += 1 )
        i = startIdx - optInTimePeriod1 + 1;
        while i < startIdx {
            tempLT = *inLow.get_unchecked(i);
            tempHT = *inHigh.get_unchecked(i);
            tempCY = *inClose.get_unchecked(i - 1);
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = *inClose.get_unchecked(i) - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a1Total += closeMinusTrueLow;
            b1Total += trueRange;
            i += 1;
        }
        a2Total = 0;
        b2Total = 0;
        // for( i = startIdx - optInTimePeriod2 + 1; i < startIdx; i += 1 )
        i = startIdx - optInTimePeriod2 + 1;
        while i < startIdx {
            tempLT = *inLow.get_unchecked(i);
            tempHT = *inHigh.get_unchecked(i);
            tempCY = *inClose.get_unchecked(i - 1);
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = *inClose.get_unchecked(i) - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a2Total += closeMinusTrueLow;
            b2Total += trueRange;
            i += 1;
        }
        a3Total = 0;
        b3Total = 0;
        // for( i = startIdx - optInTimePeriod3 + 1; i < startIdx; i += 1 )
        i = startIdx - optInTimePeriod3 + 1;
        while i < startIdx {
            tempLT = *inLow.get_unchecked(i);
            tempHT = *inHigh.get_unchecked(i);
            tempCY = *inClose.get_unchecked(i - 1);
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = *inClose.get_unchecked(i) - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a3Total += closeMinusTrueLow;
            b3Total += trueRange;
            i += 1;
        }
        today = startIdx;
        outIdx = 0;
        trailingIdx1 = today - optInTimePeriod1 + 1;
        trailingIdx2 = today - optInTimePeriod2 + 1;
        trailingIdx3 = today - optInTimePeriod3 + 1;
        while today <= endIdx {
            tempLT = *inLow.get_unchecked(today);
            tempHT = *inHigh.get_unchecked(today);
            tempCY = *inClose.get_unchecked(today - 1);
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = *inClose.get_unchecked(today) - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a1Total += closeMinusTrueLow;
            a2Total += closeMinusTrueLow;
            a3Total += closeMinusTrueLow;
            b1Total += trueRange;
            b2Total += trueRange;
            b3Total += trueRange;
            output = T::ta_from_f64(0.0);
            if !(0 - T::ta_from_f64(0.00000001) < b1Total && b1Total < T::ta_from_f64(0.00000001)) {
                output += T::ta_from_f64(4.0) * (a1Total / b1Total);
            }
            if !(0 - T::ta_from_f64(0.00000001) < b2Total && b2Total < T::ta_from_f64(0.00000001)) {
                output += T::ta_from_f64(2.0) * (a2Total / b2Total);
            }
            if !(0 - T::ta_from_f64(0.00000001) < b3Total && b3Total < T::ta_from_f64(0.00000001)) {
                output += a3Total / b3Total;
            }
            tempLT = *inLow.get_unchecked(trailingIdx1);
            tempHT = *inHigh.get_unchecked(trailingIdx1);
            tempCY = *inClose.get_unchecked(trailingIdx1 - 1);
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = *inClose.get_unchecked(trailingIdx1) - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a1Total -= closeMinusTrueLow;
            b1Total -= trueRange;
            tempLT = *inLow.get_unchecked(trailingIdx2);
            tempHT = *inHigh.get_unchecked(trailingIdx2);
            tempCY = *inClose.get_unchecked(trailingIdx2 - 1);
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = *inClose.get_unchecked(trailingIdx2) - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a2Total -= closeMinusTrueLow;
            b2Total -= trueRange;
            tempLT = *inLow.get_unchecked(trailingIdx3);
            tempHT = *inHigh.get_unchecked(trailingIdx3);
            tempCY = *inClose.get_unchecked(trailingIdx3 - 1);
            trueLow = (tempLT).min(tempCY);
            closeMinusTrueLow = *inClose.get_unchecked(trailingIdx3) - trueLow;
            trueRange = tempHT - tempLT;
            tempDouble = tempCY - tempHT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            tempDouble = tempCY - tempLT.ta_abs();
            if tempDouble > trueRange {
                trueRange = tempDouble;
            }
            a3Total -= closeMinusTrueLow;
            b3Total -= trueRange;
            *outReal.get_unchecked_mut(outIdx) = T::ta_from_f64(100.0) * (output / T::ta_from_f64(7.0));
            outIdx += 1;
            today += 1;
            trailingIdx1 += 1;
            trailingIdx2 += 1;
            trailingIdx3 += 1;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
