/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::willr`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    pub fn willr_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        return optInTimePeriod - 1;
    }
    /// Williams' %R
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn willr<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.willr_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn willr_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut lowest: T;
        let mut highest: T;
        let mut tmp: T;
        let mut diff: T;
        let outIdx: i32;
        let nbInitialElementNeeded: i32;
        let mut trailingIdx: i32;
        let mut lowestIdx: i32;
        let mut highestIdx: i32;
        let mut today: i32;
        let mut i: i32;
        nbInitialElementNeeded = optInTimePeriod - 1;
        if startIdx < nbInitialElementNeeded {
            startIdx = nbInitialElementNeeded;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        diff = T::ta_from_f64(0.0);
        outIdx = 0;
        today = startIdx;
        trailingIdx = startIdx - nbInitialElementNeeded;
        highestIdx = 0 - 1;
        lowestIdx = highestIdx;
        lowest = T::ta_from_f64(0.0);
        highest = lowest;
        diff = highest;
        while today <= endIdx {
            tmp = inLow[today];
            if lowestIdx < trailingIdx {
                lowestIdx = trailingIdx;
                lowest = inLow[lowestIdx];
                i = lowestIdx;
                while { i += 1; i } <= today {
                    tmp = inLow[i];
                    if tmp < lowest {
                        lowestIdx = i;
                        lowest = tmp;
                    }
                }
                diff = (highest - lowest) / (0 - T::ta_from_f64(100.0));
            } else if tmp <= lowest {
                lowestIdx = today;
                lowest = tmp;
                diff = (highest - lowest) / (0 - T::ta_from_f64(100.0));
            }
            tmp = inHigh[today];
            if highestIdx < trailingIdx {
                highestIdx = trailingIdx;
                highest = inHigh[highestIdx];
                i = highestIdx;
                while { i += 1; i } <= today {
                    tmp = inHigh[i];
                    if tmp > highest {
                        highestIdx = i;
                        highest = tmp;
                    }
                }
                diff = (highest - lowest) / (0 - T::ta_from_f64(100.0));
            } else if tmp >= highest {
                highestIdx = today;
                highest = tmp;
                diff = (highest - lowest) / (0 - T::ta_from_f64(100.0));
            }
            if diff != T::ta_from_f64(0.0) {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = (highest - inClose[today]) / diff;
            } else {
                outReal[{ let _v = outIdx; outIdx += 1; _v }] = T::ta_from_f64(0.0);
            }
            trailingIdx += 1;
            today += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    pub unsafe fn willr_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.willr_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn willr_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut lowest: T;
        let mut highest: T;
        let mut tmp: T;
        let mut diff: T;
        let outIdx: i32;
        let nbInitialElementNeeded: i32;
        let mut trailingIdx: i32;
        let mut lowestIdx: i32;
        let mut highestIdx: i32;
        let mut today: i32;
        let mut i: i32;
        nbInitialElementNeeded = optInTimePeriod - 1;
        if startIdx < nbInitialElementNeeded {
            startIdx = nbInitialElementNeeded;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        diff = T::ta_from_f64(0.0);
        outIdx = 0;
        today = startIdx;
        trailingIdx = startIdx - nbInitialElementNeeded;
        highestIdx = 0 - 1;
        lowestIdx = highestIdx;
        lowest = T::ta_from_f64(0.0);
        highest = lowest;
        diff = highest;
        while today <= endIdx {
            tmp = *inLow.get_unchecked(today);
            if lowestIdx < trailingIdx {
                lowestIdx = trailingIdx;
                lowest = *inLow.get_unchecked(lowestIdx);
                i = lowestIdx;
                while { i += 1; i } <= today {
                    tmp = *inLow.get_unchecked(i);
                    if tmp < lowest {
                        lowestIdx = i;
                        lowest = tmp;
                    }
                }
                diff = (highest - lowest) / (0 - T::ta_from_f64(100.0));
            } else if tmp <= lowest {
                lowestIdx = today;
                lowest = tmp;
                diff = (highest - lowest) / (0 - T::ta_from_f64(100.0));
            }
            tmp = *inHigh.get_unchecked(today);
            if highestIdx < trailingIdx {
                highestIdx = trailingIdx;
                highest = *inHigh.get_unchecked(highestIdx);
                i = highestIdx;
                while { i += 1; i } <= today {
                    tmp = *inHigh.get_unchecked(i);
                    if tmp > highest {
                        highestIdx = i;
                        highest = tmp;
                    }
                }
                diff = (highest - lowest) / (0 - T::ta_from_f64(100.0));
            } else if tmp >= highest {
                highestIdx = today;
                highest = tmp;
                diff = (highest - lowest) / (0 - T::ta_from_f64(100.0));
            }
            if diff != T::ta_from_f64(0.0) {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = (highest - *inClose.get_unchecked(today)) / diff;
            } else {
                *outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = T::ta_from_f64(0.0);
            }
            trailingIdx += 1;
            today += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
