/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
// allow unused variables and dead code due to gen code weirdness
#[allow(unused_variables)]
#[allow(dead_code)]
impl Core {
    /// Lookback period for [`Core::wma`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    pub fn wma_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        return optInTimePeriod - 1;
    }
    /// Weighted Moving Average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    ///
    /// # Returns
    ///
    /// [`RetCode::Success`] on success, or an error code on failure.
    ///
    /// # Example
    ///
    /// ```
    /// use ta_lib::ta_func::{Core, RetCode};
    ///
    ///
    /// let close_prices = [1.0, 2.0, 3.0, 4.0, 5.0_f64];
    /// let mut out = [0.0_f64; 5];
    /// let mut out_beg_idx: usize = 0;
    /// let mut out_nb_element: usize = 0;
    ///
    /// let core = Core::new();
    /// let result = core.wma(
    ///  0,
    ///  4,
    ///  &close_prices,
    ///  3,
    ///  &mut out_beg_idx,
    ///  &mut out_nb_element,
    ///  &mut out,
    /// );
    ///
    /// assert_eq!(result, RetCode::Success);
    /// assert_eq!(out_beg_idx, 2);
    /// assert_eq!(out_nb_element, 3);
    /// assert!((out[0] - 2.0).abs() < 1e-10);
    /// assert!((out[1] - 3.0).abs() < 1e-10);
    /// assert!((out[2] - 4.0).abs() < 1e-10);
    /// ```
    pub fn wma(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeEndIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.int_wma(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    fn int_wma(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let divider: i32;
        let mut periodSum: f64;
        let mut periodSub: f64;
        let mut tempReal: f64;
        let mut trailingValue: f64;
        let mut inIdx: usize;
        let mut outIdx: usize;
        let mut trailingIdx: usize;
        let lookbackTotal: usize;
        let mut i: i32;
        periodSum = 0.0;
        periodSub = 0.0;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        if optInTimePeriod == 1 {
            (*outNBElement) = nbElement;
            (*outBegIdx) = startIdx;
            {
            let _n = (nbElement) as usize;
            let _di = (0) as usize;
            let _si = (startIdx) as usize;
            outReal[_di.._di + _n].copy_from_slice(&inReal[_si.._si + _n]);
        };
            return RetCode::Success;
        }
        divider = optInTimePeriod * (optInTimePeriod + 1) / 2;
        outIdx = 0;
        trailingIdx = startIdx - lookbackTotal;
        inIdx = trailingIdx;
        i = 1;
        while inIdx < startIdx {
            tempReal = (inReal[inIdx]) as f64;
            periodSub += tempReal;
            periodSum += tempReal * ((i) as f64);
            i += 1;
            inIdx += 1;
        }
        trailingValue = 0.0;
        while inIdx <= endIdx {
            tempReal = (inReal[inIdx]) as f64;
            inIdx += 1;
            periodSub += tempReal;
            periodSub -= trailingValue;
            periodSum += tempReal * ((optInTimePeriod) as f64);
            trailingValue = (inReal[trailingIdx]) as f64;
            trailingIdx += 1;
            outReal[outIdx] = periodSum / ((divider) as f64);
            outIdx += 1;
            periodSum -= periodSub;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
    /// Single-precision variant of [`Core::wma`].
    pub fn wma_s(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f32],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeEndIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.int_wma_s(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    fn int_wma_s(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f32],
        optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let divider: i32;
        let mut periodSum: f64;
        let mut periodSub: f64;
        let mut tempReal: f64;
        let mut trailingValue: f64;
        let mut inIdx: usize;
        let mut outIdx: usize;
        let mut trailingIdx: usize;
        let lookbackTotal: usize;
        let mut i: i32;
        periodSum = 0.0;
        periodSub = 0.0;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        if optInTimePeriod == 1 {
            (*outNBElement) = nbElement;
            (*outBegIdx) = startIdx;
            {
            let _n = (nbElement) as usize;
            let _di = (0) as usize;
            let _si = (startIdx) as usize;
            for _k in 0.._n {
                outReal[_di + _k] = inReal[_si + _k] as f64;
            }
        };
            return RetCode::Success;
        }
        divider = optInTimePeriod * (optInTimePeriod + 1) / 2;
        outIdx = 0;
        trailingIdx = startIdx - lookbackTotal;
        inIdx = trailingIdx;
        i = 1;
        while inIdx < startIdx {
            tempReal = (inReal[inIdx]) as f64;
            periodSub += tempReal;
            periodSum += tempReal * ((i) as f64);
            i += 1;
            inIdx += 1;
        }
        trailingValue = 0.0;
        while inIdx <= endIdx {
            tempReal = (inReal[inIdx]) as f64;
            inIdx += 1;
            periodSub += tempReal;
            periodSub -= trailingValue;
            periodSum += tempReal * ((optInTimePeriod) as f64);
            trailingValue = (inReal[trailingIdx]) as f64;
            trailingIdx += 1;
            outReal[outIdx] = periodSum / ((divider) as f64);
            outIdx += 1;
            periodSum -= periodSub;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
