/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::accbands`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 20, range: 2..=100000)
    pub fn accbands_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 20;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return self.sma_lookback(optInTimePeriod);
    }
    /// Acceleration Bands
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 20, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outRealUpperBand` - Output values
    /// * `outRealMiddleBand` - Output values
    /// * `outRealLowerBand` - Output values
    pub fn accbands(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [f64],
        outRealMiddleBand: &mut [f64],
        outRealLowerBand: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 20;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.accbands_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outRealUpperBand,
            outRealMiddleBand,
            outRealLowerBand,
        );
    }
    pub fn accbands_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [f64],
        outRealMiddleBand: &mut [f64],
        outRealLowerBand: &mut [f64],
    ) -> RetCode {
        let mut retCode: RetCode = RetCode::Success;
        let mut tempBuffer1: Vec<f64> = Vec::new();
        let mut tempBuffer2: Vec<f64> = Vec::new();
        let mut outBegIdxDummy: usize = 0_usize;
        let mut outNbElementDummy: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        let mut outputSize: usize = 0_usize;
        let mut bufferSize: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut tempReal: f64 = 0.0_f64;
        unsafe {
        lookbackTotal = self.sma_lookback(optInTimePeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outputSize = endIdx - startIdx + 1;
        bufferSize = outputSize + lookbackTotal;
        tempBuffer1 = vec![0.0_f64; (bufferSize * 1) as usize];
        tempBuffer2 = vec![0.0_f64; (bufferSize * 1) as usize];
        // for( j = 0, i = startIdx - lookbackTotal; i <= endIdx; i += 1, j += 1 )
        j = 0;
        i = startIdx - lookbackTotal;
        while i <= endIdx {
            tempReal = (*inHigh.get_unchecked(i)) + (*inLow.get_unchecked(i));
            if !((tempReal).abs() < 1e-14) {
                tempReal = 4_f64 * ((*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i))) / tempReal;
                (*tempBuffer1.get_unchecked_mut(j)) = (*inHigh.get_unchecked(i)) * (1_f64 + tempReal);
                (*tempBuffer2.get_unchecked_mut(j)) = (*inLow.get_unchecked(i)) * (1_f64 - tempReal);
            } else {
                (*tempBuffer1.get_unchecked_mut(j)) = (*inHigh.get_unchecked(i));
                (*tempBuffer2.get_unchecked_mut(j)) = (*inLow.get_unchecked(i));
            }
            i += 1;
            j += 1;
        }
        retCode = self.sma(startIdx, endIdx, inClose, optInTimePeriod, &mut outBegIdxDummy, &mut outNbElementDummy, outRealMiddleBand);
        if retCode != RetCode::Success || (((outNbElementDummy) as usize)) as usize != outputSize {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.sma(0, bufferSize - 1, &tempBuffer1, optInTimePeriod, &mut outBegIdxDummy, &mut outNbElementDummy, outRealUpperBand);
        if retCode != RetCode::Success || (((outNbElementDummy) as usize)) as usize != outputSize {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.sma(0, bufferSize - 1, &tempBuffer2, optInTimePeriod, &mut outBegIdxDummy, &mut outNbElementDummy, outRealLowerBand);
        if retCode != RetCode::Success || (((outNbElementDummy) as usize)) as usize != outputSize {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outputSize;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
