/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::accbands`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 20, range: 2..=100000)
    pub fn accbands_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 20;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return self.sma_lookback(optInTimePeriod);
    }
    /// Acceleration Bands
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 20, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outRealUpperBand` - Output values
    /// * `outRealMiddleBand` - Output values
    /// * `outRealLowerBand` - Output values
    pub fn accbands<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [T],
        outRealMiddleBand: &mut [T],
        outRealLowerBand: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 20;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.accbands_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outRealUpperBand,
            outRealMiddleBand,
            outRealLowerBand,
        );
    }
    pub fn accbands_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [T],
        outRealMiddleBand: &mut [T],
        outRealLowerBand: &mut [T],
    ) -> RetCode {
        let mut retCode: RetCode = RetCode::Success;
        let mut tempBuffer1: Vec<T> = Vec::new();
        let mut tempBuffer2: Vec<T> = Vec::new();
        let mut outBegIdxDummy: usize = 0_usize;
        let mut outNbElementDummy: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        let mut outputSize: usize = 0_usize;
        let mut bufferSize: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut tempReal: T = T::ta_zero();
        lookbackTotal = self.sma_lookback(optInTimePeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outputSize = endIdx - startIdx + 1;
        bufferSize = outputSize + lookbackTotal;
        tempBuffer1 = vec![T::ta_zero(); (bufferSize * 1) as usize];
        tempBuffer2 = vec![T::ta_zero(); (bufferSize * 1) as usize];
        // for( j = 0, i = startIdx - lookbackTotal; i <= endIdx; i += 1, j += 1 )
        j = 0;
        i = startIdx - lookbackTotal;
        while i <= endIdx {
            tempReal = inHigh[(i) as usize] + inLow[(i) as usize];
            if !(T::ta_from_i32(0) - T::ta_from_f64(0.00000001) < tempReal && tempReal < T::ta_from_f64(0.00000001)) {
                tempReal = T::ta_from_i32(4) * (inHigh[(i) as usize] - inLow[(i) as usize]) / tempReal;
                tempBuffer1[(j) as usize] = inHigh[(i) as usize] * (T::ta_from_i32(1) + tempReal);
                tempBuffer2[(j) as usize] = inLow[(i) as usize] * (T::ta_from_i32(1) - tempReal);
            } else {
                tempBuffer1[(j) as usize] = inHigh[(i) as usize];
                tempBuffer2[(j) as usize] = inLow[(i) as usize];
            }
            i += 1;
            j += 1;
        }
        retCode = self.sma_unguarded(startIdx, endIdx, inClose, optInTimePeriod, &mut outBegIdxDummy, &mut outNbElementDummy, outRealMiddleBand);
        if retCode != RetCode::Success || ((outNbElementDummy)) as usize != outputSize {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.sma_unguarded(0, bufferSize - 1, &tempBuffer1, optInTimePeriod, &mut outBegIdxDummy, &mut outNbElementDummy, outRealUpperBand);
        if retCode != RetCode::Success || ((outNbElementDummy)) as usize != outputSize {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.sma_unguarded(0, bufferSize - 1, &tempBuffer2, optInTimePeriod, &mut outBegIdxDummy, &mut outNbElementDummy, outRealLowerBand);
        if retCode != RetCode::Success || ((outNbElementDummy)) as usize != outputSize {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outputSize;
        return RetCode::Success;
    }
    pub unsafe fn accbands_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [T],
        outRealMiddleBand: &mut [T],
        outRealLowerBand: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 20;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.accbands_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outRealUpperBand,
            outRealMiddleBand,
            outRealLowerBand,
        );
    }
    pub unsafe fn accbands_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [T],
        outRealMiddleBand: &mut [T],
        outRealLowerBand: &mut [T],
    ) -> RetCode {
        let mut retCode: RetCode = RetCode::Success;
        let mut tempBuffer1: Vec<T> = Vec::new();
        let mut tempBuffer2: Vec<T> = Vec::new();
        let mut outBegIdxDummy: usize = 0_usize;
        let mut outNbElementDummy: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        let mut outputSize: usize = 0_usize;
        let mut bufferSize: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut tempReal: T = T::ta_zero();
        lookbackTotal = self.sma_lookback(optInTimePeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outputSize = endIdx - startIdx + 1;
        bufferSize = outputSize + lookbackTotal;
        tempBuffer1 = vec![T::ta_zero(); (bufferSize * 1) as usize];
        tempBuffer2 = vec![T::ta_zero(); (bufferSize * 1) as usize];
        // for( j = 0, i = startIdx - lookbackTotal; i <= endIdx; i += 1, j += 1 )
        j = 0;
        i = startIdx - lookbackTotal;
        while i <= endIdx {
            tempReal = (*inHigh.get_unchecked((i) as usize)) + (*inLow.get_unchecked((i) as usize));
            if !(T::ta_from_i32(0) - T::ta_from_f64(0.00000001) < tempReal && tempReal < T::ta_from_f64(0.00000001)) {
                tempReal = T::ta_from_i32(4) * ((*inHigh.get_unchecked((i) as usize)) - (*inLow.get_unchecked((i) as usize))) / tempReal;
                (*tempBuffer1.get_unchecked_mut((j) as usize)) = (*inHigh.get_unchecked((i) as usize)) * (T::ta_from_i32(1) + tempReal);
                (*tempBuffer2.get_unchecked_mut((j) as usize)) = (*inLow.get_unchecked((i) as usize)) * (T::ta_from_i32(1) - tempReal);
            } else {
                (*tempBuffer1.get_unchecked_mut((j) as usize)) = (*inHigh.get_unchecked((i) as usize));
                (*tempBuffer2.get_unchecked_mut((j) as usize)) = (*inLow.get_unchecked((i) as usize));
            }
            i += 1;
            j += 1;
        }
        retCode = self.sma_unguarded(startIdx, endIdx, inClose, optInTimePeriod, &mut outBegIdxDummy, &mut outNbElementDummy, outRealMiddleBand);
        if retCode != RetCode::Success || ((outNbElementDummy)) as usize != outputSize {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.sma_unguarded(0, bufferSize - 1, &tempBuffer1, optInTimePeriod, &mut outBegIdxDummy, &mut outNbElementDummy, outRealUpperBand);
        if retCode != RetCode::Success || ((outNbElementDummy)) as usize != outputSize {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.sma_unguarded(0, bufferSize - 1, &tempBuffer2, optInTimePeriod, &mut outBegIdxDummy, &mut outNbElementDummy, outRealLowerBand);
        if retCode != RetCode::Success || ((outNbElementDummy)) as usize != outputSize {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outputSize;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
