/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::ad`].
    ///
    /// # Arguments
    ///
    pub fn ad_lookback(&self) -> usize {
        return (0) as usize;
    }
    /// Chaikin A/D Line
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `inVolume` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn ad(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        inVolume: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.ad_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            inVolume,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn ad_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        inVolume: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut nbBar: usize = 0_usize;
        let mut currentBar: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut high: f64 = 0.0_f64;
        let mut low: f64 = 0.0_f64;
        let mut close: f64 = 0.0_f64;
        let mut tmp: f64 = 0.0_f64;
        let mut ad: f64 = 0.0_f64;
        nbBar = endIdx - startIdx + 1;
        (*outNBElement) = nbBar;
        (*outBegIdx) = startIdx;
        currentBar = startIdx;
        outIdx = 0;
        ad = 0.0;
        while nbBar != 0 {
            high = inHigh[currentBar];
            low = inLow[currentBar];
            tmp = high - low;
            close = inClose[currentBar];
            if tmp > 0.0 {
                ad += (close - low - (high - close)) / tmp * ((inVolume[currentBar]) as f64);
            }
            outReal[{ let _v = outIdx; outIdx += 1; _v }] = ad;
            currentBar += 1;
            nbBar -= 1;
        }
        return RetCode::Success;
    }
    pub unsafe fn ad_unchecked(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        inVolume: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.ad_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            inVolume,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn ad_unguarded_unchecked(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        inVolume: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut nbBar: usize = 0_usize;
        let mut currentBar: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut high: f64 = 0.0_f64;
        let mut low: f64 = 0.0_f64;
        let mut close: f64 = 0.0_f64;
        let mut tmp: f64 = 0.0_f64;
        let mut ad: f64 = 0.0_f64;
        nbBar = endIdx - startIdx + 1;
        (*outNBElement) = nbBar;
        (*outBegIdx) = startIdx;
        currentBar = startIdx;
        outIdx = 0;
        ad = 0.0;
        while nbBar != 0 {
            high = (*inHigh.get_unchecked(currentBar));
            low = (*inLow.get_unchecked(currentBar));
            tmp = high - low;
            close = (*inClose.get_unchecked(currentBar));
            if tmp > 0.0 {
                ad += (close - low - (high - close)) / tmp * (((*inVolume.get_unchecked(currentBar))) as f64);
            }
            (*outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = ad;
            currentBar += 1;
            nbBar -= 1;
        }
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
