/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::bbands`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 5, range: 2..=100000)
    /// * `optInNbDevUp` - Number of period (default: 2, range: -2147483648..=2147483647)
    /// * `optInNbDevDn` - Number of period (default: 2, range: -2147483648..=2147483647)
    pub fn bbands_lookback(&self, mut optInTimePeriod: i32, mut optInNbDevUp: f64, mut optInNbDevDn: f64, mut optInMAType: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return self.ma_lookback(optInTimePeriod, optInMAType);
    }
    /// Bollinger Bands
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 5, range: 2..=100000)
    /// * `optInNbDevUp` - Number of period (default: 2, range: -2147483648..=2147483647)
    /// * `optInNbDevDn` - Number of period (default: 2, range: -2147483648..=2147483647)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outRealUpperBand` - Output values
    /// * `outRealMiddleBand` - Output values
    /// * `outRealLowerBand` - Output values
    pub fn bbands(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInNbDevUp: f64,
        mut optInNbDevDn: f64,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [f64],
        outRealMiddleBand: &mut [f64],
        outRealLowerBand: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.bbands_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            optInNbDevUp,
            optInNbDevDn,
            optInMAType,
            outBegIdx,
            outNBElement,
            outRealUpperBand,
            outRealMiddleBand,
            outRealLowerBand,
        );
    }
    pub fn bbands_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInNbDevUp: f64,
        mut optInNbDevDn: f64,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outRealUpperBand: &mut [f64],
        outRealMiddleBand: &mut [f64],
        outRealLowerBand: &mut [f64],
    ) -> RetCode {
        let mut retCode: RetCode = RetCode::Success;
        let mut i: usize = 0_usize;
        let mut tempReal: f64 = 0.0_f64;
        let mut tempReal2: f64 = 0.0_f64;
        let mut tempBuffer1: Vec<f64> = Vec::new();
        let mut tempBuffer2: Vec<f64> = Vec::new();
        unsafe {
        if inReal == outRealUpperBand {
            tempBuffer1 = outRealMiddleBand.to_vec();
            tempBuffer2 = outRealLowerBand.to_vec();
        } else if inReal == outRealLowerBand {
            tempBuffer1 = outRealMiddleBand.to_vec();
            tempBuffer2 = outRealUpperBand.to_vec();
        } else if inReal == outRealMiddleBand {
            tempBuffer1 = outRealLowerBand.to_vec();
            tempBuffer2 = outRealUpperBand.to_vec();
        } else {
            tempBuffer1 = outRealMiddleBand.to_vec();
            tempBuffer2 = outRealUpperBand.to_vec();
        }
        if tempBuffer1 == inReal || tempBuffer2 == inReal {
            return RetCode::BadParam;
        }
        retCode = self.ma(startIdx, endIdx, inReal, optInTimePeriod, optInMAType, outBegIdx, outNBElement, &mut tempBuffer1[..]);
        if retCode != RetCode::Success || (((*outNBElement)) as usize) == 0 {
            (*outNBElement) = 0;
            return retCode;
        }
        if (optInMAType) as usize == 0 {
            let mut _tempReal: f64 = 0.0_f64;
            let mut _periodTotal2: f64 = 0.0_f64;
            let mut _meanValue2: f64 = 0.0_f64;
            let mut _outIdx: usize = 0_usize;
            let mut _startSum: usize = 0_usize;
            let mut _endSum: usize = 0_usize;
            _startSum = (1 + (((*outBegIdx)) as usize) - (optInTimePeriod) as usize) as usize;
            _endSum = (((*outBegIdx)) as usize) as usize;
            _periodTotal2 = 0.0;
            // for( _outIdx = _startSum; _outIdx < _endSum; _outIdx += 1 )
            _outIdx = _startSum;
            while _outIdx < _endSum {
                _tempReal = (*inReal.get_unchecked(_outIdx));
                _tempReal *= _tempReal;
                _periodTotal2 += _tempReal;
                _outIdx += 1;
            }
            // for( _outIdx = 0; _outIdx < ((((*outNBElement)) as usize)) as usize; _outIdx += 1, _startSum += 1, _endSum += 1 )
            _outIdx = 0;
            while _outIdx < ((((*outNBElement)) as usize)) as usize {
                _tempReal = (*inReal.get_unchecked(_endSum));
                _tempReal *= _tempReal;
                _periodTotal2 += _tempReal;
                _meanValue2 = _periodTotal2 / ((optInTimePeriod) as f64);
                _tempReal = (*inReal.get_unchecked(_startSum));
                _tempReal *= _tempReal;
                _periodTotal2 -= _tempReal;
                _tempReal = (*tempBuffer1.get_unchecked(_outIdx));
                _tempReal *= _tempReal;
                _meanValue2 -= _tempReal;
                if !((_meanValue2) < 1e-14) {
                    (*tempBuffer2.get_unchecked_mut(_outIdx)) = (_meanValue2).sqrt();
                } else {
                    (*tempBuffer2.get_unchecked_mut(_outIdx)) = 0.0;
                }
                _outIdx += 1;
                _startSum += 1;
                _endSum += 1;
            }
        } else {
            retCode = self.stddev((((*outBegIdx)) as usize) as usize, endIdx, inReal, optInTimePeriod, 1.0, outBegIdx, outNBElement, &mut tempBuffer2[..]);
            if retCode != RetCode::Success {
                (*outNBElement) = 0;
                return retCode;
            }
        }
        if tempBuffer1 != outRealMiddleBand {
            {
            let _n = ((*outNBElement) * 1) as usize;
            let _di = (0) as usize;
            let _si = (0) as usize;
            outRealMiddleBand[_di.._di + _n].copy_from_slice(&tempBuffer1[_si.._si + _n]);
        };
        }
        if optInNbDevUp == optInNbDevDn {
            if optInNbDevUp == 1.0 {
                // for( i = 0; i < ((((*outNBElement)) as usize)) as usize; i += 1 )
                i = 0;
                while i < ((((*outNBElement)) as usize)) as usize {
                    tempReal = (*tempBuffer2.get_unchecked(i));
                    tempReal2 = (*outRealMiddleBand.get_unchecked(i));
                    (*outRealUpperBand.get_unchecked_mut(i)) = tempReal2 + tempReal;
                    (*outRealLowerBand.get_unchecked_mut(i)) = tempReal2 - tempReal;
                    i += 1;
                }
            } else {
                // for( i = 0; i < ((((*outNBElement)) as usize)) as usize; i += 1 )
                i = 0;
                while i < ((((*outNBElement)) as usize)) as usize {
                    tempReal = (*tempBuffer2.get_unchecked(i)) * optInNbDevUp;
                    tempReal2 = (*outRealMiddleBand.get_unchecked(i));
                    (*outRealUpperBand.get_unchecked_mut(i)) = tempReal2 + tempReal;
                    (*outRealLowerBand.get_unchecked_mut(i)) = tempReal2 - tempReal;
                    i += 1;
                }
            }
        } else if optInNbDevUp == 1.0 {
            // for( i = 0; i < ((((*outNBElement)) as usize)) as usize; i += 1 )
            i = 0;
            while i < ((((*outNBElement)) as usize)) as usize {
                tempReal = (*tempBuffer2.get_unchecked(i));
                tempReal2 = (*outRealMiddleBand.get_unchecked(i));
                (*outRealUpperBand.get_unchecked_mut(i)) = tempReal2 + tempReal;
                (*outRealLowerBand.get_unchecked_mut(i)) = tempReal2 - tempReal * optInNbDevDn;
                i += 1;
            }
        } else if optInNbDevDn == 1.0 {
            // for( i = 0; i < ((((*outNBElement)) as usize)) as usize; i += 1 )
            i = 0;
            while i < ((((*outNBElement)) as usize)) as usize {
                tempReal = (*tempBuffer2.get_unchecked(i));
                tempReal2 = (*outRealMiddleBand.get_unchecked(i));
                (*outRealLowerBand.get_unchecked_mut(i)) = tempReal2 - tempReal;
                (*outRealUpperBand.get_unchecked_mut(i)) = tempReal2 + tempReal * optInNbDevUp;
                i += 1;
            }
        } else {
            // for( i = 0; i < ((((*outNBElement)) as usize)) as usize; i += 1 )
            i = 0;
            while i < ((((*outNBElement)) as usize)) as usize {
                tempReal = (*tempBuffer2.get_unchecked(i));
                tempReal2 = (*outRealMiddleBand.get_unchecked(i));
                (*outRealUpperBand.get_unchecked_mut(i)) = tempReal2 + tempReal * optInNbDevUp;
                (*outRealLowerBand.get_unchecked_mut(i)) = tempReal2 - tempReal * optInNbDevDn;
                i += 1;
            }
        }
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
