/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlhighwave`].
    ///
    /// # Arguments
    ///
    pub fn cdlhighwave_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let ShadowVeryLong_rangeType: i32 = self.candle_settings.shadow_very_long.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryLong_avgPeriod: i32 = self.candle_settings.shadow_very_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryLong_factor: f64 = self.candle_settings.shadow_very_long.factor;
        return ((BodyShort_avgPeriod).max(ShadowVeryLong_avgPeriod)) as usize;
    }
    /// High-Wave Candle
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlhighwave(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut BodyPeriodTotal: f64 = 0.0_f64;
        let mut ShadowPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut BodyTrailingIdx: usize = 0_usize;
        let mut ShadowTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let ShadowVeryLong_rangeType: i32 = self.candle_settings.shadow_very_long.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryLong_avgPeriod: i32 = self.candle_settings.shadow_very_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryLong_factor: f64 = self.candle_settings.shadow_very_long.factor;
        lookbackTotal = self.cdlhighwave_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyPeriodTotal = 0.0;
        BodyTrailingIdx = startIdx - (BodyShort_avgPeriod) as usize;
        ShadowPeriodTotal = 0.0;
        ShadowTrailingIdx = startIdx - (ShadowVeryLong_avgPeriod) as usize;
        i = BodyTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_0 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = ShadowTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: f64;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_1 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            ShadowPeriodTotal += _candlerange_1;
            i += 1;
        }
        outIdx = 0;
        loop {
            if (inClose[i] - inOpen[i]).abs() < { let _cr = match BodyShort_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => inHigh[i] - inLow[i], _ => inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs() }; let _avg = if BodyShort_avgPeriod != 0 { (BodyPeriodTotal) / (BodyShort_avgPeriod as f64) } else { _cr }; let _div = if BodyShort_rangeType == 2 { 2.0 } else { 1.0 }; (BodyShort_factor) * _avg / _div } && (inHigh[i] - (if inClose[i] >= inOpen[i] { inClose[i] } else { inOpen[i] })) > { let _cr = match ShadowVeryLong_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => inHigh[i] - inLow[i], _ => inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs() }; let _avg = if ShadowVeryLong_avgPeriod != 0 { (ShadowPeriodTotal) / (ShadowVeryLong_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryLong_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryLong_factor) * _avg / _div } && ((if inClose[i] >= inOpen[i] { inOpen[i] } else { inClose[i] }) - inLow[i]) > { let _cr = match ShadowVeryLong_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => inHigh[i] - inLow[i], _ => inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs() }; let _avg = if ShadowVeryLong_avgPeriod != 0 { (ShadowPeriodTotal) / (ShadowVeryLong_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryLong_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryLong_factor) * _avg / _div } {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = ((if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 }) * 100) as i32;
            } else {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 0;
            }
            let mut _candlerange_2: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_2 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_2 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            let mut _candlerange_3: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_3 = (inClose[BodyTrailingIdx] - inOpen[BodyTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_3 = inHigh[BodyTrailingIdx] - inLow[BodyTrailingIdx];
                }
                2 => {
                    _candlerange_3 = inHigh[BodyTrailingIdx] - inLow[BodyTrailingIdx] - (inClose[BodyTrailingIdx] - inOpen[BodyTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            BodyPeriodTotal += _candlerange_2 - _candlerange_3;
            let mut _candlerange_4: f64;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_4 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_4 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_4 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            let mut _candlerange_5: f64;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_5 = (inClose[ShadowTrailingIdx] - inOpen[ShadowTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_5 = inHigh[ShadowTrailingIdx] - inLow[ShadowTrailingIdx];
                }
                2 => {
                    _candlerange_5 = inHigh[ShadowTrailingIdx] - inLow[ShadowTrailingIdx] - (inClose[ShadowTrailingIdx] - inOpen[ShadowTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            ShadowPeriodTotal += _candlerange_4 - _candlerange_5;
            i += 1;
            BodyTrailingIdx += 1;
            ShadowTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    pub fn cdlhighwave_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyPeriodTotal: f64 = 0.0_f64;
        let mut ShadowPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut BodyTrailingIdx: usize = 0_usize;
        let mut ShadowTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let ShadowVeryLong_rangeType: i32 = self.candle_settings.shadow_very_long.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryLong_avgPeriod: i32 = self.candle_settings.shadow_very_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryLong_factor: f64 = self.candle_settings.shadow_very_long.factor;
        unsafe {
        lookbackTotal = self.cdlhighwave_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyPeriodTotal = 0.0;
        BodyTrailingIdx = startIdx - (BodyShort_avgPeriod) as usize;
        ShadowPeriodTotal = 0.0;
        ShadowTrailingIdx = startIdx - (ShadowVeryLong_avgPeriod) as usize;
        i = BodyTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_0 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_0 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_0 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = ShadowTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: f64;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_1 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_1 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_1 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            ShadowPeriodTotal += _candlerange_1;
            i += 1;
        }
        outIdx = 0;
        loop {
            if ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() < { let _cr = match BodyShort_rangeType { 0 => ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs(), 1 => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)), _ => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() }; let _avg = if BodyShort_avgPeriod != 0 { (BodyPeriodTotal) / (BodyShort_avgPeriod as f64) } else { _cr }; let _div = if BodyShort_rangeType == 2 { 2.0 } else { 1.0 }; (BodyShort_factor) * _avg / _div } && ((*inHigh.get_unchecked(i)) - (if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { (*inClose.get_unchecked(i)) } else { (*inOpen.get_unchecked(i)) })) > { let _cr = match ShadowVeryLong_rangeType { 0 => ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs(), 1 => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)), _ => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() }; let _avg = if ShadowVeryLong_avgPeriod != 0 { (ShadowPeriodTotal) / (ShadowVeryLong_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryLong_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryLong_factor) * _avg / _div } && ((if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { (*inOpen.get_unchecked(i)) } else { (*inClose.get_unchecked(i)) }) - (*inLow.get_unchecked(i))) > { let _cr = match ShadowVeryLong_rangeType { 0 => ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs(), 1 => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)), _ => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() }; let _avg = if ShadowVeryLong_avgPeriod != 0 { (ShadowPeriodTotal) / (ShadowVeryLong_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryLong_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryLong_factor) * _avg / _div } {
                (*outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = ((if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { 1 } else { 0 - 1 }) * 100) as i32;
            } else {
                (*outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = 0;
            }
            let mut _candlerange_2: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_2 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_2 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_2 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            let mut _candlerange_3: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_3 = ((*inClose.get_unchecked(BodyTrailingIdx)) - (*inOpen.get_unchecked(BodyTrailingIdx))).abs();
                }
                1 => {
                    _candlerange_3 = (*inHigh.get_unchecked(BodyTrailingIdx)) - (*inLow.get_unchecked(BodyTrailingIdx));
                }
                2 => {
                    _candlerange_3 = (*inHigh.get_unchecked(BodyTrailingIdx)) - (*inLow.get_unchecked(BodyTrailingIdx)) - ((*inClose.get_unchecked(BodyTrailingIdx)) - (*inOpen.get_unchecked(BodyTrailingIdx))).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            BodyPeriodTotal += _candlerange_2 - _candlerange_3;
            let mut _candlerange_4: f64;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_4 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_4 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_4 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            let mut _candlerange_5: f64;
            match ShadowVeryLong_rangeType {
                0 => {
                    _candlerange_5 = ((*inClose.get_unchecked(ShadowTrailingIdx)) - (*inOpen.get_unchecked(ShadowTrailingIdx))).abs();
                }
                1 => {
                    _candlerange_5 = (*inHigh.get_unchecked(ShadowTrailingIdx)) - (*inLow.get_unchecked(ShadowTrailingIdx));
                }
                2 => {
                    _candlerange_5 = (*inHigh.get_unchecked(ShadowTrailingIdx)) - (*inLow.get_unchecked(ShadowTrailingIdx)) - ((*inClose.get_unchecked(ShadowTrailingIdx)) - (*inOpen.get_unchecked(ShadowTrailingIdx))).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            ShadowPeriodTotal += _candlerange_4 - _candlerange_5;
            i += 1;
            BodyTrailingIdx += 1;
            ShadowTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
