/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlhikkake`].
    ///
    /// # Arguments
    ///
    pub fn cdlhikkake_lookback(&self) -> usize {
        return (5) as usize;
    }
    /// Hikkake Pattern
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlhikkake<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlhikkake_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdlhikkake_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut patternIdx: usize = 0_usize;
        let mut patternResult: i32 = 0_i32;
        lookbackTotal = self.cdlhikkake_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        patternIdx = 0;
        patternResult = 0;
        i = startIdx - 3;
        while i < startIdx {
            if inHigh[(i - 1) as usize] < inHigh[(i - 2) as usize] && inLow[(i - 1) as usize] > inLow[(i - 2) as usize] && (inHigh[(i) as usize] < inHigh[(i - 1) as usize] && inLow[(i) as usize] < inLow[(i - 1) as usize] || inHigh[(i) as usize] > inHigh[(i - 1) as usize] && inLow[(i) as usize] > inLow[(i - 1) as usize]) {
                patternResult = 100 * if inHigh[(i) as usize] < inHigh[(i - 1) as usize] { 1 } else { 0 - 1 };
                patternIdx = i;
            } else if i <= patternIdx + 3 && (patternResult > 0 && inClose[(i) as usize] > inHigh[(patternIdx - 1) as usize] || patternResult < 0 && inClose[(i) as usize] < inLow[(patternIdx - 1) as usize]) {
                patternIdx = 0;
            }
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if inHigh[(i - 1) as usize] < inHigh[(i - 2) as usize] && inLow[(i - 1) as usize] > inLow[(i - 2) as usize] && (inHigh[(i) as usize] < inHigh[(i - 1) as usize] && inLow[(i) as usize] < inLow[(i - 1) as usize] || inHigh[(i) as usize] > inHigh[(i - 1) as usize] && inLow[(i) as usize] > inLow[(i - 1) as usize]) {
                patternResult = 100 * if inHigh[(i) as usize] < inHigh[(i - 1) as usize] { 1 } else { 0 - 1 };
                patternIdx = i;
                outInteger[({ let _v = outIdx; outIdx += 1; _v }) as usize] = (patternResult) as i32;
            } else if i <= patternIdx + 3 && (patternResult > 0 && inClose[(i) as usize] > inHigh[(patternIdx - 1) as usize] || patternResult < 0 && inClose[(i) as usize] < inLow[(patternIdx - 1) as usize]) {
                outInteger[({ let _v = outIdx; outIdx += 1; _v }) as usize] = (patternResult + (100 * if patternResult > 0 { 1 } else { 0 - 1 }) as i32) as i32;
                patternIdx = 0;
            } else {
                outInteger[({ let _v = outIdx; outIdx += 1; _v }) as usize] = 0;
            }
            i += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    pub unsafe fn cdlhikkake_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlhikkake_unguarded_unchecked(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn cdlhikkake_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut patternIdx: usize = 0_usize;
        let mut patternResult: i32 = 0_i32;
        lookbackTotal = self.cdlhikkake_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        patternIdx = 0;
        patternResult = 0;
        i = startIdx - 3;
        while i < startIdx {
            if (*inHigh.get_unchecked((i - 1) as usize)) < (*inHigh.get_unchecked((i - 2) as usize)) && (*inLow.get_unchecked((i - 1) as usize)) > (*inLow.get_unchecked((i - 2) as usize)) && ((*inHigh.get_unchecked((i) as usize)) < (*inHigh.get_unchecked((i - 1) as usize)) && (*inLow.get_unchecked((i) as usize)) < (*inLow.get_unchecked((i - 1) as usize)) || (*inHigh.get_unchecked((i) as usize)) > (*inHigh.get_unchecked((i - 1) as usize)) && (*inLow.get_unchecked((i) as usize)) > (*inLow.get_unchecked((i - 1) as usize))) {
                patternResult = 100 * if (*inHigh.get_unchecked((i) as usize)) < (*inHigh.get_unchecked((i - 1) as usize)) { 1 } else { 0 - 1 };
                patternIdx = i;
            } else if i <= patternIdx + 3 && (patternResult > 0 && (*inClose.get_unchecked((i) as usize)) > (*inHigh.get_unchecked((patternIdx - 1) as usize)) || patternResult < 0 && (*inClose.get_unchecked((i) as usize)) < (*inLow.get_unchecked((patternIdx - 1) as usize))) {
                patternIdx = 0;
            }
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (*inHigh.get_unchecked((i - 1) as usize)) < (*inHigh.get_unchecked((i - 2) as usize)) && (*inLow.get_unchecked((i - 1) as usize)) > (*inLow.get_unchecked((i - 2) as usize)) && ((*inHigh.get_unchecked((i) as usize)) < (*inHigh.get_unchecked((i - 1) as usize)) && (*inLow.get_unchecked((i) as usize)) < (*inLow.get_unchecked((i - 1) as usize)) || (*inHigh.get_unchecked((i) as usize)) > (*inHigh.get_unchecked((i - 1) as usize)) && (*inLow.get_unchecked((i) as usize)) > (*inLow.get_unchecked((i - 1) as usize))) {
                patternResult = 100 * if (*inHigh.get_unchecked((i) as usize)) < (*inHigh.get_unchecked((i - 1) as usize)) { 1 } else { 0 - 1 };
                patternIdx = i;
                (*outInteger.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = (patternResult) as i32;
            } else if i <= patternIdx + 3 && (patternResult > 0 && (*inClose.get_unchecked((i) as usize)) > (*inHigh.get_unchecked((patternIdx - 1) as usize)) || patternResult < 0 && (*inClose.get_unchecked((i) as usize)) < (*inLow.get_unchecked((patternIdx - 1) as usize))) {
                (*outInteger.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = (patternResult + (100 * if patternResult > 0 { 1 } else { 0 - 1 }) as i32) as i32;
                patternIdx = 0;
            } else {
                (*outInteger.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = 0;
            }
            i += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
