/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlinneck`].
    ///
    /// # Arguments
    ///
    pub fn cdlinneck_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let Equal_rangeType: i32 = self.candle_settings.equal.range_type;
        #[allow(non_snake_case)]
        let Equal_avgPeriod: i32 = self.candle_settings.equal.avg_period;
        #[allow(non_snake_case)]
        let Equal_factor: f64 = self.candle_settings.equal.factor;
        return ((Equal_avgPeriod).max(BodyLong_avgPeriod) + 1) as usize;
    }
    /// In-Neck Pattern
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlinneck<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlinneck_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdlinneck_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut EqualPeriodTotal: T = T::ta_zero();
        let mut BodyLongPeriodTotal: T = T::ta_zero();
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut EqualTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let Equal_rangeType: i32 = self.candle_settings.equal.range_type;
        #[allow(non_snake_case)]
        let Equal_avgPeriod: i32 = self.candle_settings.equal.avg_period;
        #[allow(non_snake_case)]
        let Equal_factor: f64 = self.candle_settings.equal.factor;
        lookbackTotal = self.cdlinneck_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        EqualPeriodTotal = T::ta_from_i32(0 as i32);
        EqualTrailingIdx = startIdx - (Equal_avgPeriod) as usize;
        BodyLongPeriodTotal = T::ta_from_i32(0 as i32);
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = EqualTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match Equal_rangeType {
                0 => {
                    _candlerange_0 = (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_0 = inHigh[(i - 1) as usize] - inLow[(i - 1) as usize];
                }
                2 => {
                    _candlerange_0 = inHigh[(i - 1) as usize] - inLow[(i - 1) as usize] - (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            EqualPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_1 = (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_1 = inHigh[(i - 1) as usize] - inLow[(i - 1) as usize];
                }
                2 => {
                    _candlerange_1 = inHigh[(i - 1) as usize] - inLow[(i - 1) as usize] - (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            BodyLongPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if inClose[(i - 1) as usize] >= inOpen[(i - 1) as usize] { 1 } else { 0 - 1 }) as i32 == 0 - 1 && (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs() > self.ta_candleaverage(BodyLong_rangeType, BodyLong_avgPeriod, BodyLong_factor, BodyLongPeriodTotal, inOpen[(i - 1) as usize], inHigh[(i - 1) as usize], inLow[(i - 1) as usize], inClose[(i - 1) as usize]) && if inClose[(i) as usize] >= inOpen[(i) as usize] { 1 } else { 0 - 1 } == 1 && inOpen[(i) as usize] < inLow[(i - 1) as usize] && inClose[(i) as usize] <= inClose[(i - 1) as usize] + self.ta_candleaverage(Equal_rangeType, Equal_avgPeriod, Equal_factor, EqualPeriodTotal, inOpen[(i - 1) as usize], inHigh[(i - 1) as usize], inLow[(i - 1) as usize], inClose[(i - 1) as usize]) && inClose[(i) as usize] >= inClose[(i - 1) as usize] {
                outInteger[({ let _v = outIdx; outIdx += 1; _v }) as usize] = (0 - 100) as i32;
            } else {
                outInteger[({ let _v = outIdx; outIdx += 1; _v }) as usize] = 0;
            }
            let mut _candlerange_2: T;
            match Equal_rangeType {
                0 => {
                    _candlerange_2 = (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_2 = inHigh[(i - 1) as usize] - inLow[(i - 1) as usize];
                }
                2 => {
                    _candlerange_2 = inHigh[(i - 1) as usize] - inLow[(i - 1) as usize] - (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_3: T;
            match Equal_rangeType {
                0 => {
                    _candlerange_3 = (inClose[(EqualTrailingIdx - 1) as usize] - inOpen[(EqualTrailingIdx - 1) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_3 = inHigh[(EqualTrailingIdx - 1) as usize] - inLow[(EqualTrailingIdx - 1) as usize];
                }
                2 => {
                    _candlerange_3 = inHigh[(EqualTrailingIdx - 1) as usize] - inLow[(EqualTrailingIdx - 1) as usize] - (inClose[(EqualTrailingIdx - 1) as usize] - inOpen[(EqualTrailingIdx - 1) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            EqualPeriodTotal += _candlerange_2 - _candlerange_3;
            let mut _candlerange_4: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_4 = (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_4 = inHigh[(i - 1) as usize] - inLow[(i - 1) as usize];
                }
                2 => {
                    _candlerange_4 = inHigh[(i - 1) as usize] - inLow[(i - 1) as usize] - (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_5: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_5 = (inClose[(BodyLongTrailingIdx - 1) as usize] - inOpen[(BodyLongTrailingIdx - 1) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_5 = inHigh[(BodyLongTrailingIdx - 1) as usize] - inLow[(BodyLongTrailingIdx - 1) as usize];
                }
                2 => {
                    _candlerange_5 = inHigh[(BodyLongTrailingIdx - 1) as usize] - inLow[(BodyLongTrailingIdx - 1) as usize] - (inClose[(BodyLongTrailingIdx - 1) as usize] - inOpen[(BodyLongTrailingIdx - 1) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            BodyLongPeriodTotal += _candlerange_4 - _candlerange_5;
            i += 1;
            EqualTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    pub unsafe fn cdlinneck_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlinneck_unguarded_unchecked(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn cdlinneck_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut EqualPeriodTotal: T = T::ta_zero();
        let mut BodyLongPeriodTotal: T = T::ta_zero();
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut EqualTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let Equal_rangeType: i32 = self.candle_settings.equal.range_type;
        #[allow(non_snake_case)]
        let Equal_avgPeriod: i32 = self.candle_settings.equal.avg_period;
        #[allow(non_snake_case)]
        let Equal_factor: f64 = self.candle_settings.equal.factor;
        lookbackTotal = self.cdlinneck_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        EqualPeriodTotal = T::ta_from_i32(0 as i32);
        EqualTrailingIdx = startIdx - (Equal_avgPeriod) as usize;
        BodyLongPeriodTotal = T::ta_from_i32(0 as i32);
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = EqualTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match Equal_rangeType {
                0 => {
                    _candlerange_0 = ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_0 = (*inHigh.get_unchecked((i - 1) as usize)) - (*inLow.get_unchecked((i - 1) as usize));
                }
                2 => {
                    _candlerange_0 = (*inHigh.get_unchecked((i - 1) as usize)) - (*inLow.get_unchecked((i - 1) as usize)) - ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            EqualPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_1 = ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_1 = (*inHigh.get_unchecked((i - 1) as usize)) - (*inLow.get_unchecked((i - 1) as usize));
                }
                2 => {
                    _candlerange_1 = (*inHigh.get_unchecked((i - 1) as usize)) - (*inLow.get_unchecked((i - 1) as usize)) - ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            BodyLongPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if (*inClose.get_unchecked((i - 1) as usize)) >= (*inOpen.get_unchecked((i - 1) as usize)) { 1 } else { 0 - 1 }) as i32 == 0 - 1 && ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs() > self.ta_candleaverage(BodyLong_rangeType, BodyLong_avgPeriod, BodyLong_factor, BodyLongPeriodTotal, (*inOpen.get_unchecked((i - 1) as usize)), (*inHigh.get_unchecked((i - 1) as usize)), (*inLow.get_unchecked((i - 1) as usize)), (*inClose.get_unchecked((i - 1) as usize))) && if (*inClose.get_unchecked((i) as usize)) >= (*inOpen.get_unchecked((i) as usize)) { 1 } else { 0 - 1 } == 1 && (*inOpen.get_unchecked((i) as usize)) < (*inLow.get_unchecked((i - 1) as usize)) && (*inClose.get_unchecked((i) as usize)) <= (*inClose.get_unchecked((i - 1) as usize)) + self.ta_candleaverage(Equal_rangeType, Equal_avgPeriod, Equal_factor, EqualPeriodTotal, (*inOpen.get_unchecked((i - 1) as usize)), (*inHigh.get_unchecked((i - 1) as usize)), (*inLow.get_unchecked((i - 1) as usize)), (*inClose.get_unchecked((i - 1) as usize))) && (*inClose.get_unchecked((i) as usize)) >= (*inClose.get_unchecked((i - 1) as usize)) {
                (*outInteger.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = (0 - 100) as i32;
            } else {
                (*outInteger.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = 0;
            }
            let mut _candlerange_2: T;
            match Equal_rangeType {
                0 => {
                    _candlerange_2 = ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_2 = (*inHigh.get_unchecked((i - 1) as usize)) - (*inLow.get_unchecked((i - 1) as usize));
                }
                2 => {
                    _candlerange_2 = (*inHigh.get_unchecked((i - 1) as usize)) - (*inLow.get_unchecked((i - 1) as usize)) - ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_3: T;
            match Equal_rangeType {
                0 => {
                    _candlerange_3 = ((*inClose.get_unchecked((EqualTrailingIdx - 1) as usize)) - (*inOpen.get_unchecked((EqualTrailingIdx - 1) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_3 = (*inHigh.get_unchecked((EqualTrailingIdx - 1) as usize)) - (*inLow.get_unchecked((EqualTrailingIdx - 1) as usize));
                }
                2 => {
                    _candlerange_3 = (*inHigh.get_unchecked((EqualTrailingIdx - 1) as usize)) - (*inLow.get_unchecked((EqualTrailingIdx - 1) as usize)) - ((*inClose.get_unchecked((EqualTrailingIdx - 1) as usize)) - (*inOpen.get_unchecked((EqualTrailingIdx - 1) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            EqualPeriodTotal += _candlerange_2 - _candlerange_3;
            let mut _candlerange_4: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_4 = ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_4 = (*inHigh.get_unchecked((i - 1) as usize)) - (*inLow.get_unchecked((i - 1) as usize));
                }
                2 => {
                    _candlerange_4 = (*inHigh.get_unchecked((i - 1) as usize)) - (*inLow.get_unchecked((i - 1) as usize)) - ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_5: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_5 = ((*inClose.get_unchecked((BodyLongTrailingIdx - 1) as usize)) - (*inOpen.get_unchecked((BodyLongTrailingIdx - 1) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_5 = (*inHigh.get_unchecked((BodyLongTrailingIdx - 1) as usize)) - (*inLow.get_unchecked((BodyLongTrailingIdx - 1) as usize));
                }
                2 => {
                    _candlerange_5 = (*inHigh.get_unchecked((BodyLongTrailingIdx - 1) as usize)) - (*inLow.get_unchecked((BodyLongTrailingIdx - 1) as usize)) - ((*inClose.get_unchecked((BodyLongTrailingIdx - 1) as usize)) - (*inOpen.get_unchecked((BodyLongTrailingIdx - 1) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            BodyLongPeriodTotal += _candlerange_4 - _candlerange_5;
            i += 1;
            EqualTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
