/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlidentical3crows`].
    ///
    /// # Arguments
    ///
    pub fn cdlidentical3crows_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let Equal_rangeType: i32 = self.candle_settings.equal.range_type;
        #[allow(non_snake_case)]
        let Equal_avgPeriod: i32 = self.candle_settings.equal.avg_period;
        #[allow(non_snake_case)]
        let Equal_factor: f64 = self.candle_settings.equal.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        return ((ShadowVeryShort_avgPeriod).max(Equal_avgPeriod) + 2) as usize;
    }
    /// Identical Three Crows
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlidentical3crows(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlidentical3crows_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdlidentical3crows_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut ShadowVeryShortPeriodTotal: [f64; 3 as usize] = [0.0_f64; 3 as usize];
        let mut EqualPeriodTotal: [f64; 3 as usize] = [0.0_f64; 3 as usize];
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut ShadowVeryShortTrailingIdx: usize = 0_usize;
        let mut EqualTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let Equal_rangeType: i32 = self.candle_settings.equal.range_type;
        #[allow(non_snake_case)]
        let Equal_avgPeriod: i32 = self.candle_settings.equal.avg_period;
        #[allow(non_snake_case)]
        let Equal_factor: f64 = self.candle_settings.equal.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        lookbackTotal = self.cdlidentical3crows_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        ShadowVeryShortPeriodTotal[2] = 0.0;
        ShadowVeryShortPeriodTotal[1] = 0.0;
        ShadowVeryShortPeriodTotal[0] = 0.0;
        ShadowVeryShortTrailingIdx = startIdx - (ShadowVeryShort_avgPeriod) as usize;
        EqualPeriodTotal[2] = 0.0;
        EqualPeriodTotal[1] = 0.0;
        EqualPeriodTotal[0] = 0.0;
        EqualTrailingIdx = startIdx - (Equal_avgPeriod) as usize;
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_0 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            ShadowVeryShortPeriodTotal[2] = ShadowVeryShortPeriodTotal[2] + _candlerange_0;
            let mut _candlerange_1: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_1 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            ShadowVeryShortPeriodTotal[1] = ShadowVeryShortPeriodTotal[1] + _candlerange_1;
            let mut _candlerange_2: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_2 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_2 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            ShadowVeryShortPeriodTotal[0] = ShadowVeryShortPeriodTotal[0] + _candlerange_2;
            i += 1;
        }
        i = EqualTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: f64;
            match Equal_rangeType {
                0 => {
                    _candlerange_3 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_3 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_3 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            EqualPeriodTotal[2] = EqualPeriodTotal[2] + _candlerange_3;
            let mut _candlerange_4: f64;
            match Equal_rangeType {
                0 => {
                    _candlerange_4 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_4 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_4 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            EqualPeriodTotal[1] = EqualPeriodTotal[1] + _candlerange_4;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if ((if inClose[i - 2] >= inOpen[i - 2] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && ((if inClose[i - 2] >= inOpen[i - 2] { inOpen[i - 2] } else { inClose[i - 2] }) - inLow[i - 2]) < { let _cr = match ShadowVeryShort_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => inHigh[i - 2] - inLow[i - 2], _ => inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { (ShadowVeryShortPeriodTotal[2]) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && ((if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && ((if inClose[i - 1] >= inOpen[i - 1] { inOpen[i - 1] } else { inClose[i - 1] }) - inLow[i - 1]) < { let _cr = match ShadowVeryShort_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => inHigh[i - 1] - inLow[i - 1], _ => inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { (ShadowVeryShortPeriodTotal[1]) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && ((if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && ((if inClose[i] >= inOpen[i] { inOpen[i] } else { inClose[i] }) - inLow[i]) < { let _cr = match ShadowVeryShort_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => inHigh[i] - inLow[i], _ => inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { (ShadowVeryShortPeriodTotal[0]) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && inClose[i - 2] > inClose[i - 1] && inClose[i - 1] > inClose[i] && inOpen[i - 1] <= inClose[i - 2] + { let _cr = match Equal_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => inHigh[i - 2] - inLow[i - 2], _ => inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs() }; let _avg = if Equal_avgPeriod != 0 { (EqualPeriodTotal[2]) / (Equal_avgPeriod as f64) } else { _cr }; let _div = if Equal_rangeType == 2 { 2.0 } else { 1.0 }; (Equal_factor) * _avg / _div } && inOpen[i - 1] >= inClose[i - 2] - { let _cr = match Equal_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => inHigh[i - 2] - inLow[i - 2], _ => inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs() }; let _avg = if Equal_avgPeriod != 0 { (EqualPeriodTotal[2]) / (Equal_avgPeriod as f64) } else { _cr }; let _div = if Equal_rangeType == 2 { 2.0 } else { 1.0 }; (Equal_factor) * _avg / _div } && inOpen[i] <= inClose[i - 1] + { let _cr = match Equal_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => inHigh[i - 1] - inLow[i - 1], _ => inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs() }; let _avg = if Equal_avgPeriod != 0 { (EqualPeriodTotal[1]) / (Equal_avgPeriod as f64) } else { _cr }; let _div = if Equal_rangeType == 2 { 2.0 } else { 1.0 }; (Equal_factor) * _avg / _div } && inOpen[i] >= inClose[i - 1] - { let _cr = match Equal_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => inHigh[i - 1] - inLow[i - 1], _ => inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs() }; let _avg = if Equal_avgPeriod != 0 { (EqualPeriodTotal[1]) / (Equal_avgPeriod as f64) } else { _cr }; let _div = if Equal_rangeType == 2 { 2.0 } else { 1.0 }; (Equal_factor) * _avg / _div } {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = (0 - 100) as i32;
            } else {
                outInteger[{ let _v = outIdx; outIdx += 1; _v }] = 0;
            }
            // for( totIdx = 2; totIdx >= 0; totIdx -= 1 )
            totIdx = 2;
            loop {
                let mut _candlerange_5: f64;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_5 = (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_5 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_5 = inHigh[i - totIdx] - inLow[i - totIdx] - (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_5 = 0.0;
                    }
                }
                let mut _candlerange_6: f64;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_6 = (inClose[ShadowVeryShortTrailingIdx - totIdx] - inOpen[ShadowVeryShortTrailingIdx - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_6 = inHigh[ShadowVeryShortTrailingIdx - totIdx] - inLow[ShadowVeryShortTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_6 = inHigh[ShadowVeryShortTrailingIdx - totIdx] - inLow[ShadowVeryShortTrailingIdx - totIdx] - (inClose[ShadowVeryShortTrailingIdx - totIdx] - inOpen[ShadowVeryShortTrailingIdx - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_6 = 0.0;
                    }
                }
                ShadowVeryShortPeriodTotal[totIdx] = ShadowVeryShortPeriodTotal[totIdx] + (_candlerange_5 - _candlerange_6);
                if totIdx == 0 { break; }
                totIdx -= 1;
            }
            // for( totIdx = 2; totIdx >= 1; totIdx -= 1 )
            totIdx = 2;
            loop {
                let mut _candlerange_7: f64;
                match Equal_rangeType {
                    0 => {
                        _candlerange_7 = (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_7 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_7 = inHigh[i - totIdx] - inLow[i - totIdx] - (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_7 = 0.0;
                    }
                }
                let mut _candlerange_8: f64;
                match Equal_rangeType {
                    0 => {
                        _candlerange_8 = (inClose[EqualTrailingIdx - totIdx] - inOpen[EqualTrailingIdx - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_8 = inHigh[EqualTrailingIdx - totIdx] - inLow[EqualTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_8 = inHigh[EqualTrailingIdx - totIdx] - inLow[EqualTrailingIdx - totIdx] - (inClose[EqualTrailingIdx - totIdx] - inOpen[EqualTrailingIdx - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_8 = 0.0;
                    }
                }
                EqualPeriodTotal[totIdx] = EqualPeriodTotal[totIdx] + (_candlerange_7 - _candlerange_8);
                if totIdx == 1 { break; }
                totIdx -= 1;
            }
            i += 1;
            ShadowVeryShortTrailingIdx += 1;
            EqualTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    pub unsafe fn cdlidentical3crows_unchecked(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlidentical3crows_unguarded_unchecked(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn cdlidentical3crows_unguarded_unchecked(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut ShadowVeryShortPeriodTotal: [f64; 3 as usize] = [0.0_f64; 3 as usize];
        let mut EqualPeriodTotal: [f64; 3 as usize] = [0.0_f64; 3 as usize];
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut ShadowVeryShortTrailingIdx: usize = 0_usize;
        let mut EqualTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let Equal_rangeType: i32 = self.candle_settings.equal.range_type;
        #[allow(non_snake_case)]
        let Equal_avgPeriod: i32 = self.candle_settings.equal.avg_period;
        #[allow(non_snake_case)]
        let Equal_factor: f64 = self.candle_settings.equal.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        lookbackTotal = self.cdlidentical3crows_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*ShadowVeryShortPeriodTotal.get_unchecked_mut(2)) = 0.0;
        (*ShadowVeryShortPeriodTotal.get_unchecked_mut(1)) = 0.0;
        (*ShadowVeryShortPeriodTotal.get_unchecked_mut(0)) = 0.0;
        ShadowVeryShortTrailingIdx = startIdx - (ShadowVeryShort_avgPeriod) as usize;
        (*EqualPeriodTotal.get_unchecked_mut(2)) = 0.0;
        (*EqualPeriodTotal.get_unchecked_mut(1)) = 0.0;
        (*EqualPeriodTotal.get_unchecked_mut(0)) = 0.0;
        EqualTrailingIdx = startIdx - (Equal_avgPeriod) as usize;
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_0 = ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs();
                }
                1 => {
                    _candlerange_0 = (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2));
                }
                2 => {
                    _candlerange_0 = (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)) - ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            (*ShadowVeryShortPeriodTotal.get_unchecked_mut(2)) = (*ShadowVeryShortPeriodTotal.get_unchecked(2)) + _candlerange_0;
            let mut _candlerange_1: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_1 = ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs();
                }
                1 => {
                    _candlerange_1 = (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1));
                }
                2 => {
                    _candlerange_1 = (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            (*ShadowVeryShortPeriodTotal.get_unchecked_mut(1)) = (*ShadowVeryShortPeriodTotal.get_unchecked(1)) + _candlerange_1;
            let mut _candlerange_2: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_2 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_2 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_2 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            (*ShadowVeryShortPeriodTotal.get_unchecked_mut(0)) = (*ShadowVeryShortPeriodTotal.get_unchecked(0)) + _candlerange_2;
            i += 1;
        }
        i = EqualTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: f64;
            match Equal_rangeType {
                0 => {
                    _candlerange_3 = ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs();
                }
                1 => {
                    _candlerange_3 = (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2));
                }
                2 => {
                    _candlerange_3 = (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)) - ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            (*EqualPeriodTotal.get_unchecked_mut(2)) = (*EqualPeriodTotal.get_unchecked(2)) + _candlerange_3;
            let mut _candlerange_4: f64;
            match Equal_rangeType {
                0 => {
                    _candlerange_4 = ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs();
                }
                1 => {
                    _candlerange_4 = (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1));
                }
                2 => {
                    _candlerange_4 = (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            (*EqualPeriodTotal.get_unchecked_mut(1)) = (*EqualPeriodTotal.get_unchecked(1)) + _candlerange_4;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if ((if (*inClose.get_unchecked(i - 2)) >= (*inOpen.get_unchecked(i - 2)) { 1 } else { 0 - 1 })) as i32 == 0 - 1 && ((if (*inClose.get_unchecked(i - 2)) >= (*inOpen.get_unchecked(i - 2)) { (*inOpen.get_unchecked(i - 2)) } else { (*inClose.get_unchecked(i - 2)) }) - (*inLow.get_unchecked(i - 2))) < { let _cr = match ShadowVeryShort_rangeType { 0 => ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs(), 1 => (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)), _ => (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)) - ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { ((*ShadowVeryShortPeriodTotal.get_unchecked(2))) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && ((if (*inClose.get_unchecked(i - 1)) >= (*inOpen.get_unchecked(i - 1)) { 1 } else { 0 - 1 })) as i32 == 0 - 1 && ((if (*inClose.get_unchecked(i - 1)) >= (*inOpen.get_unchecked(i - 1)) { (*inOpen.get_unchecked(i - 1)) } else { (*inClose.get_unchecked(i - 1)) }) - (*inLow.get_unchecked(i - 1))) < { let _cr = match ShadowVeryShort_rangeType { 0 => ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs(), 1 => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)), _ => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { ((*ShadowVeryShortPeriodTotal.get_unchecked(1))) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && ((if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { 1 } else { 0 - 1 })) as i32 == 0 - 1 && ((if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { (*inOpen.get_unchecked(i)) } else { (*inClose.get_unchecked(i)) }) - (*inLow.get_unchecked(i))) < { let _cr = match ShadowVeryShort_rangeType { 0 => ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs(), 1 => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)), _ => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { ((*ShadowVeryShortPeriodTotal.get_unchecked(0))) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && (*inClose.get_unchecked(i - 2)) > (*inClose.get_unchecked(i - 1)) && (*inClose.get_unchecked(i - 1)) > (*inClose.get_unchecked(i)) && (*inOpen.get_unchecked(i - 1)) <= (*inClose.get_unchecked(i - 2)) + { let _cr = match Equal_rangeType { 0 => ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs(), 1 => (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)), _ => (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)) - ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs() }; let _avg = if Equal_avgPeriod != 0 { ((*EqualPeriodTotal.get_unchecked(2))) / (Equal_avgPeriod as f64) } else { _cr }; let _div = if Equal_rangeType == 2 { 2.0 } else { 1.0 }; (Equal_factor) * _avg / _div } && (*inOpen.get_unchecked(i - 1)) >= (*inClose.get_unchecked(i - 2)) - { let _cr = match Equal_rangeType { 0 => ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs(), 1 => (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)), _ => (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)) - ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs() }; let _avg = if Equal_avgPeriod != 0 { ((*EqualPeriodTotal.get_unchecked(2))) / (Equal_avgPeriod as f64) } else { _cr }; let _div = if Equal_rangeType == 2 { 2.0 } else { 1.0 }; (Equal_factor) * _avg / _div } && (*inOpen.get_unchecked(i)) <= (*inClose.get_unchecked(i - 1)) + { let _cr = match Equal_rangeType { 0 => ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs(), 1 => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)), _ => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() }; let _avg = if Equal_avgPeriod != 0 { ((*EqualPeriodTotal.get_unchecked(1))) / (Equal_avgPeriod as f64) } else { _cr }; let _div = if Equal_rangeType == 2 { 2.0 } else { 1.0 }; (Equal_factor) * _avg / _div } && (*inOpen.get_unchecked(i)) >= (*inClose.get_unchecked(i - 1)) - { let _cr = match Equal_rangeType { 0 => ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs(), 1 => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)), _ => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() }; let _avg = if Equal_avgPeriod != 0 { ((*EqualPeriodTotal.get_unchecked(1))) / (Equal_avgPeriod as f64) } else { _cr }; let _div = if Equal_rangeType == 2 { 2.0 } else { 1.0 }; (Equal_factor) * _avg / _div } {
                (*outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = (0 - 100) as i32;
            } else {
                (*outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = 0;
            }
            // for( totIdx = 2; totIdx >= 0; totIdx -= 1 )
            totIdx = 2;
            loop {
                let mut _candlerange_5: f64;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_5 = ((*inClose.get_unchecked(i - totIdx)) - (*inOpen.get_unchecked(i - totIdx))).abs();
                    }
                    1 => {
                        _candlerange_5 = (*inHigh.get_unchecked(i - totIdx)) - (*inLow.get_unchecked(i - totIdx));
                    }
                    2 => {
                        _candlerange_5 = (*inHigh.get_unchecked(i - totIdx)) - (*inLow.get_unchecked(i - totIdx)) - ((*inClose.get_unchecked(i - totIdx)) - (*inOpen.get_unchecked(i - totIdx))).abs();
                    }
                    _ => {
                        _candlerange_5 = 0.0;
                    }
                }
                let mut _candlerange_6: f64;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_6 = ((*inClose.get_unchecked(ShadowVeryShortTrailingIdx - totIdx)) - (*inOpen.get_unchecked(ShadowVeryShortTrailingIdx - totIdx))).abs();
                    }
                    1 => {
                        _candlerange_6 = (*inHigh.get_unchecked(ShadowVeryShortTrailingIdx - totIdx)) - (*inLow.get_unchecked(ShadowVeryShortTrailingIdx - totIdx));
                    }
                    2 => {
                        _candlerange_6 = (*inHigh.get_unchecked(ShadowVeryShortTrailingIdx - totIdx)) - (*inLow.get_unchecked(ShadowVeryShortTrailingIdx - totIdx)) - ((*inClose.get_unchecked(ShadowVeryShortTrailingIdx - totIdx)) - (*inOpen.get_unchecked(ShadowVeryShortTrailingIdx - totIdx))).abs();
                    }
                    _ => {
                        _candlerange_6 = 0.0;
                    }
                }
                (*ShadowVeryShortPeriodTotal.get_unchecked_mut(totIdx)) = (*ShadowVeryShortPeriodTotal.get_unchecked(totIdx)) + (_candlerange_5 - _candlerange_6);
                if totIdx == 0 { break; }
                totIdx -= 1;
            }
            // for( totIdx = 2; totIdx >= 1; totIdx -= 1 )
            totIdx = 2;
            loop {
                let mut _candlerange_7: f64;
                match Equal_rangeType {
                    0 => {
                        _candlerange_7 = ((*inClose.get_unchecked(i - totIdx)) - (*inOpen.get_unchecked(i - totIdx))).abs();
                    }
                    1 => {
                        _candlerange_7 = (*inHigh.get_unchecked(i - totIdx)) - (*inLow.get_unchecked(i - totIdx));
                    }
                    2 => {
                        _candlerange_7 = (*inHigh.get_unchecked(i - totIdx)) - (*inLow.get_unchecked(i - totIdx)) - ((*inClose.get_unchecked(i - totIdx)) - (*inOpen.get_unchecked(i - totIdx))).abs();
                    }
                    _ => {
                        _candlerange_7 = 0.0;
                    }
                }
                let mut _candlerange_8: f64;
                match Equal_rangeType {
                    0 => {
                        _candlerange_8 = ((*inClose.get_unchecked(EqualTrailingIdx - totIdx)) - (*inOpen.get_unchecked(EqualTrailingIdx - totIdx))).abs();
                    }
                    1 => {
                        _candlerange_8 = (*inHigh.get_unchecked(EqualTrailingIdx - totIdx)) - (*inLow.get_unchecked(EqualTrailingIdx - totIdx));
                    }
                    2 => {
                        _candlerange_8 = (*inHigh.get_unchecked(EqualTrailingIdx - totIdx)) - (*inLow.get_unchecked(EqualTrailingIdx - totIdx)) - ((*inClose.get_unchecked(EqualTrailingIdx - totIdx)) - (*inOpen.get_unchecked(EqualTrailingIdx - totIdx))).abs();
                    }
                    _ => {
                        _candlerange_8 = 0.0;
                    }
                }
                (*EqualPeriodTotal.get_unchecked_mut(totIdx)) = (*EqualPeriodTotal.get_unchecked(totIdx)) + (_candlerange_7 - _candlerange_8);
                if totIdx == 1 { break; }
                totIdx -= 1;
            }
            i += 1;
            ShadowVeryShortTrailingIdx += 1;
            EqualTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
