/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlkickingbylength`].
    ///
    /// # Arguments
    ///
    pub fn cdlkickingbylength_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        return ((ShadowVeryShort_avgPeriod).max(BodyLong_avgPeriod) + 1) as usize;
    }
    /// Kicking - bull/bear determined by the longer marubozu
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlkickingbylength(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlkickingbylength_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdlkickingbylength_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut ShadowVeryShortPeriodTotal: [f64; 2 as usize] = [0.0_f64; 2 as usize];
        let mut BodyLongPeriodTotal: [f64; 2 as usize] = [0.0_f64; 2 as usize];
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut ShadowVeryShortTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        unsafe {
        lookbackTotal = self.cdlkickingbylength_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*ShadowVeryShortPeriodTotal.get_unchecked_mut(1)) = 0.0;
        (*ShadowVeryShortPeriodTotal.get_unchecked_mut(0)) = 0.0;
        ShadowVeryShortTrailingIdx = startIdx - (ShadowVeryShort_avgPeriod) as usize;
        (*BodyLongPeriodTotal.get_unchecked_mut(1)) = 0.0;
        (*BodyLongPeriodTotal.get_unchecked_mut(0)) = 0.0;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_0 = ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs();
                }
                1 => {
                    _candlerange_0 = (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1));
                }
                2 => {
                    _candlerange_0 = (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            (*ShadowVeryShortPeriodTotal.get_unchecked_mut(1)) = (*ShadowVeryShortPeriodTotal.get_unchecked(1)) + _candlerange_0;
            let mut _candlerange_1: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_1 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_1 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_1 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            (*ShadowVeryShortPeriodTotal.get_unchecked_mut(0)) = (*ShadowVeryShortPeriodTotal.get_unchecked(0)) + _candlerange_1;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_2: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_2 = ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs();
                }
                1 => {
                    _candlerange_2 = (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1));
                }
                2 => {
                    _candlerange_2 = (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            (*BodyLongPeriodTotal.get_unchecked_mut(1)) = (*BodyLongPeriodTotal.get_unchecked(1)) + _candlerange_2;
            let mut _candlerange_3: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_3 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_3 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_3 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            (*BodyLongPeriodTotal.get_unchecked_mut(0)) = (*BodyLongPeriodTotal.get_unchecked(0)) + _candlerange_3;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if (*inClose.get_unchecked(i - 1)) >= (*inOpen.get_unchecked(i - 1)) { 1 } else { 0 - 1 }) == 0 - (if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { 1 } else { 0 - 1 }) && ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() > { let _cr = match BodyLong_rangeType { 0 => ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs(), 1 => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)), _ => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() }; let _avg = if BodyLong_avgPeriod != 0 { ((*BodyLongPeriodTotal.get_unchecked(1))) / (BodyLong_avgPeriod as f64) } else { _cr }; let _div = if BodyLong_rangeType == 2 { 2.0 } else { 1.0 }; (BodyLong_factor) * _avg / _div } && ((*inHigh.get_unchecked(i - 1)) - (if (*inClose.get_unchecked(i - 1)) >= (*inOpen.get_unchecked(i - 1)) { (*inClose.get_unchecked(i - 1)) } else { (*inOpen.get_unchecked(i - 1)) })) < { let _cr = match ShadowVeryShort_rangeType { 0 => ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs(), 1 => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)), _ => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { ((*ShadowVeryShortPeriodTotal.get_unchecked(1))) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && ((if (*inClose.get_unchecked(i - 1)) >= (*inOpen.get_unchecked(i - 1)) { (*inOpen.get_unchecked(i - 1)) } else { (*inClose.get_unchecked(i - 1)) }) - (*inLow.get_unchecked(i - 1))) < { let _cr = match ShadowVeryShort_rangeType { 0 => ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs(), 1 => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)), _ => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { ((*ShadowVeryShortPeriodTotal.get_unchecked(1))) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() > { let _cr = match BodyLong_rangeType { 0 => ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs(), 1 => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)), _ => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() }; let _avg = if BodyLong_avgPeriod != 0 { ((*BodyLongPeriodTotal.get_unchecked(0))) / (BodyLong_avgPeriod as f64) } else { _cr }; let _div = if BodyLong_rangeType == 2 { 2.0 } else { 1.0 }; (BodyLong_factor) * _avg / _div } && ((*inHigh.get_unchecked(i)) - (if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { (*inClose.get_unchecked(i)) } else { (*inOpen.get_unchecked(i)) })) < { let _cr = match ShadowVeryShort_rangeType { 0 => ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs(), 1 => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)), _ => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { ((*ShadowVeryShortPeriodTotal.get_unchecked(0))) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && ((if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { (*inOpen.get_unchecked(i)) } else { (*inClose.get_unchecked(i)) }) - (*inLow.get_unchecked(i))) < { let _cr = match ShadowVeryShort_rangeType { 0 => ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs(), 1 => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)), _ => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { ((*ShadowVeryShortPeriodTotal.get_unchecked(0))) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && (((if (*inClose.get_unchecked(i - 1)) >= (*inOpen.get_unchecked(i - 1)) { 1 } else { 0 - 1 })) as i32 == 0 - 1 && ((if (*inLow.get_unchecked(i)) > (*inHigh.get_unchecked(i - 1)) { 1 } else { 0 }) != 0) || (if (*inClose.get_unchecked(i - 1)) >= (*inOpen.get_unchecked(i - 1)) { 1 } else { 0 - 1 }) == 1 && ((if (*inHigh.get_unchecked(i)) < (*inLow.get_unchecked(i - 1)) { 1 } else { 0 }) != 0)) {
                (*outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = ((if (*inClose.get_unchecked(((if ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() > ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() { i } else { i - 1 })) as usize)) >= (*inOpen.get_unchecked(((if ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() > ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() { i } else { i - 1 })) as usize)) { 1 } else { 0 - 1 }) * 100) as i32;
            } else {
                (*outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = 0;
            }
            // for( totIdx = 1; totIdx >= 0; totIdx -= 1 )
            totIdx = 1;
            loop {
                let mut _candlerange_4: f64;
                match BodyLong_rangeType {
                    0 => {
                        _candlerange_4 = ((*inClose.get_unchecked(i - totIdx)) - (*inOpen.get_unchecked(i - totIdx))).abs();
                    }
                    1 => {
                        _candlerange_4 = (*inHigh.get_unchecked(i - totIdx)) - (*inLow.get_unchecked(i - totIdx));
                    }
                    2 => {
                        _candlerange_4 = (*inHigh.get_unchecked(i - totIdx)) - (*inLow.get_unchecked(i - totIdx)) - ((*inClose.get_unchecked(i - totIdx)) - (*inOpen.get_unchecked(i - totIdx))).abs();
                    }
                    _ => {
                        _candlerange_4 = 0.0;
                    }
                }
                let mut _candlerange_5: f64;
                match BodyLong_rangeType {
                    0 => {
                        _candlerange_5 = ((*inClose.get_unchecked(BodyLongTrailingIdx - totIdx)) - (*inOpen.get_unchecked(BodyLongTrailingIdx - totIdx))).abs();
                    }
                    1 => {
                        _candlerange_5 = (*inHigh.get_unchecked(BodyLongTrailingIdx - totIdx)) - (*inLow.get_unchecked(BodyLongTrailingIdx - totIdx));
                    }
                    2 => {
                        _candlerange_5 = (*inHigh.get_unchecked(BodyLongTrailingIdx - totIdx)) - (*inLow.get_unchecked(BodyLongTrailingIdx - totIdx)) - ((*inClose.get_unchecked(BodyLongTrailingIdx - totIdx)) - (*inOpen.get_unchecked(BodyLongTrailingIdx - totIdx))).abs();
                    }
                    _ => {
                        _candlerange_5 = 0.0;
                    }
                }
                (*BodyLongPeriodTotal.get_unchecked_mut(totIdx)) = (*BodyLongPeriodTotal.get_unchecked(totIdx)) + (_candlerange_4 - _candlerange_5);
                let mut _candlerange_6: f64;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_6 = ((*inClose.get_unchecked(i - totIdx)) - (*inOpen.get_unchecked(i - totIdx))).abs();
                    }
                    1 => {
                        _candlerange_6 = (*inHigh.get_unchecked(i - totIdx)) - (*inLow.get_unchecked(i - totIdx));
                    }
                    2 => {
                        _candlerange_6 = (*inHigh.get_unchecked(i - totIdx)) - (*inLow.get_unchecked(i - totIdx)) - ((*inClose.get_unchecked(i - totIdx)) - (*inOpen.get_unchecked(i - totIdx))).abs();
                    }
                    _ => {
                        _candlerange_6 = 0.0;
                    }
                }
                let mut _candlerange_7: f64;
                match ShadowVeryShort_rangeType {
                    0 => {
                        _candlerange_7 = ((*inClose.get_unchecked(ShadowVeryShortTrailingIdx - totIdx)) - (*inOpen.get_unchecked(ShadowVeryShortTrailingIdx - totIdx))).abs();
                    }
                    1 => {
                        _candlerange_7 = (*inHigh.get_unchecked(ShadowVeryShortTrailingIdx - totIdx)) - (*inLow.get_unchecked(ShadowVeryShortTrailingIdx - totIdx));
                    }
                    2 => {
                        _candlerange_7 = (*inHigh.get_unchecked(ShadowVeryShortTrailingIdx - totIdx)) - (*inLow.get_unchecked(ShadowVeryShortTrailingIdx - totIdx)) - ((*inClose.get_unchecked(ShadowVeryShortTrailingIdx - totIdx)) - (*inOpen.get_unchecked(ShadowVeryShortTrailingIdx - totIdx))).abs();
                    }
                    _ => {
                        _candlerange_7 = 0.0;
                    }
                }
                (*ShadowVeryShortPeriodTotal.get_unchecked_mut(totIdx)) = (*ShadowVeryShortPeriodTotal.get_unchecked(totIdx)) + (_candlerange_6 - _candlerange_7);
                if totIdx == 0 { break; }
                totIdx -= 1;
            }
            i += 1;
            ShadowVeryShortTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
