/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlmathold`].
    ///
    /// # Arguments
    ///
    /// * `optInPenetration` - Number of period (default: 0, range: 0..=2147483647)
    pub fn cdlmathold_lookback(&self, mut optInPenetration: f64) -> usize {
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        return ((BodyShort_avgPeriod).max(BodyLong_avgPeriod) + 4) as usize;
    }
    /// Mat Hold
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInPenetration` - Number of period (default: 0, range: 0..=2147483647)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlmathold(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        mut optInPenetration: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlmathold_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            optInPenetration,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdlmathold_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        mut optInPenetration: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyPeriodTotal: [f64; 5 as usize] = [0.0_f64; 5 as usize];
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut BodyShortTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        lookbackTotal = self.cdlmathold_lookback(optInPenetration);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*BodyPeriodTotal.get_unchecked_mut(4)) = 0.0;
        (*BodyPeriodTotal.get_unchecked_mut(3)) = 0.0;
        (*BodyPeriodTotal.get_unchecked_mut(2)) = 0.0;
        (*BodyPeriodTotal.get_unchecked_mut(1)) = 0.0;
        (*BodyPeriodTotal.get_unchecked_mut(0)) = 0.0;
        BodyShortTrailingIdx = startIdx - (BodyShort_avgPeriod) as usize;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = BodyShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_0 = ((*inClose.get_unchecked(i - 3)) - (*inOpen.get_unchecked(i - 3))).abs();
                }
                1 => {
                    _candlerange_0 = (*inHigh.get_unchecked(i - 3)) - (*inLow.get_unchecked(i - 3));
                }
                2 => {
                    _candlerange_0 = (*inHigh.get_unchecked(i - 3)) - (*inLow.get_unchecked(i - 3)) - ((*inClose.get_unchecked(i - 3)) - (*inOpen.get_unchecked(i - 3))).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut(3)) = (*BodyPeriodTotal.get_unchecked(3)) + _candlerange_0;
            let mut _candlerange_1: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_1 = ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs();
                }
                1 => {
                    _candlerange_1 = (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2));
                }
                2 => {
                    _candlerange_1 = (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)) - ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut(2)) = (*BodyPeriodTotal.get_unchecked(2)) + _candlerange_1;
            let mut _candlerange_2: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_2 = ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs();
                }
                1 => {
                    _candlerange_2 = (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1));
                }
                2 => {
                    _candlerange_2 = (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut(1)) = (*BodyPeriodTotal.get_unchecked(1)) + _candlerange_2;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_3 = ((*inClose.get_unchecked(i - 4)) - (*inOpen.get_unchecked(i - 4))).abs();
                }
                1 => {
                    _candlerange_3 = (*inHigh.get_unchecked(i - 4)) - (*inLow.get_unchecked(i - 4));
                }
                2 => {
                    _candlerange_3 = (*inHigh.get_unchecked(i - 4)) - (*inLow.get_unchecked(i - 4)) - ((*inClose.get_unchecked(i - 4)) - (*inOpen.get_unchecked(i - 4))).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut(4)) = (*BodyPeriodTotal.get_unchecked(4)) + _candlerange_3;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if ((*inClose.get_unchecked(i - 4)) - (*inOpen.get_unchecked(i - 4))).abs() > { let _cr = match BodyLong_rangeType { 0 => ((*inClose.get_unchecked(i - 4)) - (*inOpen.get_unchecked(i - 4))).abs(), 1 => (*inHigh.get_unchecked(i - 4)) - (*inLow.get_unchecked(i - 4)), _ => (*inHigh.get_unchecked(i - 4)) - (*inLow.get_unchecked(i - 4)) - ((*inClose.get_unchecked(i - 4)) - (*inOpen.get_unchecked(i - 4))).abs() }; let _avg = if BodyLong_avgPeriod != 0 { ((*BodyPeriodTotal.get_unchecked(4))) / (BodyLong_avgPeriod as f64) } else { _cr }; let _div = if BodyLong_rangeType == 2 { 2.0 } else { 1.0 }; (BodyLong_factor) * _avg / _div } && ((*inClose.get_unchecked(i - 3)) - (*inOpen.get_unchecked(i - 3))).abs() < { let _cr = match BodyShort_rangeType { 0 => ((*inClose.get_unchecked(i - 3)) - (*inOpen.get_unchecked(i - 3))).abs(), 1 => (*inHigh.get_unchecked(i - 3)) - (*inLow.get_unchecked(i - 3)), _ => (*inHigh.get_unchecked(i - 3)) - (*inLow.get_unchecked(i - 3)) - ((*inClose.get_unchecked(i - 3)) - (*inOpen.get_unchecked(i - 3))).abs() }; let _avg = if BodyShort_avgPeriod != 0 { ((*BodyPeriodTotal.get_unchecked(3))) / (BodyShort_avgPeriod as f64) } else { _cr }; let _div = if BodyShort_rangeType == 2 { 2.0 } else { 1.0 }; (BodyShort_factor) * _avg / _div } && ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs() < { let _cr = match BodyShort_rangeType { 0 => ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs(), 1 => (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)), _ => (*inHigh.get_unchecked(i - 2)) - (*inLow.get_unchecked(i - 2)) - ((*inClose.get_unchecked(i - 2)) - (*inOpen.get_unchecked(i - 2))).abs() }; let _avg = if BodyShort_avgPeriod != 0 { ((*BodyPeriodTotal.get_unchecked(2))) / (BodyShort_avgPeriod as f64) } else { _cr }; let _div = if BodyShort_rangeType == 2 { 2.0 } else { 1.0 }; (BodyShort_factor) * _avg / _div } && ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() < { let _cr = match BodyShort_rangeType { 0 => ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs(), 1 => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)), _ => (*inHigh.get_unchecked(i - 1)) - (*inLow.get_unchecked(i - 1)) - ((*inClose.get_unchecked(i - 1)) - (*inOpen.get_unchecked(i - 1))).abs() }; let _avg = if BodyShort_avgPeriod != 0 { ((*BodyPeriodTotal.get_unchecked(1))) / (BodyShort_avgPeriod as f64) } else { _cr }; let _div = if BodyShort_rangeType == 2 { 2.0 } else { 1.0 }; (BodyShort_factor) * _avg / _div } && (if (*inClose.get_unchecked(i - 4)) >= (*inOpen.get_unchecked(i - 4)) { 1 } else { 0 - 1 }) == 1 && ((if (*inClose.get_unchecked(i - 3)) >= (*inOpen.get_unchecked(i - 3)) { 1 } else { 0 - 1 })) as i32 == 0 - 1 && (if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { 1 } else { 0 - 1 }) == 1 && ((if ((*inOpen.get_unchecked(i - 3))).min((*inClose.get_unchecked(i - 3))) > ((*inOpen.get_unchecked(i - 4))).max((*inClose.get_unchecked(i - 4))) { 1 } else { 0 }) != 0) && ((*inOpen.get_unchecked(i - 2))).min((*inClose.get_unchecked(i - 2))) < (*inClose.get_unchecked(i - 4)) && ((*inOpen.get_unchecked(i - 1))).min((*inClose.get_unchecked(i - 1))) < (*inClose.get_unchecked(i - 4)) && ((*inOpen.get_unchecked(i - 2))).min((*inClose.get_unchecked(i - 2))) > (*inClose.get_unchecked(i - 4)) - ((*inClose.get_unchecked(i - 4)) - (*inOpen.get_unchecked(i - 4))).abs() * optInPenetration && ((*inOpen.get_unchecked(i - 1))).min((*inClose.get_unchecked(i - 1))) > (*inClose.get_unchecked(i - 4)) - ((*inClose.get_unchecked(i - 4)) - (*inOpen.get_unchecked(i - 4))).abs() * optInPenetration && ((*inClose.get_unchecked(i - 2))).max((*inOpen.get_unchecked(i - 2))) < (*inOpen.get_unchecked(i - 3)) && ((*inClose.get_unchecked(i - 1))).max((*inOpen.get_unchecked(i - 1))) < ((*inClose.get_unchecked(i - 2))).max((*inOpen.get_unchecked(i - 2))) && (*inOpen.get_unchecked(i)) > (*inClose.get_unchecked(i - 1)) && (*inClose.get_unchecked(i)) > (((*inHigh.get_unchecked(i - 3))).max((*inHigh.get_unchecked(i - 2)))).max((*inHigh.get_unchecked(i - 1))) {
                (*outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = 100;
            } else {
                (*outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = 0;
            }
            let mut _candlerange_4: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_4 = ((*inClose.get_unchecked(i - 4)) - (*inOpen.get_unchecked(i - 4))).abs();
                }
                1 => {
                    _candlerange_4 = (*inHigh.get_unchecked(i - 4)) - (*inLow.get_unchecked(i - 4));
                }
                2 => {
                    _candlerange_4 = (*inHigh.get_unchecked(i - 4)) - (*inLow.get_unchecked(i - 4)) - ((*inClose.get_unchecked(i - 4)) - (*inOpen.get_unchecked(i - 4))).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            let mut _candlerange_5: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_5 = ((*inClose.get_unchecked(BodyLongTrailingIdx - 4)) - (*inOpen.get_unchecked(BodyLongTrailingIdx - 4))).abs();
                }
                1 => {
                    _candlerange_5 = (*inHigh.get_unchecked(BodyLongTrailingIdx - 4)) - (*inLow.get_unchecked(BodyLongTrailingIdx - 4));
                }
                2 => {
                    _candlerange_5 = (*inHigh.get_unchecked(BodyLongTrailingIdx - 4)) - (*inLow.get_unchecked(BodyLongTrailingIdx - 4)) - ((*inClose.get_unchecked(BodyLongTrailingIdx - 4)) - (*inOpen.get_unchecked(BodyLongTrailingIdx - 4))).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut(4)) = (*BodyPeriodTotal.get_unchecked(4)) + (_candlerange_4 - _candlerange_5);
            // for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
            totIdx = 3;
            loop {
                let mut _candlerange_6: f64;
                match BodyShort_rangeType {
                    0 => {
                        _candlerange_6 = ((*inClose.get_unchecked(i - totIdx)) - (*inOpen.get_unchecked(i - totIdx))).abs();
                    }
                    1 => {
                        _candlerange_6 = (*inHigh.get_unchecked(i - totIdx)) - (*inLow.get_unchecked(i - totIdx));
                    }
                    2 => {
                        _candlerange_6 = (*inHigh.get_unchecked(i - totIdx)) - (*inLow.get_unchecked(i - totIdx)) - ((*inClose.get_unchecked(i - totIdx)) - (*inOpen.get_unchecked(i - totIdx))).abs();
                    }
                    _ => {
                        _candlerange_6 = 0.0;
                    }
                }
                let mut _candlerange_7: f64;
                match BodyShort_rangeType {
                    0 => {
                        _candlerange_7 = ((*inClose.get_unchecked(BodyShortTrailingIdx - totIdx)) - (*inOpen.get_unchecked(BodyShortTrailingIdx - totIdx))).abs();
                    }
                    1 => {
                        _candlerange_7 = (*inHigh.get_unchecked(BodyShortTrailingIdx - totIdx)) - (*inLow.get_unchecked(BodyShortTrailingIdx - totIdx));
                    }
                    2 => {
                        _candlerange_7 = (*inHigh.get_unchecked(BodyShortTrailingIdx - totIdx)) - (*inLow.get_unchecked(BodyShortTrailingIdx - totIdx)) - ((*inClose.get_unchecked(BodyShortTrailingIdx - totIdx)) - (*inOpen.get_unchecked(BodyShortTrailingIdx - totIdx))).abs();
                    }
                    _ => {
                        _candlerange_7 = 0.0;
                    }
                }
                (*BodyPeriodTotal.get_unchecked_mut(totIdx)) = (*BodyPeriodTotal.get_unchecked(totIdx)) + (_candlerange_6 - _candlerange_7);
                if totIdx == 1 { break; }
                totIdx -= 1;
            }
            i += 1;
            BodyShortTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
