/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlrisefall3methods`].
    ///
    /// # Arguments
    ///
    pub fn cdlrisefall3methods_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        return ((BodyShort_avgPeriod).max(BodyLong_avgPeriod) + 4) as usize;
    }
    /// Rising/Falling Three Methods
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlrisefall3methods<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlrisefall3methods_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdlrisefall3methods_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyPeriodTotal: [T; 5 as usize] = [T::ta_zero(); 5 as usize];
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut BodyShortTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        lookbackTotal = self.cdlrisefall3methods_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyPeriodTotal[(4) as usize] = T::ta_from_i32(0 as i32);
        BodyPeriodTotal[(3) as usize] = T::ta_from_i32(0 as i32);
        BodyPeriodTotal[(2) as usize] = T::ta_from_i32(0 as i32);
        BodyPeriodTotal[(1) as usize] = T::ta_from_i32(0 as i32);
        BodyPeriodTotal[(0) as usize] = T::ta_from_i32(0 as i32);
        BodyShortTrailingIdx = startIdx - (BodyShort_avgPeriod) as usize;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = BodyShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_0 = (inClose[(i - 3) as usize] - inOpen[(i - 3) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_0 = inHigh[(i - 3) as usize] - inLow[(i - 3) as usize];
                }
                2 => {
                    _candlerange_0 = inHigh[(i - 3) as usize] - inLow[(i - 3) as usize] - (inClose[(i - 3) as usize] - inOpen[(i - 3) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal[(3) as usize] = BodyPeriodTotal[(3) as usize] + _candlerange_0;
            let mut _candlerange_1: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_1 = (inClose[(i - 2) as usize] - inOpen[(i - 2) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_1 = inHigh[(i - 2) as usize] - inLow[(i - 2) as usize];
                }
                2 => {
                    _candlerange_1 = inHigh[(i - 2) as usize] - inLow[(i - 2) as usize] - (inClose[(i - 2) as usize] - inOpen[(i - 2) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal[(2) as usize] = BodyPeriodTotal[(2) as usize] + _candlerange_1;
            let mut _candlerange_2: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_2 = (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_2 = inHigh[(i - 1) as usize] - inLow[(i - 1) as usize];
                }
                2 => {
                    _candlerange_2 = inHigh[(i - 1) as usize] - inLow[(i - 1) as usize] - (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal[(1) as usize] = BodyPeriodTotal[(1) as usize] + _candlerange_2;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_3 = (inClose[(i - 4) as usize] - inOpen[(i - 4) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_3 = inHigh[(i - 4) as usize] - inLow[(i - 4) as usize];
                }
                2 => {
                    _candlerange_3 = inHigh[(i - 4) as usize] - inLow[(i - 4) as usize] - (inClose[(i - 4) as usize] - inOpen[(i - 4) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal[(4) as usize] = BodyPeriodTotal[(4) as usize] + _candlerange_3;
            let mut _candlerange_4: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_4 = (inClose[(i) as usize] - inOpen[(i) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_4 = inHigh[(i) as usize] - inLow[(i) as usize];
                }
                2 => {
                    _candlerange_4 = inHigh[(i) as usize] - inLow[(i) as usize] - (inClose[(i) as usize] - inOpen[(i) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal[(0) as usize] = BodyPeriodTotal[(0) as usize] + _candlerange_4;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (inClose[(i - 4) as usize] - inOpen[(i - 4) as usize]).ta_abs() > self.ta_candleaverage(BodyLong_rangeType, BodyLong_avgPeriod, BodyLong_factor, BodyPeriodTotal[(4) as usize], inOpen[(i - 4) as usize], inHigh[(i - 4) as usize], inLow[(i - 4) as usize], inClose[(i - 4) as usize]) && (inClose[(i - 3) as usize] - inOpen[(i - 3) as usize]).ta_abs() < self.ta_candleaverage(BodyShort_rangeType, BodyShort_avgPeriod, BodyShort_factor, BodyPeriodTotal[(3) as usize], inOpen[(i - 3) as usize], inHigh[(i - 3) as usize], inLow[(i - 3) as usize], inClose[(i - 3) as usize]) && (inClose[(i - 2) as usize] - inOpen[(i - 2) as usize]).ta_abs() < self.ta_candleaverage(BodyShort_rangeType, BodyShort_avgPeriod, BodyShort_factor, BodyPeriodTotal[(2) as usize], inOpen[(i - 2) as usize], inHigh[(i - 2) as usize], inLow[(i - 2) as usize], inClose[(i - 2) as usize]) && (inClose[(i - 1) as usize] - inOpen[(i - 1) as usize]).ta_abs() < self.ta_candleaverage(BodyShort_rangeType, BodyShort_avgPeriod, BodyShort_factor, BodyPeriodTotal[(1) as usize], inOpen[(i - 1) as usize], inHigh[(i - 1) as usize], inLow[(i - 1) as usize], inClose[(i - 1) as usize]) && (inClose[(i) as usize] - inOpen[(i) as usize]).ta_abs() > self.ta_candleaverage(BodyLong_rangeType, BodyLong_avgPeriod, BodyLong_factor, BodyPeriodTotal[(0) as usize], inOpen[(i) as usize], inHigh[(i) as usize], inLow[(i) as usize], inClose[(i) as usize]) && if inClose[(i - 4) as usize] >= inOpen[(i - 4) as usize] { 1 } else { 0 - 1 } == 0 - if inClose[(i - 3) as usize] >= inOpen[(i - 3) as usize] { 1 } else { 0 - 1 } && if inClose[(i - 3) as usize] >= inOpen[(i - 3) as usize] { 1 } else { 0 - 1 } == if inClose[(i - 2) as usize] >= inOpen[(i - 2) as usize] { 1 } else { 0 - 1 } && if inClose[(i - 2) as usize] >= inOpen[(i - 2) as usize] { 1 } else { 0 - 1 } == if inClose[(i - 1) as usize] >= inOpen[(i - 1) as usize] { 1 } else { 0 - 1 } && if inClose[(i - 1) as usize] >= inOpen[(i - 1) as usize] { 1 } else { 0 - 1 } == 0 - if inClose[(i) as usize] >= inOpen[(i) as usize] { 1 } else { 0 - 1 } && (inOpen[(i - 3) as usize]).min(inClose[(i - 3) as usize]) < inHigh[(i - 4) as usize] && (inOpen[(i - 3) as usize]).max(inClose[(i - 3) as usize]) > inLow[(i - 4) as usize] && (inOpen[(i - 2) as usize]).min(inClose[(i - 2) as usize]) < inHigh[(i - 4) as usize] && (inOpen[(i - 2) as usize]).max(inClose[(i - 2) as usize]) > inLow[(i - 4) as usize] && (inOpen[(i - 1) as usize]).min(inClose[(i - 1) as usize]) < inHigh[(i - 4) as usize] && (inOpen[(i - 1) as usize]).max(inClose[(i - 1) as usize]) > inLow[(i - 4) as usize] && inClose[(i - 2) as usize] * T::ta_from_i32(if inClose[(i - 4) as usize] >= inOpen[(i - 4) as usize] { 1 } else { 0 - 1 } as i32) < inClose[(i - 3) as usize] * T::ta_from_i32(if inClose[(i - 4) as usize] >= inOpen[(i - 4) as usize] { 1 } else { 0 - 1 } as i32) && inClose[(i - 1) as usize] * T::ta_from_i32(if inClose[(i - 4) as usize] >= inOpen[(i - 4) as usize] { 1 } else { 0 - 1 } as i32) < inClose[(i - 2) as usize] * T::ta_from_i32(if inClose[(i - 4) as usize] >= inOpen[(i - 4) as usize] { 1 } else { 0 - 1 } as i32) && inOpen[(i) as usize] * T::ta_from_i32(if inClose[(i - 4) as usize] >= inOpen[(i - 4) as usize] { 1 } else { 0 - 1 } as i32) > inClose[(i - 1) as usize] * T::ta_from_i32(if inClose[(i - 4) as usize] >= inOpen[(i - 4) as usize] { 1 } else { 0 - 1 } as i32) && inClose[(i) as usize] * T::ta_from_i32(if inClose[(i - 4) as usize] >= inOpen[(i - 4) as usize] { 1 } else { 0 - 1 } as i32) > inClose[(i - 4) as usize] * T::ta_from_i32(if inClose[(i - 4) as usize] >= inOpen[(i - 4) as usize] { 1 } else { 0 - 1 } as i32) {
                outInteger[({ let _v = outIdx; outIdx += 1; _v }) as usize] = (100 * if inClose[(i - 4) as usize] >= inOpen[(i - 4) as usize] { 1 } else { 0 - 1 }) as i32;
            } else {
                outInteger[({ let _v = outIdx; outIdx += 1; _v }) as usize] = 0;
            }
            let mut _candlerange_5: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_5 = (inClose[(i - 4) as usize] - inOpen[(i - 4) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_5 = inHigh[(i - 4) as usize] - inLow[(i - 4) as usize];
                }
                2 => {
                    _candlerange_5 = inHigh[(i - 4) as usize] - inLow[(i - 4) as usize] - (inClose[(i - 4) as usize] - inOpen[(i - 4) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_6: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_6 = (inClose[(BodyLongTrailingIdx - 4) as usize] - inOpen[(BodyLongTrailingIdx - 4) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_6 = inHigh[(BodyLongTrailingIdx - 4) as usize] - inLow[(BodyLongTrailingIdx - 4) as usize];
                }
                2 => {
                    _candlerange_6 = inHigh[(BodyLongTrailingIdx - 4) as usize] - inLow[(BodyLongTrailingIdx - 4) as usize] - (inClose[(BodyLongTrailingIdx - 4) as usize] - inOpen[(BodyLongTrailingIdx - 4) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_6 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal[(4) as usize] = BodyPeriodTotal[(4) as usize] + (_candlerange_5 - _candlerange_6);
            // for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
            totIdx = 3;
            loop {
                let mut _candlerange_7: T;
                match BodyShort_rangeType {
                    0 => {
                        _candlerange_7 = (inClose[(i - totIdx) as usize] - inOpen[(i - totIdx) as usize]).ta_abs();
                    }
                    1 => {
                        _candlerange_7 = inHigh[(i - totIdx) as usize] - inLow[(i - totIdx) as usize];
                    }
                    2 => {
                        _candlerange_7 = inHigh[(i - totIdx) as usize] - inLow[(i - totIdx) as usize] - (inClose[(i - totIdx) as usize] - inOpen[(i - totIdx) as usize]).ta_abs();
                    }
                    _ => {
                        _candlerange_7 = T::ta_from_f64(0.0);
                    }
                }
                let mut _candlerange_8: T;
                match BodyShort_rangeType {
                    0 => {
                        _candlerange_8 = (inClose[(BodyShortTrailingIdx - totIdx) as usize] - inOpen[(BodyShortTrailingIdx - totIdx) as usize]).ta_abs();
                    }
                    1 => {
                        _candlerange_8 = inHigh[(BodyShortTrailingIdx - totIdx) as usize] - inLow[(BodyShortTrailingIdx - totIdx) as usize];
                    }
                    2 => {
                        _candlerange_8 = inHigh[(BodyShortTrailingIdx - totIdx) as usize] - inLow[(BodyShortTrailingIdx - totIdx) as usize] - (inClose[(BodyShortTrailingIdx - totIdx) as usize] - inOpen[(BodyShortTrailingIdx - totIdx) as usize]).ta_abs();
                    }
                    _ => {
                        _candlerange_8 = T::ta_from_f64(0.0);
                    }
                }
                BodyPeriodTotal[(totIdx) as usize] = BodyPeriodTotal[(totIdx) as usize] + (_candlerange_7 - _candlerange_8);
                if totIdx == 1 { break; }
                totIdx -= 1;
            }
            let mut _candlerange_9: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_9 = (inClose[(i) as usize] - inOpen[(i) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_9 = inHigh[(i) as usize] - inLow[(i) as usize];
                }
                2 => {
                    _candlerange_9 = inHigh[(i) as usize] - inLow[(i) as usize] - (inClose[(i) as usize] - inOpen[(i) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_9 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_10: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_10 = (inClose[(BodyLongTrailingIdx) as usize] - inOpen[(BodyLongTrailingIdx) as usize]).ta_abs();
                }
                1 => {
                    _candlerange_10 = inHigh[(BodyLongTrailingIdx) as usize] - inLow[(BodyLongTrailingIdx) as usize];
                }
                2 => {
                    _candlerange_10 = inHigh[(BodyLongTrailingIdx) as usize] - inLow[(BodyLongTrailingIdx) as usize] - (inClose[(BodyLongTrailingIdx) as usize] - inOpen[(BodyLongTrailingIdx) as usize]).ta_abs();
                }
                _ => {
                    _candlerange_10 = T::ta_from_f64(0.0);
                }
            }
            BodyPeriodTotal[(0) as usize] = BodyPeriodTotal[(0) as usize] + (_candlerange_9 - _candlerange_10);
            i += 1;
            BodyShortTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    pub unsafe fn cdlrisefall3methods_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlrisefall3methods_unguarded_unchecked(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn cdlrisefall3methods_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[T],
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyPeriodTotal: [T; 5 as usize] = [T::ta_zero(); 5 as usize];
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut BodyShortTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        lookbackTotal = self.cdlrisefall3methods_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*BodyPeriodTotal.get_unchecked_mut((4) as usize)) = T::ta_from_i32(0 as i32);
        (*BodyPeriodTotal.get_unchecked_mut((3) as usize)) = T::ta_from_i32(0 as i32);
        (*BodyPeriodTotal.get_unchecked_mut((2) as usize)) = T::ta_from_i32(0 as i32);
        (*BodyPeriodTotal.get_unchecked_mut((1) as usize)) = T::ta_from_i32(0 as i32);
        (*BodyPeriodTotal.get_unchecked_mut((0) as usize)) = T::ta_from_i32(0 as i32);
        BodyShortTrailingIdx = startIdx - (BodyShort_avgPeriod) as usize;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = BodyShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_0 = ((*inClose.get_unchecked((i - 3) as usize)) - (*inOpen.get_unchecked((i - 3) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_0 = (*inHigh.get_unchecked((i - 3) as usize)) - (*inLow.get_unchecked((i - 3) as usize));
                }
                2 => {
                    _candlerange_0 = (*inHigh.get_unchecked((i - 3) as usize)) - (*inLow.get_unchecked((i - 3) as usize)) - ((*inClose.get_unchecked((i - 3) as usize)) - (*inOpen.get_unchecked((i - 3) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_0 = T::ta_from_f64(0.0);
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut((3) as usize)) = (*BodyPeriodTotal.get_unchecked((3) as usize)) + _candlerange_0;
            let mut _candlerange_1: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_1 = ((*inClose.get_unchecked((i - 2) as usize)) - (*inOpen.get_unchecked((i - 2) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_1 = (*inHigh.get_unchecked((i - 2) as usize)) - (*inLow.get_unchecked((i - 2) as usize));
                }
                2 => {
                    _candlerange_1 = (*inHigh.get_unchecked((i - 2) as usize)) - (*inLow.get_unchecked((i - 2) as usize)) - ((*inClose.get_unchecked((i - 2) as usize)) - (*inOpen.get_unchecked((i - 2) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_1 = T::ta_from_f64(0.0);
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut((2) as usize)) = (*BodyPeriodTotal.get_unchecked((2) as usize)) + _candlerange_1;
            let mut _candlerange_2: T;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_2 = ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_2 = (*inHigh.get_unchecked((i - 1) as usize)) - (*inLow.get_unchecked((i - 1) as usize));
                }
                2 => {
                    _candlerange_2 = (*inHigh.get_unchecked((i - 1) as usize)) - (*inLow.get_unchecked((i - 1) as usize)) - ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_2 = T::ta_from_f64(0.0);
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut((1) as usize)) = (*BodyPeriodTotal.get_unchecked((1) as usize)) + _candlerange_2;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_3 = ((*inClose.get_unchecked((i - 4) as usize)) - (*inOpen.get_unchecked((i - 4) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_3 = (*inHigh.get_unchecked((i - 4) as usize)) - (*inLow.get_unchecked((i - 4) as usize));
                }
                2 => {
                    _candlerange_3 = (*inHigh.get_unchecked((i - 4) as usize)) - (*inLow.get_unchecked((i - 4) as usize)) - ((*inClose.get_unchecked((i - 4) as usize)) - (*inOpen.get_unchecked((i - 4) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_3 = T::ta_from_f64(0.0);
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut((4) as usize)) = (*BodyPeriodTotal.get_unchecked((4) as usize)) + _candlerange_3;
            let mut _candlerange_4: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_4 = ((*inClose.get_unchecked((i) as usize)) - (*inOpen.get_unchecked((i) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_4 = (*inHigh.get_unchecked((i) as usize)) - (*inLow.get_unchecked((i) as usize));
                }
                2 => {
                    _candlerange_4 = (*inHigh.get_unchecked((i) as usize)) - (*inLow.get_unchecked((i) as usize)) - ((*inClose.get_unchecked((i) as usize)) - (*inOpen.get_unchecked((i) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_4 = T::ta_from_f64(0.0);
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut((0) as usize)) = (*BodyPeriodTotal.get_unchecked((0) as usize)) + _candlerange_4;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if ((*inClose.get_unchecked((i - 4) as usize)) - (*inOpen.get_unchecked((i - 4) as usize))).ta_abs() > self.ta_candleaverage(BodyLong_rangeType, BodyLong_avgPeriod, BodyLong_factor, (*BodyPeriodTotal.get_unchecked((4) as usize)), (*inOpen.get_unchecked((i - 4) as usize)), (*inHigh.get_unchecked((i - 4) as usize)), (*inLow.get_unchecked((i - 4) as usize)), (*inClose.get_unchecked((i - 4) as usize))) && ((*inClose.get_unchecked((i - 3) as usize)) - (*inOpen.get_unchecked((i - 3) as usize))).ta_abs() < self.ta_candleaverage(BodyShort_rangeType, BodyShort_avgPeriod, BodyShort_factor, (*BodyPeriodTotal.get_unchecked((3) as usize)), (*inOpen.get_unchecked((i - 3) as usize)), (*inHigh.get_unchecked((i - 3) as usize)), (*inLow.get_unchecked((i - 3) as usize)), (*inClose.get_unchecked((i - 3) as usize))) && ((*inClose.get_unchecked((i - 2) as usize)) - (*inOpen.get_unchecked((i - 2) as usize))).ta_abs() < self.ta_candleaverage(BodyShort_rangeType, BodyShort_avgPeriod, BodyShort_factor, (*BodyPeriodTotal.get_unchecked((2) as usize)), (*inOpen.get_unchecked((i - 2) as usize)), (*inHigh.get_unchecked((i - 2) as usize)), (*inLow.get_unchecked((i - 2) as usize)), (*inClose.get_unchecked((i - 2) as usize))) && ((*inClose.get_unchecked((i - 1) as usize)) - (*inOpen.get_unchecked((i - 1) as usize))).ta_abs() < self.ta_candleaverage(BodyShort_rangeType, BodyShort_avgPeriod, BodyShort_factor, (*BodyPeriodTotal.get_unchecked((1) as usize)), (*inOpen.get_unchecked((i - 1) as usize)), (*inHigh.get_unchecked((i - 1) as usize)), (*inLow.get_unchecked((i - 1) as usize)), (*inClose.get_unchecked((i - 1) as usize))) && ((*inClose.get_unchecked((i) as usize)) - (*inOpen.get_unchecked((i) as usize))).ta_abs() > self.ta_candleaverage(BodyLong_rangeType, BodyLong_avgPeriod, BodyLong_factor, (*BodyPeriodTotal.get_unchecked((0) as usize)), (*inOpen.get_unchecked((i) as usize)), (*inHigh.get_unchecked((i) as usize)), (*inLow.get_unchecked((i) as usize)), (*inClose.get_unchecked((i) as usize))) && if (*inClose.get_unchecked((i - 4) as usize)) >= (*inOpen.get_unchecked((i - 4) as usize)) { 1 } else { 0 - 1 } == 0 - if (*inClose.get_unchecked((i - 3) as usize)) >= (*inOpen.get_unchecked((i - 3) as usize)) { 1 } else { 0 - 1 } && if (*inClose.get_unchecked((i - 3) as usize)) >= (*inOpen.get_unchecked((i - 3) as usize)) { 1 } else { 0 - 1 } == if (*inClose.get_unchecked((i - 2) as usize)) >= (*inOpen.get_unchecked((i - 2) as usize)) { 1 } else { 0 - 1 } && if (*inClose.get_unchecked((i - 2) as usize)) >= (*inOpen.get_unchecked((i - 2) as usize)) { 1 } else { 0 - 1 } == if (*inClose.get_unchecked((i - 1) as usize)) >= (*inOpen.get_unchecked((i - 1) as usize)) { 1 } else { 0 - 1 } && if (*inClose.get_unchecked((i - 1) as usize)) >= (*inOpen.get_unchecked((i - 1) as usize)) { 1 } else { 0 - 1 } == 0 - if (*inClose.get_unchecked((i) as usize)) >= (*inOpen.get_unchecked((i) as usize)) { 1 } else { 0 - 1 } && ((*inOpen.get_unchecked((i - 3) as usize))).min((*inClose.get_unchecked((i - 3) as usize))) < (*inHigh.get_unchecked((i - 4) as usize)) && ((*inOpen.get_unchecked((i - 3) as usize))).max((*inClose.get_unchecked((i - 3) as usize))) > (*inLow.get_unchecked((i - 4) as usize)) && ((*inOpen.get_unchecked((i - 2) as usize))).min((*inClose.get_unchecked((i - 2) as usize))) < (*inHigh.get_unchecked((i - 4) as usize)) && ((*inOpen.get_unchecked((i - 2) as usize))).max((*inClose.get_unchecked((i - 2) as usize))) > (*inLow.get_unchecked((i - 4) as usize)) && ((*inOpen.get_unchecked((i - 1) as usize))).min((*inClose.get_unchecked((i - 1) as usize))) < (*inHigh.get_unchecked((i - 4) as usize)) && ((*inOpen.get_unchecked((i - 1) as usize))).max((*inClose.get_unchecked((i - 1) as usize))) > (*inLow.get_unchecked((i - 4) as usize)) && (*inClose.get_unchecked((i - 2) as usize)) * T::ta_from_i32(if (*inClose.get_unchecked((i - 4) as usize)) >= (*inOpen.get_unchecked((i - 4) as usize)) { 1 } else { 0 - 1 } as i32) < (*inClose.get_unchecked((i - 3) as usize)) * T::ta_from_i32(if (*inClose.get_unchecked((i - 4) as usize)) >= (*inOpen.get_unchecked((i - 4) as usize)) { 1 } else { 0 - 1 } as i32) && (*inClose.get_unchecked((i - 1) as usize)) * T::ta_from_i32(if (*inClose.get_unchecked((i - 4) as usize)) >= (*inOpen.get_unchecked((i - 4) as usize)) { 1 } else { 0 - 1 } as i32) < (*inClose.get_unchecked((i - 2) as usize)) * T::ta_from_i32(if (*inClose.get_unchecked((i - 4) as usize)) >= (*inOpen.get_unchecked((i - 4) as usize)) { 1 } else { 0 - 1 } as i32) && (*inOpen.get_unchecked((i) as usize)) * T::ta_from_i32(if (*inClose.get_unchecked((i - 4) as usize)) >= (*inOpen.get_unchecked((i - 4) as usize)) { 1 } else { 0 - 1 } as i32) > (*inClose.get_unchecked((i - 1) as usize)) * T::ta_from_i32(if (*inClose.get_unchecked((i - 4) as usize)) >= (*inOpen.get_unchecked((i - 4) as usize)) { 1 } else { 0 - 1 } as i32) && (*inClose.get_unchecked((i) as usize)) * T::ta_from_i32(if (*inClose.get_unchecked((i - 4) as usize)) >= (*inOpen.get_unchecked((i - 4) as usize)) { 1 } else { 0 - 1 } as i32) > (*inClose.get_unchecked((i - 4) as usize)) * T::ta_from_i32(if (*inClose.get_unchecked((i - 4) as usize)) >= (*inOpen.get_unchecked((i - 4) as usize)) { 1 } else { 0 - 1 } as i32) {
                (*outInteger.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = (100 * if (*inClose.get_unchecked((i - 4) as usize)) >= (*inOpen.get_unchecked((i - 4) as usize)) { 1 } else { 0 - 1 }) as i32;
            } else {
                (*outInteger.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = 0;
            }
            let mut _candlerange_5: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_5 = ((*inClose.get_unchecked((i - 4) as usize)) - (*inOpen.get_unchecked((i - 4) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_5 = (*inHigh.get_unchecked((i - 4) as usize)) - (*inLow.get_unchecked((i - 4) as usize));
                }
                2 => {
                    _candlerange_5 = (*inHigh.get_unchecked((i - 4) as usize)) - (*inLow.get_unchecked((i - 4) as usize)) - ((*inClose.get_unchecked((i - 4) as usize)) - (*inOpen.get_unchecked((i - 4) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_5 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_6: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_6 = ((*inClose.get_unchecked((BodyLongTrailingIdx - 4) as usize)) - (*inOpen.get_unchecked((BodyLongTrailingIdx - 4) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_6 = (*inHigh.get_unchecked((BodyLongTrailingIdx - 4) as usize)) - (*inLow.get_unchecked((BodyLongTrailingIdx - 4) as usize));
                }
                2 => {
                    _candlerange_6 = (*inHigh.get_unchecked((BodyLongTrailingIdx - 4) as usize)) - (*inLow.get_unchecked((BodyLongTrailingIdx - 4) as usize)) - ((*inClose.get_unchecked((BodyLongTrailingIdx - 4) as usize)) - (*inOpen.get_unchecked((BodyLongTrailingIdx - 4) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_6 = T::ta_from_f64(0.0);
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut((4) as usize)) = (*BodyPeriodTotal.get_unchecked((4) as usize)) + (_candlerange_5 - _candlerange_6);
            // for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
            totIdx = 3;
            loop {
                let mut _candlerange_7: T;
                match BodyShort_rangeType {
                    0 => {
                        _candlerange_7 = ((*inClose.get_unchecked((i - totIdx) as usize)) - (*inOpen.get_unchecked((i - totIdx) as usize))).ta_abs();
                    }
                    1 => {
                        _candlerange_7 = (*inHigh.get_unchecked((i - totIdx) as usize)) - (*inLow.get_unchecked((i - totIdx) as usize));
                    }
                    2 => {
                        _candlerange_7 = (*inHigh.get_unchecked((i - totIdx) as usize)) - (*inLow.get_unchecked((i - totIdx) as usize)) - ((*inClose.get_unchecked((i - totIdx) as usize)) - (*inOpen.get_unchecked((i - totIdx) as usize))).ta_abs();
                    }
                    _ => {
                        _candlerange_7 = T::ta_from_f64(0.0);
                    }
                }
                let mut _candlerange_8: T;
                match BodyShort_rangeType {
                    0 => {
                        _candlerange_8 = ((*inClose.get_unchecked((BodyShortTrailingIdx - totIdx) as usize)) - (*inOpen.get_unchecked((BodyShortTrailingIdx - totIdx) as usize))).ta_abs();
                    }
                    1 => {
                        _candlerange_8 = (*inHigh.get_unchecked((BodyShortTrailingIdx - totIdx) as usize)) - (*inLow.get_unchecked((BodyShortTrailingIdx - totIdx) as usize));
                    }
                    2 => {
                        _candlerange_8 = (*inHigh.get_unchecked((BodyShortTrailingIdx - totIdx) as usize)) - (*inLow.get_unchecked((BodyShortTrailingIdx - totIdx) as usize)) - ((*inClose.get_unchecked((BodyShortTrailingIdx - totIdx) as usize)) - (*inOpen.get_unchecked((BodyShortTrailingIdx - totIdx) as usize))).ta_abs();
                    }
                    _ => {
                        _candlerange_8 = T::ta_from_f64(0.0);
                    }
                }
                (*BodyPeriodTotal.get_unchecked_mut((totIdx) as usize)) = (*BodyPeriodTotal.get_unchecked((totIdx) as usize)) + (_candlerange_7 - _candlerange_8);
                if totIdx == 1 { break; }
                totIdx -= 1;
            }
            let mut _candlerange_9: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_9 = ((*inClose.get_unchecked((i) as usize)) - (*inOpen.get_unchecked((i) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_9 = (*inHigh.get_unchecked((i) as usize)) - (*inLow.get_unchecked((i) as usize));
                }
                2 => {
                    _candlerange_9 = (*inHigh.get_unchecked((i) as usize)) - (*inLow.get_unchecked((i) as usize)) - ((*inClose.get_unchecked((i) as usize)) - (*inOpen.get_unchecked((i) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_9 = T::ta_from_f64(0.0);
                }
            }
            let mut _candlerange_10: T;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_10 = ((*inClose.get_unchecked((BodyLongTrailingIdx) as usize)) - (*inOpen.get_unchecked((BodyLongTrailingIdx) as usize))).ta_abs();
                }
                1 => {
                    _candlerange_10 = (*inHigh.get_unchecked((BodyLongTrailingIdx) as usize)) - (*inLow.get_unchecked((BodyLongTrailingIdx) as usize));
                }
                2 => {
                    _candlerange_10 = (*inHigh.get_unchecked((BodyLongTrailingIdx) as usize)) - (*inLow.get_unchecked((BodyLongTrailingIdx) as usize)) - ((*inClose.get_unchecked((BodyLongTrailingIdx) as usize)) - (*inOpen.get_unchecked((BodyLongTrailingIdx) as usize))).ta_abs();
                }
                _ => {
                    _candlerange_10 = T::ta_from_f64(0.0);
                }
            }
            (*BodyPeriodTotal.get_unchecked_mut((0) as usize)) = (*BodyPeriodTotal.get_unchecked((0) as usize)) + (_candlerange_9 - _candlerange_10);
            i += 1;
            BodyShortTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
