/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlshootingstar`].
    ///
    /// # Arguments
    ///
    pub fn cdlshootingstar_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let ShadowLong_rangeType: i32 = self.candle_settings.shadow_long.range_type;
        #[allow(non_snake_case)]
        let ShadowLong_avgPeriod: i32 = self.candle_settings.shadow_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowLong_factor: f64 = self.candle_settings.shadow_long.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        return (((BodyShort_avgPeriod).max(ShadowLong_avgPeriod)).max(ShadowVeryShort_avgPeriod) + 1) as usize;
    }
    /// Shooting Star
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlshootingstar(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.cdlshootingstar_unguarded(
            startIdx,
            endIdx,
            inOpen,
            inHigh,
            inLow,
            inClose,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn cdlshootingstar_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyPeriodTotal: f64 = 0.0_f64;
        let mut ShadowLongPeriodTotal: f64 = 0.0_f64;
        let mut ShadowVeryShortPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut BodyTrailingIdx: usize = 0_usize;
        let mut ShadowLongTrailingIdx: usize = 0_usize;
        let mut ShadowVeryShortTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        #[allow(non_snake_case)]
        let ShadowLong_rangeType: i32 = self.candle_settings.shadow_long.range_type;
        #[allow(non_snake_case)]
        let ShadowLong_avgPeriod: i32 = self.candle_settings.shadow_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowLong_factor: f64 = self.candle_settings.shadow_long.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        lookbackTotal = self.cdlshootingstar_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyPeriodTotal = 0.0;
        BodyTrailingIdx = startIdx - (BodyShort_avgPeriod) as usize;
        ShadowLongPeriodTotal = 0.0;
        ShadowLongTrailingIdx = startIdx - (ShadowLong_avgPeriod) as usize;
        ShadowVeryShortPeriodTotal = 0.0;
        ShadowVeryShortTrailingIdx = startIdx - (ShadowVeryShort_avgPeriod) as usize;
        i = BodyTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_0 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_0 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_0 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = ShadowLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_1 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_1 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_1 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            ShadowLongPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_2: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_2 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_2 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_2 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            ShadowVeryShortPeriodTotal += _candlerange_2;
            i += 1;
        }
        outIdx = 0;
        loop {
            if ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() < { let _cr = match BodyShort_rangeType { 0 => ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs(), 1 => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)), _ => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() }; let _avg = if BodyShort_avgPeriod != 0 { (BodyPeriodTotal) / (BodyShort_avgPeriod as f64) } else { _cr }; let _div = if BodyShort_rangeType == 2 { 2.0 } else { 1.0 }; (BodyShort_factor) * _avg / _div } && ((*inHigh.get_unchecked(i)) - (if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { (*inClose.get_unchecked(i)) } else { (*inOpen.get_unchecked(i)) })) > { let _cr = match ShadowLong_rangeType { 0 => ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs(), 1 => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)), _ => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() }; let _avg = if ShadowLong_avgPeriod != 0 { (ShadowLongPeriodTotal) / (ShadowLong_avgPeriod as f64) } else { _cr }; let _div = if ShadowLong_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowLong_factor) * _avg / _div } && ((if (*inClose.get_unchecked(i)) >= (*inOpen.get_unchecked(i)) { (*inOpen.get_unchecked(i)) } else { (*inClose.get_unchecked(i)) }) - (*inLow.get_unchecked(i))) < { let _cr = match ShadowVeryShort_rangeType { 0 => ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs(), 1 => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)), _ => (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs() }; let _avg = if ShadowVeryShort_avgPeriod != 0 { (ShadowVeryShortPeriodTotal) / (ShadowVeryShort_avgPeriod as f64) } else { _cr }; let _div = if ShadowVeryShort_rangeType == 2 { 2.0 } else { 1.0 }; (ShadowVeryShort_factor) * _avg / _div } && ((if ((*inOpen.get_unchecked(i))).min((*inClose.get_unchecked(i))) > ((*inOpen.get_unchecked(i - 1))).max((*inClose.get_unchecked(i - 1))) { 1 } else { 0 }) != 0) {
                (*outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = (0 - 100) as i32;
            } else {
                (*outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = 0;
            }
            let mut _candlerange_3: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_3 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_3 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_3 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            let mut _candlerange_4: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_4 = ((*inClose.get_unchecked(BodyTrailingIdx)) - (*inOpen.get_unchecked(BodyTrailingIdx))).abs();
                }
                1 => {
                    _candlerange_4 = (*inHigh.get_unchecked(BodyTrailingIdx)) - (*inLow.get_unchecked(BodyTrailingIdx));
                }
                2 => {
                    _candlerange_4 = (*inHigh.get_unchecked(BodyTrailingIdx)) - (*inLow.get_unchecked(BodyTrailingIdx)) - ((*inClose.get_unchecked(BodyTrailingIdx)) - (*inOpen.get_unchecked(BodyTrailingIdx))).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            BodyPeriodTotal += _candlerange_3 - _candlerange_4;
            let mut _candlerange_5: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_5 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_5 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_5 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            let mut _candlerange_6: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_6 = ((*inClose.get_unchecked(ShadowLongTrailingIdx)) - (*inOpen.get_unchecked(ShadowLongTrailingIdx))).abs();
                }
                1 => {
                    _candlerange_6 = (*inHigh.get_unchecked(ShadowLongTrailingIdx)) - (*inLow.get_unchecked(ShadowLongTrailingIdx));
                }
                2 => {
                    _candlerange_6 = (*inHigh.get_unchecked(ShadowLongTrailingIdx)) - (*inLow.get_unchecked(ShadowLongTrailingIdx)) - ((*inClose.get_unchecked(ShadowLongTrailingIdx)) - (*inOpen.get_unchecked(ShadowLongTrailingIdx))).abs();
                }
                _ => {
                    _candlerange_6 = 0.0;
                }
            }
            ShadowLongPeriodTotal += _candlerange_5 - _candlerange_6;
            let mut _candlerange_7: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_7 = ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                1 => {
                    _candlerange_7 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i));
                }
                2 => {
                    _candlerange_7 = (*inHigh.get_unchecked(i)) - (*inLow.get_unchecked(i)) - ((*inClose.get_unchecked(i)) - (*inOpen.get_unchecked(i))).abs();
                }
                _ => {
                    _candlerange_7 = 0.0;
                }
            }
            let mut _candlerange_8: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_8 = ((*inClose.get_unchecked(ShadowVeryShortTrailingIdx)) - (*inOpen.get_unchecked(ShadowVeryShortTrailingIdx))).abs();
                }
                1 => {
                    _candlerange_8 = (*inHigh.get_unchecked(ShadowVeryShortTrailingIdx)) - (*inLow.get_unchecked(ShadowVeryShortTrailingIdx));
                }
                2 => {
                    _candlerange_8 = (*inHigh.get_unchecked(ShadowVeryShortTrailingIdx)) - (*inLow.get_unchecked(ShadowVeryShortTrailingIdx)) - ((*inClose.get_unchecked(ShadowVeryShortTrailingIdx)) - (*inOpen.get_unchecked(ShadowVeryShortTrailingIdx))).abs();
                }
                _ => {
                    _candlerange_8 = 0.0;
                }
            }
            ShadowVeryShortPeriodTotal += _candlerange_7 - _candlerange_8;
            i += 1;
            BodyTrailingIdx += 1;
            ShadowLongTrailingIdx += 1;
            ShadowVeryShortTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
