/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::correl`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 1..=100000)
    pub fn correl_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod - 1) as usize;
    }
    /// Pearson's Correlation Coefficient (r)
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal0` - Input price series
    /// * `inReal1` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn correl<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal0: &[T],
        inReal1: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.correl_unguarded(
            startIdx,
            endIdx,
            inReal0,
            inReal1,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn correl_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal0: &[T],
        inReal1: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut sumXY: T = T::ta_zero();
        let mut sumX: T = T::ta_zero();
        let mut sumY: T = T::ta_zero();
        let mut sumX2: T = T::ta_zero();
        let mut sumY2: T = T::ta_zero();
        let mut x: T = T::ta_zero();
        let mut y: T = T::ta_zero();
        let mut trailingX: T = T::ta_zero();
        let mut trailingY: T = T::ta_zero();
        let mut tempReal: T = T::ta_zero();
        let mut lookbackTotal: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        trailingIdx = startIdx - lookbackTotal;
        sumY2 = T::ta_from_f64(0.0);
        sumX2 = sumY2;
        sumY = sumX2;
        sumX = sumY;
        sumXY = sumX;
        for today in (trailingIdx as usize)..=(startIdx as usize) {
            x = inReal0[(today) as usize];
            sumX += x;
            sumX2 += x * x;
            y = inReal1[(today) as usize];
            sumXY += x * y;
            sumY += y;
            sumY2 += y * y;
        }
        today = (startIdx as usize) + 1;
        trailingX = inReal0[(trailingIdx) as usize];
        trailingY = inReal1[({ let _v = trailingIdx; trailingIdx += 1; _v }) as usize];
        tempReal = (sumX2 - sumX * sumX / T::ta_from_i32(optInTimePeriod)) * (sumY2 - sumY * sumY / T::ta_from_i32(optInTimePeriod));
        if !(tempReal < T::ta_from_f64(0.00000001)) {
            outReal[(0) as usize] = (sumXY - sumX * sumY / T::ta_from_i32(optInTimePeriod)) / tempReal.ta_sqrt();
        } else {
            outReal[(0) as usize] = T::ta_from_f64(0.0);
        }
        outIdx = 1;
        while today <= endIdx {
            sumX -= trailingX;
            sumX2 -= trailingX * trailingX;
            sumXY -= trailingX * trailingY;
            sumY -= trailingY;
            sumY2 -= trailingY * trailingY;
            x = inReal0[(today) as usize];
            sumX += x;
            sumX2 += x * x;
            y = inReal1[({ let _v = today; today += 1; _v }) as usize];
            sumXY += x * y;
            sumY += y;
            sumY2 += y * y;
            trailingX = inReal0[(trailingIdx) as usize];
            trailingY = inReal1[({ let _v = trailingIdx; trailingIdx += 1; _v }) as usize];
            tempReal = (sumX2 - sumX * sumX / T::ta_from_i32(optInTimePeriod)) * (sumY2 - sumY * sumY / T::ta_from_i32(optInTimePeriod));
            if !(tempReal < T::ta_from_f64(0.00000001)) {
                outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = (sumXY - sumX * sumY / T::ta_from_i32(optInTimePeriod)) / tempReal.ta_sqrt();
            } else {
                outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = T::ta_from_f64(0.0);
            }
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    pub unsafe fn correl_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal0: &[T],
        inReal1: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.correl_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal0,
            inReal1,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn correl_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal0: &[T],
        inReal1: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut sumXY: T = T::ta_zero();
        let mut sumX: T = T::ta_zero();
        let mut sumY: T = T::ta_zero();
        let mut sumX2: T = T::ta_zero();
        let mut sumY2: T = T::ta_zero();
        let mut x: T = T::ta_zero();
        let mut y: T = T::ta_zero();
        let mut trailingX: T = T::ta_zero();
        let mut trailingY: T = T::ta_zero();
        let mut tempReal: T = T::ta_zero();
        let mut lookbackTotal: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        trailingIdx = startIdx - lookbackTotal;
        sumY2 = T::ta_from_f64(0.0);
        sumX2 = sumY2;
        sumY = sumX2;
        sumX = sumY;
        sumXY = sumX;
        for today in (trailingIdx as usize)..=(startIdx as usize) {
            x = (*inReal0.get_unchecked((today) as usize));
            sumX += x;
            sumX2 += x * x;
            y = (*inReal1.get_unchecked((today) as usize));
            sumXY += x * y;
            sumY += y;
            sumY2 += y * y;
        }
        today = (startIdx as usize) + 1;
        trailingX = (*inReal0.get_unchecked((trailingIdx) as usize));
        trailingY = (*inReal1.get_unchecked(({ let _v = trailingIdx; trailingIdx += 1; _v }) as usize));
        tempReal = (sumX2 - sumX * sumX / T::ta_from_i32(optInTimePeriod)) * (sumY2 - sumY * sumY / T::ta_from_i32(optInTimePeriod));
        if !(tempReal < T::ta_from_f64(0.00000001)) {
            (*outReal.get_unchecked_mut((0) as usize)) = (sumXY - sumX * sumY / T::ta_from_i32(optInTimePeriod)) / tempReal.ta_sqrt();
        } else {
            (*outReal.get_unchecked_mut((0) as usize)) = T::ta_from_f64(0.0);
        }
        outIdx = 1;
        while today <= endIdx {
            sumX -= trailingX;
            sumX2 -= trailingX * trailingX;
            sumXY -= trailingX * trailingY;
            sumY -= trailingY;
            sumY2 -= trailingY * trailingY;
            x = (*inReal0.get_unchecked((today) as usize));
            sumX += x;
            sumX2 += x * x;
            y = (*inReal1.get_unchecked(({ let _v = today; today += 1; _v }) as usize));
            sumXY += x * y;
            sumY += y;
            sumY2 += y * y;
            trailingX = (*inReal0.get_unchecked((trailingIdx) as usize));
            trailingY = (*inReal1.get_unchecked(({ let _v = trailingIdx; trailingIdx += 1; _v }) as usize));
            tempReal = (sumX2 - sumX * sumX / T::ta_from_i32(optInTimePeriod)) * (sumY2 - sumY * sumY / T::ta_from_i32(optInTimePeriod));
            if !(tempReal < T::ta_from_f64(0.00000001)) {
                (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = (sumXY - sumX * sumY / T::ta_from_i32(optInTimePeriod)) / tempReal.ta_sqrt();
            } else {
                (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = T::ta_from_f64(0.0);
            }
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
