/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::dx`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    pub fn dx_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        if optInTimePeriod > 1 {
            return (optInTimePeriod + self.unstable_period[FuncUnstId::Dx as usize]) as usize;
        } else {
            return (2) as usize;
        }
    }
    /// Directional Movement Index
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn dx<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.dx_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn dx_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut today: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut prevHigh: T = T::ta_zero();
        let mut prevLow: T = T::ta_zero();
        let mut prevClose: T = T::ta_zero();
        let mut prevMinusDM: T = T::ta_zero();
        let mut prevPlusDM: T = T::ta_zero();
        let mut prevTR: T = T::ta_zero();
        let mut tempReal: T = T::ta_zero();
        let tempReal2: T = T::ta_zero();
        let mut diffP: T = T::ta_zero();
        let mut diffM: T = T::ta_zero();
        let mut minusDI: T = T::ta_zero();
        let mut plusDI: T = T::ta_zero();
        let mut i: usize = 0_usize;
        if optInTimePeriod > 1 {
            lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::Dx as usize]) as usize;
        } else {
            lookbackTotal = 2;
        }
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx;
        (*outBegIdx) = today;
        prevMinusDM = T::ta_from_f64(0.0);
        prevPlusDM = T::ta_from_f64(0.0);
        prevTR = T::ta_from_f64(0.0);
        today = startIdx - lookbackTotal;
        prevHigh = inHigh[(today) as usize];
        prevLow = inLow[(today) as usize];
        prevClose = inClose[(today) as usize];
        i = (optInTimePeriod - 1) as usize;
        while { let _v = i; i -= 1; _v } > 0 {
            today += 1;
            tempReal = inHigh[(today) as usize];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[(today) as usize];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > T::ta_from_i32(0) && diffP < diffM {
                prevMinusDM += diffM;
            } else if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM += diffP;
            }
            let mut _true_range_0: T;
            let mut range_0: T = prevHigh - prevLow;
            let mut tmp_0: T = (prevHigh - prevClose).ta_abs();
            if tmp_0 > range_0 {
                range_0 = tmp_0;
            }
            tmp_0 = (prevLow - prevClose).ta_abs();
            if tmp_0 > range_0 {
                range_0 = tmp_0;
            }
            _true_range_0 = range_0;
            tempReal = _true_range_0;
            prevTR += tempReal;
            prevClose = inClose[(today) as usize];
        }
        i = (self.unstable_period[FuncUnstId::Dx as usize] + 1) as usize;
        while { let _v = i; i -= 1; _v } != 0 {
            today += 1;
            tempReal = inHigh[(today) as usize];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[(today) as usize];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            prevMinusDM -= prevMinusDM / T::ta_from_i32(optInTimePeriod);
            prevPlusDM -= prevPlusDM / T::ta_from_i32(optInTimePeriod);
            if diffM > T::ta_from_i32(0) && diffP < diffM {
                prevMinusDM += diffM;
            } else if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM += diffP;
            }
            let mut _true_range_1: T;
            let mut range_1: T = prevHigh - prevLow;
            let mut tmp_1: T = (prevHigh - prevClose).ta_abs();
            if tmp_1 > range_1 {
                range_1 = tmp_1;
            }
            tmp_1 = (prevLow - prevClose).ta_abs();
            if tmp_1 > range_1 {
                range_1 = tmp_1;
            }
            _true_range_1 = range_1;
            tempReal = _true_range_1;
            prevTR = prevTR - prevTR / T::ta_from_i32(optInTimePeriod) + tempReal;
            prevClose = inClose[(today) as usize];
        }
        if !(T::ta_from_i32(0) - T::ta_from_f64(0.00000001) < prevTR && prevTR < T::ta_from_f64(0.00000001)) {
            minusDI = (T::ta_from_f64(100.0) * (prevMinusDM / prevTR));
            plusDI = (T::ta_from_f64(100.0) * (prevPlusDM / prevTR));
            tempReal = minusDI + plusDI;
            if !(T::ta_from_i32(0) - T::ta_from_f64(0.00000001) < tempReal && tempReal < T::ta_from_f64(0.00000001)) {
                outReal[(0) as usize] = (T::ta_from_f64(100.0) * ((minusDI - plusDI).ta_abs() / tempReal));
            } else {
                outReal[(0) as usize] = T::ta_from_f64(0.0);
            }
        } else {
            outReal[(0) as usize] = T::ta_from_f64(0.0);
        }
        outIdx = 1;
        while today < endIdx {
            today += 1;
            tempReal = inHigh[(today) as usize];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[(today) as usize];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            prevMinusDM -= prevMinusDM / T::ta_from_i32(optInTimePeriod);
            prevPlusDM -= prevPlusDM / T::ta_from_i32(optInTimePeriod);
            if diffM > T::ta_from_i32(0) && diffP < diffM {
                prevMinusDM += diffM;
            } else if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM += diffP;
            }
            let mut _true_range_2: T;
            let mut range_2: T = prevHigh - prevLow;
            let mut tmp_2: T = (prevHigh - prevClose).ta_abs();
            if tmp_2 > range_2 {
                range_2 = tmp_2;
            }
            tmp_2 = (prevLow - prevClose).ta_abs();
            if tmp_2 > range_2 {
                range_2 = tmp_2;
            }
            _true_range_2 = range_2;
            tempReal = _true_range_2;
            prevTR = prevTR - prevTR / T::ta_from_i32(optInTimePeriod) + tempReal;
            prevClose = inClose[(today) as usize];
            if !(T::ta_from_i32(0) - T::ta_from_f64(0.00000001) < prevTR && prevTR < T::ta_from_f64(0.00000001)) {
                minusDI = (T::ta_from_f64(100.0) * (prevMinusDM / prevTR));
                plusDI = (T::ta_from_f64(100.0) * (prevPlusDM / prevTR));
                tempReal = minusDI + plusDI;
                if !(T::ta_from_i32(0) - T::ta_from_f64(0.00000001) < tempReal && tempReal < T::ta_from_f64(0.00000001)) {
                    outReal[(outIdx) as usize] = (T::ta_from_f64(100.0) * ((minusDI - plusDI).ta_abs() / tempReal));
                } else {
                    outReal[(outIdx) as usize] = outReal[(outIdx - 1) as usize];
                }
            } else {
                outReal[(outIdx) as usize] = outReal[(outIdx - 1) as usize];
            }
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    pub unsafe fn dx_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.dx_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn dx_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut today: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut prevHigh: T = T::ta_zero();
        let mut prevLow: T = T::ta_zero();
        let mut prevClose: T = T::ta_zero();
        let mut prevMinusDM: T = T::ta_zero();
        let mut prevPlusDM: T = T::ta_zero();
        let mut prevTR: T = T::ta_zero();
        let mut tempReal: T = T::ta_zero();
        let tempReal2: T = T::ta_zero();
        let mut diffP: T = T::ta_zero();
        let mut diffM: T = T::ta_zero();
        let mut minusDI: T = T::ta_zero();
        let mut plusDI: T = T::ta_zero();
        let mut i: usize = 0_usize;
        if optInTimePeriod > 1 {
            lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::Dx as usize]) as usize;
        } else {
            lookbackTotal = 2;
        }
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx;
        (*outBegIdx) = today;
        prevMinusDM = T::ta_from_f64(0.0);
        prevPlusDM = T::ta_from_f64(0.0);
        prevTR = T::ta_from_f64(0.0);
        today = startIdx - lookbackTotal;
        prevHigh = (*inHigh.get_unchecked((today) as usize));
        prevLow = (*inLow.get_unchecked((today) as usize));
        prevClose = (*inClose.get_unchecked((today) as usize));
        i = (optInTimePeriod - 1) as usize;
        while { let _v = i; i -= 1; _v } > 0 {
            today += 1;
            tempReal = (*inHigh.get_unchecked((today) as usize));
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = (*inLow.get_unchecked((today) as usize));
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > T::ta_from_i32(0) && diffP < diffM {
                prevMinusDM += diffM;
            } else if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM += diffP;
            }
            let mut _true_range_0: T;
            let mut range_0: T = prevHigh - prevLow;
            let mut tmp_0: T = (prevHigh - prevClose).ta_abs();
            if tmp_0 > range_0 {
                range_0 = tmp_0;
            }
            tmp_0 = (prevLow - prevClose).ta_abs();
            if tmp_0 > range_0 {
                range_0 = tmp_0;
            }
            _true_range_0 = range_0;
            tempReal = _true_range_0;
            prevTR += tempReal;
            prevClose = (*inClose.get_unchecked((today) as usize));
        }
        i = (self.unstable_period[FuncUnstId::Dx as usize] + 1) as usize;
        while { let _v = i; i -= 1; _v } != 0 {
            today += 1;
            tempReal = (*inHigh.get_unchecked((today) as usize));
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = (*inLow.get_unchecked((today) as usize));
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            prevMinusDM -= prevMinusDM / T::ta_from_i32(optInTimePeriod);
            prevPlusDM -= prevPlusDM / T::ta_from_i32(optInTimePeriod);
            if diffM > T::ta_from_i32(0) && diffP < diffM {
                prevMinusDM += diffM;
            } else if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM += diffP;
            }
            let mut _true_range_1: T;
            let mut range_1: T = prevHigh - prevLow;
            let mut tmp_1: T = (prevHigh - prevClose).ta_abs();
            if tmp_1 > range_1 {
                range_1 = tmp_1;
            }
            tmp_1 = (prevLow - prevClose).ta_abs();
            if tmp_1 > range_1 {
                range_1 = tmp_1;
            }
            _true_range_1 = range_1;
            tempReal = _true_range_1;
            prevTR = prevTR - prevTR / T::ta_from_i32(optInTimePeriod) + tempReal;
            prevClose = (*inClose.get_unchecked((today) as usize));
        }
        if !(T::ta_from_i32(0) - T::ta_from_f64(0.00000001) < prevTR && prevTR < T::ta_from_f64(0.00000001)) {
            minusDI = (T::ta_from_f64(100.0) * (prevMinusDM / prevTR));
            plusDI = (T::ta_from_f64(100.0) * (prevPlusDM / prevTR));
            tempReal = minusDI + plusDI;
            if !(T::ta_from_i32(0) - T::ta_from_f64(0.00000001) < tempReal && tempReal < T::ta_from_f64(0.00000001)) {
                (*outReal.get_unchecked_mut((0) as usize)) = (T::ta_from_f64(100.0) * ((minusDI - plusDI).ta_abs() / tempReal));
            } else {
                (*outReal.get_unchecked_mut((0) as usize)) = T::ta_from_f64(0.0);
            }
        } else {
            (*outReal.get_unchecked_mut((0) as usize)) = T::ta_from_f64(0.0);
        }
        outIdx = 1;
        while today < endIdx {
            today += 1;
            tempReal = (*inHigh.get_unchecked((today) as usize));
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = (*inLow.get_unchecked((today) as usize));
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            prevMinusDM -= prevMinusDM / T::ta_from_i32(optInTimePeriod);
            prevPlusDM -= prevPlusDM / T::ta_from_i32(optInTimePeriod);
            if diffM > T::ta_from_i32(0) && diffP < diffM {
                prevMinusDM += diffM;
            } else if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM += diffP;
            }
            let mut _true_range_2: T;
            let mut range_2: T = prevHigh - prevLow;
            let mut tmp_2: T = (prevHigh - prevClose).ta_abs();
            if tmp_2 > range_2 {
                range_2 = tmp_2;
            }
            tmp_2 = (prevLow - prevClose).ta_abs();
            if tmp_2 > range_2 {
                range_2 = tmp_2;
            }
            _true_range_2 = range_2;
            tempReal = _true_range_2;
            prevTR = prevTR - prevTR / T::ta_from_i32(optInTimePeriod) + tempReal;
            prevClose = (*inClose.get_unchecked((today) as usize));
            if !(T::ta_from_i32(0) - T::ta_from_f64(0.00000001) < prevTR && prevTR < T::ta_from_f64(0.00000001)) {
                minusDI = (T::ta_from_f64(100.0) * (prevMinusDM / prevTR));
                plusDI = (T::ta_from_f64(100.0) * (prevPlusDM / prevTR));
                tempReal = minusDI + plusDI;
                if !(T::ta_from_i32(0) - T::ta_from_f64(0.00000001) < tempReal && tempReal < T::ta_from_f64(0.00000001)) {
                    (*outReal.get_unchecked_mut((outIdx) as usize)) = (T::ta_from_f64(100.0) * ((minusDI - plusDI).ta_abs() / tempReal));
                } else {
                    (*outReal.get_unchecked_mut((outIdx) as usize)) = (*outReal.get_unchecked((outIdx - 1) as usize));
                }
            } else {
                (*outReal.get_unchecked_mut((outIdx) as usize)) = (*outReal.get_unchecked((outIdx - 1) as usize));
            }
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
