/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::mfi`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    pub fn mfi_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod + self.unstable_period[FuncUnstId::Mfi as usize]) as usize;
    }
    /// Money Flow Index
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `inVolume` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn mfi<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        inVolume: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.mfi_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            inVolume,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn mfi_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        inVolume: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut posSumMF: T = T::ta_zero();
        let mut negSumMF: T = T::ta_zero();
        let mut prevValue: T = T::ta_zero();
        let mut tempValue1: T = T::ta_zero();
        let mut tempValue2: T = T::ta_zero();
        let mut lookbackTotal: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut mflow_positive: [T; 50 as usize] = [T::ta_zero(); 50 as usize];
        let mut mflow_negative: [T; 50 as usize] = [T::ta_zero(); 50 as usize];
        let mut mflow_Idx: usize = 0_usize;
        mflow_Idx = 0;
        {
            let _n = ((optInTimePeriod) as usize * 1) as usize;
            let _si = (0) as usize;
            mflow_positive[_si.._si + _n].fill(T::ta_zero());
        };
        {
            let _n = ((optInTimePeriod) as usize * 1) as usize;
            let _si = (0) as usize;
            mflow_negative[_si.._si + _n].fill(T::ta_zero());
        };
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::Mfi as usize]) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx - lookbackTotal;
        prevValue = (inHigh[(today) as usize] + inLow[(today) as usize] + inClose[(today) as usize]) / T::ta_from_f64(3.0);
        posSumMF = T::ta_from_f64(0.0);
        negSumMF = T::ta_from_f64(0.0);
        today += 1;
        // for( i = (optInTimePeriod) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod) as usize;
        while i > 0 {
            tempValue1 = (inHigh[(today) as usize] + inLow[(today) as usize] + inClose[(today) as usize]) / T::ta_from_f64(3.0);
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            tempValue1 *= inVolume[({ let _v = today; today += 1; _v }) as usize];
            if tempValue2 < T::ta_from_i32(0) {
                mflow_negative[(mflow_Idx) as usize] = tempValue1;
                negSumMF += tempValue1;
                mflow_positive[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
            } else if tempValue2 > T::ta_from_i32(0) {
                mflow_positive[(mflow_Idx) as usize] = tempValue1;
                posSumMF += tempValue1;
                mflow_negative[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
            } else {
                mflow_positive[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
                mflow_negative[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
            }
            mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
            i -= 1;
        }
        if today > startIdx {
            tempValue1 = posSumMF + negSumMF;
            if tempValue1 < T::ta_from_f64(1.0) {
                outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = T::ta_from_f64(0.0);
            } else {
                outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = T::ta_from_f64(100.0) * (posSumMF / tempValue1);
            }
        } else {
            while today < startIdx {
                posSumMF -= mflow_positive[(mflow_Idx) as usize];
                negSumMF -= mflow_negative[(mflow_Idx) as usize];
                tempValue1 = (inHigh[(today) as usize] + inLow[(today) as usize] + inClose[(today) as usize]) / T::ta_from_f64(3.0);
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                tempValue1 *= inVolume[({ let _v = today; today += 1; _v }) as usize];
                if tempValue2 < T::ta_from_i32(0) {
                    mflow_negative[(mflow_Idx) as usize] = tempValue1;
                    negSumMF += tempValue1;
                    mflow_positive[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
                } else if tempValue2 > T::ta_from_i32(0) {
                    mflow_positive[(mflow_Idx) as usize] = tempValue1;
                    posSumMF += tempValue1;
                    mflow_negative[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
                } else {
                    mflow_positive[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
                    mflow_negative[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
                }
                mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
            }
        }
        while today <= endIdx {
            posSumMF -= mflow_positive[(mflow_Idx) as usize];
            negSumMF -= mflow_negative[(mflow_Idx) as usize];
            tempValue1 = (inHigh[(today) as usize] + inLow[(today) as usize] + inClose[(today) as usize]) / T::ta_from_f64(3.0);
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            tempValue1 *= inVolume[({ let _v = today; today += 1; _v }) as usize];
            if tempValue2 < T::ta_from_i32(0) {
                mflow_negative[(mflow_Idx) as usize] = tempValue1;
                negSumMF += tempValue1;
                mflow_positive[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
            } else if tempValue2 > T::ta_from_i32(0) {
                mflow_positive[(mflow_Idx) as usize] = tempValue1;
                posSumMF += tempValue1;
                mflow_negative[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
            } else {
                mflow_positive[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
                mflow_negative[(mflow_Idx) as usize] = T::ta_from_f64(0.0);
            }
            tempValue1 = posSumMF + negSumMF;
            if tempValue1 < T::ta_from_f64(1.0) {
                outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = T::ta_from_f64(0.0);
            } else {
                outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = T::ta_from_f64(100.0) * (posSumMF / tempValue1);
            }
            mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    pub unsafe fn mfi_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        inVolume: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.mfi_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            inClose,
            inVolume,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn mfi_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        inClose: &[T],
        inVolume: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut posSumMF: T = T::ta_zero();
        let mut negSumMF: T = T::ta_zero();
        let mut prevValue: T = T::ta_zero();
        let mut tempValue1: T = T::ta_zero();
        let mut tempValue2: T = T::ta_zero();
        let mut lookbackTotal: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut mflow_positive: [T; 50 as usize] = [T::ta_zero(); 50 as usize];
        let mut mflow_negative: [T; 50 as usize] = [T::ta_zero(); 50 as usize];
        let mut mflow_Idx: usize = 0_usize;
        mflow_Idx = 0;
        {
            let _n = ((optInTimePeriod) as usize * 1) as usize;
            let _si = (0) as usize;
            mflow_positive[_si.._si + _n].fill(T::ta_zero());
        };
        {
            let _n = ((optInTimePeriod) as usize * 1) as usize;
            let _si = (0) as usize;
            mflow_negative[_si.._si + _n].fill(T::ta_zero());
        };
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::Mfi as usize]) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx - lookbackTotal;
        prevValue = ((*inHigh.get_unchecked((today) as usize)) + (*inLow.get_unchecked((today) as usize)) + (*inClose.get_unchecked((today) as usize))) / T::ta_from_f64(3.0);
        posSumMF = T::ta_from_f64(0.0);
        negSumMF = T::ta_from_f64(0.0);
        today += 1;
        // for( i = (optInTimePeriod) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod) as usize;
        while i > 0 {
            tempValue1 = ((*inHigh.get_unchecked((today) as usize)) + (*inLow.get_unchecked((today) as usize)) + (*inClose.get_unchecked((today) as usize))) / T::ta_from_f64(3.0);
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            tempValue1 *= (*inVolume.get_unchecked(({ let _v = today; today += 1; _v }) as usize));
            if tempValue2 < T::ta_from_i32(0) {
                (*mflow_negative.get_unchecked_mut((mflow_Idx) as usize)) = tempValue1;
                negSumMF += tempValue1;
                (*mflow_positive.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
            } else if tempValue2 > T::ta_from_i32(0) {
                (*mflow_positive.get_unchecked_mut((mflow_Idx) as usize)) = tempValue1;
                posSumMF += tempValue1;
                (*mflow_negative.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
            } else {
                (*mflow_positive.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
                (*mflow_negative.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
            }
            mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
            i -= 1;
        }
        if today > startIdx {
            tempValue1 = posSumMF + negSumMF;
            if tempValue1 < T::ta_from_f64(1.0) {
                (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = T::ta_from_f64(0.0);
            } else {
                (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = T::ta_from_f64(100.0) * (posSumMF / tempValue1);
            }
        } else {
            while today < startIdx {
                posSumMF -= (*mflow_positive.get_unchecked((mflow_Idx) as usize));
                negSumMF -= (*mflow_negative.get_unchecked((mflow_Idx) as usize));
                tempValue1 = ((*inHigh.get_unchecked((today) as usize)) + (*inLow.get_unchecked((today) as usize)) + (*inClose.get_unchecked((today) as usize))) / T::ta_from_f64(3.0);
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                tempValue1 *= (*inVolume.get_unchecked(({ let _v = today; today += 1; _v }) as usize));
                if tempValue2 < T::ta_from_i32(0) {
                    (*mflow_negative.get_unchecked_mut((mflow_Idx) as usize)) = tempValue1;
                    negSumMF += tempValue1;
                    (*mflow_positive.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
                } else if tempValue2 > T::ta_from_i32(0) {
                    (*mflow_positive.get_unchecked_mut((mflow_Idx) as usize)) = tempValue1;
                    posSumMF += tempValue1;
                    (*mflow_negative.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
                } else {
                    (*mflow_positive.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
                    (*mflow_negative.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
                }
                mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
            }
        }
        while today <= endIdx {
            posSumMF -= (*mflow_positive.get_unchecked((mflow_Idx) as usize));
            negSumMF -= (*mflow_negative.get_unchecked((mflow_Idx) as usize));
            tempValue1 = ((*inHigh.get_unchecked((today) as usize)) + (*inLow.get_unchecked((today) as usize)) + (*inClose.get_unchecked((today) as usize))) / T::ta_from_f64(3.0);
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            tempValue1 *= (*inVolume.get_unchecked(({ let _v = today; today += 1; _v }) as usize));
            if tempValue2 < T::ta_from_i32(0) {
                (*mflow_negative.get_unchecked_mut((mflow_Idx) as usize)) = tempValue1;
                negSumMF += tempValue1;
                (*mflow_positive.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
            } else if tempValue2 > T::ta_from_i32(0) {
                (*mflow_positive.get_unchecked_mut((mflow_Idx) as usize)) = tempValue1;
                posSumMF += tempValue1;
                (*mflow_negative.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
            } else {
                (*mflow_positive.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
                (*mflow_negative.get_unchecked_mut((mflow_Idx) as usize)) = T::ta_from_f64(0.0);
            }
            tempValue1 = posSumMF + negSumMF;
            if tempValue1 < T::ta_from_f64(1.0) {
                (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = T::ta_from_f64(0.0);
            } else {
                (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = T::ta_from_f64(100.0) * (posSumMF / tempValue1);
            }
            mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
