/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::minindex`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    pub fn minindex_lookback(&self, mut optInTimePeriod: i32) -> i32 {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return -1;
        }
        return optInTimePeriod - 1;
    }
    /// Index of lowest value over a specified period
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn minindex<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.minindex_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub fn minindex_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut lowest: T;
        let mut tmp: T;
        let outIdx: i32;
        let nbInitialElementNeeded: i32;
        let mut trailingIdx: i32;
        let mut lowestIdx: i32;
        let mut today: i32;
        let mut i: i32;
        nbInitialElementNeeded = optInTimePeriod - 1;
        if startIdx < nbInitialElementNeeded {
            startIdx = nbInitialElementNeeded;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx;
        trailingIdx = startIdx - nbInitialElementNeeded;
        lowestIdx = 0 - 1;
        lowest = T::ta_from_f64(0.0);
        while today <= endIdx {
            tmp = inReal[today];
            if lowestIdx < trailingIdx {
                lowestIdx = trailingIdx;
                lowest = inReal[lowestIdx];
                i = lowestIdx;
                while { i += 1; i } <= today {
                    tmp = inReal[i];
                    if tmp < lowest {
                        lowestIdx = i;
                        lowest = tmp;
                    }
                }
            } else if tmp <= lowest {
                lowestIdx = today;
                lowest = tmp;
            }
            outInteger[{ let _v = outIdx; outIdx += 1; _v }] = lowestIdx;
            trailingIdx += 1;
            today += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    pub unsafe fn minindex_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.minindex_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outInteger,
        );
    }
    pub unsafe fn minindex_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut lowest: T;
        let mut tmp: T;
        let outIdx: i32;
        let nbInitialElementNeeded: i32;
        let mut trailingIdx: i32;
        let mut lowestIdx: i32;
        let mut today: i32;
        let mut i: i32;
        nbInitialElementNeeded = optInTimePeriod - 1;
        if startIdx < nbInitialElementNeeded {
            startIdx = nbInitialElementNeeded;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx;
        trailingIdx = startIdx - nbInitialElementNeeded;
        lowestIdx = 0 - 1;
        lowest = T::ta_from_f64(0.0);
        while today <= endIdx {
            tmp = *inReal.get_unchecked(today);
            if lowestIdx < trailingIdx {
                lowestIdx = trailingIdx;
                lowest = *inReal.get_unchecked(lowestIdx);
                i = lowestIdx;
                while { i += 1; i } <= today {
                    tmp = *inReal.get_unchecked(i);
                    if tmp < lowest {
                        lowestIdx = i;
                        lowest = tmp;
                    }
                }
            } else if tmp <= lowest {
                lowestIdx = today;
                lowest = tmp;
            }
            *outInteger.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v }) = lowestIdx;
            trailingIdx += 1;
            today += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
