/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::plus_dm`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 1..=100000)
    pub fn plus_dm_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        if optInTimePeriod > 1 {
            return (optInTimePeriod + self.unstable_period[FuncUnstId::PlusDM as usize] - 1) as usize;
        } else {
            return (1) as usize;
        }
    }
    /// Plus Directional Movement
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn plus_dm<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.plus_dm_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn plus_dm_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut today: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut prevHigh: T = T::ta_zero();
        let mut prevLow: T = T::ta_zero();
        let mut tempReal: T = T::ta_zero();
        let mut prevPlusDM: T = T::ta_zero();
        let mut diffP: T = T::ta_zero();
        let mut diffM: T = T::ta_zero();
        let mut i: usize = 0_usize;
        if optInTimePeriod > 1 {
            lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::PlusDM as usize] - 1) as usize;
        } else {
            lookbackTotal = 1;
        }
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod <= 1 {
            (*outBegIdx) = startIdx;
            today = startIdx - 1;
            prevHigh = inHigh[(today) as usize];
            prevLow = inLow[(today) as usize];
            while today < endIdx {
                today += 1;
                tempReal = inHigh[(today) as usize];
                diffP = tempReal - prevHigh;
                prevHigh = tempReal;
                tempReal = inLow[(today) as usize];
                diffM = prevLow - tempReal;
                prevLow = tempReal;
                if diffP > T::ta_from_i32(0) && diffP > diffM {
                    outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = diffP;
                } else {
                    outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = T::ta_from_i32(0 as i32);
                }
            }
            (*outNBElement) = outIdx;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        prevPlusDM = T::ta_from_f64(0.0);
        today = startIdx - lookbackTotal;
        prevHigh = inHigh[(today) as usize];
        prevLow = inLow[(today) as usize];
        i = (optInTimePeriod - 1) as usize;
        while { let _v = i; i -= 1; _v } > 0 {
            today += 1;
            tempReal = inHigh[(today) as usize];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[(today) as usize];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM += diffP;
            }
        }
        i = (self.unstable_period[FuncUnstId::PlusDM as usize]) as usize;
        while { let _v = i; i -= 1; _v } != 0 {
            today += 1;
            tempReal = inHigh[(today) as usize];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[(today) as usize];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM = prevPlusDM - prevPlusDM / T::ta_from_i32(optInTimePeriod) + diffP;
            } else {
                prevPlusDM = prevPlusDM - prevPlusDM / T::ta_from_i32(optInTimePeriod);
            }
        }
        outReal[(0) as usize] = prevPlusDM;
        outIdx = 1;
        while today < endIdx {
            today += 1;
            tempReal = inHigh[(today) as usize];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[(today) as usize];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM = prevPlusDM - prevPlusDM / T::ta_from_i32(optInTimePeriod) + diffP;
            } else {
                prevPlusDM = prevPlusDM - prevPlusDM / T::ta_from_i32(optInTimePeriod);
            }
            outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = prevPlusDM;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    pub unsafe fn plus_dm_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.plus_dm_unguarded_unchecked(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn plus_dm_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[T],
        inLow: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut today: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut prevHigh: T = T::ta_zero();
        let mut prevLow: T = T::ta_zero();
        let mut tempReal: T = T::ta_zero();
        let mut prevPlusDM: T = T::ta_zero();
        let mut diffP: T = T::ta_zero();
        let mut diffM: T = T::ta_zero();
        let mut i: usize = 0_usize;
        if optInTimePeriod > 1 {
            lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::PlusDM as usize] - 1) as usize;
        } else {
            lookbackTotal = 1;
        }
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod <= 1 {
            (*outBegIdx) = startIdx;
            today = startIdx - 1;
            prevHigh = (*inHigh.get_unchecked((today) as usize));
            prevLow = (*inLow.get_unchecked((today) as usize));
            while today < endIdx {
                today += 1;
                tempReal = (*inHigh.get_unchecked((today) as usize));
                diffP = tempReal - prevHigh;
                prevHigh = tempReal;
                tempReal = (*inLow.get_unchecked((today) as usize));
                diffM = prevLow - tempReal;
                prevLow = tempReal;
                if diffP > T::ta_from_i32(0) && diffP > diffM {
                    (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = diffP;
                } else {
                    (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = T::ta_from_i32(0 as i32);
                }
            }
            (*outNBElement) = outIdx;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        prevPlusDM = T::ta_from_f64(0.0);
        today = startIdx - lookbackTotal;
        prevHigh = (*inHigh.get_unchecked((today) as usize));
        prevLow = (*inLow.get_unchecked((today) as usize));
        i = (optInTimePeriod - 1) as usize;
        while { let _v = i; i -= 1; _v } > 0 {
            today += 1;
            tempReal = (*inHigh.get_unchecked((today) as usize));
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = (*inLow.get_unchecked((today) as usize));
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM += diffP;
            }
        }
        i = (self.unstable_period[FuncUnstId::PlusDM as usize]) as usize;
        while { let _v = i; i -= 1; _v } != 0 {
            today += 1;
            tempReal = (*inHigh.get_unchecked((today) as usize));
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = (*inLow.get_unchecked((today) as usize));
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM = prevPlusDM - prevPlusDM / T::ta_from_i32(optInTimePeriod) + diffP;
            } else {
                prevPlusDM = prevPlusDM - prevPlusDM / T::ta_from_i32(optInTimePeriod);
            }
        }
        (*outReal.get_unchecked_mut((0) as usize)) = prevPlusDM;
        outIdx = 1;
        while today < endIdx {
            today += 1;
            tempReal = (*inHigh.get_unchecked((today) as usize));
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = (*inLow.get_unchecked((today) as usize));
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffP > T::ta_from_i32(0) && diffP > diffM {
                prevPlusDM = prevPlusDM - prevPlusDM / T::ta_from_i32(optInTimePeriod) + diffP;
            } else {
                prevPlusDM = prevPlusDM - prevPlusDM / T::ta_from_i32(optInTimePeriod);
            }
            (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = prevPlusDM;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
