/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::sarext`].
    ///
    /// # Arguments
    ///
    /// * `optInStartValue` - Number of period (default: 0, range: -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInOffsetOnReverse` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationInitLong` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationLong` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationMaxLong` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationInitShort` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationShort` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationMaxShort` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    pub fn sarext_lookback(&self, mut optInStartValue: f64, mut optInOffsetOnReverse: f64, mut optInAccelerationInitLong: f64, mut optInAccelerationLong: f64, mut optInAccelerationMaxLong: f64, mut optInAccelerationInitShort: f64, mut optInAccelerationShort: f64, mut optInAccelerationMaxShort: f64) -> usize {
        return (1) as usize;
    }
    /// Parabolic SAR - Extended
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `optInStartValue` - Number of period (default: 0, range: -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInOffsetOnReverse` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationInitLong` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationLong` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationMaxLong` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationInitShort` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationShort` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInAccelerationMaxShort` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn sarext(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        mut optInStartValue: f64,
        mut optInOffsetOnReverse: f64,
        mut optInAccelerationInitLong: f64,
        mut optInAccelerationLong: f64,
        mut optInAccelerationMaxLong: f64,
        mut optInAccelerationInitShort: f64,
        mut optInAccelerationShort: f64,
        mut optInAccelerationMaxShort: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        return self.sarext_unguarded(
            startIdx,
            endIdx,
            inHigh,
            inLow,
            optInStartValue,
            optInOffsetOnReverse,
            optInAccelerationInitLong,
            optInAccelerationLong,
            optInAccelerationMaxLong,
            optInAccelerationInitShort,
            optInAccelerationShort,
            optInAccelerationMaxShort,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn sarext_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        mut optInStartValue: f64,
        mut optInOffsetOnReverse: f64,
        mut optInAccelerationInitLong: f64,
        mut optInAccelerationLong: f64,
        mut optInAccelerationMaxLong: f64,
        mut optInAccelerationInitShort: f64,
        mut optInAccelerationShort: f64,
        mut optInAccelerationMaxShort: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut retCode: RetCode = RetCode::Success;
        let mut isLong: usize = 0_usize;
        let mut todayIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut tempInt: usize = 0_usize;
        let mut newHigh: f64 = 0.0_f64;
        let mut newLow: f64 = 0.0_f64;
        let mut prevHigh: f64 = 0.0_f64;
        let mut prevLow: f64 = 0.0_f64;
        let mut afLong: f64 = 0.0_f64;
        let mut afShort: f64 = 0.0_f64;
        let mut ep: f64 = 0.0_f64;
        let mut sar: f64 = 0.0_f64;
        let mut ep_temp: [f64; 1 as usize] = [0.0_f64; 1 as usize];
        unsafe {
        if startIdx < 1 {
            startIdx = 1;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        afLong = optInAccelerationInitLong;
        afShort = optInAccelerationInitShort;
        if afLong > optInAccelerationMaxLong {
            optInAccelerationInitLong = optInAccelerationMaxLong;
            afLong = optInAccelerationInitLong;
        }
        if optInAccelerationLong > optInAccelerationMaxLong {
            optInAccelerationLong = optInAccelerationMaxLong;
        }
        if afShort > optInAccelerationMaxShort {
            optInAccelerationInitShort = optInAccelerationMaxShort;
            afShort = optInAccelerationInitShort;
        }
        if optInAccelerationShort > optInAccelerationMaxShort {
            optInAccelerationShort = optInAccelerationMaxShort;
        }
        if optInStartValue == 0_f64 {
            let mut _dup_out: usize = 0_usize;
            retCode = self.minus_dm(startIdx, startIdx, inHigh, inLow, 1, &mut tempInt, &mut _dup_out, &mut ep_temp);
            if (*ep_temp.get_unchecked(0)) > 0_f64 {
                isLong = 0;
            } else {
                isLong = 1;
            }
            if retCode != RetCode::Success {
                (*outBegIdx) = 0;
                (*outNBElement) = 0;
                return retCode;
            }
        } else if optInStartValue > 0_f64 {
            isLong = 1;
        } else {
            isLong = 0;
        }
        (*outBegIdx) = startIdx;
        outIdx = 0;
        todayIdx = startIdx;
        newHigh = (*inHigh.get_unchecked(todayIdx - 1));
        newLow = (*inLow.get_unchecked(todayIdx - 1));
        if optInStartValue == 0_f64 {
            if isLong == 1 {
                ep = (*inHigh.get_unchecked(todayIdx));
                sar = newLow;
            } else {
                ep = (*inLow.get_unchecked(todayIdx));
                sar = newHigh;
            }
        } else if optInStartValue > 0_f64 {
            ep = (*inHigh.get_unchecked(todayIdx));
            sar = optInStartValue;
        } else {
            ep = (*inLow.get_unchecked(todayIdx));
            sar = (optInStartValue).abs();
        }
        newLow = (*inLow.get_unchecked(todayIdx));
        newHigh = (*inHigh.get_unchecked(todayIdx));
        while todayIdx <= endIdx {
            prevLow = newLow;
            prevHigh = newHigh;
            newLow = (*inLow.get_unchecked(todayIdx));
            newHigh = (*inHigh.get_unchecked(todayIdx));
            todayIdx += 1;
            if isLong == 1 {
                if newLow <= sar {
                    isLong = 0;
                    sar = ep;
                    if sar < prevHigh {
                        sar = prevHigh;
                    }
                    if sar < newHigh {
                        sar = newHigh;
                    }
                    if optInOffsetOnReverse != 0.0 {
                        sar += sar * optInOffsetOnReverse;
                    }
                    (*outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = 0_f64 - sar;
                    afShort = optInAccelerationInitShort;
                    ep = newLow;
                    sar = sar + afShort * (ep - sar);
                    if sar < prevHigh {
                        sar = prevHigh;
                    }
                    if sar < newHigh {
                        sar = newHigh;
                    }
                } else {
                    (*outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = sar;
                    if newHigh > ep {
                        ep = newHigh;
                        afLong += optInAccelerationLong;
                        if afLong > optInAccelerationMaxLong {
                            afLong = optInAccelerationMaxLong;
                        }
                    }
                    sar = sar + afLong * (ep - sar);
                    if sar > prevLow {
                        sar = prevLow;
                    }
                    if sar > newLow {
                        sar = newLow;
                    }
                }
            } else if newHigh >= sar {
                isLong = 1;
                sar = ep;
                if sar > prevLow {
                    sar = prevLow;
                }
                if sar > newLow {
                    sar = newLow;
                }
                if optInOffsetOnReverse != 0.0 {
                    sar -= sar * optInOffsetOnReverse;
                }
                (*outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = sar;
                afLong = optInAccelerationInitLong;
                ep = newHigh;
                sar = sar + afLong * (ep - sar);
                if sar > prevLow {
                    sar = prevLow;
                }
                if sar > newLow {
                    sar = newLow;
                }
            } else {
                (*outReal.get_unchecked_mut({ let _v = outIdx; outIdx += 1; _v })) = 0_f64 - sar;
                if newLow < ep {
                    ep = newLow;
                    afShort += optInAccelerationShort;
                    if afShort > optInAccelerationMaxShort {
                        afShort = optInAccelerationMaxShort;
                    }
                }
                sar = sar + afShort * (ep - sar);
                if sar < prevHigh {
                    sar = prevHigh;
                }
                if sar < newHigh {
                    sar = newHigh;
                }
            }
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
