/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::t3`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 5, range: 2..=100000)
    /// * `optInVFactor` - Number of period (default: 0, range: 0..=1)
    pub fn t3_lookback(&self, mut optInTimePeriod: i32, mut optInVFactor: f64) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (6 * (optInTimePeriod - 1) + self.unstable_period[FuncUnstId::T3 as usize]) as usize;
    }
    /// Triple Exponential Moving Average (T3)
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 5, range: 2..=100000)
    /// * `optInVFactor` - Number of period (default: 0, range: 0..=1)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn t3<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        mut optInVFactor: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.t3_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            optInVFactor,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn t3_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        mut optInVFactor: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut k: T = T::ta_zero();
        let mut one_minus_k: T = T::ta_zero();
        let mut e1: T = T::ta_zero();
        let mut e2: T = T::ta_zero();
        let mut e3: T = T::ta_zero();
        let mut e4: T = T::ta_zero();
        let mut e5: T = T::ta_zero();
        let mut e6: T = T::ta_zero();
        let mut c1: T = T::ta_zero();
        let mut c2: T = T::ta_zero();
        let mut c3: T = T::ta_zero();
        let mut c4: T = T::ta_zero();
        let mut tempReal: T = T::ta_zero();
        lookbackTotal = (6 * (optInTimePeriod - 1) + self.unstable_period[FuncUnstId::T3 as usize]) as usize;
        if startIdx <= lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        today = startIdx - lookbackTotal;
        k = T::ta_from_f64(2.0) / (T::ta_from_i32(optInTimePeriod) + T::ta_from_f64(1.0));
        one_minus_k = T::ta_from_f64(1.0) - k;
        tempReal = inReal[({ let _v = today; today += 1; _v }) as usize];
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            tempReal += inReal[({ let _v = today; today += 1; _v }) as usize];
            i -= 1;
        }
        e1 = tempReal / T::ta_from_i32(optInTimePeriod);
        tempReal = e1;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = k * inReal[({ let _v = today; today += 1; _v }) as usize] + one_minus_k * e1;
            tempReal += e1;
            i -= 1;
        }
        e2 = tempReal / T::ta_from_i32(optInTimePeriod);
        tempReal = e2;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = k * inReal[({ let _v = today; today += 1; _v }) as usize] + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            tempReal += e2;
            i -= 1;
        }
        e3 = tempReal / T::ta_from_i32(optInTimePeriod);
        tempReal = e3;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = k * inReal[({ let _v = today; today += 1; _v }) as usize] + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            e3 = k * e2 + one_minus_k * e3;
            tempReal += e3;
            i -= 1;
        }
        e4 = tempReal / T::ta_from_i32(optInTimePeriod);
        tempReal = e4;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = k * inReal[({ let _v = today; today += 1; _v }) as usize] + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            e3 = k * e2 + one_minus_k * e3;
            e4 = k * e3 + one_minus_k * e4;
            tempReal += e4;
            i -= 1;
        }
        e5 = tempReal / T::ta_from_i32(optInTimePeriod);
        tempReal = e5;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = k * inReal[({ let _v = today; today += 1; _v }) as usize] + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            e3 = k * e2 + one_minus_k * e3;
            e4 = k * e3 + one_minus_k * e4;
            e5 = k * e4 + one_minus_k * e5;
            tempReal += e5;
            i -= 1;
        }
        e6 = tempReal / T::ta_from_i32(optInTimePeriod);
        while today <= startIdx {
            e1 = k * inReal[({ let _v = today; today += 1; _v }) as usize] + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            e3 = k * e2 + one_minus_k * e3;
            e4 = k * e3 + one_minus_k * e4;
            e5 = k * e4 + one_minus_k * e5;
            e6 = k * e5 + one_minus_k * e6;
        }
        tempReal = T::ta_from_f64(optInVFactor) * T::ta_from_f64(optInVFactor);
        c1 = T::ta_from_i32(0) - tempReal * T::ta_from_f64(optInVFactor);
        c2 = T::ta_from_f64(3.0) * (tempReal - c1);
        c3 = (T::ta_from_i32(0) - T::ta_from_f64(6.0)) * tempReal - T::ta_from_f64(3.0) * (T::ta_from_f64(optInVFactor) - c1);
        c4 = T::ta_from_f64(1.0) + T::ta_from_f64(3.0) * T::ta_from_f64(optInVFactor) - c1 + T::ta_from_f64(3.0) * tempReal;
        outIdx = 0;
        outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = c1 * e6 + c2 * e5 + c3 * e4 + c4 * e3;
        while today <= endIdx {
            e1 = k * inReal[({ let _v = today; today += 1; _v }) as usize] + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            e3 = k * e2 + one_minus_k * e3;
            e4 = k * e3 + one_minus_k * e4;
            e5 = k * e4 + one_minus_k * e5;
            e6 = k * e5 + one_minus_k * e6;
            outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = c1 * e6 + c2 * e5 + c3 * e4 + c4 * e3;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    pub unsafe fn t3_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        mut optInVFactor: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.t3_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            optInVFactor,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn t3_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        mut optInVFactor: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut k: T = T::ta_zero();
        let mut one_minus_k: T = T::ta_zero();
        let mut e1: T = T::ta_zero();
        let mut e2: T = T::ta_zero();
        let mut e3: T = T::ta_zero();
        let mut e4: T = T::ta_zero();
        let mut e5: T = T::ta_zero();
        let mut e6: T = T::ta_zero();
        let mut c1: T = T::ta_zero();
        let mut c2: T = T::ta_zero();
        let mut c3: T = T::ta_zero();
        let mut c4: T = T::ta_zero();
        let mut tempReal: T = T::ta_zero();
        lookbackTotal = (6 * (optInTimePeriod - 1) + self.unstable_period[FuncUnstId::T3 as usize]) as usize;
        if startIdx <= lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        today = startIdx - lookbackTotal;
        k = T::ta_from_f64(2.0) / (T::ta_from_i32(optInTimePeriod) + T::ta_from_f64(1.0));
        one_minus_k = T::ta_from_f64(1.0) - k;
        tempReal = (*inReal.get_unchecked(({ let _v = today; today += 1; _v }) as usize));
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            tempReal += (*inReal.get_unchecked(({ let _v = today; today += 1; _v }) as usize));
            i -= 1;
        }
        e1 = tempReal / T::ta_from_i32(optInTimePeriod);
        tempReal = e1;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = k * (*inReal.get_unchecked(({ let _v = today; today += 1; _v }) as usize)) + one_minus_k * e1;
            tempReal += e1;
            i -= 1;
        }
        e2 = tempReal / T::ta_from_i32(optInTimePeriod);
        tempReal = e2;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = k * (*inReal.get_unchecked(({ let _v = today; today += 1; _v }) as usize)) + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            tempReal += e2;
            i -= 1;
        }
        e3 = tempReal / T::ta_from_i32(optInTimePeriod);
        tempReal = e3;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = k * (*inReal.get_unchecked(({ let _v = today; today += 1; _v }) as usize)) + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            e3 = k * e2 + one_minus_k * e3;
            tempReal += e3;
            i -= 1;
        }
        e4 = tempReal / T::ta_from_i32(optInTimePeriod);
        tempReal = e4;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = k * (*inReal.get_unchecked(({ let _v = today; today += 1; _v }) as usize)) + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            e3 = k * e2 + one_minus_k * e3;
            e4 = k * e3 + one_minus_k * e4;
            tempReal += e4;
            i -= 1;
        }
        e5 = tempReal / T::ta_from_i32(optInTimePeriod);
        tempReal = e5;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = k * (*inReal.get_unchecked(({ let _v = today; today += 1; _v }) as usize)) + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            e3 = k * e2 + one_minus_k * e3;
            e4 = k * e3 + one_minus_k * e4;
            e5 = k * e4 + one_minus_k * e5;
            tempReal += e5;
            i -= 1;
        }
        e6 = tempReal / T::ta_from_i32(optInTimePeriod);
        while today <= startIdx {
            e1 = k * (*inReal.get_unchecked(({ let _v = today; today += 1; _v }) as usize)) + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            e3 = k * e2 + one_minus_k * e3;
            e4 = k * e3 + one_minus_k * e4;
            e5 = k * e4 + one_minus_k * e5;
            e6 = k * e5 + one_minus_k * e6;
        }
        tempReal = T::ta_from_f64(optInVFactor) * T::ta_from_f64(optInVFactor);
        c1 = T::ta_from_i32(0) - tempReal * T::ta_from_f64(optInVFactor);
        c2 = T::ta_from_f64(3.0) * (tempReal - c1);
        c3 = (T::ta_from_i32(0) - T::ta_from_f64(6.0)) * tempReal - T::ta_from_f64(3.0) * (T::ta_from_f64(optInVFactor) - c1);
        c4 = T::ta_from_f64(1.0) + T::ta_from_f64(3.0) * T::ta_from_f64(optInVFactor) - c1 + T::ta_from_f64(3.0) * tempReal;
        outIdx = 0;
        (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = c1 * e6 + c2 * e5 + c3 * e4 + c4 * e3;
        while today <= endIdx {
            e1 = k * (*inReal.get_unchecked(({ let _v = today; today += 1; _v }) as usize)) + one_minus_k * e1;
            e2 = k * e1 + one_minus_k * e2;
            e3 = k * e2 + one_minus_k * e3;
            e4 = k * e3 + one_minus_k * e4;
            e5 = k * e4 + one_minus_k * e5;
            e6 = k * e5 + one_minus_k * e6;
            (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = c1 * e6 + c2 * e5 + c3 * e4 + c4 * e3;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
