/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::tema`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    pub fn tema_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        let mut retValue: usize = 0_usize;
        retValue = self.ema_lookback(optInTimePeriod);
        return retValue * 3;
    }
    /// Triple Exponential Moving Average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn tema<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.tema_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn tema_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut firstEMA: Vec<T> = Vec::new();
        let mut secondEMA: Vec<T> = Vec::new();
        let mut firstEMABegIdx: usize = 0_usize;
        let mut firstEMANbElement: usize = 0_usize;
        let mut secondEMABegIdx: usize = 0_usize;
        let mut secondEMANbElement: usize = 0_usize;
        let mut thirdEMABegIdx: usize = 0_usize;
        let mut thirdEMANbElement: usize = 0_usize;
        let mut tempInt: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut lookbackEMA: usize = 0_usize;
        let mut firstEMAIdx: usize = 0_usize;
        let mut secondEMAIdx: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        (*outNBElement) = 0;
        (*outBegIdx) = 0;
        lookbackEMA = self.ema_lookback(optInTimePeriod);
        lookbackTotal = lookbackEMA * 3;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        tempInt = lookbackTotal + (endIdx - startIdx) + 1;
        firstEMA = vec![T::ta_zero(); (tempInt * 1) as usize];
        retCode = self.ema_unguarded(startIdx - lookbackEMA * 2, endIdx, inReal, optInTimePeriod, &mut firstEMABegIdx, &mut firstEMANbElement, &mut firstEMA[..]);
        if retCode != RetCode::Success || firstEMANbElement == 0 {
            return retCode;
        }
        secondEMA = vec![T::ta_zero(); (firstEMANbElement * 1) as usize];
        retCode = self.ema_unguarded(0, firstEMANbElement - 1, &firstEMA, optInTimePeriod, &mut secondEMABegIdx, &mut secondEMANbElement, &mut secondEMA[..]);
        if retCode != RetCode::Success || secondEMANbElement == 0 {
            return retCode;
        }
        retCode = self.ema_unguarded(0, secondEMANbElement - 1, &secondEMA, optInTimePeriod, &mut thirdEMABegIdx, &mut thirdEMANbElement, outReal);
        if retCode != RetCode::Success || thirdEMANbElement == 0 {
            return retCode;
        }
        firstEMAIdx = thirdEMABegIdx + secondEMABegIdx;
        secondEMAIdx = thirdEMABegIdx;
        (*outBegIdx) = firstEMAIdx + firstEMABegIdx;
        outIdx = 0;
        while outIdx < thirdEMANbElement {
            outReal[(outIdx) as usize] = outReal[(outIdx) as usize] + (T::ta_from_f64(3.0) * firstEMA[({ let _v = firstEMAIdx; firstEMAIdx += 1; _v }) as usize] - T::ta_from_f64(3.0) * secondEMA[({ let _v = secondEMAIdx; secondEMAIdx += 1; _v }) as usize]);
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    pub unsafe fn tema_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.tema_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn tema_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut firstEMA: Vec<T> = Vec::new();
        let mut secondEMA: Vec<T> = Vec::new();
        let mut firstEMABegIdx: usize = 0_usize;
        let mut firstEMANbElement: usize = 0_usize;
        let mut secondEMABegIdx: usize = 0_usize;
        let mut secondEMANbElement: usize = 0_usize;
        let mut thirdEMABegIdx: usize = 0_usize;
        let mut thirdEMANbElement: usize = 0_usize;
        let mut tempInt: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut lookbackEMA: usize = 0_usize;
        let mut firstEMAIdx: usize = 0_usize;
        let mut secondEMAIdx: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        (*outNBElement) = 0;
        (*outBegIdx) = 0;
        lookbackEMA = self.ema_lookback(optInTimePeriod);
        lookbackTotal = lookbackEMA * 3;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        tempInt = lookbackTotal + (endIdx - startIdx) + 1;
        firstEMA = vec![T::ta_zero(); (tempInt * 1) as usize];
        retCode = self.ema_unguarded(startIdx - lookbackEMA * 2, endIdx, inReal, optInTimePeriod, &mut firstEMABegIdx, &mut firstEMANbElement, &mut firstEMA[..]);
        if retCode != RetCode::Success || firstEMANbElement == 0 {
            return retCode;
        }
        secondEMA = vec![T::ta_zero(); (firstEMANbElement * 1) as usize];
        retCode = self.ema_unguarded(0, firstEMANbElement - 1, &firstEMA, optInTimePeriod, &mut secondEMABegIdx, &mut secondEMANbElement, &mut secondEMA[..]);
        if retCode != RetCode::Success || secondEMANbElement == 0 {
            return retCode;
        }
        retCode = self.ema_unguarded(0, secondEMANbElement - 1, &secondEMA, optInTimePeriod, &mut thirdEMABegIdx, &mut thirdEMANbElement, outReal);
        if retCode != RetCode::Success || thirdEMANbElement == 0 {
            return retCode;
        }
        firstEMAIdx = thirdEMABegIdx + secondEMABegIdx;
        secondEMAIdx = thirdEMABegIdx;
        (*outBegIdx) = firstEMAIdx + firstEMABegIdx;
        outIdx = 0;
        while outIdx < thirdEMANbElement {
            (*outReal.get_unchecked_mut((outIdx) as usize)) = (*outReal.get_unchecked((outIdx) as usize)) + (T::ta_from_f64(3.0) * (*firstEMA.get_unchecked(({ let _v = firstEMAIdx; firstEMAIdx += 1; _v }) as usize)) - T::ta_from_f64(3.0) * (*secondEMA.get_unchecked(({ let _v = secondEMAIdx; secondEMAIdx += 1; _v }) as usize)));
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
