/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::tsf`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    pub fn tsf_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod - 1) as usize;
    }
    /// Time Series Forecast
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn tsf<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.tsf_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn tsf_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut outIdx: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut SumX: T = T::ta_zero();
        let mut SumXY: T = T::ta_zero();
        let mut SumY: T = T::ta_zero();
        let mut SumXSqr: T = T::ta_zero();
        let mut Divisor: T = T::ta_zero();
        let mut m: T = T::ta_zero();
        let mut b: T = T::ta_zero();
        let mut i: usize = 0_usize;
        let mut tempValue1: T = T::ta_zero();
        lookbackTotal = self.tsf_lookback(optInTimePeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx;
        SumX = T::ta_from_i32(optInTimePeriod * (optInTimePeriod - 1)) * T::ta_from_f64(0.5);
        SumXSqr = T::ta_from_i32(optInTimePeriod * (optInTimePeriod - 1) * (2 * optInTimePeriod - 1) / 6);
        Divisor = SumX * SumX - T::ta_from_i32(optInTimePeriod) * SumXSqr;
        while today <= endIdx {
            SumXY = T::ta_from_i32(0 as i32);
            SumY = T::ta_from_i32(0 as i32);
            // for( i = (optInTimePeriod) as usize; { let _v = i; i -= 1; _v } != 0;  )
            i = (optInTimePeriod) as usize;
            while { let _v = i; i -= 1; _v } != 0 {
                tempValue1 = inReal[(today - i) as usize];
                SumY += tempValue1;
                SumXY += (T::ta_from_i32((i) as i32)) * tempValue1;
            }
            m = (T::ta_from_i32(optInTimePeriod) * SumXY - SumX * SumY) / Divisor;
            b = (SumY - m * SumX) / (T::ta_from_i32(optInTimePeriod));
            outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = b + m * (T::ta_from_i32(optInTimePeriod));
            today += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    pub unsafe fn tsf_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.tsf_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn tsf_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut outIdx: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut SumX: T = T::ta_zero();
        let mut SumXY: T = T::ta_zero();
        let mut SumY: T = T::ta_zero();
        let mut SumXSqr: T = T::ta_zero();
        let mut Divisor: T = T::ta_zero();
        let mut m: T = T::ta_zero();
        let mut b: T = T::ta_zero();
        let mut i: usize = 0_usize;
        let mut tempValue1: T = T::ta_zero();
        lookbackTotal = self.tsf_lookback(optInTimePeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx;
        SumX = T::ta_from_i32(optInTimePeriod * (optInTimePeriod - 1)) * T::ta_from_f64(0.5);
        SumXSqr = T::ta_from_i32(optInTimePeriod * (optInTimePeriod - 1) * (2 * optInTimePeriod - 1) / 6);
        Divisor = SumX * SumX - T::ta_from_i32(optInTimePeriod) * SumXSqr;
        while today <= endIdx {
            SumXY = T::ta_from_i32(0 as i32);
            SumY = T::ta_from_i32(0 as i32);
            // for( i = (optInTimePeriod) as usize; { let _v = i; i -= 1; _v } != 0;  )
            i = (optInTimePeriod) as usize;
            while { let _v = i; i -= 1; _v } != 0 {
                tempValue1 = (*inReal.get_unchecked((today - i) as usize));
                SumY += tempValue1;
                SumXY += (T::ta_from_i32((i) as i32)) * tempValue1;
            }
            m = (T::ta_from_i32(optInTimePeriod) * SumXY - SumX * SumY) / Divisor;
            b = (SumY - m * SumX) / (T::ta_from_i32(optInTimePeriod));
            (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = b + m * (T::ta_from_i32(optInTimePeriod));
            today += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
