/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::wma`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    pub fn wma_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod - 1) as usize;
    }
    /// Weighted Moving Average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn wma<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.wma_unguarded(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub fn wma_unguarded<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut inIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut divider: usize = 0_usize;
        let mut periodSum: T = T::ta_zero();
        let mut periodSub: T = T::ta_zero();
        let mut tempReal: T = T::ta_zero();
        let mut trailingValue: T = T::ta_zero();
        let mut lookbackTotal: usize = 0_usize;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        if optInTimePeriod == 1 {
            (*outBegIdx) = startIdx;
            (*outNBElement) = endIdx - startIdx + 1;
            {
            let _n = ((((*outNBElement))) as usize * 1) as usize;
            let _di = (0) as usize;
            let _si = ((startIdx) as usize) as usize;
            outReal[_di.._di + _n].copy_from_slice(&inReal[_si.._si + _n]);
        };
            return RetCode::Success;
        }
        divider = (optInTimePeriod * (optInTimePeriod + 1) >> 1) as usize;
        outIdx = 0;
        trailingIdx = startIdx - lookbackTotal;
        periodSub = T::ta_from_f64((T::ta_from_f64(0.0)).ta_to_f64());
        periodSum = periodSub;
        inIdx = trailingIdx;
        i = 1;
        while inIdx < startIdx {
            tempReal = inReal[({ let _v = inIdx; inIdx += 1; _v }) as usize];
            periodSub += tempReal;
            periodSum += tempReal * T::ta_from_i32((i) as i32);
            i += 1;
        }
        trailingValue = T::ta_from_f64(0.0);
        while inIdx <= endIdx {
            tempReal = inReal[({ let _v = inIdx; inIdx += 1; _v }) as usize];
            periodSub += tempReal;
            periodSub -= trailingValue;
            periodSum += tempReal * T::ta_from_i32(optInTimePeriod);
            trailingValue = inReal[({ let _v = trailingIdx; trailingIdx += 1; _v }) as usize];
            outReal[({ let _v = outIdx; outIdx += 1; _v }) as usize] = periodSum / T::ta_from_i32((divider) as i32);
            periodSum -= periodSub;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    pub unsafe fn wma_unchecked<T: TaFloat>(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        return self.wma_unguarded_unchecked(
            startIdx,
            endIdx,
            inReal,
            optInTimePeriod,
            outBegIdx,
            outNBElement,
            outReal,
        );
    }
    pub unsafe fn wma_unguarded_unchecked<T: TaFloat>(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[T],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [T],
    ) -> RetCode {
        let mut inIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut divider: usize = 0_usize;
        let mut periodSum: T = T::ta_zero();
        let mut periodSub: T = T::ta_zero();
        let mut tempReal: T = T::ta_zero();
        let mut trailingValue: T = T::ta_zero();
        let mut lookbackTotal: usize = 0_usize;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        if optInTimePeriod == 1 {
            (*outBegIdx) = startIdx;
            (*outNBElement) = endIdx - startIdx + 1;
            {
            let _n = ((((*outNBElement))) as usize * 1) as usize;
            let _di = (0) as usize;
            let _si = ((startIdx) as usize) as usize;
            outReal[_di.._di + _n].copy_from_slice(&inReal[_si.._si + _n]);
        };
            return RetCode::Success;
        }
        divider = (optInTimePeriod * (optInTimePeriod + 1) >> 1) as usize;
        outIdx = 0;
        trailingIdx = startIdx - lookbackTotal;
        periodSub = T::ta_from_f64((T::ta_from_f64(0.0)).ta_to_f64());
        periodSum = periodSub;
        inIdx = trailingIdx;
        i = 1;
        while inIdx < startIdx {
            tempReal = (*inReal.get_unchecked(({ let _v = inIdx; inIdx += 1; _v }) as usize));
            periodSub += tempReal;
            periodSum += tempReal * T::ta_from_i32((i) as i32);
            i += 1;
        }
        trailingValue = T::ta_from_f64(0.0);
        while inIdx <= endIdx {
            tempReal = (*inReal.get_unchecked(({ let _v = inIdx; inIdx += 1; _v }) as usize));
            periodSub += tempReal;
            periodSub -= trailingValue;
            periodSum += tempReal * T::ta_from_i32(optInTimePeriod);
            trailingValue = (*inReal.get_unchecked(({ let _v = trailingIdx; trailingIdx += 1; _v }) as usize));
            (*outReal.get_unchecked_mut(({ let _v = outIdx; outIdx += 1; _v }) as usize)) = periodSum / T::ta_from_i32((divider) as i32);
            periodSum -= periodSub;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
