/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility ta_codegen.
 *  Any modifications will be lost on next execution of ta_codegen.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  112400 MF   Template creation.
 *  052603 MF   Adapt code to compile with .NET Managed C++
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::rocr`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 10, range: 1..=100000)
    #[inline]
    pub fn rocr_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 10;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod) as usize;
    }
    /// Rate of change ratio: (price/prevPrice)
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 10, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn rocr(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 10;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut inIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut tempReal: f64 = 0.0_f64;
        // The interpretation of the rate of change varies widely depending
        // which software and/or books you are refering to.
        //
        // The following is the table of Rate-Of-Change implemented in TA-LIB:
        //       MOM     = (price - prevPrice)         [Momentum]
        //       ROC     = ((price/prevPrice)-1)*100   [Rate of change]
        //       ROCP    = (price-prevPrice)/prevPrice [Rate of change Percentage]
        //       ROCR    = (price/prevPrice)           [Rate of change ratio]
        //       ROCR100 = (price/prevPrice)*100       [Rate of change ratio 100 Scale]
        //
        // Here are the equivalent function in other software:
        //       TA-Lib  |   Tradestation   |    Metastock
        //       =================================================
        //       MOM     |   Momentum       |    ROC (Point)
        //       ROC     |   ROC            |    ROC (Percent)
        //       ROCP    |   PercentChange  |    -
        //       ROCR    |   -              |    -
        //       ROCR100 |   -              |    MO
        //
        // The MOM function is the only one who is not normalized, and thus
        // should be avoided for comparing different time serie of prices.
        //
        // ROC and ROCP are centered at zero and can have positive and negative
        // value. Here are some equivalence:
        //    ROC = ROCP/100
        //        = ((price-prevPrice)/prevPrice)/100
        //        = ((price/prevPrice)-1)*100
        //
        // ROCR and ROCR100 are ratio respectively centered at 1 and 100 and are
        // always positive values.
        // Move up the start index if there is not
        // enough initial data.
        if startIdx < (optInTimePeriod) as usize {
            startIdx = (optInTimePeriod) as usize;
        }
        // Make sure there is still something to evaluate.
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        // Calculate Rate of change Ratio: (price / prevPrice)
        outIdx = 0;
        inIdx = startIdx;
        trailingIdx = startIdx - (optInTimePeriod) as usize;
        while inIdx <= endIdx {
            tempReal = inReal[{ let _v = trailingIdx; trailingIdx += 1; _v }];
            if tempReal != 0.0 {
                outReal[outIdx] = ((inReal[inIdx] / tempReal) as f64);
                outIdx += 1;
            } else {
                outReal[outIdx] = 0.0;
                outIdx += 1;
            }
            inIdx += 1;
        }
        // Set output limits.
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn rocr_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut inIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut tempReal: f64 = 0.0_f64;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        if startIdx < (optInTimePeriod) as usize {
            startIdx = (optInTimePeriod) as usize;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        inIdx = startIdx;
        trailingIdx = startIdx - (optInTimePeriod) as usize;
        while inIdx <= endIdx {
            tempReal = *inReal.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
            if tempReal != 0.0 {
                *outReal.as_mut_ptr().add(outIdx) = ((*inReal.as_ptr().add(inIdx) / tempReal) as f64);
                outIdx += 1;
            } else {
                *outReal.as_mut_ptr().add(outIdx) = 0.0;
                outIdx += 1;
            }
            inIdx += 1;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/***************/
/* End of File */
/***************/
