/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility ta_codegen.
 *  Any modifications will be lost on next execution of ta_codegen.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  112400 MF   Template creation.
 *  052603 MF   Adapt code to compile with .NET Managed C++
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::wma`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    #[inline]
    pub fn wma_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod - 1) as usize;
    }
    /// Weighted Moving Average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn wma(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut inIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut divider: usize = 0_usize;
        let mut periodSum: f64 = 0.0_f64;
        let mut periodSub: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        let mut trailingValue: f64 = 0.0_f64;
        let mut lookbackTotal: usize = 0_usize;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        // Move up the start index if there is not
        // enough initial data.
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        // Make sure there is still something to evaluate.
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        // To make the rest more efficient, handle exception
        // case where the user is asking for a period of '1'.
        // In that case outputs equals inputs for the requested
        // range.
        if optInTimePeriod == 1 {
            (*outBegIdx) = startIdx;
            (*outNBElement) = endIdx - startIdx + 1;
            {
            let _n = ((((*outNBElement) as usize)) as usize * 1) as usize;
            let _di = (0) as usize;
            let _si = (startIdx) as usize;
            outReal[_di.._di + _n].copy_from_slice(&inReal[_si.._si + _n]);
        };
            return RetCode::Success;
        }
        // Calculate the divider (always an integer value).
        // By induction: 1+2+3+4+'n' = n(n+1)/2
        // '>>1' is usually faster than '/2' for unsigned.
        divider = (optInTimePeriod * (optInTimePeriod + 1) >> 1) as usize;
        // The algo used here use a very basic property of
        // multiplication/addition: (x*2) = x+x
        //
        // As an example, a 3 period weighted can be
        // interpreted in two way:
        //  (x1*1)+(x2*2)+(x3*3)
        //      OR
        //  x1+x2+x2+x3+x3+x3 (this is the periodSum)
        //
        // When you move forward in the time serie
        // you can quickly adjust the periodSum for the
        // period by substracting:
        //   x1+x2+x3 (This is the periodSub)
        // Making the new periodSum equals to:
        //   x2+x3+x3
        //
        // You can then add the new price bar
        // which is x4+x4+x4 giving:
        //   x2+x3+x3+x4+x4+x4
        //
        // At this point one iteration is completed and you can
        // see that we are back to the step 1 of this example.
        //
        // Why making it so un-intuitive? The number of memory
        // access and floating point operations are kept to a
        // minimum with this algo.
        outIdx = 0;
        trailingIdx = startIdx - lookbackTotal;
        // Evaluate the initial periodSum/periodSub and trailingValue.
        periodSub = 0.0 as f64;
        periodSum = periodSub;
        inIdx = trailingIdx;
        i = 1;
        while inIdx < startIdx {
            tempReal = inReal[{ let _v = inIdx; inIdx += 1; _v }];
            periodSub += tempReal;
            periodSum += tempReal * ((i) as f64);
            i += 1;
        }
        trailingValue = 0.0;
        // Tight loop for the requested range.
        while inIdx <= endIdx {
            // Add the current price bar to the sum
            // who are carried through the iterations.
            tempReal = inReal[{ let _v = inIdx; inIdx += 1; _v }];
            periodSub += tempReal;
            periodSub -= trailingValue;
            periodSum += tempReal * ((optInTimePeriod) as f64);
            // Save the trailing value for being substract at
            // the next iteration.
            // (must be saved here just in case outReal and
            //  inReal are the same buffer).
            trailingValue = inReal[{ let _v = trailingIdx; trailingIdx += 1; _v }];
            // Calculate the WMA for this price bar.
            outReal[outIdx] = periodSum / ((divider) as f64);
            outIdx += 1;
            // Prepare the periodSum for the next iteration.
            periodSum -= periodSub;
        }
        // Set output limits.
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn wma_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut inIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut divider: usize = 0_usize;
        let mut periodSum: f64 = 0.0_f64;
        let mut periodSub: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        let mut trailingValue: f64 = 0.0_f64;
        let mut lookbackTotal: usize = 0_usize;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        if optInTimePeriod == 1 {
            (*outBegIdx) = startIdx;
            (*outNBElement) = endIdx - startIdx + 1;
            {
            let _n = ((((*outNBElement) as usize)) as usize * 1) as usize;
            let _di = (0) as usize;
            let _si = (startIdx) as usize;
            outReal[_di.._di + _n].copy_from_slice(&inReal[_si.._si + _n]);
        };
            return RetCode::Success;
        }
        divider = (optInTimePeriod * (optInTimePeriod + 1) >> 1) as usize;
        outIdx = 0;
        trailingIdx = startIdx - lookbackTotal;
        periodSub = 0.0 as f64;
        periodSum = periodSub;
        inIdx = trailingIdx;
        i = 1;
        while inIdx < startIdx {
            tempReal = *inReal.as_ptr().add({ let _v = inIdx; inIdx += 1; _v });
            periodSub += tempReal;
            periodSum += tempReal * ((i) as f64);
            i += 1;
        }
        trailingValue = 0.0;
        while inIdx <= endIdx {
            tempReal = *inReal.as_ptr().add({ let _v = inIdx; inIdx += 1; _v });
            periodSub += tempReal;
            periodSub -= trailingValue;
            periodSum += tempReal * ((optInTimePeriod) as f64);
            trailingValue = *inReal.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
            *outReal.as_mut_ptr().add(outIdx) = periodSum / ((divider) as f64);
            outIdx += 1;
            periodSum -= periodSub;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/***************/
/* End of File */
/***************/
