use std::collections::HashMap;

use crate::ir::*;
use crate::parser::enums::lookup_variant;
use crate::registry::Registry;

pub fn generate(func: &FuncDef, enums: &HashMap<String, EnumDef>, registry: &Registry) -> String {
    let mut out = String::new();
    out.push_str(&gen_header());
    out.push_str(&gen_imports());
    out.push_str(&gen_impl_block(func, enums, registry));
    out.push_str(&gen_footer());
    out
}

fn gen_header() -> String {
    let mut out = String::new();
    out.push_str("/* TA-LIB Copyright (c) 1999-2025, Mario Fortier\n");
    out.push_str(" * All rights reserved.\n");
    out.push_str(" *\n");
    out.push_str(" * Redistribution and use in source and binary forms, with or\n");
    out.push_str(" * without modification, are permitted provided that the following\n");
    out.push_str(" * conditions are met:\n");
    out.push_str(" *\n");
    out.push_str(" * - Redistributions of source code must retain the above copyright\n");
    out.push_str(" *   notice, this list of conditions and the following disclaimer.\n");
    out.push_str(" *\n");
    out.push_str(" * - Redistributions in binary form must reproduce the above copyright\n");
    out.push_str(" *   notice, this list of conditions and the following disclaimer in\n");
    out.push_str(" *   the documentation and/or other materials provided with the\n");
    out.push_str(" *   distribution.\n");
    out.push_str(" *\n");
    out.push_str(" * - Neither name of author nor the names of its contributors\n");
    out.push_str(" *   may be used to endorse or promote products derived from this\n");
    out.push_str(" *   software without specific prior written permission.\n");
    out.push_str(" *\n");
    out.push_str(" * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n");
    out.push_str(" * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n");
    out.push_str(" * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n");
    out.push_str(" * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n");
    out.push_str(" * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n");
    out.push_str(" * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n");
    out.push_str(" * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\n");
    out.push_str(" * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\n");
    out.push_str(" * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,\n");
    out.push_str(" * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\n");
    out.push_str(" * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,\n");
    out.push_str(" * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n");
    out.push_str(" */\n\n");
    out.push_str("/* Important:\n");
    out.push_str(" *  This file is automatically generated by the utility gen_code.\n");
    out.push_str(" *  Any modifications will be lost on next execution of gen_code.\n");
    out.push_str(" *\n");
    out.push_str(" *  Modifications should instead be done with the \"C\" source file\n");
    out.push_str(" *  in ta-lib\\src\\ta_func\n");
    out.push_str(" */\n\n");
    out
}

fn gen_imports() -> String {
    "// Import types from parent module\n\
     use super::*;\n\n"
        .to_string()
}

fn gen_impl_block(func: &FuncDef, enums: &HashMap<String, EnumDef>, registry: &Registry) -> String {
    let mut out = String::new();
    let snake = func.name.to_lowercase();
    let has_opt_inputs = !func.optional_inputs.is_empty();

    out.push_str(
        "// Allow non-snake-case names to maintain TA-Lib API compatibility\n\
         #[allow(non_snake_case)]\n\
         // allow unused variables and dead code due to gen code weirdness\n\
         #[allow(unused_variables)]\n\
         #[allow(dead_code)]\n\
         impl Core {\n",
    );

    out.push_str(&gen_lookback(func, &snake, enums, registry));

    if has_opt_inputs {
        // Two-layer structure: public function + private logic function
        out.push_str(&gen_public_func(func, &snake, false, registry));
        out.push_str(&gen_internal_func(func, &snake, false, enums, registry));
        out.push_str(&gen_public_func(func, &snake, true, registry));
        out.push_str(&gen_internal_func(func, &snake, true, enums, registry));
    } else {
        // Simple flat function (no optional params)
        out.push_str(&gen_func(func, &snake, false, enums, registry));
        out.push_str(&gen_func(func, &snake, true, enums, registry));
    }

    // Generate unsafe variants (double and single precision)
    out.push_str(&gen_unsafe_func(func, &snake, false));
    out.push_str(&gen_unsafe_func(func, &snake, true));

    out.push_str("}\n");
    out
}

fn gen_lookback(func: &FuncDef, snake: &str, enums: &HashMap<String, EnumDef>, registry: &Registry) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "    /// Lookback period for [`Core::{}`].\n",
        snake
    ));
    out.push_str("    ///\n");
    out.push_str("    /// # Arguments\n");
    out.push_str("    ///\n");

    let has_opt_inputs = !func.optional_inputs.is_empty();

    if has_opt_inputs {
        // Document optional params
        for opt in &func.optional_inputs {
            if let (Some(default), Some((lo, hi))) = (opt.default, opt.range) {
                out.push_str(&format!(
                    "    /// * `{}` - Number of period (default: {}, range: {}..={})\n",
                    opt.name, default as i64, lo, hi
                ));
            }
        }

        // Build parameter list
        let mut params = Vec::new();
        for opt in &func.optional_inputs {
            let rust_type = match opt.param_type {
                ParamType::Real => "f64",
                ParamType::Integer | ParamType::Enum(_) => "i32",
            };
            params.push(format!("mut {}: {}", opt.name, rust_type));
        }

        out.push_str(&format!(
            "    pub fn {}_lookback(&self, {}) -> i32 {{\n",
            snake,
            params.join(", ")
        ));

        // Param validation
        for opt in &func.optional_inputs {
            out.push_str(&gen_opt_param_validation(opt, "        ", true));
        }

        // Return lookback expression
        match &func.lookback {
            Some(LookbackExpr::Literal(n)) => {
                out.push_str(&format!("        return {};\n", n));
            }
            Some(LookbackExpr::ParamMinus(param, offset)) => {
                out.push_str(&format!("        return {} - {};\n", param, offset));
            }
            Some(LookbackExpr::Code(stmts)) => {
                out.push_str(&render_lookback_code(stmts, enums, registry));
            }
            None => {
                out.push_str("        return 0;\n");
            }
        }
    } else {
        out.push_str(&format!(
            "    pub fn {}_lookback(&self) -> i32 {{\n",
            snake
        ));
        match &func.lookback {
            Some(LookbackExpr::Literal(n)) => {
                out.push_str(&format!("        return {};\n", n));
            }
            Some(LookbackExpr::ParamMinus(param, offset)) => {
                out.push_str(&format!("        return {} - {};\n", param, offset));
            }
            Some(LookbackExpr::Code(stmts)) => {
                out.push_str(&render_lookback_code(stmts, enums, registry));
            }
            None => {
                out.push_str("        return 0;\n");
            }
        }
    }

    out.push_str("    }\n");
    out
}

/// Generate the public wrapper function (for functions with optional params).
/// This validates params and delegates to <name>_logic.
fn gen_public_func(func: &FuncDef, snake: &str, single_precision: bool, _registry: &Registry) -> String {
    let mut out = String::new();
    let suffix = if single_precision { "_s" } else { "" };
    let func_name = format!("{}{}", snake, suffix);
    let input_type = if single_precision { "f32" } else { "f64" };
    let logic_func_name = format!("{}_logic{}", snake, suffix);

    // Doc comments
    if single_precision {
        out.push_str(&format!(
            "    /// Single-precision variant of [`Core::{}`].\n",
            snake
        ));
    } else {
        let title = func.description.as_deref().or(func.hint.as_deref()).unwrap_or(&func.group);
        out.push_str(&format!("    /// {}\n", title));
        out.push_str("    ///\n");
        out.push_str("    /// # Arguments\n");
        out.push_str("    ///\n");
        out.push_str("    /// * `startIdx` - Start index for calculation range\n");
        out.push_str("    /// * `endIdx` - End index for calculation range (inclusive)\n");
        for input in &func.inputs {
            out.push_str(&format!(
                "    /// * `{}` - Input price series\n",
                input.name
            ));
        }
        for opt in &func.optional_inputs {
            if let (Some(default), Some((lo, hi))) = (opt.default, opt.range) {
                out.push_str(&format!(
                    "    /// * `{}` - Number of period (default: {}, range: {}..={})\n",
                    opt.name, default as i64, lo, hi
                ));
            }
        }
        out.push_str("    /// * `outBegIdx` - First valid output index\n");
        out.push_str("    /// * `outNBElement` - Number of valid output elements\n");
        for output in &func.outputs {
            out.push_str(&format!("    /// * `{}` - Output values\n", output.name));
        }
        out.push_str("    ///\n");
        out.push_str("    /// # Returns\n");
        out.push_str("    ///\n");
        out.push_str(
            "    /// [`RetCode::Success`] on success, or an error code on failure.\n",
        );
        out.push_str("    ///\n");
        out.push_str("    /// # Example\n");
        out.push_str("    ///\n");
        out.push_str("    /// ```\n");
        out.push_str("    /// use ta_lib::ta_func::{Core, RetCode};\n");
        out.push_str("    ///\n");
        out.push_str("    ///\n");
        // Generate example with specific values for SMA-like functions
        out.push_str("    /// let close_prices = [1.0, 2.0, 3.0, 4.0, 5.0_f64];\n");
        out.push_str("    /// let mut out = [0.0_f64; 5];\n");
        out.push_str("    /// let mut out_beg_idx: usize = 0;\n");
        out.push_str("    /// let mut out_nb_element: usize = 0;\n");
        out.push_str("    ///\n");
        out.push_str("    /// let core = Core::new();\n");
        out.push_str(&format!("    /// let result = core.{}(\n", snake));
        out.push_str("    ///  0,\n");
        out.push_str("    ///  4,\n");
        out.push_str("    ///  &close_prices,\n");
        // Use a sensible example value for opt params
        for opt in &func.optional_inputs {
            if let Some((lo, _hi)) = opt.range {
                out.push_str(&format!("    ///  {},\n", lo + 1)); // use lo+1 = 3
            }
        }
        out.push_str("    ///  &mut out_beg_idx,\n");
        out.push_str("    ///  &mut out_nb_element,\n");
        out.push_str("    ///  &mut out,\n");
        out.push_str("    /// );\n");
        out.push_str("    ///\n");
        out.push_str("    /// assert_eq!(result, RetCode::Success);\n");
        // Add specific assertions for SMA
        out.push_str("    /// assert_eq!(out_beg_idx, 2);\n");
        out.push_str("    /// assert_eq!(out_nb_element, 3);\n");
        out.push_str("    /// assert!((out[0] - 2.0).abs() < 1e-10);\n");
        out.push_str("    /// assert!((out[1] - 3.0).abs() < 1e-10);\n");
        out.push_str("    /// assert!((out[2] - 4.0).abs() < 1e-10);\n");
        out.push_str("    /// ```\n");
    }

    // Function signature
    out.push_str(&format!("    pub fn {}(\n", func_name));
    out.push_str("        &self,\n");
    out.push_str("        startIdx: usize,\n");
    out.push_str("        endIdx: usize,\n");
    for input in &func.inputs {
        out.push_str(&format!(
            "        {}: &[{}],\n",
            input.name, input_type
        ));
    }
    for opt in &func.optional_inputs {
        let rust_type = match opt.param_type {
            ParamType::Real => "f64",
            ParamType::Integer | ParamType::Enum(_) => "i32",
        };
        out.push_str(&format!("        mut {}: {},\n", opt.name, rust_type));
    }
    out.push_str("        outBegIdx: &mut usize,\n");
    out.push_str("        outNBElement: &mut usize,\n");
    for output in &func.outputs {
        let rust_type = match output.param_type {
            ParamType::Real => "f64",
            ParamType::Integer | ParamType::Enum(_) => "i32",
        };
        out.push_str(&format!(
            "        {}: &mut [{}],\n",
            output.name, rust_type
        ));
    }
    out.push_str("    ) -> RetCode {\n");

    // Range check
    out.push_str("        if endIdx < startIdx {\n");
    out.push_str("            return RetCode::OutOfRangeEndIndex;\n");
    out.push_str("        }\n");

    // Param validation
    for opt in &func.optional_inputs {
        out.push_str(&gen_opt_param_validation(opt, "        ", false));
    }

    // Delegate to logic function
    out.push_str(&format!("        return self.{}(\n", logic_func_name));
    out.push_str("            startIdx,\n");
    out.push_str("            endIdx,\n");
    for input in &func.inputs {
        out.push_str(&format!("            {},\n", input.name));
    }
    for opt in &func.optional_inputs {
        out.push_str(&format!("            {},\n", opt.name));
    }
    out.push_str("            outBegIdx,\n");
    out.push_str("            outNBElement,\n");
    for output in &func.outputs {
        out.push_str(&format!("            {},\n", output.name));
    }
    out.push_str("        );\n");
    out.push_str("    }\n");

    out
}

/// Generate the logic (private) function for functions with optional params.
fn gen_internal_func(func: &FuncDef, snake: &str, single_precision: bool, enums: &HashMap<String, EnumDef>, registry: &Registry) -> String {
    let mut out = String::new();
    let suffix = if single_precision { "_s" } else { "" };
    let func_name = format!("{}_logic{}", snake, suffix);
    let input_type = if single_precision { "f32" } else { "f64" };

    // Function signature (private)
    out.push_str(&format!("    fn {}(\n", func_name));
    out.push_str("        &self,\n");
    out.push_str("        mut startIdx: usize,\n");
    out.push_str("        endIdx: usize,\n");
    for input in &func.inputs {
        out.push_str(&format!(
            "        {}: &[{}],\n",
            input.name, input_type
        ));
    }
    for opt in &func.optional_inputs {
        let rust_type = match opt.param_type {
            ParamType::Real => "f64",
            ParamType::Integer | ParamType::Enum(_) => "i32",
        };
        out.push_str(&format!("        {}: {},\n", opt.name, rust_type));
    }
    out.push_str("        outBegIdx: &mut usize,\n");
    out.push_str("        outNBElement: &mut usize,\n");
    for output in &func.outputs {
        let rust_type = match output.param_type {
            ParamType::Real => "f64",
            ParamType::Integer | ParamType::Enum(_) => "i32",
        };
        out.push_str(&format!(
            "        {}: &mut [{}],\n",
            output.name, rust_type
        ));
    }
    out.push_str("    ) -> RetCode {\n");

    // Declare local variables (excluding loop iterators consumed by for-loops)
    let for_loop_vars = collect_for_loop_vars(&func.body);
    let var_inits: std::collections::HashMap<String, &Expr> = func
        .body
        .iter()
        .filter_map(|s| {
            if let Statement::VarDecl { name, init: Some(init), .. } = s {
                Some((name.clone(), init))
            } else {
                None
            }
        })
        .collect();
    for stmt in &func.body {
        if let Statement::VarDecl {
            var_type, name, ..
        } = stmt
        {
            if for_loop_vars.contains(name) {
                continue;
            }
            let rust_type = match var_type {
                VarType::Real => "f64",
                VarType::Integer => "i32",
                VarType::Index => "usize",
                VarType::RetCodeType => "RetCode",
            };
            // Determine if mut is needed: variable assigned more than once total
            let total_assigns = count_assignments(name, &func.body);
            let needs_mut = total_assigns > 1;
            if needs_mut {
                out.push_str(&format!("        let mut {}: {};\n", name, rust_type));
            } else {
                out.push_str(&format!("        let {}: {};\n", name, rust_type));
            }
        }
    }

    // Collect output array names for cast insertion
    let output_names: Vec<String> = func.outputs.iter().map(|o| o.name.clone()).collect();

    // Collect variables that have both VarDecl init AND a body assignment
    let body_assigned: std::collections::HashSet<String> = func
        .body
        .iter()
        .filter_map(|s| {
            if let Statement::Assign { target: Expr::Var(name), .. } = s {
                Some(name.clone())
            } else {
                None
            }
        })
        .collect();

    // Emit VarDecl initializations only when there's no body assignment for the same var
    for stmt in &func.body {
        if let Statement::VarDecl { name, init: Some(init), .. } = stmt {
            if for_loop_vars.contains(name) {
                continue;
            }
            if body_assigned.contains(name) {
                continue; // body assignment will handle it
            }
            out.push_str(&format!(
                "        {} = {};\n",
                name,
                render_expr(init, single_precision, registry)
            ));
        }
    }

    // Render body statements
    for stmt in &func.body {
        if matches!(stmt, Statement::VarDecl { .. }) {
            continue;
        }
        out.push_str(&render_statement(stmt, 8, single_precision, &for_loop_vars, &var_inits, &output_names, enums, registry));
    }

    out.push_str("        return RetCode::Success;\n");
    out.push_str("    }\n");

    out
}

/// Generate a flat function (for functions without optional params, like MULT).
fn gen_func(func: &FuncDef, snake: &str, single_precision: bool, enums: &HashMap<String, EnumDef>, registry: &Registry) -> String {
    let mut out = String::new();
    let suffix = if single_precision { "_s" } else { "" };
    let func_name = format!("{}{}", snake, suffix);

    // Doc comments
    if single_precision {
        out.push_str(&format!(
            "    /// Single-precision variant of [`Core::{}`].\n",
            snake
        ));
    } else {
        let title = func.description.as_deref().or(func.hint.as_deref()).unwrap_or(&func.group);
        out.push_str(&format!("    /// {}\n", title));
        out.push_str("    ///\n");
        out.push_str("    /// # Arguments\n");
        out.push_str("    ///\n");
        out.push_str("    /// * `startIdx` - Start index for calculation range\n");
        out.push_str("    /// * `endIdx` - End index for calculation range (inclusive)\n");
        for input in &func.inputs {
            out.push_str(&format!(
                "    /// * `{}` - Input price series\n",
                input.name
            ));
        }
        out.push_str("    /// * `outBegIdx` - First valid output index\n");
        out.push_str("    /// * `outNBElement` - Number of valid output elements\n");
        for output in &func.outputs {
            out.push_str(&format!("    /// * `{}` - Output values\n", output.name));
        }
        out.push_str("    ///\n");
        out.push_str("    /// # Returns\n");
        out.push_str("    ///\n");
        out.push_str(
            "    /// [`RetCode::Success`] on success, or an error code on failure.\n",
        );
        out.push_str("    ///\n");
        out.push_str("    /// # Example\n");
        out.push_str("    ///\n");
        out.push_str("    /// ```\n");
        out.push_str("    /// use ta_lib::ta_func::{Core, RetCode};\n");
        out.push_str("    ///\n");
        // Generate example input declarations
        for _input in &func.inputs {
            out.push_str("    /// let input = [1.0_f64; 50];\n");
        }
        out.push_str("    /// let mut out = [0.0_f64; 50];\n");
        out.push_str("    /// let mut out_beg_idx: usize = 0;\n");
        out.push_str("    /// let mut out_nb_element: usize = 0;\n");
        out.push_str("    ///\n");
        out.push_str("    /// let core = Core::new();\n");
        out.push_str(&format!("    /// let result = core.{}(\n", snake));
        out.push_str("    ///  0,\n");
        out.push_str("    ///  49,\n");
        for _input in &func.inputs {
            out.push_str("    ///  &input,\n");
        }
        out.push_str("    ///  &mut out_beg_idx,\n");
        out.push_str("    ///  &mut out_nb_element,\n");
        out.push_str("    ///  &mut out,\n");
        out.push_str("    /// );\n");
        out.push_str("    ///\n");
        out.push_str("    /// assert_eq!(result, RetCode::Success);\n");
        out.push_str("    /// ```\n");
    }

    // Function signature
    let input_type = if single_precision { "f32" } else { "f64" };

    out.push_str(&format!("    pub fn {}(\n", func_name));
    out.push_str("        &self,\n");
    out.push_str("        startIdx: usize,\n");
    out.push_str("        endIdx: usize,\n");
    for input in &func.inputs {
        out.push_str(&format!(
            "        {}: &[{}],\n",
            input.name, input_type
        ));
    }
    for opt in &func.optional_inputs {
        let rust_type = match opt.param_type {
            ParamType::Real => "f64",
            ParamType::Integer | ParamType::Enum(_) => "i32",
        };
        out.push_str(&format!("        {}: {},\n", opt.name, rust_type));
    }
    out.push_str("        outBegIdx: &mut usize,\n");
    out.push_str("        outNBElement: &mut usize,\n");
    for output in &func.outputs {
        let rust_type = match output.param_type {
            ParamType::Real => "f64",
            ParamType::Integer | ParamType::Enum(_) => "i32",
        };
        out.push_str(&format!(
            "        {}: &mut [{}],\n",
            output.name, rust_type
        ));
    }
    out.push_str("    ) -> RetCode {\n");

    // Declare local variables (excluding loop iterators consumed by for-loops)
    let for_loop_vars = collect_for_loop_vars(&func.body);
    // Build map of VarDecl init expressions for for-loop start values
    let var_inits: std::collections::HashMap<String, &Expr> = func
        .body
        .iter()
        .filter_map(|s| {
            if let Statement::VarDecl { name, init: Some(init), .. } = s {
                Some((name.clone(), init))
            } else {
                None
            }
        })
        .collect();
    for stmt in &func.body {
        if let Statement::VarDecl {
            var_type, name, ..
        } = stmt
        {
            if for_loop_vars.contains(name) {
                continue;
            }
            let rust_type = match var_type {
                VarType::Real => "f64",
                VarType::Integer => "i32",
                VarType::Index => "usize",
                VarType::RetCodeType => "RetCode",
            };
            // Determine if mut is needed: variable assigned more than once total
            let total_assigns = count_assignments(name, &func.body);
            let needs_mut = total_assigns > 1;
            if needs_mut {
                out.push_str(&format!("        let mut {}: {};\n", name, rust_type));
            } else {
                out.push_str(&format!("        let {}: {};\n", name, rust_type));
            }
        }
    }

    // Validation (no startIdx < 0 for usize)
    out.push_str("        if endIdx < startIdx {\n");
    out.push_str("            return RetCode::OutOfRangeEndIndex;\n");
    out.push_str("        }\n");

    // Emit VarDecl initializations (excluding for-loop vars)
    for stmt in &func.body {
        if let Statement::VarDecl { name, init: Some(init), .. } = stmt {
            if for_loop_vars.contains(name) {
                continue;
            }
            out.push_str(&format!(
                "        {} = {};\n",
                name,
                render_expr(init, single_precision, registry)
            ));
        }
    }

    // Collect output array names for cast insertion
    let output_names: Vec<String> = func.outputs.iter().map(|o| o.name.clone()).collect();

    // Render body statements
    for stmt in &func.body {
        if matches!(stmt, Statement::VarDecl { .. }) {
            continue;
        }
        out.push_str(&render_statement(stmt, 8, single_precision, &for_loop_vars, &var_inits, &output_names, enums, registry));
    }

    out.push_str("        return RetCode::Success;\n");
    out.push_str("    }\n");

    out
}

/// Generate an unsafe raw-pointer variant that wraps the logic/guarded function.
/// Uses `*const f64` / `*mut f64` instead of slices for FFI compatibility.
fn gen_unsafe_func(func: &FuncDef, snake: &str, single_precision: bool) -> String {
    let mut out = String::new();
    let suffix = if single_precision { "_s" } else { "" };
    let func_name = format!("{}_unsafe{}", snake, suffix);
    let input_type = if single_precision { "f32" } else { "f64" };
    let delegate_name = format!("{}{}", snake, suffix);

    out.push_str(&format!(
        "    // TODO: unsafe variant — thin wrapper around {} with raw pointer API\n",
        delegate_name
    ));
    out.push_str(&format!(
        "    // pub unsafe fn {}(\n",
        func_name
    ));
    out.push_str("    //     &self,\n");
    out.push_str("    //     startIdx: usize,\n");
    out.push_str("    //     endIdx: usize,\n");
    for input in &func.inputs {
        out.push_str(&format!(
            "    //     {}: *const {},\n",
            input.name, input_type
        ));
    }
    for opt in &func.optional_inputs {
        let rust_type = match opt.param_type {
            ParamType::Real => "f64",
            ParamType::Integer | ParamType::Enum(_) => "i32",
        };
        out.push_str(&format!("    //     {}: {},\n", opt.name, rust_type));
    }
    out.push_str("    //     outBegIdx: *mut usize,\n");
    out.push_str("    //     outNBElement: *mut usize,\n");
    for output in &func.outputs {
        let rust_type = match output.param_type {
            ParamType::Real => "f64",
            ParamType::Integer | ParamType::Enum(_) => "i32",
        };
        out.push_str(&format!(
            "    //     {}: *mut {},\n",
            output.name, rust_type
        ));
    }
    out.push_str("    // ) -> RetCode { ... }\n");

    out
}

/// Generate optional parameter validation code.
/// For lookback functions, the error return is -1.
/// For main functions, the error return is RetCode::BadParam.
fn gen_opt_param_validation(opt: &OptInput, pad: &str, is_lookback: bool) -> String {
    let mut out = String::new();
    let name = &opt.name;

    if opt.param_type == ParamType::Integer {
        if let Some(default) = opt.default {
            out.push_str(&format!(
                "{}if (({}) as i32) == (i32::MIN) {{\n",
                pad, name
            ));
            out.push_str(&format!(
                "{}    {} = {};\n",
                pad, name, default as i64
            ));

            if let Some((lo, hi)) = opt.range {
                let err_return = if is_lookback {
                    "return -1;"
                } else {
                    "return RetCode::BadParam;"
                };
                out.push_str(&format!(
                    "{}}} else if ((({}) as i32) < {}) || ((({}) as i32) > {}) {{\n",
                    pad, name, lo, name, hi
                ));
                out.push_str(&format!(
                    "{}    {}\n",
                    pad, err_return
                ));
            }

            out.push_str(&format!("{}}}\n", pad));
        }
    }

    out
}

/// Count how many times a variable is assigned in the body (including VarDecl inits).
/// Assignments inside loops count as 2 (since they execute multiple times).
/// Used to determine if `mut` is needed on a local variable declaration.
fn count_assignments(name: &str, body: &[Statement]) -> usize {
    count_assignments_inner(name, body, false)
}

fn count_assignments_inner(name: &str, body: &[Statement], in_loop: bool) -> usize {
    let mut count = 0;
    for stmt in body {
        match stmt {
            Statement::VarDecl { name: vname, init, .. } => {
                if vname == name && init.is_some() {
                    count += 1;
                }
            }
            Statement::Assign { target, .. } => {
                if let Expr::Var(tname) = target {
                    if tname == name {
                        // Assignments in loops count as multiple
                        count += if in_loop { 2 } else { 1 };
                    }
                }
            }
            Statement::While { body: while_body, .. } => {
                count += count_assignments_inner(name, while_body, true);
            }
            Statement::For { body: for_body, .. } | Statement::ForC { body: for_body, .. } => {
                count += count_assignments_inner(name, for_body, true);
            }
            Statement::Block { body: block_body } => {
                count += count_assignments_inner(name, block_body, in_loop);
            }
            Statement::If { then_body, else_body, .. } => {
                count += count_assignments_inner(name, then_body, in_loop);
                count += count_assignments_inner(name, else_body, in_loop);
            }
            Statement::Return { .. } | Statement::Break | Statement::Continue => {}
            Statement::Switch { cases, default, .. } => {
                for (_, case_body) in cases {
                    count += count_assignments_inner(name, case_body, in_loop);
                }
                count += count_assignments_inner(name, default, in_loop);
            }
        }
    }
    count
}

/// Detect while loops that are simple for-loop patterns:
/// `while i <= endIdx { ... i += 1; }` where i is declared as `index i = startIdx`
/// Returns the set of variable names used as loop iterators.
fn collect_for_loop_vars(body: &[Statement]) -> Vec<String> {
    let mut vars = Vec::new();
    // Find VarDecl + While pairs
    let decls: std::collections::HashMap<String, &Expr> = body
        .iter()
        .filter_map(|s| {
            if let Statement::VarDecl { name, init: Some(init), var_type } = s {
                if *var_type == VarType::Index {
                    return Some((name.clone(), init));
                }
            }
            None
        })
        .collect();

    for stmt in body {
        match stmt {
            Statement::While { condition, body: while_body } => {
                if let Some(iter_var) = detect_for_pattern(condition, while_body, &decls) {
                    vars.push(iter_var);
                }
            }
            // These statement types don't contain for-loop patterns at the top level
            Statement::For { .. } | Statement::ForC { .. } | Statement::Block { .. }
            | Statement::VarDecl { .. } | Statement::Assign { .. } | Statement::If { .. }
            | Statement::Return { .. } | Statement::Break | Statement::Continue
            | Statement::Switch { .. } => {}
        }
    }
    vars
}

/// Check if a while loop matches the pattern: while iter_var <= bound { ... iter_var += 1 }
fn detect_for_pattern(
    condition: &Expr,
    while_body: &[Statement],
    decls: &std::collections::HashMap<String, &Expr>,
) -> Option<String> {
    // condition must be BinOp(Var(iter), LessEq, Var(bound))
    if let Expr::BinOp(left, BinOp::LessEq, _right) = condition {
        if let Expr::Var(iter_name) = left.as_ref() {
            // Check that iter_name is declared as an index var
            if decls.contains_key(iter_name) {
                // Check last statement is iter_name += 1
                if let Some(Statement::Assign { target, value, .. }) = while_body.last() {
                    if let Expr::Var(tname) = target {
                        if tname == iter_name {
                            if let Expr::BinOp(l, BinOp::Add, r) = value {
                                if let (Expr::Var(ln), Expr::IntLiteral(1)) =
                                    (l.as_ref(), r.as_ref())
                                {
                                    if ln == iter_name {
                                        return Some(iter_name.clone());
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    None
}

fn render_statement(
    stmt: &Statement,
    indent: usize,
    single_precision: bool,
    for_loop_vars: &[String],
    var_inits: &std::collections::HashMap<String, &Expr>,
    output_names: &[String],
    enums: &HashMap<String, EnumDef>,
    registry: &Registry,
) -> String {
    let pad = " ".repeat(indent);
    match stmt {
        Statement::VarDecl { .. } => String::new(), // already handled
        Statement::Block { body: block_body } => {
            let mut out = String::new();
            for s in block_body {
                out.push_str(&render_statement(s, indent, single_precision, for_loop_vars, var_inits, output_names, enums, registry));
            }
            out
        }
        Statement::For { var, count, body: for_body } => {
            let mut out = format!(
                "{}for {} in (1..={}).rev() {{\n",
                pad, var, render_expr(count, single_precision, registry)
            );
            for s in for_body {
                out.push_str(&render_statement(s, indent + 4, single_precision, for_loop_vars, var_inits, output_names, enums, registry));
            }
            out.push_str(&format!("{}}}\n", pad));
            out
        }
        Statement::ForC { init, condition, update, body: for_body } => {
            let init_str = render_statement(init, 0, single_precision, for_loop_vars, var_inits, output_names, enums, registry);
            let init_trimmed = init_str.trim().trim_end_matches(';');
            let update_str = render_statement(update, 0, single_precision, for_loop_vars, var_inits, output_names, enums, registry);
            let update_trimmed = update_str.trim().trim_end_matches(';');
            let mut out = format!(
                "{}// for( {}; {}; {} )\n",
                pad, init_trimmed, render_expr(condition, single_precision, registry), update_trimmed
            );
            out.push_str(&format!("{}{};\n", pad, init_trimmed));
            out.push_str(&format!("{}while {} {{\n", pad, render_expr(condition, single_precision, registry)));
            for s in for_body {
                out.push_str(&render_statement(s, indent + 4, single_precision, for_loop_vars, var_inits, output_names, enums, registry));
            }
            out.push_str(&format!("{}    {};\n", pad, update_trimmed));
            out.push_str(&format!("{}}}\n", pad));
            out
        }
        Statement::Assign { target, value, compound } => {
            // Statement-level FuncCall: when target is Var("_"), render just the expansion
            if let Expr::Var(tname) = target {
                if tname == "_" {
                    if let Expr::FuncCall(fname, args) = value {
                        return format!(
                            "{}{};\n",
                            pad,
                            render_func_call(fname, args, single_precision, registry)
                        );
                    }
                }
            }
            // Only fold compound assignments if the original source used +=/-=/etc.
            if *compound {
                if let (Expr::Var(tname), Expr::BinOp(left, op, right)) = (target, value) {
                    if let Expr::Var(lname) = left.as_ref() {
                        if lname == tname {
                            let op_str = match op {
                                BinOp::Add => "+=",
                                BinOp::Sub => "-=",
                                BinOp::Mul => "*=",
                                BinOp::Div => "/=",
                                BinOp::Mod | BinOp::LessEq | BinOp::Less
                                | BinOp::Greater | BinOp::GreaterEq | BinOp::Eq
                                | BinOp::NotEq | BinOp::And | BinOp::Or => "",
                            };
                            if !op_str.is_empty() {
                                let target_str =
                                    render_assign_target(target, single_precision, registry);
                                return format!(
                                    "{}{} {} {};\n",
                                    pad,
                                    target_str,
                                    op_str,
                                    render_expr(right, single_precision, registry)
                                );
                            }
                        }
                    }
                }
            }
            let target_str = render_assign_target(target, single_precision, registry);
            let value_str = render_expr(value, single_precision, registry);
            // Add `as f64` cast for output array assignments only when the value
            // contains uncast input array accesses (which may be f32 in single precision)
            let needs_cast = if let Expr::ArrayAccess(name, _) = target {
                output_names.contains(name) && expr_has_uncast_array_access(value)
            } else {
                false
            };
            if needs_cast {
                format!("{}{} = ({}) as f64;\n", pad, target_str, value_str)
            } else {
                format!("{}{} = {};\n", pad, target_str, value_str)
            }
        }
        Statement::While {
            condition,
            body: while_body,
        } => {
            // Check if this is a for-loop pattern
            if let Expr::BinOp(left, BinOp::LessEq, right) = condition {
                if let Expr::Var(iter_name) = left.as_ref() {
                    if for_loop_vars.contains(iter_name) {
                        let start_expr = if let Some(init) = var_inits.get(iter_name) {
                            render_expr(init, single_precision, registry)
                        } else {
                            iter_name.clone()
                        };
                        let end_expr = render_expr(right, single_precision, registry);
                        let mut out = format!(
                            "{}for {} in ({} as usize)..=({} as usize) {{\n",
                            pad, iter_name, start_expr, end_expr
                        );
                        // Render body except last statement (the i += 1)
                        for s in &while_body[..while_body.len() - 1] {
                            out.push_str(&render_statement(
                                s,
                                indent + 4,
                                single_precision,
                                for_loop_vars,
                                var_inits,
                                output_names,
                                enums,
                                registry,
                            ));
                        }
                        out.push_str(&format!("{}}}\n", pad));
                        return out;
                    }
                }
            }
            // Regular while loop
            let mut out = format!(
                "{}while {} {{\n",
                pad,
                render_expr(condition, single_precision, registry)
            );
            for s in while_body {
                out.push_str(&render_statement(s, indent + 4, single_precision, for_loop_vars, var_inits, output_names, enums, registry));
            }
            out.push_str(&format!("{}}}\n", pad));
            out
        }
        Statement::If {
            condition,
            then_body,
            else_body,
        } => {
            let mut out = format!(
                "{}if {} {{\n",
                pad,
                render_expr(condition, single_precision, registry)
            );
            for s in then_body {
                out.push_str(&render_statement(s, indent + 4, single_precision, for_loop_vars, var_inits, output_names, enums, registry));
            }
            if else_body.is_empty() {
                out.push_str(&format!("{}}}\n", pad));
            } else {
                out.push_str(&format!("{}}} else ", pad));
                // Check if the else body is a single if statement (else-if chain)
                if else_body.len() == 1 {
                    if let Statement::If { .. } = &else_body[0] {
                        // Render as else if (strip leading pad since we already have "} else ")
                        let if_str = render_statement(&else_body[0], indent, single_precision, for_loop_vars, var_inits, output_names, enums, registry);
                        // Remove leading whitespace from the if statement
                        out.push_str(if_str.trim_start());
                        return out;
                    }
                }
                out.push_str("{\n");
                for s in else_body {
                    out.push_str(&render_statement(s, indent + 4, single_precision, for_loop_vars, var_inits, output_names, enums, registry));
                }
                out.push_str(&format!("{}}}\n", pad));
            }
            out
        }
        Statement::Return { value } => {
            match value {
                Some(expr) => {
                    let rendered = render_return_expr(expr, single_precision, registry);
                    format!("{}return {};\n", pad, rendered)
                }
                None => format!("{}return;\n", pad),
            }
        }
        Statement::Break => format!("{}break;\n", pad),
        Statement::Continue => format!("{}continue;\n", pad),
        Statement::Switch { expr, cases, default } => {
            let mut out = format!("{}match {} {{\n", pad, render_expr(expr, single_precision, registry));
            for (label, case_body) in cases {
                let rust_label = render_switch_label(label, enums);
                out.push_str(&format!("{}    {} => {{\n", pad, rust_label));
                for s in case_body {
                    out.push_str(&render_statement(s, indent + 8, single_precision, for_loop_vars, var_inits, output_names, enums, registry));
                }
                out.push_str(&format!("{}    }}\n", pad));
                }
            if !default.is_empty() {
                out.push_str(&format!("{}    _ => {{\n", pad));
                for s in default {
                    out.push_str(&render_statement(s, indent + 8, single_precision, for_loop_vars, var_inits, output_names, enums, registry));
                }
                out.push_str(&format!("{}    }}\n", pad));
            }
            out.push_str(&format!("{}}}\n", pad));
            out
        }
    }
}

/// Map a switch case label to Rust. For enum variant labels like `MAType_SMA`,
/// look up the integer value from the enum definitions.
fn render_switch_label(label: &str, enums: &HashMap<String, EnumDef>) -> String {
    if let Some((_enum_name, variant)) = lookup_variant(label, enums) {
        format!("{}", variant.value)
    } else {
        label.to_string()
    }
}

/// Check if an expression contains array accesses that are NOT wrapped in a Cast.
/// This is used to determine if an output array assignment needs an `as f64` cast.
/// Input array accesses that are already cast (e.g., `(double)inReal[i]`) don't need
/// an outer cast because they're already f64.
fn expr_has_uncast_array_access(expr: &Expr) -> bool {
    match expr {
        Expr::ArrayAccess(_, _) => true,
        Expr::Cast(_, _) => false, // Cast wraps the array access, so it's already typed
        Expr::BinOp(left, _, right) => {
            expr_has_uncast_array_access(left) || expr_has_uncast_array_access(right)
        }
        Expr::Not(inner) => expr_has_uncast_array_access(inner),
        Expr::FuncCall(_, args) => args.iter().any(|a| expr_has_uncast_array_access(a)),
        Expr::Literal(_) | Expr::IntLiteral(_) | Expr::Var(_) | Expr::PointerDeref(_) => false,
    }
}

fn render_assign_target(expr: &Expr, single_precision: bool, registry: &Registry) -> String {
    match expr {
        Expr::Var(name) if name == "outBegIdx" || name == "outNBElement" => {
            format!("(*{})", name)
        }
        Expr::Var(name) => name.clone(),
        Expr::ArrayAccess(name, idx) => {
            format!("{}[{}]", name, render_expr(idx, single_precision, registry))
        }
        Expr::Literal(_) | Expr::IntLiteral(_) | Expr::BinOp(_, _, _)
        | Expr::Cast(_, _) | Expr::Not(_) | Expr::FuncCall(_, _)
        | Expr::PointerDeref(_) => render_expr(expr, single_precision, registry),
    }
}

/// Get operator precedence (higher = binds tighter).
fn op_precedence(op: &BinOp) -> u8 {
    match op {
        BinOp::Or => 1,
        BinOp::And => 2,
        BinOp::Eq | BinOp::NotEq => 3,
        BinOp::Less | BinOp::LessEq | BinOp::Greater | BinOp::GreaterEq => 4,
        BinOp::Add | BinOp::Sub => 5,
        BinOp::Mul | BinOp::Div | BinOp::Mod => 6,
    }
}

/// Render a BinOp operand, adding parens when the child BinOp has lower precedence
/// (or same precedence on the right side for left-associative ops).
/// Also wraps Cast expressions for correct `as` precedence.
fn render_binop_operand(
    expr: &Expr,
    parent_op: &BinOp,
    is_left: bool,
    single_precision: bool,
    registry: &Registry,
) -> String {
    match expr {
        Expr::Cast(_, _) => format!("({})", render_expr(expr, single_precision, registry)),
        Expr::BinOp(_, child_op, _) => {
            let parent_prec = op_precedence(parent_op);
            let child_prec = op_precedence(child_op);
            // Need parens if child has lower precedence, or same precedence on right side
            if child_prec < parent_prec || (!is_left && child_prec == parent_prec) {
                format!("({})", render_expr(expr, single_precision, registry))
            } else {
                render_expr(expr, single_precision, registry)
            }
        }
        Expr::Literal(_) | Expr::IntLiteral(_) | Expr::Var(_)
        | Expr::ArrayAccess(_, _) | Expr::Not(_) | Expr::FuncCall(_, _)
        | Expr::PointerDeref(_) => render_expr(expr, single_precision, registry),
    }
}

/// Render a return expression, mapping known enum values to Rust constants.
fn render_return_expr(expr: &Expr, single_precision: bool, registry: &Registry) -> String {
    if let Expr::Var(name) = expr {
        return match name.as_str() {
            "SUCCESS" => "RetCode::Success".to_string(),
            "BadParam" => "RetCode::BadParam".to_string(),
            "OutOfRangeEndIndex" => "RetCode::OutOfRangeEndIndex".to_string(),
            "OutOfRangeStartIndex" => "RetCode::OutOfRangeStartIndex".to_string(),
            _ => render_expr(expr, single_precision, registry),
        };
    }
    render_expr(expr, single_precision, registry)
}

fn render_expr(expr: &Expr, single_precision: bool, registry: &Registry) -> String {
    match expr {
        Expr::Literal(f) => {
            if *f == f.floor() && f.abs() < 1e15 {
                format!("{}.0", *f as i64)
            } else {
                format!("{}", f)
            }
        }
        Expr::IntLiteral(i) => format!("{}", i),
        Expr::Var(name) => match name.as_str() {
            "COMPATIBILITY" => "(self.compatibility)".to_string(),
            "METASTOCK" => "Compatibility::Metastock".to_string(),
            "DEFAULT" => "Compatibility::Default".to_string(),
            "BAD_PARAM" => "RetCode::BadParam".to_string(),
            "SUCCESS" => "RetCode::Success".to_string(),
            _ => name.clone(),
        },
        Expr::ArrayAccess(name, idx) => {
            format!("{}[{}]", name, render_expr(idx, single_precision, registry))
        }
        Expr::FuncCall(fname, args) => render_func_call(fname, args, single_precision, registry),
        Expr::BinOp(left, op, right) => {
            let op_str = match op {
                BinOp::Add => " + ",
                BinOp::Sub => " - ",
                BinOp::Mul => " * ",
                BinOp::Div => " / ",
                BinOp::Mod => " % ",
                BinOp::LessEq => " <= ",
                BinOp::Less => " < ",
                BinOp::Greater => " > ",
                BinOp::GreaterEq => " >= ",
                BinOp::Eq => " == ",
                BinOp::NotEq => " != ",
                BinOp::And => " && ",
                BinOp::Or => " || ",
            };
            // Wrap Cast subexpressions in parens for correct Rust `as` precedence
            let left_str = render_binop_operand(left, op, true, single_precision, registry);
            let right_str = render_binop_operand(right, op, false, single_precision, registry);
            format!(
                "{}{}{}",
                left_str,
                op_str,
                right_str
            )
        }
        Expr::Cast(var_type, inner) => {
            let rust_type = match var_type {
                VarType::Real => "f64",
                VarType::Integer => "i32",
                VarType::Index => "usize",
                VarType::RetCodeType => "RetCode",
            };
            format!("({}) as {}", render_expr(inner, single_precision, registry), rust_type)
        }
        Expr::Not(inner) => {
            format!("!({})", render_expr(inner, single_precision, registry))
        }
        Expr::PointerDeref(name) => format!("(*{})", name),
    }
}

/// Render a complex lookback body (LookbackExpr::Code) into Rust code.
fn render_lookback_code(stmts: &[Statement], enums: &HashMap<String, EnumDef>, registry: &Registry) -> String {
    let mut out = String::new();
    let empty_for_loop_vars: Vec<String> = Vec::new();
    let empty_var_inits: std::collections::HashMap<String, &Expr> = std::collections::HashMap::new();
    let empty_output_names: Vec<String> = Vec::new();

    // Declare local variables from VarDecl statements
    for stmt in stmts {
        if let Statement::VarDecl { var_type, name, .. } = stmt {
            let rust_type = match var_type {
                VarType::Real => "f64",
                VarType::Integer => "i32",
                VarType::Index => "usize",
                VarType::RetCodeType => "RetCode",
            };
            // Count assignments to determine mutability
            let total_assigns = count_assignments(name, stmts);
            let needs_mut = total_assigns > 1;
            if needs_mut {
                out.push_str(&format!("        let mut {}: {};\n", name, rust_type));
            } else {
                out.push_str(&format!("        let {}: {};\n", name, rust_type));
            }
        }
    }

    // Render non-VarDecl statements
    for stmt in stmts {
        if matches!(stmt, Statement::VarDecl { .. }) {
            continue;
        }
        out.push_str(&render_statement(
            stmt,
            8,
            false, // lookback doesn't depend on single_precision
            &empty_for_loop_vars,
            &empty_var_inits,
            &empty_output_names,
            enums,
            registry,
        ));
    }

    out
}

/// Convert a function identifier to PascalCase for FuncUnstId enum.
/// e.g., "RSI" -> "Rsi", "SMA" -> "Sma"
fn to_pascal_case(s: &str) -> String {
    let lower = s.to_lowercase();
    let mut chars = lower.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

/// Render a FuncCall expression to Rust code.
fn render_func_call(fname: &str, args: &[Expr], single_precision: bool, registry: &Registry) -> String {
    if fname == "UNSTABLE_PERIOD" {
        // UNSTABLE_PERIOD(RSI) -> self.unstable_period[FuncUnstId::Rsi as usize]
        if let Some(Expr::Var(func_name)) = args.first() {
            let pascal = to_pascal_case(func_name);
            return format!("self.unstable_period[FuncUnstId::{} as usize]", pascal);
        }
        "self.unstable_period[0]".to_string()
    } else if fname == "COMPATIBILITY" {
        // COMPATIBILITY() -> self.compatibility
        "self.compatibility".to_string()
    } else if fname == "IS_ZERO" {
        // IS_ZERO(x) -> ((-(0.00000000000001)) < x) && (x < (0.00000000000001))
        if let Some(arg) = args.first() {
            let x = render_expr(arg, single_precision, registry);
            return format!(
                "((-(0.00000000000001)) < {}) && ({} < (0.00000000000001))",
                x, x
            );
        }
        "false".to_string()
    } else if fname == "ARRAY_COPY" {
        // ARRAY_COPY(dst, dstOff, src, srcOff, count)
        if args.len() == 5 {
            let dst = render_expr(&args[0], single_precision, registry);
            let dst_off = render_expr(&args[1], single_precision, registry);
            let src = render_expr(&args[2], single_precision, registry);
            let src_off = render_expr(&args[3], single_precision, registry);
            let count = render_expr(&args[4], single_precision, registry);
            if single_precision {
                // f32 -> f64: element-wise loop
                return format!(
                    "{{\n            let _n = ({}) as usize;\n            let _di = ({}) as usize;\n            let _si = ({}) as usize;\n            for _k in 0.._n {{\n                {}[_di + _k] = {}[_si + _k] as f64;\n            }}\n        }}",
                    count, dst_off, src_off, dst, src
                );
            } else {
                // f64 -> f64: copy_from_slice
                return format!(
                    "{{\n            let _n = ({}) as usize;\n            let _di = ({}) as usize;\n            let _si = ({}) as usize;\n            {}[_di.._di + _n].copy_from_slice(&{}[_si.._si + _n]);\n        }}",
                    count, dst_off, src_off, dst, src
                );
            }
        }
        "/* ARRAY_COPY: bad args */".to_string()
    } else if fname == "PER_TO_K" {
        // PER_TO_K(period) -> 2.0_f64 / ((period) as f64 + 1.0_f64)
        if let Some(arg) = args.first() {
            let x = render_expr(arg, single_precision, registry);
            return format!("2.0_f64 / (({}) as f64 + 1.0_f64)", x);
        }
        "0.0_f64".to_string()
    } else if fname.ends_with("_Lookback") {
        // RSI_Lookback(args...) -> self.rsi_lookback(args...)
        let rust_name = fname.to_lowercase();
        let rendered_args: Vec<String> = args.iter().map(|a| render_expr(a, single_precision, registry)).collect();
        format!("self.{}({})", rust_name, rendered_args.join(", "))
    } else if fname.ends_with("_lookback") {
        // sma_lookback(args...) -> self.sma_lookback(args...)  (prefix-free names from C source)
        let rendered_args: Vec<String> = args.iter().map(|a| render_expr(a, single_precision, registry)).collect();
        format!("self.{}({})", fname, rendered_args.join(", "))
    } else if fname.ends_with("_logic") {
        // sma_logic(args...) -> self.sma_logic(args...) or self.sma_logic_s(args...) for single precision
        let rust_name = if single_precision {
            format!("{}_s", fname)
        } else {
            fname.to_string()
        };
        let rendered_args: Vec<String> = args.iter().map(|a| render_expr(a, single_precision, registry)).collect();
        format!("self.{}({})", rust_name, rendered_args.join(", "))
    } else if is_ta_function(fname) {
        // TA function call: SMA(...) -> self.sma(...) or self.sma_s(...) for single precision
        let rust_name = if single_precision {
            format!("{}_s", fname.to_lowercase())
        } else {
            fname.to_lowercase()
        };
        let rendered_args: Vec<String> = args.iter().map(|a| render_expr(a, single_precision, registry)).collect();
        format!("self.{}({})", rust_name, rendered_args.join(", "))
    } else {
        // Generic function call (math functions etc.)
        let rendered_args: Vec<String> = args.iter().map(|a| render_expr(a, single_precision, registry)).collect();
        format!("{}({})", fname, rendered_args.join(", "))
    }
}

/// Check if a function name is a known TA-Lib function (uppercase name).
/// These get mapped to self.name() method calls in Rust.
fn is_ta_function(name: &str) -> bool {
    // TA function names are all-uppercase (SMA, EMA, RSI, etc.)
    // Exclude known builtins that are handled separately
    !name.is_empty()
        && name.chars().all(|c| c.is_ascii_uppercase() || c == '_')
        && !matches!(
            name,
            "UNSTABLE_PERIOD"
                | "IS_ZERO"
                | "ARRAY_COPY"
                | "PER_TO_K"
                | "COMPATIBILITY"
                | "METASTOCK"
                | "DEFAULT"
        )
        && !name.ends_with("_Lookback")
}

fn gen_footer() -> String {
    "/* Generated */\n\n\
     /***************/\n\
     /* End of File */\n\
     /***************/\n"
        .to_string()
}
